### ISSUE TITLE
Missing cvextern.dll

### ISSUE THREAD

**Issue by gsantopaolo** [emgucv/emgucv#10]
Hi,
   I've just downloaded the repo to test it. Try to compile RealtimeCamera (Universal Windows) and I get the error:
**_This package do not contain necessary binary for Windows 10 UWP (32bit). Emgu CV for Windows Commercial License is required. Missing cvextern.dll '	Emgu.CV\Emgu.CV.projitems_**
According to your [licensing page](http://www.emgu.com/wiki/index.php/Licensing:), how can I run that sample under the Open Source Licensing?

thank you
-g

**Comment by emgucv** [comment]
Hi, 

At this moment, the open source license only provide access to the Windows Desktop (Windows Forms) release. 

The UWP release is available under a commercial license. 

Best regards,

Canming

**Comment by gsantopaolo** [comment]
@emgucv thanks for your answer, do you have a mail adders where i can write?

**Comment by emgucv** [comment]
Hi, we had received your email at support@emgu.com 

We will continue our discussion there. 

Closing this ticket now.

Thanks,

Canming

**Comment by rpysork** [comment]
Is there any plan to make UWP available for open source license? If so, what is your time frame?
