### ISSUE TITLE
CMake generated file error.

### ISSUE THREAD

**Issue by synercoder** [emgucv/emgucv#104]
I cloned this repo, followed the instructions (with issues, see #103) and then the project would not build.

The auto generated file (CMAKE) ".\Emgu.CV\Dnn\NetGenerated.cs" contains a small problem. This file works for the project Emgu.CV.World, but fails for the project Emgu.CV.World.NetStandard1_4.

The file ".\Emgu.CV\Dnn\Net.cs" starts with the line: `#if !(NETFX_CORE || NETSTANDARD1_4)`. But this line is absent in the NetGenerated.cs file. 

Therefor the class doesn't know about the private field `_ptr` and thus errors on the lines:

42. `DnnInvoke.cveNetSetPreferableBackend(_ptr, value); `

...

50. `DnnInvoke.cveNetSetPreferableTarget(_ptr, value); `

...

58. `DnnInvoke.cveNetEnableFusion(_ptr, value); `

I fixed this by adding the line `#if !(NETFX_CORE || NETSTANDARD1_4)` to the start of the file, and `#endif` to the ending of the file on my pc.

But I don't know how the file is generated, and I can not create a pull request to fix it because of that. (I don't know C++/CMAKE)

**Comment by emgucv** [comment]
Closing ticket now.
