### ISSUE TITLE
No euclidean transform estimation methods (findTransformECC or reg contrib)

### ISSUE THREAD

**Issue by Callum-Shipton** [emgucv/emgucv#105]
The findTransformECC method has not been wrapped, I need this function since I am looking to only estimate a euclidean transformation. (I.E no scaling/shearing only rotation and translation.) And doing so with the other functions (estimateRigidTransform with fullAffine = false) introduces too much error as it still includes scaling.

[Edit: Also, the contrib module reg has euclidean transformation estimations so wrapping the reg contrib module would also be sufficient.]

Would this be possible? With guidance, I could attempt wrapping it myself.

Thanks.

**Comment by emgucv** [comment]
Added in this commit: 
6bfb68c41814cea796971718ffb8658dfa0adff2 
Thanks for pointing that out.
