### ISSUE TITLE
Does the new UWP support mean that emgu can be used on xbox?

### ISSUE THREAD

**Issue by dbruning** [emgucv/emgucv#11]
Emgucv now supports UWP and Windows 10 support as of [3.1.0](http://www.emgu.com/wiki/index.php/Version_History#Emgu.CV-3.1.0-r16.12)

It's possible to develop Windows 10 UWP apps that run on the xbox.

Would a UWP app using EmguCV 3.1.0 run on an xbox?

**Comment by emgucv** [comment]
Yes, our 3.1.0-r16_12 UWP release can run on an XBOX One under dev mode.
