### ISSUE TITLE
Ubunto 16.04 build error

### ISSUE THREAD

**Issue by srikarreddy** [emgucv/emgucv#110]
I followed  steps in the following link for ubuntu 16.04
[http://www.emgu.com/wiki/index.php/Download_And_Installation]
./apt_install_dependency **Success**
./cmake_configure **Success**
but when i do **cmake** in the root directory I get the following error

-- CSC_EXECUTABLE_120: /usr/bin/csc
-- MSBUILD_EXECUTABLE_120 : /usr/bin/msbuild
-- CSC_EXECUTABLE_140: /usr/bin/csc
-- MSBUILD_EXECUTABLE_140 : /usr/bin/msbuild
-- CSC_EXECUTABLE_150: /usr/bin/csc
-- MSBUILD_EXECUTABLE_150 : /usr/bin/msbuild
-- Found csc: /usr/bin/csc
-- Found gacutil: /usr/bin/gacutil
-- Found al: /usr/bin/al
-- Found resgen: /usr/bin/resgen
-- Found msbuild: /usr/bin/msbuild
-- Extracting Emgu CV git version, please wait...
-- Emgu CV GIT VERSION: 2944
-- Building for Linux
-- Including the following files in package: /home/administrator/emgucv/libs/Emgu.CV.World.xml;/home/administrator/emgucv/libs/Emgu.CV.World.dll
-- HAVE_PREBUILD_EMGU_CV_WORLD: ON
-- Package name will be emgucv
CMake Error at opencv/CMakeLists.txt:11 (message):
  

  FATAL: In-source builds are not allowed.

             You should create a separate directory for build files.

**Comment by emgucv** [comment]
I have tested with the 3.4.1 release tag. Complies fine on Ubuntu 16.04. Please give it a try.

**Comment by emgucv** [comment]
Closing ticket now.
