### ISSUE TITLE
Undistort doesn't correctly apply newCameraMatrix

### ISSUE THREAD

**Issue by Callum-Shipton** [emgucv/emgucv#111]
I believe theres a bug in undistort, where the newCameraMatrix is not being applied correctly. 

Line 274 in imgproc_c.cpp:

`cv::undistort(*src, *dst, *cameraMatrix, *distorCoeffs, newCameraMatrix ? *cameraMatrix : (cv::InputArray) cv::noArray());`

should be:

`cv::undistort(*src, *dst, *cameraMatrix, *distorCoeffs, newCameraMatrix ? *newCameraMatrix : (cv::InputArray) cv::noArray());`

**Comment by emgucv** [comment]
Fixed in Git master. Thanks for pointing out.
