### ISSUE TITLE
lib\x64\tfextern.dll is missing in version 3.3.0

### ISSUE THREAD

**Issue by connywesth** [emgucv/emgucv#115]
When building Project Emgu i get a compiling error in several projects:

Severity	Code	Description	Project	File	Line	Suppression State
Error		'This package do not contain necessary binary for WindowsForms. X64 is targeted, but file C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\..\lib\x64\tfextern.dll is missing.'	CVInterop	C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\Emgu.TF.projitems	217	
Error		'This package do not contain necessary binary for WindowsForms. X64 is targeted, but file C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\..\lib\x64\tfextern.dll is missing.'	Emgu.TF.World	C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\Emgu.TF.projitems	217	
Error		'This package do not contain necessary binary for WindowsForms. X64 is targeted, but file C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\..\lib\x64\tfextern.dll is missing.'	InceptionObjectRecognition	C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\Emgu.TF.projitems	217	
Error		'This package do not contain necessary binary for WindowsForms. X64 is targeted, but file C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\..\lib\x64\tfextern.dll is missing.'	MultiboxPeopleDetection	C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\Emgu.TF.projitems	217	
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	Emgu.TF.World		1	Active
Warning		The referenced component 'System' could not be found.	Emgu.TF.World			
Warning		The referenced component 'System.Core' could not be found.	Emgu.TF.World			
Warning		The referenced component 'System.Data' could not be found.	Emgu.TF.World			
Warning		The referenced component 'System.Data.DataSetExtensions' could not be found.	Emgu.TF.World			
Warning		The referenced component 'System.Net' could not be found.	Emgu.TF.World			
Warning		The referenced component 'System.XML' could not be found.	Emgu.TF.World			
Warning		The referenced component 'System.Xml.Linq' could not be found.	Emgu.TF.World			

Error message:

Severity	Code	Description	Project	File	Line	Suppression State
Error		'This package do not contain necessary binary for WindowsForms. X64 is targeted, but file C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\..\lib\x64\tfextern.dll is missing.'	CVInterop	C:\Projects\C#\RoadRage\Komponenter\libemgutf\Emgu.TF\Emgu.TF.projitems	217

**Comment by emgucv** [comment]
It seems like you are using Emgu TF. This issue tracker is for Emgu CV, please report Emgu TF issue here instead:
https://github.com/emgucv/emgutf/issues

The tfextern.dll file is included in the official Emgu TF releases under the "lib\x64" folder. It is not checked into the Git repository.

**Comment by emgucv** [comment]
Closing ticket now.

**Comment by connywesth** [comment]
If you dont check in all files needed by the project, the entire project becomes useless!

I just cant compile and link project to test at all. It was all just a huge waste of my time to look at this project.
