### ISSUE TITLE
Dnn Importer.populateNet, unknown layer type transpose in op permute_1_1/transpose

### ISSUE THREAD

**Issue by andyl1992** [emgucv/emgucv#116]
When importing a model i have produced with keras tensor flow, certain layers will not import correctly. I tried to replace the flatten layer with manual reshapes as is the known fix for opencv, but when using emgucv it has not worked for me. 

I am getting an error unknown layer type transpose in op permute_1_1/transpose

**Comment by emgucv** [comment]
Which Emgu CV version are you using? Can the model be imported from the same Open CV version?

**Comment by emgucv** [comment]
Closing ticket now due to inactivity.
