### ISSUE TITLE
'TargetConditions.h' file not found

### ISSUE THREAD

**Issue by Castaneda1914** [emgucv/emgucv#117]
Hello! I'm trying to build emgucv for mac using this tutorial [http://www.emgu.com/wiki/index.php/Download_And_Installation](url) and getting an error from cmake: 
`/Users/../Projects/emgucv/Emgu.CV.Extern/tesseract/libtesseract/leptonica/leptonica-1.74/src/gplot.c:103:10: fatal error: 
      'TargetConditions.h' file not found
#include "TargetConditions.h"
1 error generated.`
I'm using Mac Os Sierra 10.12.6 and Xcode 9.2, command line tools are installed.

**Comment by emgucv** [comment]
I have tested with the 3.4.1 release tag, XCode 9.3 and OSX 10.13.4. 
Compiles with no issues. Please give it a try.

**Comment by emgucv** [comment]
Closing ticket now.
