### ISSUE TITLE
LATCH DetectAndComputer error:  An unhandled exception of type 'Emgu.CV.Util.CvException' occurred in Emgu.CV.World.dll

### ISSUE THREAD

**Issue by fastlater** [emgucv/emgucv#119]
Is the LATCH class in `Emgu.CV.XFeatures2D` working or it is under development?
I am working on the TrafficSignRecognition sample and I am trying to change SURF detector for LATCH detector but I am getting the error mentioned in the title of this issue.
My code is as below:
```
        private LATCH _latchDet;
        private VectorOfKeyPoint _modelKeypoints2;
        private Mat _modelDescriptors2;
        public StopSignDetector(IInputArray stopSignModel)
        {
                _modelKeypoints2 = new VectorOfKeyPoint();
                _modelDescriptors2 = new Mat();
                _latchDet.DetectAndCompute(redMask, null, _modelKeypoints2, _modelDescriptors2, false);
```

I will appreciate any feedback. Thanks in advance.

**Comment by emgucv** [comment]
Hi,
  
LATCH is only a descriptor calculator, and not a feature detector. Check the Open CV documentation here:
https://docs.opencv.org/trunk/d6/d36/classcv_1_1xfeatures2d_1_1LATCH.html

If it is not a feature detector, calling DetectAndCompute will result in error. 

You can use AKAZE, which is both a feature detector and a descriptor extractor.

**Comment by emgucv** [comment]
Closing ticket now.
