### ISSUE TITLE
Build Emgu.CV: CommonAssemblyInfo.cs could not be found

### ISSUE THREAD

**Issue by HNeukermans** [emgucv/emgucv#12]
I'm trying to build the Emgu.CV solution inside platform/windows.desktop
But I get this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'E:\Development\Net\emgucv\Emgu.CV.World\..\CommonAssemblyInfo.cs' could not be found.	Emgu.CV.World	E:\Development\Net\emgucv\Emgu.CV.World\CSC	1	Active

Any idea on how to fix this ?

**Comment by emgucv** [comment]
The CommonAssemblyInfo.cs file needed to be generated with CMake during project configuration.

Build instructions can be found here: http://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git

**Comment by watoo** [comment]
Dear @emgucv 
I'm getting the same error, Please provide some more details on how to use CMake to generate CommonAssemblyInfo.cs. 

I'm using visual studio 2015. And I'm trying to build the Emgu.CV solution inside platform/windows.desktop 

this [link](http://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git) says *You will need to install CMAKE in-order to build the unmanaged C++ code (OpenCV and cvextern.dll).* I have downloaded and unzpied CMake but don't know what to do next. There is no .exe file through which I can install it. 

I would be great if we can have step by step instructions on how to run project.
