### ISSUE TITLE
where is X86 dlls in version3.4?

### ISSUE THREAD

**Issue by hulumiaomiao** [emgucv/emgucv#121]
I did not find bin--X86 or X64 files and DLLS in more than 3.3 versions.But I didn't see any of these changes in the version update record.Why is that?

pre Thank you for reply

**Comment by emgucv** [comment]
The native files have been moved to the "libs\x86" and "libs\x64" folders in the release package.

**Comment by emgucv** [comment]
Closing ticket now.
