### ISSUE TITLE
CartToPolar does not accept IntPtr.Zero

### ISSUE THREAD

**Issue by illiteratePhD** [emgucv/emgucv#124]
In summary for CartToPolar:

...
//   magnitude:
//     The destination array of magnitudes, may be set to IntPtr.Zero if it is not needed
//
//   angle:
//     The destination array of angles, may be set to IntPtr.Zero if it is not needed.
//     The angles are measured in radians (0..2?) or in degrees (0..360?).
...

IntPtr.Zero is not an acceptable input on either of these. I assume that the intent is to create a Mat or Image with IntPtr.Zero as source but that is not clear.

**Comment by ArXen42** [comment]
Didn't find a way to disable angles either. And there is no magnitude function to do this.

**Comment by emgucv** [comment]
Thanks for point that out. The documentation for this function is out dated. It was carried over from a older version of Open CV. 

In the 3.4.1 release, you need to pass in an IOutputArray for Magnitudes and an IOutputArray for Angles, the computation can not be skipped.

**Comment by emgucv** [comment]
Closing ticket now.
