### ISSUE TITLE
ExMessage:OpenCV: clEnqueueWriteBuffer(q, (cl_mem)u->handle, CL_TRUE, dstrawofs, total, alignedPtr.getAlignedPtr(), 0, 0, 0) >= 0

### ISSUE THREAD

**Issue by 18628271760** [emgucv/emgucv#127]
Hi all,
I met a tricky exception when use EmguCV in a WPF project.  My project is a face recognize monitor application which compiled successfully and ran more than 3 days before. 
Unfortunately, during the second round performance test, an exception throw out as below: 

ExType:Emgu.CV.Util.CvException
ExMessage:OpenCV: clEnqueueWriteBuffer(q, (cl_mem)u->handle, CL_TRUE, dstrawofs, total, alignedPtr.getAlignedPtr(), 0, 0, 0) >= 0
ExSource:Emgu.CV.World

I put relevant source code as below:
 private void DetectFacesWithoutSave(Mat image)
        {
            lock (this)
            {
                OnFaceDetectionStateChanged(true);
                detectingInProgress = true;
                List<FaceFeatures> detectedFaces = new List<FaceFeatures>();

                var watch = Stopwatch.StartNew();
                using (var grayImage = new UMat())
                {
                    // Convert image to grayscale
                    CvInvoke.CvtColor(image, grayImage, Emgu.CV.CvEnum.ColorConversion.Bgr2Gray);

                    //normalizes brightness and increases contrast of the image
                    CvInvoke.EqualizeHist(grayImage, grayImage);

                    //Detect the faces  from the gray scale image and store the locations as rectangle in FaceFeature each
                    try
                    {
                        Rectangle[] facesDetected = faceClassifier.DetectMultiScale(grayImage, 1.1, 3, new Size(32, 32));
                        foreach (Rectangle facerect in facesDetected)
                        {
                            FaceFeatures face = new FaceFeatures(facerect, grayImage.Cols, grayImage.Rows, image);
                            detectedFaces.Add(face);
                        }                       
                    }
                    catch (Exception ex)
                    {
                        LogHelper.LogError(ex);
                    }
                }
                watch.Stop();
                lastDetectedFaces = detectedFaces;
                OnNoFaceDetectionStateChanged(false, detectedFaces, (int)watch.ElapsedMilliseconds, image);
                detectingInProgress = false;
                //counter = 0;
            }
        }

I searched such exception on stack-overflow, CSDN and other webs but found no good solution. 
Appreciate your feedback and solution.  TKS!

My E-mail: 847833088@qq.com

**Comment by emgucv** [comment]
It seems like a OpenCL code path issues with the OpenCL driver on your workstation. You can disable Open CL by calling 
`CvInvoke.UseOpenCL = false;`
before involving the code you listed above.

**Comment by Theoda** [comment]
> 
> 
> It seems like a OpenCL code path issues with the OpenCL driver on your workstation. You can disable Open CL by calling
> `CvInvoke.UseOpenCL = false;`
> before involving the code you listed above.

It definitely helps! Thanks.

It seems only Intel graphics might get this problem. Fortunately, it's solved.
