### ISSUE TITLE
DescriptorMatcher Missing Functions

### ISSUE THREAD

**Issue by jkanalakis** [emgucv/emgucv#128]
In OpenCV 3, the [DescriptorMatcher](https://docs.opencv.org/3.4.1/db/d39/classcv_1_1DescriptorMatcher.html) class has a function called match() in addition to the knnMatch() function as well as a train() function. However, I do not see the match() nor train() in the Emgu.CV version of DescriptorMatcher. Are these functions missing in or are they located in another class?

**Comment by emgucv** [comment]
Closing ticket now.
