### ISSUE TITLE
GC.AddMemoryPressure(StructSize.MIplImage) missing in Image.MapDataToImage()

### ISSUE THREAD

**Issue by pm-od** [emgucv/emgucv#13]
There are two places where an ImageHeader gets allocated using CvInvoke.cvCreateImageHeader(): Image.AllocateData() and Image.MapDataToImage(). The latter gets used if the Image is creatued using unmanaged memory. Both places use _imageDataReleaseMode = ImageDataReleaseMode.ReleaseHeaderOnly, either explicitely or implicitely (default value). 

But only Image.AllocateData() calls GC.AddMemoryPressure(StructSize.MIplImage), whereas Image.MapDataToImage() does not!

In both cases Image.DisposeObject() calls GC.RemoveMemoryPressure(StructSize.MIplImage);

So it seems like GC.AddMemoryPressure(StructSize.MIplImage) is missing in Image.MapDataToImage().

**Comment by emgucv** [comment]
Thanks for pointing that out. You are correct, memory pressure should be added in Image.MatDataToImage() function. It is fixed in commit: 3cd6fb7e815df746ce0646c983e965f7d160d501
