### ISSUE TITLE
Targets are not working in VS2017

### ISSUE THREAD

**Issue by JobaDiniz** [emgucv/emgucv#130]
In **V2017** the targets file does not work anymore. The native dll's are not copied to the output on build.

Any insights on how to resolve this?

Related: https://github.com/emgucv/emgucv/issues/23

**Comment by emgucv** [comment]
The nuget package in 4.3 release no longer use the ".targets" file. It is deploying the native binary by putting them into the "runtimes/{arch}/native/"  folder.

Closing ticket now.
