### ISSUE TITLE
Automatic Face Attendance Management system Using EmguCv

### ISSUE THREAD

**Issue by Hazim1** [emgucv/emgucv#136]
Hi Guys, i want to make a project on Automatic face attendance management system using Emgu Cv Winform.  this is my Final Year Project, but the problem is that, i have no tutorials, no material for that, and i'm on basic level, after three months i'll submit my project,  after the working 1/2 hours my eyes are tired and i'm unable to work more and unable to search material or write code,, due to that reason i'm unable to complete my project. kindly please some one help me for that;.

**Comment by emgucv** [comment]
Sorry about that. 

Your post is a request for help to build your application. 

This is an issues tracker. I am going to close this ticket now.
