### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dolevi101** [emgucv/emgucv#137]
Hi everyone,
when I try to build my project after I added all the references, as I saw in the example project you provided, I get that error message:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'VideoCapture' exists in both 'Emgu.CV.World.NetStandard1_4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Emgu.CV.World, Version=3.4.1.2976, Culture=neutral, PublicKeyToken=________________'	DLY_firstTry	c:\users\dolev\source\repos\DLY_firstTry\DLY_firstTry\Program.cs	18	Active

When I tried to remove either Emgu.CV.World or Emgu.CV.World.NetStandard1_4 refernce I got some other errors.
Thank you.

**Comment by emgucv** [comment]
You should not use both Emgu.CV.World.NetStandard1_4 and Emgu.CV.World.dll, they target different frameworks and mostly contains the same classes definitions. Please remove the .NetStandard1_4 references if you are developping for Windows Forms.

**Comment by emgucv** [comment]
Closing ticket now.
