### ISSUE TITLE
Stitching error when after SetWarper is called

### ISSUE THREAD

**Issue by footorama** [emgucv/emgucv#140]
indeed in stitching_c.cpp you have things like : 

	cv::detail::CompressedRectilinearWarper* ptr = new cv::detail::CompressedRectilinearWarper(scale);
	*creator = dynamic_cast<cv::WarperCreator*>(ptr);
	*rotationWarper = dynamic_cast<cv::detail::RotationWarper*>(ptr);

but cv::detail::CompressedRectilinearWarper does not inherit WarperCreator. It is another class : cv::CompressedRectilinearWarper that implement the Warper Creator.

It would be great if you can fix this.

Thanks

**Comment by emgucv** [comment]
Look like it has already been fixed in the current source code.

Thanks for pointing that out. Sorry that we haven't respond to your post sooner.
