### ISSUE TITLE
New Canny overload

### ISSUE THREAD

**Issue by linquize** [emgucv/emgucv#142]
2 years ago, a new Canny() overload is implemented.

```C++
void Canny(InputArray dx, InputArray dy, OutputArray edges, double threshold1, double threshold2, bool L2gradient = false);
```

But it is not wrapped in `cvextern`

https://github.com/opencv/opencv/commit/460b1dc2faf030c171fc2fd43ddb113bc800596e

**Comment by emgucv** [comment]
Pull request has been merged, thanks, closing the ticket now.
