### ISSUE TITLE
Do you plan to have UWP available as open source license?

### ISSUE THREAD

**Issue by rpysork** [emgucv/emgucv#15]
Related to this issue (https://github.com/emgucv/emgucv/issues/10) but since the issue is closed already. 

Do you plan to have UWP available as open source license?
If so, what is the time frame?

**Comment by emgucv** [comment]
Hi rpysork, 

The UWP release is only available under the commercial license. We do not have a plan to release it under open source license in the near future. 

Best regards,

Canming
