### ISSUE TITLE
System.AccessViolationException when using OgjectnessBING class.

### ISSUE THREAD

**Issue by mauja** [emgucv/emgucv#154]
I am getting an access violation, when calling the "SetTrainingPath()" method of the "ObjectnessBING" class.

My environment is: Windows 10 / Visual Studio 17 / EMGU.CV v3.4.1.2976

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Emgu.CV;
using Emgu.CV.Util;
using Emgu.CV.Saliency;

namespace EmguError
{
    class Program
    {
        static void Main(string[] args)
        {
            ObjectnessBING objectnessBING = new ObjectnessBING();
            objectnessBING.SetTrainingPath("C:/TEMP/ObjNessB2W8HSV.idx.yml");
        }
    }
}`

**Comment by emgucv** [comment]
The path "C:/TEMP/ObjNessB2W8HSV.idx.yml" is not a valid path on Windows. 
Windows system path should look something like: "C:\\TEMP", please give this a try. (I have tested with the latest development code using "C:\\TEMP" as the training path and it do not cause an access violation.

**Comment by mauja** [comment]
…I found the development code on Git, but got the error shown below, when I used a Git GUI on my desktop, to download it.

I see the next step is to run:


git submodule update --init --recursive

But, I am not sure this will work, given the prior error.


[cid:image003.png@01D433F6.73C50490]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mauja** [comment]
I built the latest emgucv project locally, and confirmed that the issue is resolved.
