### ISSUE TITLE
tesseract_ccutil build fails

### ISSUE THREAD

**Issue by Garonenur** [emgucv/emgucv#155]
the current master fails to build with lots of errors in tesseract_ccutil (mainblk.cpp).

VS 2017, windows 10

this leads to cvextern failing, as it can not link tesseract_ccutil.lib

**Comment by Garonenur** [comment]
setting tesseract-ocr to the most recent commit in the emgucv_4.0.0-beta.3 branch fixes this problem.
please update the submodule.

**Comment by emgucv** [comment]
Thanks for pointing out, fixed in this commit:
40d993a027a404ac461183ca76d362477352fd5a
