### ISSUE TITLE
Missing files in Emgu.CV.World?

### ISSUE THREAD

**Issue by mlstudies** [emgucv/emgucv#156]
I am now compiling the latest version of EmguCV. At 99%, many file-not-found errors are reported. I checked the repo, the Emgu.CV.World folder inde contain these files. 

![](https://i.stack.imgur.com/VJdnd.jpg)

`
[ 99%] Building ../../../../libs/Emgu.CV.World.dll
Microsoft (R) Visual C# Compiler version 2.7.0.62620 (e873e693)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Brisk.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Moments.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/Filters/CudaSobelFilter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/PInvoke/CvType/MDMatch.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Tiff/TiffWriter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Contrib/ImgHash/AverageHash.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/Android/AndroidFileAsset.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Video/FarnebackOpticalFlow.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/DisposableObject.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/DescriptorMatcher.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/EventArgs.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/GpuMat.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/MomentsGenerated.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/FastDetector.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/ICodeGenerable.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Tiff/TileTiffWriter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/IInterpolatable.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/Platform.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Feature2D.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/GpuMatGenerated.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Ocl/Device.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/PInvoke/CvType/MIplImage.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Video/KalmanFilter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/Toolbox.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Features2DInvoke.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/TimedImage.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/PinnedArray.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/TypeEnum.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Features2DTracker.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/Imgproc/CudaCannyEdgeDetector.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Ocl/DeviceGenerated.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/FlannBasedMatcher.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/UnmanagedObject.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Contrib/ImgHash/BlockMeanHash.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/CameraCalibration/Quaternions.cs' could not be found. 

```

**Comment by mlstudies** [comment]
Urgent! Anyone knows how to solve this issue?

**Comment by mlstudies** [comment]
The compiler is complaining it cannot find the files. There is nothing under the folder Emgu.CV.World on github. Please have a look!

~[](https://camo.githubusercontent.com/e654ac43762adf4d749f6e7b45b76dfccc878271/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f5230754e4c2e706e67)

**Comment by mauja** [comment]
Try using [https://desktop.github.com/](url) to clone the repository.

Also, note the ".." in the path to the missing files, it indicates you need to go up one level in the directory tree. For example [https://github.com/emgucv/emgucv/tree/master/Emgu.CV/CameraCalibration](url) contains the .cs files.

**Comment by emgucv** [comment]
If you are using the master branch, please let us know the commit tag you are using and we will take a look. The development code is constantly changing and Ubuntu compilation may have issues from time to time. 

I can confirm that the current master at 0ee48dc330471157f926741c635d120bebaf882e can be compiled on Ubuntu 18.04 with no issues.

Please use a tagged release if the master branch cannot be compiled.

**Comment by emgucv** [comment]
FYI, The Emgu.CV.World folder is supposed to be empty. It references the shared projects from Emgu.CV and Emgu.Util folders. The source codes are located in the Emgu.CV and Emgu.Util folder.

**Comment by emgucv** [comment]
Closing ticket now.
