### ISSUE TITLE
emgucv.sln not in the root folder.

### ISSUE THREAD

**Issue by mauja** [emgucv/emgucv#157]
I am following the 64-bit Windows build instructions, found here:
[http://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git](url)

The instructions specify that emgucv.sln should be in the root folder.

The only emgucv.sln, that I can find, is in the "root/b" folder.
E.g.: "C:\Users\mauja\Projects\GitHub\emgucv\b\emgucv.sln"

Furthermore, running "Build_Binary_x86-64_doc.bat" twice, as the instructions specify, does not put the emgucv.sln file, in the root folder.

Is it okay to use the one under the "b" subdirectory?

**Comment by Garonenur** [comment]
I found it there, too, and it usually works. The library files then end up under root\libs if you follow the instructions.
The instructions should be modified.

**Comment by mauja** [comment]
I have gotten the build to work, for Windows x64 platforms. The steps are below.

Steps:
1)	Get the latest emgucv project, from GitHub.
2)	Open cmd.exe and run “Build_Binary_x86-64_doc.bat”
3)	Open “GitHub\emgucv\b\emgucv.sln”
4)	Select only “cvextern”, and build Release x64 version.
5)	Select “ALL_BUILD” and build Release x64.
6)	Note that the output NuGet package is in "GitHub\emgucv\platforms\nuget"
7)	Note that to use this NuGet package, your C# app must be configured to target the x64 platform.
