### ISSUE TITLE
Watershed function

### ISSUE THREAD

**Issue by nana88** [emgucv/emgucv#16]
Hello,

This is my first time using EmguCV. If I make any mistakes, please forgive me...
I would like to apply Watershed function but I've got a blank (white) output. I copied this example code from the internet. I don't know what else I could do, please help me.

 `Image<Bgr, Byte> image = new Image<Bgr, byte>("input.jpg");`
`Image<Gray, Int32> marker = new Image<Gray, Int32>(image.Width, image.Height);`
`Rectangle rect = image.ROI;`
`marker.SetZero();`
`marker.Draw(new CircleF(new PointF(rect.Left + rect.Width / 2.0f, rect.Top + rect.Height / 2.0f),
                  (float)(Math.Min(image.Width, image.Height) / 4.0f)),
               new Gray(255),
               0);`
`CvInvoke.Watershed(image, marker);`

**Comment by emgucv** [comment]
Hi, 

A quick look at your code, if you use marker as the output of the watershed function, the drawing code will be completely wiped out. So it will be the same as if you just call:

Image<Bgr, Byte> image = new Image<Bgr, byte>("input.jpg");
Mat marker = new Mat()
CvInvoke.Watershed(image, marker);

A typical requirement for Watershed function's input, as documented:

Before passing the image to the function, you have to roughly outline the desired regions in the image markers with positive (>0) indices. So, every region is represented as one or more connected components with the pixel values 1, 2, 3, and so on. Such markers can be retrieved from a binary mask using findContours and drawContours (see the watershed.cpp demo). The markers are "seeds" of the future image regions. All the other pixels in markers , whose relation to the outlined regions is not known and should be defined by the algorithm, should be set to 0's. In the function output, each pixel in markers is set to a value of the "seed" components or to -1 at boundaries between the regions.

You will need to make sure your image satisfy the requirements (which seems not in your case).
