### ISSUE TITLE
SuperpixelSLIC cannot be created

### ISSUE THREAD

**Issue by martinbur** [emgucv/emgucv#162]
There is a parameter missing in the call of the opencv function. That is why always an error is returned. See the source code I found in emgucv. The "algorithm" is not forwarded.

cv::ximgproc::SuperpixelSLIC* cveSuperpixelSLICCreate(cv::_InputArray* image, int algorithm, int regionSize, float ruler)
{
	cv::Ptr<cv::ximgproc::SuperpixelSLIC> ptr = cv::ximgproc::createSuperpixelSLIC(*image, regionSize, ruler);
	ptr.addref();
	return ptr.get();
}

**Comment by emgucv** [comment]
Thanks for the report.

Fixed in the following commits:
38105b132f31b95fd728936688136f02e41c77de
7d054f6917e7c7a3fad626ac837323dd236d38ed

It will be included in the next release.

**Comment by emgucv** [comment]
Closing ticket now.
