### ISSUE TITLE
Emgu.CV.VideoWriter isOpened at False

### ISSUE THREAD

**Issue by cxjacquel** [emgucv/emgucv#164]
Hello, 

On Android 6.0 XPeria Sony; Impossible to register a video file. 
The VideoWriter is not opened? 

I use : Emgu.CV.VideoWriter.Fourcc('H', '2', '6', '4')

Could you help ?
Thx

**Comment by emgucv** [comment]
Open CV do not implement VideoWriter class on Android devices. It is an empty class and "IsOpen" will always return false on Android. As a result, Emgu CV's VideoWriter will have the same behavior as the class it wrapped.

**Comment by emgucv** [comment]
If you need to write video files on Android, please consider converting the Mat/Image file to native Android Bitmap class, and use native android sdk to write Bitmap files to Video file.
This class may help but we have not tried:

**Comment by emgucv** [comment]
Closing ticket now.
