### ISSUE TITLE
RTrees GetVotes Implementation?

### ISSUE THREAD

**Issue by mtriff** [emgucv/emgucv#166]
Hello,

Do you plan on exposing the RTrees.GetVotes method? (OpenCV docs: https://docs.opencv.org/3.4.3/d0/d65/classcv_1_1ml_1_1RTrees.html#a46cd96dee4738c07899067344efe2956)

If so, will it be included in the next release?

Thank you.

**Comment by emgucv** [comment]
Added in the following commit:
59c3cc5a0c38e7150f9bd2a6724ca791148166e2

It will be included in the 4.x release.

**Comment by mtriff** [comment]
Awesome, thank you. Do you have a planned ETA for the 4.x release?
