### ISSUE TITLE
Net Standard

### ISSUE THREAD

**Issue by bernd5** [emgucv/emgucv#17]
Hi guys,

I would like if we could make emguCV netstandard compatible. There is just one bug issue. All platform switches refer to to the real platforms.
With this i mean all the compiler switches like "#if __ANDROID__" ...

It would be much better if we would define new platform independent compiler switches like:
- SYSTEM_DRAWING_BITMAP_SUPPORTED

Kind regards,

Bernd

**Comment by emgucv** [comment]
Hi Bernd, 

We prefer to use predefined compiler macros rather than creating new ones. Using predefined compiler macro allows the shared project to be included for different platforms without the need to ask the host project to add additional definition in the project properties. 

If we are to use custom defined flags, all the host project that include the shared project will need to set several different flags in the project property, which can be a hassle to remember (e.g. what flags to be defined to Android, what flags to be defined for iOS etc).

Best regards,

Canming

**Comment by bernd5** [comment]
I absolutely agree that it would be really nasty if you had to define some flags in your property files...
What I mean is that you define platform spefic flags in one global MSBuild file.

The real problem with the current implementation is that we have to check the whole framework code to add a new platform.
So my idea is to create an abstraction layer, which defines which platform support which features.

This could be done by a MSBuild-Task:

Example:
`
<Target Name="SetupDefineConstants" BeforeTargets="Build">
    
    <PropertyGroup>
      <ExpandedDefineConstants>;$(DefineConstants);</ExpandedDefineConstants>
    </PropertyGroup>
    
    
    <PropertyGroup>
      
      <FeaturePlatform>NET_FRAMEWORK</FeaturePlatform>
    </PropertyGroup>
    <PropertyGroup Condition="$(ExpandedDefineConstants.Contains(';NETCOREAPP1_1;'))">
      <FeaturePlatform>NETCORE</FeaturePlatform>
    </PropertyGroup>
    <PropertyGroup Condition="$(ExpandedDefineConstants.Contains(';__ANDROID__;'))">
      <FeaturePlatform>ANDROID</FeaturePlatform>
    </PropertyGroup>
    <PropertyGroup Condition="$(ExpandedDefineConstants.Contains(';__IOS__;'))">
      <FeaturePlatform>IOS</FeaturePlatform>
    </PropertyGroup>
    

    
    <PropertyGroup Condition="'$(FeaturePlatform)' == 'IOS'">
      <Feature_UIKit>True</Feature_UIKit>
      <Feature_Serialisation>True</Feature_Serialisation>
      
    </PropertyGroup>
    <PropertyGroup Condition="'$(FeaturePlatform)' == 'NET_FRAMEWORK'">
      <Feature_SystemDrawing>True</Feature_SystemDrawing>
      <Feature_Serialisation>True</Feature_Serialisation>
      <Feature_UIKit>False</Feature_UIKit>
    </PropertyGroup>


    
    <PropertyGroup Condition="'$(Feature_SystemDrawing)' == 'True'">
      <DefineConstants>$(DefineConstants);SYSTEM_DRAWING_BITMAP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Feature_Serialisation)' == 'True'">
      <DefineConstants>$(DefineConstants);SYSTEM_SERIALISATION</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Feature_UIKit)' == 'True'">
      <DefineConstants>$(DefineConstants);UIKIT</DefineConstants>
    </PropertyGroup>
    

    <Message Text="DefineConstants: $(DefineConstants)" />
  </Target>
`

**Comment by bernd5** [comment]
A simpler way would be to use ItemLists for all the features like:

```
<!-- Feature Mapping of each Platform -->
    <ItemGroup Condition="'$(FeaturePlatform)' == 'IOS'">
      <PlatformFeature Include="UIKit" />
      <PlatformFeature Include="Serialisation" />
    </ItemGroup>
    <ItemGroup Condition="'$(FeaturePlatform)' == 'ANDROID'">
      <PlatformFeature Include="AndroidBitmap" />
    </ItemGroup>
    <ItemGroup Condition="'$(FeaturePlatform)' == 'NET_FRAMEWORK'">
      <PlatformFeature Include="SystemDrawing" />
      <PlatformFeature Include="Serialisation" />
    </ItemGroup>
```
