### ISSUE TITLE
CvInvoke.Threshold documentation is wrong

### ISSUE THREAD

**Issue by illiteratePhD** [emgucv/emgucv#171]
From emgu API docs for Threshold

> src
> Type: Emgu.CV.IInputArray
> Source array (single-channel, 8-bit of 32-bit floating point).
> dst
> Type: Emgu.CV.IOutputArray
> Destination array; must be either the same type as src or 8-bit.

Looking at the same from OpenCV

> src | input array (multiple-channel, 8-bit or 32-bit floating point).
> dst | output array of the same size and type and the same number of channels as src.

Calling Threshold and always using byte as output format will lead to failures when input format is not byte.

**Comment by emgucv** [comment]
Thanks for the report. It has been fixed now.

**Comment by AhmadEgb** [comment]
**Please, could you review my report! I can't continue programming without fixing that bug!**

**Comment by emgucv** [comment]
This has already been fixed in the Git repo. Please see the 2nd comment from above. It will be included in the next v4.0 release.
