### ISSUE TITLE
CvInvoke.PutText shows garbled characters when Chinese is passed in

### ISSUE THREAD

**Issue by crybigsea** [emgucv/emgucv#176]
Hello:

I have this example code:
`
CvInvoke.PutText(img,"你好，世界！", new System.Drawing.Point(10, 80),  FontFace.HersheyComplex, 1.0, new Bgr(0, 255, 0).MCvScalar);
`
When I run the program, the screen displays a string of question marks like this:"?????????".
Is this a problem with character encoding?

Thanks! :-)

**Comment by emgucv** [comment]
Open CV's PutText function do not support Unicode. 
See this:
http://answers.opencv.org/question/86997/how-can-i-put-text-on-image-using-opencv-puttext-function/

**Comment by crybigsea** [comment]
thinks...
