### ISSUE TITLE
Ability to set theRNG.state missing

### ISSUE THREAD

**Issue by illiteratePhD** [emgucv/emgucv#185]
I would like to use opencv's randu and randn methods but a key functionality for random data is currently missing in EMGU CV and that is the possibility to set the randomization seed. Especially for testing purposes this is essential and unfortunately this oversight basically disqualifies the wrapper methods completely. The functionality exists (see link below) in OpenCV but is currently not exposed (as far as I am able to see at least). 

[theRNG in OpenCV](https://docs.opencv.org/3.4/d2/de8/group__core__array.html#ga75843061d150ad6564b5447e38e57722)

**Comment by emgucv** [comment]
Added RNG class in this commit: cb359129ba550a83479ec51a609140b0dd1b17dd

**Comment by illiteratePhD** [comment]
Fantastic!

**Comment by emgucv** [comment]
Closing ticket now.
