### ISSUE TITLE
unresolved  Freetype build error

### ISSUE THREAD

**Issue by SteveFaultless** [emgucv/emgucv#186]
I'm following the instructions at:
http://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git

Everything goes smoothly until I try building the cvextern project. I get the error:

`185 unresolved external symbol hb_ft_font_create referenced in function "public: virtual void __cdecl cv::freetype::FreeType2Impl::loadFontData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)" (?loadFontData@FreeType2Impl@freetype@cv@@UEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z)`

I've googled for the error, but it seems to have been solved in OpenCV around 2016:
https://github.com/opencv/opencv_contrib/issues/919

Other people seem to have had trouble, and I've had various troubles with freetype in the past - I saw it flash by during configuration and thought "oh no, it has freetype."

I don't need to write text for my application, so any suggestions at all, even if they break freetype, are welcome.

**Comment by emgucv** [comment]
Should have been fixed now, through a few commits such as follows:
e21abd3a15cdcc99b01bf5918385799325e0d28d 
b1d31d81a079a28f9b138dd672ad98fe005769e9
1b35a7cf492fa4ee29f8ab02d3085c9fabf45148
2a3b73dc386d4e42653cb2246c815a3163e7ecc4

I have tested with 2a3b73dc386d4e42653cb2246c815a3163e7ecc4 and compilation goes through without issues.

**Comment by emgucv** [comment]
Closing ticket now.
