### ISSUE TITLE
CvInvoke.GrabCut has problem

### ISSUE THREAD

**Issue by EugenyNews** [emgucv/emgucv#190]
I try transfer to GrabCut mask with regions for add\remove on source image:
Matrix<double> bgdModel_mask = new Matrix<double>(1, 13 * 5);
Matrix<double> fgdModel_mask = new Matrix<double>(1, 13 * 5);
Image<Gray, byte> mask_mask = new Image<Gray, byte>(img.Size);

Emgu.CV.Structure.Gray g_add = new Gray(3);
Emgu.CV.Structure.Gray g_remove = new Gray(2);

for (int i = 0; i < pictureBox1.Image.Width; i++)
{
    for (int j = 0; j < pictureBox1.Image.Height; j++)
    {
        Color cl_ = new_image.GetPixel(i, j);
        if ((cl_.R == Color.Red.R) && (cl_.B == Color.Red.B) && (cl_.G == Color.Red.G))
            mask_mask[j, i] = g_add;
        if ((cl_.R == Color.Blue.R) && (cl_.B == Color.Blue.B) && (cl_.G == Color.Blue.G))
            mask_mask[j, i] = g_remove;
    }
}
CvInvoke.GrabCut(img, mask_mask, rect, bgdModel_mask, fgdModel_mask, 2,
                 //Emgu.CV.CvEnum.GrabcutInitType.InitWithMask |
                 Emgu.CV.CvEnum.GrabcutInitType.InitWithRect
                );
CvInvoke.GrabCut(img, mask_mask, rect, bgdModel_mask, fgdModel_mask, 2, Emgu.CV.CvEnum.GrabcutInitType.Eval);
using (ScalarArray ia_mask = new ScalarArray(3))
    CvInvoke.Compare(mask_mask, ia_mask, mask_mask, Emgu.CV.CvEnum.CmpType.Equal);

Image<Bgr, byte> result3_mask = new Image<Bgr, byte>(img.Width, img.Height);
img.Copy(result3_mask, mask_mask);
pictureBox2.Image = (result3_mask).ToBitmap();

if not set flag Emgu.CV.CvEnum.GrabcutInitType.InitWithMask, regions for add\remove not affect on the result, if flag Emgu.CV.CvEnum.GrabcutInitType.InitWithMask included, fired: Emgu.CV.Util.CvException: 'OpenCV: totalSampleCount > 0'

**Comment by emgucv** [comment]
Can you save the image files that was send to the GrabCut function and upload it here?
That will simply the test code and narrow down the scope.

FYI, our v3.4.3 release was tested against the following grab-cut unit-test and they pass the tests before the release:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Test/AutoTestVarious.cs#L2092 
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Test/AutoTestVarious.cs#L2109

**Comment by emgucv** [comment]
Closing ticket now.
