### ISSUE TITLE
.SmoothGaussian Ram issue

### ISSUE THREAD

**Issue by Ahmad-Agbaria** [emgucv/emgucv#192]
I  have about 100 images, So I started sending them one by one to the ProcessImage function. and it keeps using so much Ram until it reaches around 5-GB and then my program crashes As mentioned: .SmoothGaussian performs Gaussian Smoothing in the current image and returns the result.

Please Note:I started removing some parts of my code, until I reached a point where I was 100% that, my Ram issue is caused by the highlighted line of code in specific! Also I am using Emgu CV version 3.4.3

I tried typing both: temp.Dispose(); and temp=null(); after declaring it but didn't work!
My code could be found here:
https://stackoverflow.com/questions/53875995/emgu-cv-ram-issue

**Comment by emgucv** [comment]
Works well with your image, using this code:

**Comment by emgucv** [comment]
Closing ticket now.
