### ISSUE TITLE
Ubuntu 18.4 , how open with monodevelop?

### ISSUE THREAD

**Issue by R0BER** [emgucv/emgucv#193]
Hi.
I have followed the instructions and can run the examples.
When I execute them, it runs perfect.
Now as I open it with monodevelop for ubuntu, I do not know where the example is.

inside Solution folder:
Android
Crossplataform
ios
mac
windows desktop
windows store

But, I do not know which one to use.
Thank you very much, the examples look great.
And sorry for my bad English

**Comment by emgucv** [comment]
Mono develop is not longer suported.

Closing ticket now.
