### ISSUE TITLE
Problems rotating large resolution images

### ISSUE THREAD

**Issue by Dooh0126** [emgucv/emgucv#196]
Hi
An exception occurred while using Emgu.CV.Image.Rotate.
Please let me know what the problem is.

Environment
```
windows10
visual studio 2017
.net framework 4.7
nugeeeeeeeeeeet package EMGU.CV  3.4.3.3016
image reeeeeeeeesolution 4096 x 32768
```

 Code used
```
Image<Structure.Gray, byte> image = new Image<Structure.Gray, byte>(path);
image = image.Rotate(90, new Structure.Gray(), false);
```

Exceptions and StackTrace.
```
ex	{"External component has thrown an exception."}	System.Exception {System.Runtime.InteropServices.SEHException}
Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
ErrorCode	-2147467259	int
HResult	-2147467259	int
HelpLink	null	string
InnerException	null	System.Exception
Message	"External component has thrown an exception."	string
Source	"Emgu.CV.World"	string
TargetSite	{Void cveWarpAffine(IntPtr, IntPtr, IntPtr, System.Drawing.Size ByRef, Int32, Emgu.CV.CvEnum.BorderType, Emgu.CV.Structure.MCvScalar ByRef)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
StackTrace
   at Emgu.CV.CvInvoke.cveWarpAffine(IntPtr src, IntPtr dst, IntPtr mapMatrix, Size& dsize, Int32 flags, BorderType borderMode, MCvScalar& fillval)
   at Emgu.CV.CvInvoke.WarpAffine(IInputArray src, IOutputArray dst, IInputArray mapMatrix, Size dsize, Inter interpMethod, Warp warpMethod, BorderType borderMode, MCvScalar borderValue)
   at Emgu.CV.Image`2.WarpAffine(Mat mapMatrix, Int32 width, Int32 height, Inter interpolationType, Warp warpType, BorderType borderMode, TColor backgroundColor)
   at Emgu.CV.Image`2.Rotate(Double angle, PointF center, Inter interpolationMethod, TColor background, Boolean crop)
   at Emgu.CV.Image`2.Rotate(Double angle, TColor background, Boolean crop)
```

**Comment by emgucv** [comment]
Tested to work with the following code:

```

**Comment by FelixKras** [comment]
The image is apparently 128MB ... 
I wouldn't expect it to work... maybe consider splitting to patches and doing them separately

**Comment by Dooh0126** [comment]
emgucv!
Thanks for the reply.
I checked it too late.
I checked with the test code you gave me.
At 4096 x 32768 resolution, the same exception stack appears.
I adjusted the width and height and checked again.
Perhaps there is a problem with height size.
The width is fixed to 4096 and the height is set to 32766, which works normally.
Please confirm.
Should this issue be closed?

FelixKras!
Thanks for the reply.
I totally agree with you.
Maybe this problem is solved.

**Comment by emgucv** [comment]
The Rotate function call cv::remap, and cv::remap check image size is no more than 32768 (SHRT_MAX). 
https://github.com/emgucv/opencv/blob/master/modules/imgproc/src/imgwarp.cpp#L1729 
If the size is not less than 32768, it will throw exception, but in this case, because Concurrently is used, it is crashing the threads. 

Please use image size (width or height) less than 32768.
