### ISSUE TITLE
EmguCV Unity osx

### ISSUE THREAD

**Issue by Marsgames** [emgucv/emgucv#199]
Hey,

Is there a way to use emgucv for Unity with osx ? 

When I try to compile platforms/osx I got a large amount of errors.
When I try to use the emgucv.bundle inside Emgu.CV.Unity folder, it seems be empty.

I don't really know where to start.

Thank you for your help.

**Comment by emgucv** [comment]
Emgu CV for Unity is available to be purchased from the Unity Asset store:
https://assetstore.unity.com/packages/tools/particles-effects/emgu-cv-v3-x-24681
All the component are pre-compiled and packaged up for you.

**Comment by emgucv** [comment]
Closing ticket now.
