### ISSUE TITLE
FastDetector.DetectAndCompute excepts but DetectRaw + Compute works.

### ISSUE THREAD

**Issue by ipeerbhai** [emgucv/emgucv#2]
Hello,

I'm trying to make a FAST detector, using this code from the site:
http://www.emgu.com/wiki/index.php/FAST_feature_detector_in_CSharp
but updating the code to work with the 3.1 NuGet package.

This will crash in Emgu.CV.World.dll with no useful information -- If I comment out DetectAndCompute, and uncomment DetectRaw and Compute, it works a little longer( routine still crashes, but at a different point ):

public static Mat DrawFAST(Mat modelImage, Mat observedImage)            
             Mat homography = new Mat();

            FastDetector fastCPU = new FastDetector(10, true);
            VectorOfKeyPoint modelKeyPoints = new VectorOfKeyPoint();
            VectorOfKeyPoint observedKeyPoints = new VectorOfKeyPoint();

            BriefDescriptorExtractor descriptor = new BriefDescriptorExtractor();
            VectorOfVectorOfDMatch matches = new VectorOfVectorOfDMatch();

            Mat mask = null;
            int k = 2;
            double uniquenessThreshold = 0.8;

            //extract features from the object image
            //fastCPU.DetectRaw(modelImage, modelKeyPoints);  // This would work
            Mat modelDescriptors = new Mat();
            //descriptor.Compute(modelImage, modelKeyPoints, modelDescriptors); // This would work

            fastCPU.DetectAndCompute(modelImage, null, modelKeyPoints, modelDescriptors, false); // This will crash, but I don't see why.

**Comment by emgucv** [comment]
Hi, Fast is a Feature detector and not a Descriptor extractor. Therefore calling DetectAndCompute is expected to failed (should throw exception, and if not caught, results in crash). This is the expected behavior. 

Calling fastCPU.DetectRaw should work (extract feature points with FAST)
Calling descriptor.Compute should work (compute descriptor with Brief using the Fast keypoints)

I have just tested them on the Git master branch and it works but it should also works for the 3.1-r16.12.

**Comment by ipeerbhai** [comment]
Ahh, thanks.   I went and updated the sample code linked earlier to the 3.x classes, and get a crash on this call:  Features2DToolbox.VoteForUniqueness(matches, uniquenessThreshold, mask);  Same thing -- First chance exception, if I mark the exception for catching, I crash the debugger.

Here's the full function:
        public Mat DrawFAST(Mat modelImage, Mat observedImage)
        {
            Mat homography = new Mat();

            FastDetector fastCPU = new FastDetector(10, true);
            VectorOfKeyPoint modelKeyPoints = new VectorOfKeyPoint();
            VectorOfKeyPoint observedKeyPoints = new VectorOfKeyPoint();

            BriefDescriptorExtractor descriptor = new BriefDescriptorExtractor();
            VectorOfVectorOfDMatch matches = new VectorOfVectorOfDMatch();

            Mat mask = null;
            int k = 2;
            double uniquenessThreshold = 0.8;

            //extract features from the object image
            fastCPU.DetectRaw(modelImage, modelKeyPoints);
            Mat modelDescriptors = new Mat();
            descriptor.Compute(modelImage, modelKeyPoints, modelDescriptors);

            // extract features from the observed image
            fastCPU.DetectRaw(observedImage, observedKeyPoints);
            Mat observedDescriptors = new Mat();
            descriptor.Compute(observedImage, observedKeyPoints, observedDescriptors);
            BFMatcher matcher = new BFMatcher(DistanceType.L2);
            matcher.Add(modelDescriptors);

            matcher.KnnMatch(observedDescriptors, matches, k, null);
            mask = new Mat(matches.Size, 1, DepthType.Cv8U, 1);
            mask.SetTo(new MCvScalar(255));
            Features2DToolbox.VoteForUniqueness(matches, uniquenessThreshold, mask); // Crashes here:

            int nonZeroCount = CvInvoke.CountNonZero(mask);
            if (nonZeroCount >= 4)
            {
                nonZeroCount = Features2DToolbox.VoteForSizeAndOrientation(modelKeyPoints, observedKeyPoints, matches, mask, 1.5, 20);
                if (nonZeroCount >= 4)
                    homography = Features2DToolbox.GetHomographyMatrixFromMatchedFeatures(
                    modelKeyPoints, observedKeyPoints, matches, mask, 2);
            }

            //Draw the matched keypoints
            Emgu.CV.Mat result = new Emgu.CV.Mat();
            Emgu.CV.Features2D.Features2DToolbox.DrawMatches(modelImage, modelKeyPoints, observedImage, observedKeyPoints,
               matches, result, new Emgu.CV.Structure.MCvScalar(255, 0, 0), new Emgu.CV.Structure.MCvScalar(255, 0, 0), mask);

            return result;
        }

**Comment by Ber123** [comment]
prompt, how to make this function work?

**Comment by DaMo123** [comment]
Did you make this method work @ipeerbhai ?
