### ISSUE TITLE
Unable to compile emgucv on osx 10.12.3

### ISSUE THREAD

**Issue by whitefire** [emgucv/emgucv#20]
Errror-message:

Linking CXX shared library ../bin/libcvextern.dylib
ld: library not found for -lgphoto2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libcvextern.dylib] Error 1
make[1]: *** [Emgu.CV.Extern/CMakeFiles/cvextern.dir/all] Error 2
make: *** [all] Error 2

**Comment by emgucv** [comment]
Just tested with the 3.2 release tag and works. Please give it a try.

**Comment by whitefire** [comment]
[100%] Linking CXX shared library ../bin/libcvextern.dylib
ld: library not found for -lgphoto2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libcvextern.dylib] Error 1
make[1]: *** [Emgu.CV.Extern/CMakeFiles/cvextern.dir/all] Error 2
make: *** [all] Error 2

**Comment by emgucv** [comment]
May be your Mac do not have the GPhoto2 library installed?

Our commercial release for Mac was build with the 3.2 Tag and do not have this issue. However, our Mac does contain the GPhoto2 library. That may be the reason why I am not able to reproduce your error message. If this continue to cause problem to you, please make sure GPhoto2 library is installed. 

An easier solution for you may be to disable GPhoto2 support when building Emgu CV.  You can do this by appending "-DWITH_GPHOTO2:BOOL=OFF" to the end of cmake configuration script in the "platform/osx/configure" file.

**Comment by whitefire** [comment]
After disabling the gphoto2-library, emgucv compiled successfully. However some underlying native library crashes every time I attempt to run Mono.

At this point I find myself rather disencouraged and have decided to tinker with something else instead. This is of course not your fault in any way. My disencouragement is my own! :)

Thank you so much for your assistance.

**Comment by emgucv** [comment]
Are you building for OSX universal architecture and developing application with Xamarin Mac / Xamarin Forms? Starting with the 3.2 release, Xamarin Mac / Xamarin Forms using "Visual Studio for Mac" or "Xamarin Studio" are the recommended way to develop for Mac. The old way of building 32-bit binary with Mono is no longer supported/recommend. 

FYI, if you are interested, you can send an email to support@emgu.com to request a pre-compiled evaluation copy of Emgu CV 3.2 for Mac. We have tested the package and all the included demo programs work as expected.

Best regards,
Canming
