### ISSUE TITLE
Missing method KNearest.FindNearest()

### ISSUE THREAD

**Issue by MBulli** [emgucv/emgucv#200]
The [findNearst](https://docs.opencv.org/3.4.4/dd/de1/classcv_1_1ml_1_1KNearest.html#a312f975c24725b57200e221a97474b45) method of the [KNearest class](https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Extern/ml/ml.cpp#L100) is missing in Emgu.Cv

Are there technical reasons or just not yet added to the API?

(I'm using Emgu.CV 3.4.3.3016)

**Comment by emgucv** [comment]
Just added in this commit 5132db5da6fc580e1c40049f42a2965e7c179014

**Comment by MBulli** [comment]
Thank you very much! :)

**Comment by emgucv** [comment]
Closing ticket now.
