### ISSUE TITLE
Missing method Aruco.CalibrateCameraCharuco

### ISSUE THREAD

**Issue by figman123456** [emgucv/emgucv#201]
Can't find the function, is there a reason why its not implemented or just been missed out by mistake?

EMGU 3.4.3

**Comment by emgucv** [comment]
It has just been added with this commit 9a440871bbf0c3c654bfa5b7cd22b1cd23c27aa8

**Comment by figman123456** [comment]
Thank you very much for such a fast response i had manged to build a version myself but I will build the official commit now its been added!
