### ISSUE TITLE
Imdecode of jp2k sometimes takes 10 seconds

### ISSUE THREAD

**Issue by FelixKras** [emgucv/emgucv#203]
I'm decoding a stream of jp2k images from an Ethernet source
99% of the time it is performing ok (~20 msec, for 640x480 images on my machine)
but sometimes it takes 10000 ± 20 msec for just the imdecode function (exactly 10 sec, never less or more)

it'd be great if someone has any information or can locate and fix this issue

**Comment by emgucv** [comment]
Does the delay happens when the jp2k images are on the local disk?

**Comment by FelixKras** [comment]
The images come from ethernet and passed to Imdecode as byte array - I'm decoding in memory so no hardware lags are at fault.

the code:

`Stopwatch sw = Stopwatch.StartNew()
CvInvoke.Imdecode(bytearray_Image,ImreadModes.GrayScale,mat_DecodedImg);
var l=sw.ElapsedMilliseconds;
if(l>2000)
{
Debug.WriteLine($"Imdecode took too long {sw.ElapsedMilliseconds}");
}`


99 percent of the time its ok, once in a while i get ~10,000 milliseconds

**Comment by FelixKras** [comment]
The images come from ethernet and passed to Imdecode as byte array - I'm decoding in memory so no hardware lags are at fault.

the code:

Stopwatch sw = Stopwatch.StartNew() CvInvoke.Imdecode(bytearray_Image,ImreadModes.GrayScale,mat_DecodedImg); var l=sw.ElapsedMilliseconds; if(l>2000) { Debug.WriteLine($"Imdecode took too long {sw.ElapsedMilliseconds}"); }

99 percent of the time its ok, once in a while i get ~10,000 milliseconds

**Comment by emgucv** [comment]
If you read the file from local disk into memory stream, then use Imdecode to decode it repeatedly, will there still be a delay?

Can you also upload the jp2k file here?

**Comment by FelixKras** [comment]
1) I dont read the file from disk, it never gets to disk it comes from a camera through tcp and gets decoded on the fly
2) I tried saving the image and decoding it again.. it doesnt replicate - which means that the data itself is ok..
3) I run this function at a dedicated thread with "high" priority, can this cause some problem? maybe some locking mechanism inside?

**Comment by emgucv** [comment]
To narrow down and see it is a bug in the CvInvoke.Imdecode, you will need to run CvInvoke.Imdecode using a steam from local storage. 

If the bug does not replicate using local storage, that means it may be a network problem: e.g. data was corrupted during transportation over the network. If that is the case, you may wait to run a checksum of the stream on the receiving end, and check if that match the checksum of the stream on the sending end.

**Comment by FelixKras** [comment]
>  you will need to run CvInvoke.Imdecode using a steam from local storage.

it has nothing to do with network or local disk... the byte array already exists when the ImDecode is called.

> If the bug does not replicate using local storage, that means it may be a network problem

the byte array is not corrupt, because eventually (after 10 sec) the function returns with decoded image. also, when i rerun the function **on the same byte array** there's no delay...

**Comment by emgucv** [comment]
Let me summarize:
1. You have a file "abc.jp2k" on a network, if your code read the file from yout network to a stream "stream1", and decode it with CvInvoke.Imread, it may occasionally cause delay of 10 seconds during decode. 
2. If you have the file "abc.jp2k" on a local disk, and your code read the file from local disk to stream "stream2", and decode it using CvInboke.Imread, it will never cause a 10 seconds delay. 
3. You are certain that "stream1" and "stream2" are equal, and yet, passing the "stream1" and "stream2" to Imdecode results in different behavior.

My question is, how can we reproduce your problem on our side, without having your network?

**Comment by FelixKras** [comment]
1 is almost correct. I don't have a file. The image is generated on another computer and sent via udp as a byte array.
2 Doesnt reproduce the same conditions because i cannot read from disk at the same rate.

i am more than certain that the problem is related to high rate of calling the Imdecode (60 per second).
on one instance i got a "unhandled exception cv: unable to remove temporary file"
can the problem be caused by some file handle the Imdecode creates and not releases?
like here:
http://answers.opencv.org/question/96454/imdecode-without-temporary-file/

to reproduce this issue i think is possible to load the imdecode function (with a same image)
and call it in a while(true) loop, with 2 threads

i have a couple of questions that maybe help me:
1) is the ImDecode function thread safe?
2) Do you know of any global Operating System resource  that imdecode uses?

**Comment by FelixKras** [comment]
by trial and error i determined that its something to do with re-entrance, i ran 3 decoders in different processes and the delay did not occur
