### ISSUE TITLE
Capture(int camIndex) didn't work

### ISSUE THREAD

**Issue by zenoszhang** [emgucv/emgucv#209]
Development Environment：windows 7 Ultimate 64bit
Source：2.4.10.1939
Project is crashed when `Capture(int camIndex)` is called, and didn't throw a exception
 language：C#  (.net framework 4.0)
` try
                {
                    int index = comboBox1.SelectedIndex;
                    _capture = new Capture(index);
                    _capture.ImageGrabbed += _capture_ImageGrabbed;
                    _capture.Start();
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
}
                `

**Comment by emgucv** [comment]
Sorry, support of Windows 7 ended on January 14, 2020, we will not be looking into this ticket in the future. 

Closing ticket now.
