### ISSUE TITLE
CvException.ErrorStr crashes program

### ISSUE THREAD

**Issue by jeremy7nelson** [emgucv/emgucv#210]
Accessing CvException.ErrorStr crashes the program, even when done in a try block. Easy to reproduce:

try
{
  // Do something to cause a CvException
}
catch (CvException e)
{
  string str= e.ErrorStr;
}

**Comment by jeremy7nelson** [comment]
Note that this is the only place where this is used so it might be a marshaling problem:
[return: MarshalAs(CvInvoke.StringMarshalType)]

**Comment by jeremy7nelson** [comment]
I found a solution to this. Opening a pull request.

**Comment by jeremy7nelson** [comment]
Fixed in master. I have no problem applying this fix to the stable branches with additional pull requests if you want that.

**Comment by emgucv** [comment]
Pull request has been merged. I am closing this ticket now. Thanks for the contribution.
