### ISSUE TITLE
Build broken in Emgu.CV.Contrib/XPhoto

### ISSUE THREAD

**Issue by jeremy7nelson** [emgucv/emgucv#212]
Build broken as of c319871a30e9d6c475664595e3a18b4db2550186 2019-02-14. It appears that we are missing Emgu.CV.Contrib/XPhoto/GrayworldWB.cs or GrayworldWB class needs to be added back into XPhotoInvoke.cs.

**Comment by emgucv** [comment]
Fixed in this commit:
c16caa84241edefc539a80f47b69792b1d5ad1d0

Thanks for the report.
