### ISSUE TITLE
Emgu.CV.World/CMakeLists.txt error

### ISSUE THREAD

**Issue by jeremy7nelson** [emgucv/emgucv#217]
Emgu.CV.World/CMakeLists.txt is missing a closing parenthesis on line 25 in commit 9bf64bde7f05fc69d277bd89f0b041b40e8ed174.

**Comment by emgucv** [comment]
Fixed in 5c78140177fe8ae3662999f7dde476a6fa6e07a1
Thanks for pointing out.
