### ISSUE TITLE
CudaSparsePyrLKOpticalFlow gives an error message

### ISSUE THREAD

**Issue by mr-kot** [emgucv/emgucv#220]
`using (CudaSparsePyrLKOpticalFlow oFlow = new CudaSparsePyrLKOpticalFlow(new Size(21, 21)))
            {
                CudaInvoke.Calc(oFlow, oldImage, currentImage, vp1, vp2, status, err);
            }`
The program is started, but gives an error message:
"Attempt of reading or record in the protected memory. It often demonstrates that other memory is damaged."

**Comment by emgucv** [comment]
Fixed in the above commit ( 1f5c00d1eaf760f446192305270226eeba7ebab2 ). 
Thanks for pointing out.

**Comment by mr-kot** [comment]
Thanks! How I will be able to use these corrections in the program. Only to wait for the new version of emgucv?

**Comment by emgucv** [comment]
It is part of the release now.
