### ISSUE TITLE
DenseHistogram Constructor OR RangeF structure documentation missleading

### ISSUE THREAD

**Issue by WeitesFeld** [emgucv/emgucv#222]
Either the documentation of the first DenseHistogram constructor "DenseHistogram Constructor (Int32, RangeF)" ( http://www.emgu.com/wiki/files/3.4.1/document/html/e4db3e6c-bcef-a7bd-d335-62b9a6eb61ff.htm ) or RangeF.Max (http://www.emgu.com/wiki/files/3.4.1/document/html/ca86797d-45c6-c88d-4265-eef6a195414a.htm) is missleading.

The constructor takes the range maximum as an not included boundary, e.g. if you type in 255, it will exclude all values from a completely white image, while 256 will include all those values.

I suggest to make it more clear that the upper range value is excluded.

**Comment by emgucv** [comment]
Fixed in this commit: ef5d5b20d499885dd88bc863cd4568a2b5a7ff71

Thanks for pointing that out.
