### ISSUE TITLE
Emgu.CV.Unity Asserttion failed 

### ISSUE THREAD

**Issue by KeurKeur** [emgucv/emgucv#226]
I wanted to use emgu on unity - hololens for a project, but when I import the folder X86 into the plugins folder , i have errors like this : 
Assertion failed: Removing Assets/Plugins/concrt140.dll because the asset does not exist
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

In the end, the folder is empty because this error is for all the files inside X86.

I use Unity 2017.4.24f1 (the LTS version) with Visual Studio 2017.

Thanks for the help.

**Comment by emgucv** [comment]
Are you using our official Emgu CV for Unity release from the Unity Asset store or from our web store?

Our official release for unity are tested and our test do not have the Assertion failed issue. Which version of the release are you using?

**Comment by emgucv** [comment]
Closing ticket now. If you can provide the additional information for trouble shooting, please re-open the ticket.
