### ISSUE TITLE
'Emgu.CV.CvInvoke' exception when computer has no installed GPU using emgucv-windesktop_x64-cuda-icc-tbb-ipp 3.4.3.3016

### ISSUE THREAD

**Issue by amanabat** [emgucv/emgucv#228]
Our company is leveraging Emgu CV binaries and we've started using the latest _**emgucv 3.4.3.3016**_ that's been compiled with CUDA. What we've noticed is that when we deploy our binaries to another computer that doesn't have a GPU installed, we get the 'Emgu.CV.CvInvoke' exception where it's looking for cvtextern.dll. 

We've followed all the [instructions](http://www.emgu.com/wiki/index.php/Download_And_Installation#Have_you_copied_the_OpenCV_dlls_to_the_execution_directory.3F) in the link and what we've discovered is that our machines where we need to deploy our software would now need to have a GPU installed.

Is there a way to still use the Emgu CV binaries compiled with CUDA even if the machine doesn't have a GPU installed or would we have to install the Emgu CV binaries compiled w/o CUDA support? This would involve our installer having to detect if there's a GPU installed and determine the corresponding binaries (CUDA or non-CUDA) to install in the target machine. Any help would be much appreciated. Thanks in advance.

**Comment by emgucv** [comment]
It should have been fixed in the 4.0.1 release from Open CV. Please give the latest version a try. 
The GPU release should be able to run on computers with no CUDA graphic card without throwing Emgu.CV.CvInvoke exception when it is looking for cvextern.dll.

**Comment by amanabat** [comment]
I can confirm that this has been fixed in the new release (4.0.1)
