### ISSUE TITLE
jpeg2000 10 bpp

### ISSUE THREAD

**Issue by FelixKras** [emgucv/emgucv#229]
i have a file that was encoded by an external hardware to jpeg2000 with 10 bit depth per pixel.
in version 3.3.x i am able to decode the file anf i get a 8bit per pixel image
on 3.4.3.X i get an "read header error"

I am certain that its because of the 10bit encoding, the question is whether it was by design to stop supporting anything but 8/16 bit

the file is not corrupted because i can still decode it with older version and it opens without a problem by IrfanView (with jpeg2000 plugin)

![10bit_rename_to_jp2](https://user-images.githubusercontent.com/42567361/56202261-55cfb480-604b-11e9-9e21-6ffe5c407675.jpg)

i attached the sample file, rename to jp2 (its not a jpeg file)

**Comment by emgucv** [comment]
Should track this Open CV ticket: https://github.com/opencv/opencv/issues/14058
