### ISSUE TITLE
Dependencies are not copied to output path of another referencing project with msbuild and nuget

### ISSUE THREAD

**Issue by lauxjpn** [emgucv/emgucv#23]
If you build a library project in Visual Studio, include the emgucv package using nuget and compile everything, you will get the x86 and x64 sub directories inside your ouput directory as expected.

Unfortunately, if you create another project that references this library project and compile it, the x86 and x64 sub directories will not be copied to the output directory of the newly created project and thus causing it to fail when calling any library project function that uses emgucv.

To solve this problem, you have to change a single file which is distributed together with the nuget package.

The `EmguCV.targets` file looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <OpenCVBinX64 Include="$(MSBuildThisFileDirectory)\native\x64\*.dll" />
    <OpenCVBinX86 Include="$(MSBuildThisFileDirectory)\native\x86\*.dll" />
  </ItemGroup>
  <Target Name="AfterBuild">
    <Copy SourceFiles="@(OpenCVBinX64)" DestinationFolder="$(OutputPath)\x64" ContinueOnError="true" SkipUnchangedFiles="true" Condition="$(CopyOpenCVBins)"/>
    <Copy SourceFiles="@(OpenCVBinX86)" DestinationFolder="$(OutputPath)\x86" ContinueOnError="true" SkipUnchangedFiles="true" Condition="$(CopyOpenCVBins)"/>
  </Target>
</Project>
```
If you replace it with the following code, it will work in both scenarios:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="'$(CopyOpenCVBins)'"> 
    <Content Include="$(MSBuildThisFileDirectory)\native\x64\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>x64\%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\native\x86\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>x86\%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by tfaris** [comment]
I just ran into this myself today.

@emgucv Any thoughts? I can confirm that @lauxjpn's solution works for me.

**Comment by lauxjpn** [comment]
It seems that the code was included in the newly added `emgucv/platforms/nuget/Emgu.CV.targets` file with commit 2f21a40 about 24 days ago.
The issue should be solved.

**Comment by emgucv** [comment]
Offical Emgu CV v3.2 release is available from Nuget:
https://www.nuget.org/packages/Emgu.CV/

We will support Nuget packages moving forward.

Thanks for the feed back.
