### ISSUE TITLE
Sample points, Image.Sample(LineSegment2D) in version 4.[Help needed]

### ISSUE THREAD

**Issue by JakobMadsenICP** [emgucv/emgucv#230]
I have in Emgu version 3.4 used Image.Sample(LineSegment2D)

like this
```
var p1 = new Point(){X=0,y=0};
var p2 = new Point(){X=10,y=10};
var profile = image.Sample(new LineSegment2D() { P1 = p1, P2 = p2 });
```
I now updated to version 4.0.1 where sample does not exist. How do I sample a line in 4.0.1?

**Comment by judchiu** [comment]
Any comment on this? I have a customer who upgraded to 4.1 and lost Image.Sample also. At least bring back CvInvoke.cvSampleLine

**Comment by emgucv** [comment]
Image<,>.Sample functions depends on cvSampleLine function which no longer exist in Open CV 4.x

Open CV now use LineIterator, which we have just added to Emgu CV with this commit:
https://github.com/emgucv/emgucv/commit/2fbe46385c7b5deb3bd2211c62adb9eed38f96e4

A simple usage to Sample a line across the image:
`Mat img = ...`
`Mat line = LineIterator.SampleLine(img, new Point(0, 0), new Point(img.Width, img.Height));`
`byte[,,] pixelData = line.GetData(true) as byte[,,];`

It will be included in the next release. You can also build the binary from the latest source code.

**Comment by emgucv** [comment]
Closing ticket now.
