### ISSUE TITLE
X86 or AnyCpu is targeted, but this CUDA CUFFT package do not support 32-bit

### ISSUE THREAD

**Issue by thug1705** [emgucv/emgucv#231]

**Comment by thug1705** [comment]
I am getting this error message when I try to build my project I installed Emgu CV 4.0.1 from nuget packages and also Emug CV - CUDA.

**Comment by emgucv** [comment]
Please check your application target and make sure that it is targeting "x64", not "x86" and not "AnyCPU". 
Open CV's can only build with 64bit of CUDA 10. Emgu CV with GPU is not able to support "x86" architecture. If you choose "AnyCPU", your application will run in "x86" mode on a 32bit computer. As a result, "AnyCPU" is also not supported.

**Comment by thug1705** [comment]
Thanks that worked

**Comment by ynioba** [comment]
@emgucv ，I haved setted my application to X64,but not work in vs2017 .net 4.6.1

**Comment by emgucv** [comment]
Make sure your project is configure for "X64", not just the solution. Please open "configuration manager" to check. 

You may have switched your solution configuration to "X64" but your project may still have "Any CPU" project configuration under "X64" solution configuration.
