### ISSUE TITLE
Equivalent example of Image Comparison in EmguCV 4.0.1

### ISSUE THREAD

**Issue by thug1705** [emgucv/emgucv#232]
Is it possible to get/find equivalent example of Image Comparison from link below done in Emgu Cv 4.0.1

http://www.emgu.com/wiki/index.php/CompareImages_-_Difference

Thanks.

**Comment by emgucv** [comment]
If you are looking for the CvInvoke.AbsDiff function, the documentation is here:
http://www.emgu.com/wiki/files/4.0.1/document/html/eb63e54b-e902-973b-588c-0b7e37a78a2f.htm

**Comment by emgucv** [comment]
Closing ticket now.
