### ISSUE TITLE
ColorMatchTemplate .NET Support

### ISSUE THREAD

**Issue by HeavenHeal** [emgucv/emgucv#236]
Hey man Can u add this to ur amazing library?

https://github.com/LaurentBerger/ColorMatchTemplate/blob/master/main.cpp

**Comment by emgucv** [comment]
Thanks for the information. 

Emgu CV will focus on wrapping Open CV function at this moment. We will not be adding the ColorMatchTemplate repo to our official release in the near future. 

Sorry about that.

**Comment by emgucv** [comment]
Closing ticket now.
