### ISSUE TITLE
ArucoInvoke.DetectCharucoDiamond results in CvException

### ISSUE THREAD

**Issue by zyliao-navifus** [emgucv/emgucv#240]
Exception is:

> System.Exception: Capture error ---> Emgu.CV.Util.CvException: OpenCV: (flags & FIXED_TYPE) != 0
   於 Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   於 Emgu.CV.Aruco.ArucoInvoke.cveArucoDetectCharucoDiamond(IntPtr image, IntPtr markerCorners, IntPtr markerIds, Single squareMarkerLengthRate, IntPtr diamondCorners, IntPtr diamondIds, IntPtr cameraMatrix, IntPtr distCoeffs)
   於 Emgu.CV.Aruco.ArucoInvoke.DetectCharucoDiamond(IInputArray image, IInputArray markerCorners, IInputArray markerIds, Single squareMarkerLengthRate, IOutputArray diamondCorners, IOutputArray diamondIds, IInputArray cameraMatrix, IInputArray distCoeffs)
   於 Aruco.MainForm.ProcessFrame(Object sender, EventArgs arg) 於 C:\Users\NaviFUS\Desktop\libemgucv-windesktop-4.0.1.3373\Emgu.CV.Example\Aruco\MainForm.cs: 行 162
   於 Emgu.CV.VideoCapture.Grab()
   於 Emgu.CV.VideoCapture.Run(ExceptionHandler eh)

I see that DrawCharucoDiamond() function has been fixed in [issue#173](https://github.com/emgucv/emgucv/issues/173), so I try to use charuco diamond. I create a charuco with id:0, 1, 2, 3 and add some codes to the sample code, but there comes a trouble on **DrawCharucoDiamond()** function. I try **ver. 4.0.1.3373** and **ver. 3.4.3.3016** but all have this problem.

test code:
`        private void ProcessFrame(object sender, EventArgs arg)
        {
            if (_capture != null && _capture.Ptr != IntPtr.Zero)
            {
                _capture.Retrieve(_frame, 0);
                _frame.CopyTo(_frameCopy);

                //cameraImageBox.Image = _frame;
                using (VectorOfInt ids = new VectorOfInt())
                using (VectorOfVectorOfPointF corners = new VectorOfVectorOfPointF())
                using (VectorOfVectorOfPointF rejected = new VectorOfVectorOfPointF())
                {
                    //DetectorParameters p = DetectorParameters.GetDefault();
                    ArucoInvoke.DetectMarkers(_frameCopy, ArucoDictionary, corners, ids, _detectorParameters, rejected);

                    if (ids.Size > 0)
                    {
                        VectorOfVectorOfPointF diamondCorners = new VectorOfVectorOfPointF();
                        VectorOfMat diamondIds = new VectorOfMat();
                        ArucoInvoke.DetectCharucoDiamond(_frameCopy, corners, ids, 17.0f / 15.0f, diamondCorners, diamondIds);
                    }

                    cameraImageBox.Image = _frameCopy.Clone();
                }
            }
            else
            {
                UpdateMessage("VideoCapture was not created");
            }
        }
`

**Comment by Peamon** [comment]
Use Mat for diamondIds

```
VectorOfVectorOfPointF diamondCorners = new VectorOfVectorOfPointF();
Mat diamondIds = new Mat();
ArucoInvoke.DetectCharucoDiamond(_frameCopy, corners, ids, 17.0f / 15.0f, diamondCorners, diamondIds);
```

**Comment by zyliao-navifus** [comment]
> Use Mat for diamondIds
> 
> ```
> VectorOfVectorOfPointF diamondCorners = new VectorOfVectorOfPointF();
> Mat diamondIds = new Mat();
> ArucoInvoke.DetectCharucoDiamond(_frameCopy, corners, ids, 17.0f / 15.0f, diamondCorners, diamondIds);
> ```

Thank you~
You save my long-standing problem
