### ISSUE TITLE
ShapeContextDistanceExtractor throwing error when build as release.

### ISSUE THREAD

**Issue by papakaliati** [emgucv/emgucv#243]
ShapeContextDistanceExtractor, when accessed from multiple threads throws an exception, when project is build on Release mode. If the project is build on debug, no error is occurring.

**Comment by emgucv** [comment]
Can you provide the source code to reproduce the error? 
ShapeContextDistanceExtractor functions may not be thread safe, you will need to take extra caution when accessing it across threads.

**Comment by emgucv** [comment]
Closing ticket now.
