### ISSUE TITLE
Initial call to Emgu.CV function incurs a delay of ~30 seconds

### ISSUE THREAD

**Issue by amanabat** [emgucv/emgucv#245]
Using the latest commercial release (**_4.0.1.3373_**) we have been seeing some random behavior where initial calls to Emgu.CV functions incurs around a 30 second delay before the function is executed. After that the succeeding calls are normally executed. 

It seems like it's trying to load all the unmanaged binaries in memory and once everything is there, the execution time is not affected anymore. We've had this behavior on separate machines and some machines don't even exhibit this behavior. We've also updated to the latest Nvidia drivers hoping that'll solve the issue on that machine but to no avail. Any help would be much appreciated. Thanks in advance.

**Comment by oldominion** [comment]
Also experiencing this problem. Most pronounced when performing the first CUDA operation as far as I can tell.

**Comment by emgucv** [comment]
The first time the opencv GPU module is loaded on your machine, it is possible that the NVidia driver JIT compiled the PTX code to target your local GPU device. See:

https://docs.opencv.org/3.0-alpha/modules/cuda/doc/introduction.html#compilation-for-different-nvidia-platforms
https://devblogs.nvidia.com/cuda-pro-tip-understand-fat-binaries-jit-caching/

It is to be expected, if the native GPU binary that target your device is not included in the precompiled binary, and device code needed to be generated from the PTX. It is normal if it last 30 seconds but the compiled device code will be cached on disk. If the cache is sufficient this delay will only took place the first time the application is run.

**Comment by emgucv** [comment]
Closing ticket now.
