### ISSUE TITLE
build error in macos

### ISSUE THREAD

**Issue by aimhigh53** [emgucv/emgucv#246]
hi
I have some problem in build emgucv

The error message:
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- broken
CMake Error at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/ins25k/Desktop/cSharpProject/emgucv/vtk/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_68ab6/fast 
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_68ab6.dir/build.make CMakeFiles/cmTC_68ab6.dir/build
    Building C object CMakeFiles/cmTC_68ab6.dir/testCCompiler.c.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_68ab6.dir/testCCompiler.c.o   -c /Users/ins25k/Desktop/cSharpProject/emgucv/vtk/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_68ab6
    /usr/local/Cellar/cmake/3.14.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_68ab6.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_68ab6.dir/testCCompiler.c.o  -o cmTC_68ab6 
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: dynamic main executables must link with libSystem.dylib for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_68ab6] Error 1
    make: *** [cmTC_68ab6/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:29 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/ins25k/Desktop/cSharpProject/emgucv/vtk/CMakeFiles/CMakeOutput.log".
See also "/Users/ins25k/Desktop/cSharpProject/emgucv/vtk/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- broken
CMake Error at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/ins25k/Desktop/cSharpProject/emgucv/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_05878/fast 
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_05878.dir/build.make CMakeFiles/cmTC_05878.dir/build
    Building C object CMakeFiles/cmTC_05878.dir/testCCompiler.c.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_05878.dir/testCCompiler.c.o   -c /Users/ins25k/Desktop/cSharpProject/emgucv/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_05878
    /usr/local/Cellar/cmake/3.14.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_05878.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_05878.dir/testCCompiler.c.o  -o cmTC_05878 
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: dynamic main executables must link with libSystem.dylib for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_05878] Error 1
    make: *** [cmTC_05878/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)

-- Configuring incomplete, errors occurred!
See also "/Users/ins25k/Desktop/cSharpProject/emgucv/CMakeFiles/CMakeOutput.log".
See also "/Users/ins25k/Desktop/cSharpProject/emgucv/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

I already install cmake ,mono and xcode
I don't know how can I deal with,,

**Comment by emgucv** [comment]
Works when running:

`configure x86_64`

Please note that x86 compilation is no longer supported with the latest macOS.

**Comment by emgucv** [comment]
Closing ticket now.
