### ISSUE TITLE
FindEssentialMat() wrong return type?

### ISSUE THREAD

**Issue by anthony-mestdach** [emgucv/emgucv#25]
Hi, When I try to find the essential matrix I cannot get the result from the method.
Emgu source emgucv/Emgu.CV/PInvoke/CvInvokeCalib3d.cs:
`public static void FindEssentialMat(IInputArray points1, IInputArray points2, IInputArray cameraMatrix, CvEnum.FmType method = CvEnum.FmType.Ransac, double prob = 0.999, double threshold = 1.0, IOutputArray mask = null);`

Opencv source:
`cv::Mat cv::findEssentialMat( InputArray _points1, InputArray _points2, InputArray _cameraMatrix,
                              int method, double prob, double threshold, OutputArray _mask)
`
Shouldn't the Emgu method return a Mat or am I doing it wrong?

**Comment by emgucv** [comment]
Fixed in commit f73119a

Thanks for reporting.
