### ISSUE TITLE
Can not distinguish colors

### ISSUE THREAD

**Issue by louispham102** [emgucv/emgucv#252]
When I compared picture has 1 color with other picture has 1 color different (black and white or blue and yellow) with accuracy of about 95%, it will return true. Is it a bug or is there a way to fix it?
Thanks for reading.

**Comment by emgucv** [comment]
It is not quite clear what you describe.

What function do you use the compare the pictures? Can you upload the pictures here? What is the expected output of the function and what is the actual output?

**Comment by emgucv** [comment]
Closing issue now.
