### ISSUE TITLE
unable to VideoWriter. Make sure you have the specific codec installed

### ISSUE THREAD

**Issue by su7456** [emgucv/emgucv#253]
int fourcc = VideoWriter.Fourcc('H', '2', '6', '4');
                            //
                            Backend[] backends = CvInvoke.WriterBackends;
                            int backend_idx = 0; //any backend;
                            foreach (Backend be in backends)
                            {
                                if (be.Name.Equals("MSMF"))
                                {
                                    backend_idx = be.ID;
                                    break;
                                }
                            }
                            #endregion
                            videowriter = new VideoWriter(saveFileDialog.FileName, backend_idx, fourcc, int_VideoFps, new Size(int_VideoWidth, int_VideoHeight), true);

**Comment by su7456** [comment]
我在使用这段代码时，执行到 videowriter = new VideoWriter(saveFileDialog.FileName, backend_idx, fourcc, int_VideoFps, new Size(int_VideoWidth, int_VideoHeight), true);时报出这个错误，我该怎么解决该问题

**Comment by emgucv** [comment]
What is the FileName that you passed to VideoWriter?
Please refer to this tutorial:
http://www.emgu.com/wiki/index.php/H264_Codec
It works with v4.1 on Windows 10. You will need to make sure the file name has extension of ".mp4"

**Comment by emgucv** [comment]
Closing issue now.
