### ISSUE TITLE
how to clear the rectangle in the image? After use the function CvInvoke.Rectangle()

### ISSUE THREAD

**Issue by romccng** [emgucv/emgucv#254]
i add a overlay in the image by CvInvoke.Rectangle(src, lastRect, new MCvScalar(255, 0, 0, 0), 3);
but i can not remove the exist rectangle in the image.

**Comment by emgucv** [comment]
It is not quite clear what you means by 'removing' the exist rectangle...
But if you want to fill up the rectangle with solid color, set the line thickness to -1.

**Comment by romccng** [comment]
i means if i overlay an rectangle on a image，just to show where i put the roi，my questuon is how to remove the rectangle？

发自我的 iPhone

**Comment by emgucv** [comment]
Do you means recovering the original image after a rectangle has been drawn over it?

**Comment by romccng** [comment]
> 
> 
> Do you means recovering the original image after a rectangle has been drawn over it?

Yes, i know i can use a copy image to draw rectangle. what i want to know is weather there is any other way can remove the rectangle in the image.

**Comment by romccng** [comment]
> 
> 
> Do you means recovering the original image after a rectangle has been drawn over it?

Yes, I don't know how to recovering the original image. i want to define a ROI by draw rectangle in a image.

**Comment by emgucv** [comment]
If you have written over pixels in the original image, that information in the part where you have written over is lost and cannot be recovered. You can try to estimate it with Inpainting, but it will only be a best guess recovery.

**Comment by emgucv** [comment]
Closing ticket now.
