### ISSUE TITLE
Build the development version of Emgu CV from source code failure

### ISSUE THREAD

**Issue by Harris123hi** [emgucv/emgucv#255]
I did the experiment according to the manual steps, but it was unsuccessful。
on Win10 x64 VS2017 ,CMake3.15.0, Build_Binary_x86_nocuda.bat.
Anything else I can try?
![3](https://user-images.githubusercontent.com/52318060/60342284-a5374700-99e3-11e9-9203-dd6c08b569e6.png)

![1](https://user-images.githubusercontent.com/52318060/60342130-35c15780-99e3-11e9-8305-75d1d81e3b18.jpg)
![2](https://user-images.githubusercontent.com/52318060/60342131-35c15780-99e3-11e9-8cc9-a8398cc7cc9d.jpg)

**Comment by emgucv** [comment]
Can you upload the full CmakeOutput.log and CMakeError.log?

Just tested the script and it works for the development master:
f52f97faa4f879d8af5ac16bb017f6ec223a861c

It also works on the 4.1.0 tag.

**Comment by Harris123hi** [comment]
CMake3.15.0 Convert to CMake3.10.3，it Work!

**Comment by emgucv** [comment]
Good to know. Cmake 3.15.0 is still under development. It is not supported at this moment.
Closing ticket for now.
