### ISSUE TITLE
Please produce NuGet package for latest Emgu CV releases

### ISSUE THREAD

**Issue by MicrocontrollersAndMore** [emgucv/emgucv#26]
I realize this has been mentioned before, but I'm not sure it has explicitly been requested.  Please produce official NuGet packages for the latest Emgu CV releases (currently Emgu.CV-3.1.0-r16.12).  The "old" way of manually including .DLLs is very outdated.

**Comment by emgucv** [comment]
It is finally here, official nuget package of Emgu CV:
https://www.nuget.org/packages/Emgu.CV/
Cheers.
