### ISSUE TITLE
Image file not getting loaded when putting in separate file in class (like example given) : Image<Bgr, Byte> imgObj = new Image<Bgr, byte>(strFile); 

### ISSUE THREAD

**Issue by Ravinderjitsidhu** [emgucv/emgucv#260]
// **************Form1.cs (startup file)
```
using System.Windows.Forms;

namespace WindowsFormsAppStub
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            TestFunction();
        }

        private void TestFunction()
        {
            ContourTest41.Class1 obj1 = new ContourTest41.Class1();
            obj1.Test();  // ***** calling Test
        }
    }
}
```

// ****************Class1.cs  // (using emgu.cv 4.1)
```
using Emgu.CV;
using Emgu.CV.CvEnum;
using Emgu.CV.Structure;
using Emgu.Util;

namespace ContourTest41
{
    public class Class1   {
        public void Test()
        {
            // test
            string strFile = @"D:\ExampleTestFolder\TEST.PNG";
            Image<Bgr, Byte> imgObj = new Image<Bgr, byte>(strFile);  // ***** issue is here image will not load in object (object will show width=0, height=0)
            imgObj = new Image<Bgr, byte>(strFile).Resize(1, (Inter)4); // *** so resize will give error
            //
            return;
        }
    }
}

```

**Comment by emgucv** [comment]
Our unit test here all runs fine for v4.1 release, and they are put in separate files and classes and they all load image files:
https://github.com/emgucv/emgucv/tree/master/Emgu.CV.Test

May be it has to do with your "TEST.PNG" file. Try replacing that file with the "pedestrian.png" in the above folder in our repository. If your code works with the above "pedestrian.png" file but not your "TEST.PNG“ file, you should check if your file is actually using the correct PNG encoding.

**Comment by Ravinderjitsidhu** [comment]
i found cvextern.dll was missing after emgu.cv 4.1 updated using NuGet package in solution.
after coping in the bin folder its working.
thankyou so much
