### ISSUE TITLE
Error when compiling a project which uses the NuGet package

### ISSUE THREAD

**Issue by paolofulgoni** [emgucv/emgucv#261]
I often get this error when compiling some projects which use the Emgu.CV NuGet package:

`Emgu.CV.targets(27,5): error : Emgu CV is not able to detect the project type, please use the pre-compiled Emgu.CV.World dll or send a bug report to support@emgu.com`

Then after some pseudo-random attempts, like unload/reaload project, the error disappears.

Unfortunately I'm not able to understand why this condition, which rises the error, sometimes is true:
`Condition="'$(EmguCvLinkTarget)'==''"`

Anyway, is there a good reason for this check?
The `EmguCvLinkTarget` property is hardcoded in the .target file, aren't all the related checks pointless?

**Comment by emgucv** [comment]
Can you upload a project that can be used to reproduce the error? We are not able to re-produce the issue. 
Looking at the Emgu.CV.target file, the EmguCvLinkTarget property should always be set to "WindowsForms" and the error shouldn't show up.

**Comment by paolofulgoni** [comment]
We use only the `EMGU.CV` NuGet package, I don't know what the _Emgu CV shared project_ is.

I understand your point. Unfortunately , as I wrote in the pull request #262 comment, I think it will be very hard to reproduce the issue. I'll try anyway and let you know.

**Comment by emgucv** [comment]
The Emgu CV shared projects are part of the ".zip" file releases.

**Comment by paolofulgoni** [comment]
OK, I understand. So I confirm we don't use them.

**Comment by paolofulgoni** [comment]
Unfortunately I wasn't unable to reproduce this issue in a new clean solution, therefore I'm closing the issue.

**Comment by Frankane** [comment]
Hi, have you get a solution now? I'm stucking on this problem too.

**Comment by emgucv** [comment]
If you are using nuget pacakges from latest release this error message should no longer exist.

Only if you are using shared projects from much older releases (>2 yrs ago), and the shared project cannot detect your project type, you will see this error message.

Which Emgu CV release are you using? Are you using nuget package or shared project? What is your project's targeted dotnet version?

**Comment by emgucv** [comment]
3.4.3 was released on Oct 2018. I would recommend upgrading to the latest release if possible. 

If staying with 3.4.3 is a requirement, you may need to reload the project if that fix the problem.

**Comment by Frankane** [comment]
OK, thanks.
