### ISSUE TITLE
userColor for applyColorMap

### ISSUE THREAD

**Issue by AlexPerni** [emgucv/emgucv#264]
The function applyColorMap() for false colors has an overload to use a user defined colormap for the color map. 
It would be great, if EmguCV could implement this overload as well. 

OpenCV Documentation link:
https://docs.opencv.org/4.1.1/d3/d50/group__imgproc__colormap.html#gacb22288ddccc55f9bd9e6d492b409cae

**Comment by emgucv** [comment]
Implemented in the above commit.

**Comment by emgucv** [comment]
Closing issue now.
