### ISSUE TITLE
EMGU.CV.targets improvement

### ISSUE THREAD

**Issue by dzeitlin** [emgucv/emgucv#266]
In `EMGU.CV.targets` Instead of
```
<EmguCvBuildX86 Condition="'$(Platform)'=='AnyCPU' OR $(Platform)'=='x86'">True</EmguCvBuildX86>

<EmguCvBuildX64 Condition="'$(Platform)'=='AnyCPU' OR '$(Platform)'=='x64'">True</EmguCvBuildX64>
```
use
```
<EmguCvBuildX86 Condition="'$(EmguCvBuildX86)' == '' AND ('$(Platform)'=='AnyCPU' OR '$(Platform)'=='x86')">True</EmguCvBuildX86>

<EmguCvBuildX64 Condition="'$(EmguCvBuildX64)' == '' AND ('$(Platform)'=='AnyCPU' OR '$(Platform)'=='x64')">True</EmguCvBuildX64>
```

this gives the ability to define and "override" in my project the logic of copying x86/x64 bits to the output folder, like this:
```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <EmguCvBuildX86>False</EmguCvBuildX86>
    ...
```

**Comment by emgucv** [comment]
The new nuget packages use the architecture specific folder for the nuget packages 

  https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

see the section that mention "Architecture-specific folders". We are no longer using the ".targets" file for deploying native binary.

Closing issue now.
