### ISSUE TITLE
Build failure on Raspbian Buster

### ISSUE THREAD

**Issue by miki87278** [emgucv/emgucv#270]
`[100%] Built target cvextern
Building ../../../libs/Emgu.CV.World.dll
[100%] Linking CXX executable ../../../../../libs/cvextern_test
Microsoft (R) Visual C# Compiler version 3.3.1-beta4-19462-11 (66a912c9)
Copyright (C) Microsoft Corporation. All rights reserved.

[100%] Built target cvextern_test
/home/pi/emgucv/Emgu.CV/Core/UMat.cs(711,39): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/UMat.cs(711,56): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/UMat.cs(711,29): error CS1503: Argument 1: cannot convert from 'Emgu.CV.UMat' to 'System.Drawing.Size'
/home/pi/emgucv/Emgu.CV/Core/UMat.cs(721,35): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/UMat.cs(721,50): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/UMat.cs(721,29): error CS1503: Argument 1: cannot convert from 'Emgu.CV.UMat' to 'System.Drawing.Size'
/home/pi/emgucv/Emgu.CV/PInvoke/CvInvoke.cs(577,65): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/Mat.cs(1079,38): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/Mat.cs(1079,55): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/Mat.cs(1089,34): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Core/Mat.cs(1089,49): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV/Util/VectorOfDMatch.cs(86,18): error CS0103: The name 'VectorOfDMatchCreateSize' does not exist in the current context
/home/pi/emgucv/Emgu.CV/Util/VectorOfDMatch.cs(86,50): error CS1503: Argument 2: cannot convert from 'bool' to 'System.Runtime.Serialization.StreamingContext'
/home/pi/emgucv/Emgu.CV.Cuda/CudaImage.cs(286,60): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV.Cuda/CudaImage.cs(286,79): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV.Cuda/CudaImage.cs(286,50): error CS1503: Argument 1: cannot convert from 'Emgu.CV.Cuda.CudaImage<TColor, TDepth>' to 'int'
/home/pi/emgucv/Emgu.CV.Cuda/CudaImage.cs(309,56): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV.Cuda/CudaImage.cs(309,71): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV.Cuda/CudaImage.cs(309,50): error CS1503: Argument 1: cannot convert from 'Emgu.CV.Cuda.CudaImage<TColor, TDepth>' to 'int'
/home/pi/emgucv/Emgu.CV.Cuda/GpuMat.cs(302,41): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV.Cuda/GpuMat.cs(302,60): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV.Cuda/GpuMat.cs(325,37): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
/home/pi/emgucv/Emgu.CV.Cuda/GpuMat.cs(325,52): error CS0104: 'Range' is an ambiguous reference between 'Emgu.CV.Structure.Range' and 'System.Range'
make[2]: *** [Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/build.make:59: Emgu.CV.World] Error 1
make[1]: *** [CMakeFiles/Makefile2:9909: Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
`

**Comment by emgucv** [comment]
We have a CI workflow now for raspbian:
https://github.com/emgucv/emgucv/actions/workflows/pi.yml

Seems to be working well. Closing ticket now.
