### ISSUE TITLE
Memory leak with ToImage()

### ISSUE THREAD

**Issue by sypack** [emgucv/emgucv#272]
This code gives a memory leak:

static void Main(string[] args)
        {
            String mPath = String.Empty;

            if (args.Length == 1)
                mPath = args[0];

            if (Directory.Exists(mPath))
            {
                foreach (String mFilename in Directory.GetFiles(mPath, "*.jpg"))
                {
                    Mat mImage = CvInvoke.Imread(mFilename);

                    Bitmap mBitmap = mImage.ToImage<Bgr, Byte>().ToBitmap();

                    mBitmap.Dispose();
                    mImage.Dispose();
                }
            }

            MessageBox.Show("Done");
        }

When i change 

Bitmap mBitmap = mImage.ToImage<Bgr, Byte>().ToBitmap();

to

Image<Bgr, Byte> mX = mImage.ToImage<Bgr, Byte>();
Bitmap mBitmap = mX.ToBitmap();

the memory leak is gone.

**Comment by emgucv** [comment]
In the line 
> Bitmap mBitmap = mImage.ToImage<Bgr, Byte>().ToBitmap();
> mBitmap.Dispose();

The ToImage<Bgr,Byte>() function created an intermediate Image<Bgr, Byte> object that is not referenced and disposed. It will be left for the garbage collector to collect and there will be no guarantee on when that happens.

If you want to manually clean up the image, you should replace it with:

```
using(Image<Bgr, Byte> tmp = mImage.ToImage<Bgr, Byte>())
{
                Bitmap mBitmap = tmp.ToBitmap();
                mBitmap.Dispose();
}
```

**Comment by emgucv** [comment]
Closing ticket now.
