### ISSUE TITLE
play rtsp audio，play rtsp audio

### ISSUE THREAD

**Issue by cdslily** [emgucv/emgucv#279]
Playing rtsp video is very smooth, start very fast, memory usage is good, can there be a way to reduce cpu usage?
Also, is there a way to play the audio of rtsp? What do you suggest?

**Comment by emgucv** [comment]
For performance on VideoCapture. You should create a ticket on Open CV's repo. I am pretty sure the Open CV team has optimized the cpu usage from RTSP stream as best as they can. There will be very little room for improvement. But I may be wrong. 

FYI, Open CV is an image processing library and do not handle audio from RTSP stream.

**Comment by cdslily** [comment]
ok ! thank you..
