### ISSUE TITLE
Can't install Emgu.CV nuget package to Android project

### ISSUE THREAD

**Issue by dmanning23** [emgucv/emgucv#284]
Trying to install the Emgu.CV nuget package to an Android project throws the following error:

Error	NU1202	Package ZedGraph 5.1.7 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package ZedGraph 5.1.7 supports: net35-client (.NETFramework,Version=v3.5,Profile=Client)

Thanks taking a look, any help is appreciated!

**Comment by emgucv** [comment]
Emgu CV for Android is only available as a commercial release. We provide a separate nuget package for Android target. In the 4.2.0 release, the nuget package for Android is named: Emgu.CV.runtime.android-CR
If you want a copy for evaluation, please send an email to support@emgu.com

**Comment by emgucv** [comment]
Closing ticket for now.
