### ISSUE TITLE
Wrap h/vconcat() overload with multiple Mats

### ISSUE THREAD

**Issue by dzarda** [emgucv/emgucv#285]
Concatenating multiple (~100) Mats will benefit performance-wise from preallocating the entire destination in one go. These overloads are unfortunately not exposed in Emgu:

```cpp
void cv::hconcat(const Mat* src, size_t nsrc, OutputArray _dst);
void cv::vconcat(const Mat* src, size_t nsrc, OutputArray _dst);
```

Source - preallocates dst Mat and does CopyTo:
https://github.com/opencv/opencv/blob/master/modules/core/src/matrix_operations.cpp#L98

**Comment by emgucv** [comment]
Added in this commit: eb68d482af894229d636df287d447c90fcb96c7f

**Comment by emgucv** [comment]
Closing ticket now.
