### ISSUE TITLE
Unity3d Issue

### ISSUE THREAD

**Issue by lijualivenow** [emgucv/emgucv#287]
I downloaded a Master build. Copied the unity project to a new folder and opened with Unity 2019.1.8f1. But I am getting error as followed

> Assets\Emgu.CV\Demo\CameraTexture.cs(5,7): error CS0246: The type or namespace name 'Emgu' could not be found (are you missing a using directive or an assembly reference?)

Total 29 errors, all are showing 

> The type or namespace name 'Emgu' could not be found.

Any solution for solving this issue?

**Comment by emgucv** [comment]
Emgu CV for Unity is only available as a commercial release. It is available for purchase in our webstore and the unity asset store.

If you want to get a copy for evaluation purpose, please send an email to support@emgu.com

**Comment by emgucv** [comment]
Closing ticket now.
