### ISSUE TITLE
Any plans to support dnn with Cuda backend?

### ISSUE THREAD

**Issue by Avrohom** [emgucv/emgucv#288]
Hi,

Was wondering if you are planning to support Cuda backend and target for the dnn module.

**Comment by emgucv** [comment]
The dnn module in the latest 4.2.0 relase added support for cuda. See release note here:
http://www.emgu.com/wiki/index.php/Version_History#Emgu.CV-4.2.0

**Comment by Avrohom** [comment]
Thing is: I have given it a spin.
![image](https://user-images.githubusercontent.com/6719297/73312801-89b64800-4221-11ea-91c8-d6a5af032c59.png)

Those are the results:
![image](https://user-images.githubusercontent.com/6719297/73312959-e580d100-4221-11ea-9848-3d3ffa38e3f0.png)

**Comment by Avrohom** [comment]
Finally got it working the way it should.

Downloaded the Cuda version from SourceForge.

![image](https://user-images.githubusercontent.com/6719297/73317115-e66b3000-422c-11ea-8b45-e3cc6ee427e3.png)

**Comment by emgucv** [comment]
Or use the Emgu.CV.runtime.windows.cuda package (https://www.nuget.org/packages/Emgu.CV.runtime.windows.cuda/) instead of Emgu.CV.runtime.windows package from nuget.

The runtime package with "cuda" in the package name is compiled with CUDA support. The other runtime without cuda is not.

**Comment by Avrohom** [comment]
Have been looking for such yesterday. Hasn't been there then. Great!
________________________________

**Comment by emgucv** [comment]
Closing ticket now.
