### ISSUE TITLE
Image<Bgra, byte> Constructor no longer accepts Bitmap parameter

### ISSUE THREAD

**Issue by rufw91** [emgucv/emgucv#289]
Hi, so I upgraded to version 4.2 and immediately got a compiler error that the constructor no longer accepts bitmap as param, this is a breaking change, advise.

**Comment by emgucv** [comment]
We have updated the change log for 4.2.0 release here:
http://www.emgu.com/wiki/index.php/Version_History#Change_Log
Included instruction to migrate code from 4.1.1 to 4.2.0. There are new extension methods. You can call "bitmap.ToMat()", "bitmap.ToUMat()" to convert Bitmap to Mat, UMat or Image<,> objects.

**Comment by bbday** [comment]
BitmapExtension.ToImage<Gray, byte>(YouBitmap)

**Comment by cayman1021** [comment]
Could anyone be kind to share how to convert Image<,> to Bitmap in version 4.2.0.3636?

"Picturebox" can only accept "Bitmap" but I can't find any function to convert "Image<,>" or "Mat" back to "Bitmap". I remembered there's ToBitmap() but now it's gone. Does that mean I can't use PictureBox anymore?

**Comment by bbday** [comment]
Image<Gray, byte> image = BitmapExtension.ToImage<Gray byte>(BitmapImage)
Bitmap bitmapImage = image.ToBitmap(); //You can use also for Mat type

**Comment by cayman1021** [comment]
> Image<Gray, byte> image = BitmapExtension.ToImage(BitmapImage)
> Bitmap bitmapImage = image.ToBitmap(); //You can use also for Mat type
> Remember to use nuget emgu.runtime.window or you can't use this library (using Emgu.CV)

Hello bbday,
Sorry, did you mean in version 4.2.0.3636? Or actually in earlier version of EmguCV? Because there's already no "ToBitmap()" function in 4.2.0.3636.

**Comment by bbday** [comment]
I mean last version available on nuget 4.2
Like i told you you must install also emgu.runtime.window or you can't access to Emgu.CV

**Comment by emgucv** [comment]
Here is the link to the nuget package:
https://www.nuget.org/packages/Emgu.CV.runtime.windows/

**Comment by cayman1021** [comment]
Did you mean using previous versions of EmguCV?
Rolling back to previous versions is not what I want, but anyway, thanks for suggestion.
I don't think there's no way to turn Image<,> or Mat back to Bitmap in new version 4.2.0.3636 and looks like I have to figure out on my own or wait.

> Image<Gray, byte> image = BitmapExtension.ToImage(BitmapImage)
> Bitmap bitmapImage = image.ToBitmap(); //You can use also for Mat type
> Remember to use nuget emgu.runtime.window or you can't use this library (using Emgu.CV)

**Comment by cayman1021** [comment]
Finally got rid of errors by installing emgu.runtime.window as you mentioned.
Thank you.

**Comment by rufw91** [comment]
Thanks it works
