### ISSUE TITLE
Invert Memory Leak

### ISSUE THREAD

**Issue by murph1329** [emgucv/emgucv#29]
**EmguCV version:** 3.1.0.2504

**Details:**
There's a noticeable memory leak with the "Image<Bgr, byte>.Not" method.  I've tested this with images of varying sizes; however, it's exacerbated when using a larger image and larger scale. The example below is running against an image at resolution 1920x1080.

I am monitoring the Private Byte growth using Process Explorer's Performance Graph.
https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

**Setup:**

            Bitmap newImg = new Bitmap(@"C:\Users\wesley.murphree\Pictures\test.png");
            int i = 0;
            Console.WriteLine("PRESS ENTER...");
            Console.ReadLine();
            do
            {
                Console.WriteLine("Iteration: " + i.ToString());
                Bitmap output = OpenCV.Invert(newImg);
                output.Dispose();
                Console.Write("Processed.  Sleeping 5 seconds....");
                System.Threading.Thread.Sleep(5000);
            }
            while (++i < 5);
            newImg.Dispose();

            Console.WriteLine("\nFinished.  Press enter to close");
            Console.ReadLine();

**Function:**

        public static Bitmap Invert(Bitmap source)
        {
            Emgu.CV.Image<Emgu.CV.Structure.Bgr, byte> imgBgrSource = new Emgu.CV.Image<Emgu.CV.Structure.Bgr, byte>(source);
            Emgu.CV.Image<Emgu.CV.Structure.Bgr, byte> inverted = imgBgrSource.Not();
            imgBgrSource.Dispose();

            Bitmap bmpImg = inverted.ToBitmap();
            inverted.Dispose();

            return bmpImg;
        }

**Comment by emgucv** [comment]
A review in the source code of "Image<TColor, TDepth>.Not" function from 3.2 release doesn't seem to indicate any managed memory leak from the C# code:

```
        public Image<TColor, TDepth> Not()
        {
            Image<TColor, TDepth> res = CopyBlank();
            CvInvoke.BitwiseNot(this, res, null);
            return res;
        }
```
Please note that for every Image<TColor,TDepth>.Not() function calls made, a new Image<,> object is created that use the managed memory (array of bytes). This managed memory won't get released unless the Garbage collector kicks in. In you are monitoring the managed memory without forcing the garbage collector to perform garbage collection, you may see the amount of allocated managed bytes increase. They will got freed only when garbage collector decided to perform a garbage collection, in which case you will see a sharp decrease of managed byte array.

**Comment by emgucv** [comment]
Closing the bug now due to inactivity.
