### ISSUE TITLE
Unity Emgu 4.x error CS1069 'Rectangle' could not be found in the namespace 'System.Drawing'

### ISSUE THREAD

**Issue by ruttlej** [emgucv/emgucv#292]
Unity version 2019.2.19f1 running on Windows 10
Emgu CV v4.x version 4.1.0

I get 533 errors, all along the line of this:

Assets\Emgu.CV\Assets\Scripts\Emgu.CV.Contrib\Tracking\MultiTracker.cs(40,61): error CS1069: The type name 'Rectangle' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

To replicate the issue

1. Start a new project in Unity version 2019.2.19f1
2. Import Emgu CV v4.x from the asset store
3. Import Emgu TF Lite v1.x from the asset store

After the second package is imported 533 persistent errors appear.
Importing other packages can also causes the errors to appear e.g. I2 Localization version 2.8.13 f2

Similar issue appears in version 2019.1.12f1

Can you please advise on how to fix

**Comment by emgucv** [comment]
We have a development build that fixed this issue. Please email us supprt@emgu.com and we will reply with the dev build for you to test with.

We will update the Asset in Unity store soon.

**Comment by emgucv** [comment]
Closing ticket now.
