### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies.

### ISSUE THREAD

**Issue by d8ahazard** [emgucv/emgucv#298]
Hello. I am getting the below error when trying to run emgu.cv in my .net core application on a Raspberry Pi. (Raspbian Buster)

I have tried a number of different configurations/settings, including installing the latest release(s) from NuGet (4.2.0.3636 and the previous release), installing those releases by downloading from github and adding as a reference...etc.

Am I missing something simple? I'm somewhat new to .net, but from my reading, it seems like this *should* be compatible with .net core as it uses .net standard. 

I have manually included the x86 and x64 directories, but am assuming these probably don't do anything on an ARM system...as well...when I manually try to add the cvextern.dll library as a reference the project doesn't like it.

If I need to switch my project to a new framework or compile libraries manually, I'm fine with that...I just need this to run on a Pi.

Edit: Is it possible to only compile the needed libraries to fix the cvextern issue?

TIA.

Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.cvCreateImageHeader(Size size, IplDepth depth, Int32 channels)
   at Emgu.CV.Image`2.AllocateData(Int32 rows, Int32 cols, Int32 numberOfChannels)
   at Emgu.CV.Image`2..ctor(Int32 width, Int32 height)

**Comment by emgucv** [comment]
The Emgu.CV nuget package only provide the managed component (the C# wrapper). You will also need the Emgu.CV.runtime.{platform} component that contains the opencv binary (C++ code)

We do not currently provide Emgu.CV.runtime.raspbian nuget package.

You will need to build the native binary for Raspberry pi (should be an cvextern.so file) and include that in the folder of executable.

**Comment by d8ahazard** [comment]
I have been trying to compile on Raspi 3, as per the instructions on your website...literally since I opened this. After running for around a day on the cmake_configure step, it fails with this error.

c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [opencv/modules/python2/CMakeFiles/opencv_python2.dir/build.make:63: opencv/modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error
make[1]: *** [CMakeFiles/Makefile2:5744: opencv/modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make: *** [Makefile:163: all] Error 2


Five days. 

Are there any instructions for cross-compiling or ARM? Any other way of fixing this?

**Comment by emgucv** [comment]
Your raspberry pi probably do not have sufficient memory to compile Emgu CV. Try to compile with a single worker instead.

The latest code compiles on a Raspberry Pi 4B with 4GB of memory in 4.5 hours. 

If you need a copy of the binary, please send an email to support@emgu.com and I will reply with a copy.

**Comment by d8ahazard** [comment]
Email sent! Thanks so much!

**Comment by zhenzhen823** [comment]
I need EmCV compiled binaries for raspberry Pi 4B.
I have sent email to  support@emgu.com
Thank you.

**Comment by d8ahazard** [comment]
> I need EmCV compiled binaries for raspberry Pi 4B.
> I have sent email to [support@emgu.com](mailto:support@emgu.com)
> Thank you.

FWIW, compiling Emgu.CV on the Pi 4 is a lot easier than on the 3. You should have enough horsepower to do it, the instructions on their page worked for me.

**Comment by zhenzhen823** [comment]
@d8ahazard , Can you share compiled binaries for rpi 4?

**Comment by emgucv** [comment]
For 32-bit Raspberry Pi OS, the official nuget package can be found here:
https://www.nuget.org/packages/Emgu.CV.runtime.debian-arm

For 64-bit Raspberry Pi OS, the official nuget package can be found here:
https://www.nuget.org/packages/Emgu.CV.runtime.debian-arm64

FYI, the 4.8.1 release is compiled for Debian bookworm. The 4.8.0 release is compiled for Debian bullseye. Please pick the release version that match your Raspberry Pi OS version.
