### ISSUE TITLE
how can I   modify transitionMatrix  ？ readonly

### ISSUE THREAD

**Issue by liuxu0938** [emgucv/emgucv#3]
Emgu.CV.World, Version=3.1.0.2504, Culture=neutral, PublicKeyToken=7281126722ab4438

namespace Emgu.CV
{
    //
    // 摘要:
    //     The class implements a standard Kalman filter. However, you can modify transitionMatrix,
    //     controlMatrix, and measurementMatrix to get an extended Kalman filter functionality.
    public class KalmanFilter : UnmanagedObject
    {
        //
        // 摘要:
        //     Initializes a new instance of the Emgu.CV.KalmanFilter class.
        //
        // 参数:
        //   dynamParams:
        //     Dimensionality of the state.
        //
        //   measureParams:
        //     Dimensionality of the measurement.
        //
        //   controlParams:
        //     Dimensionality of the control vector.
        //
        //   type:
        //     Type of the created matrices that should be Cv32F or Cv64F
        public KalmanFilter(int dynamParams, int measureParams, int controlParams, DepthType type = DepthType.Cv32F);

        //
        // 摘要:
        //     Control matrix (B) (not used if there is no control)
        public Mat ControlMatrix { get; }
        //
        // 摘要:
        //     posteriori error estimate covariance matrix (P(k)): P(k)=(I-K(k)*H)*P'(k)
        public Mat ErrorCovPost { get; }
        //
        // 摘要:
        //     priori error estimate covariance matrix (P'(k)): P'(k)=A*P(k-1)*At + Q)
        public Mat ErrorCovPre { get; }
        //
        // 摘要:
        //     Kalman gain matrix (K(k)): K(k)=P'(k)*Ht*inv(H*P'(k)*Ht+R)
        public Mat Gain { get; }
        //
        // 摘要:
        //     Measurement matrix (H)
        public Mat MeasurementMatrix { get; }
        //
        // 摘要:
        //     Measurement noise covariance matrix (R)
        public Mat MeasurementNoiseCov { get; }
        //
        // 摘要:
        //     Process noise covariance matrix (Q)
        public Mat ProcessNoiseCov { get; }
        //
        // 摘要:
        //     Corrected state (x(k)): x(k)=x'(k)+K(k)*(z(k)-H*x'(k))
        public Mat StatePost { get; }
        //
        // 摘要:
        //     Predicted state (x'(k)): x(k)=A*x(k-1)+B*u(k)
        public Mat StatePre { get; }
        //
        // 摘要:
        //     State transition matrix (A)
        public Mat TransitionMatrix { get; }

        //
        // 摘要:
        //     Updates the predicted state from the measurement.
        //
        // 参数:
        //   measurement:
        //     The measured system parameters
        public Mat Correct(Mat measurement);
        //
        // 摘要:
        //     Perform the predict operation using the option control input
        //
        // 参数:
        //   control:
        //     The control.
        //
        // 返回结果:
        //     The predicted state.
        public Mat Predict(Mat control = null);
        //
        // 摘要:
        //     Release the unmanaged resources
        protected override void DisposeObject();
    }
}

**Comment by emgucv** [comment]
Hi, you can take a look at the TestKalman function from this test class:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Test/Class1.cs

This link here will also help:
http://www.emgu.com/wiki/index.php/Working_with_Images#Accessing_the_pixels_from_Mat

As a quick tip, you will need to convert the Mat to Matrix<> object in-order to access and modify the pixel data.
