### ISSUE TITLE
setWindowProperty not available?

### ISSUE THREAD

**Issue by needfulthing** [emgucv/emgucv#303]
I want to set a window to fullscreen. When I use

`Emgu.CV.CvInvoke.NamedWindow("Emgu Window", Emgu.CV.CvEnum.NamedWindowType.Fullscreen);`

it does not work, but it might be because of a bug in the OpenCV framework (see https://github.com/opencv/opencv/issues/10438). To use the workaround I would have to change the window property from normal to fullscreen, but I can't find the implementation of this method in EmguCV 4.2.

**Comment by emgucv** [comment]
Just added the required function in this commit: b7bf2b9ca4322b248c6ea0fce6063692d6b39663

**Comment by emgucv** [comment]
Closing ticket now.
