### ISSUE TITLE
BackgroundSubtractorMOG2 segmentation fault on Linux

### ISSUE THREAD

**Issue by ispysoftware** [emgucv/emgucv#310]
creating a BackgroundSubtractorMOG2 instance on linux (dotnet core) throws a segmentation fault
I think this is related:

https://stackoverflow.com/questions/19031836/get-background-model-from-backgroundsubtractormog2-in-python

**Comment by ispysoftware** [comment]
I think this is caused by the IntPtr's in BackgroundSubtractor classes in emgucv being uninitialized. Windows is defaulting them to IntPtr.Zero but linux/ dotnet core isn't.
Need to set them explicitly

 private IntPtr _sharedPtr = IntPtr.Zero;
 private IntPtr _algorithmPtr = IntPtr.Zero;
 private IntPtr _backgroundSubtractorPtr = IntPtr.Zero;

**Comment by ispysoftware** [comment]
yep that's the issue - for this to be compatible with dotnet core you need to go through and assign IntPtr.Zero to every hanging private and protected IntPtr in the projects.

**Comment by emgucv** [comment]
Added a Unit Test in this commit:
https://github.com/emgucv/emgucv/commit/ecc06e0957d33ee0b162173ed101aa2309f66986

Checked out the latest master: https://github.com/emgucv/emgucv/commit/ecc06e0957d33ee0b162173ed101aa2309f66986 

Tested to work in Ubuntu, by following the instructions here to build the cvextern.so file:
http://www.emgu.com/wiki/index.php/Download_And_Installation#Ubuntu

Running Unit Test by going to emgucv/Emgu.CV.Test/Emgu.CV.Test.NetCore folder and type:
`dotnet test -v -d --blame`
All test passed under Ubuntu 18.04.4 LTS

**Comment by emgucv** [comment]
FYI, Ubuntu is running in 64bit mode.

**Comment by ispysoftware** [comment]
only difference here is I'm on Ubuntu 19.10

**Comment by emgucv** [comment]
How many tests failed when you run `dotnet test -v d --blame` in the "Emgu.CV.Test/Emgu.CV.Test.Netcore" folder? In Ubuntu 18.04 LTS, I have 297 tests passed out of 297. 

Can you also test with "-DENABLE_FAST_MATH:BOOL=FALSE" (the default value). Turning fast math on will scarify the floating point precision in favor of speed, which can results in test failures in some cases.

**Comment by ispysoftware** [comment]
I just rebuilt it all from source and ran it and all the tests passed OK. Copied the dll into my app folder and it worked fine. Only difference I can see is that the netstandard.dll I was using was built on windows and this one was built on linux.
