### ISSUE TITLE
Help with Raspberry Pi -> DllNotFoundException

### ISSUE THREAD

**Issue by werddomain** [emgucv/emgucv#317]
I can't find any test project for RaspBerry PI.

It will be nice if someone can make a step-by-step guide to run this library with .net core (3.1)

I'm able to compile and run an app but it crash as soon as i call the library.

On windows, it run fine.

On linux, i get the error :

>  ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to he
> lp diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared obje
> ct file: No such file or directory
>    at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
>    at Emgu.CV.CvInvoke..cctor()
>    --- End of inner exception stack trace ---
>    at Emgu.CV.CvInvoke.cveVideoCaptureRelease(IntPtr& capture)
>    at Emgu.CV.VideoCapture.DisposeObject()
>    at Emgu.Util.DisposableObject.Dispose(Boolean disposing)
>    at Emgu.Util.DisposableObject.Finalize()Index: 0
> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
>  ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to he
> lp diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared obje
> ct file: No such file or directory
>    at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
>    at Emgu.CV.CvInvoke..cctor()
>    --- End of inner exception stack trace ---
>    at Emgu.CV.CvInvoke.cveVideoCaptureCreateFromDevice(Int32 index, API apiPreference)
>    at Emgu.CV.VideoCapture..ctor(Int32 camIndex, API captureApi)

I have received the file libcvextern.so by email and i have put it in the same directory. I have also added this file to a folder who i have executed : 'export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH'

i have installed packages listed in https://raw.githubusercontent.com/emgucv/emgucv/master/platforms/raspbian/apt_install_dependency 

the app is published using this settings:
 Target Runtime: linux-arm 
 Targed Framework: netcoreapp3.1

**Comment by werddomain** [comment]
Os informations : 

> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian

**Comment by emgucv** [comment]
I have updated the instruction for building and running dotnet core application on Raspbian here:
http://www.emgu.com/wiki/index.php/Download_And_Installation#Raspbian_.28Raspberry_Pi.29
If you follow the build instruction, you should be able to build and run the .Net Core console app under "Emgu.CV.Example\BuildInfo.NetCore.Console"

The "libcvextern.so" file should be under the "libs\arm" folder in raspbian. It is best to build the ".so" file from source from your source code check out. That will make sure the managed code matched the unmanaged code.

Debug instructions are provided in case you ran into DllNotFoundException:
http://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

**Comment by werddomain** [comment]
Tanks, i will try it :)

**Comment by werddomain** [comment]
> I have updated the instruction for building and running dotnet core application on Raspbian here:
> http://www.emgu.com/wiki/index.php/Download_And_Installation#Raspbian_.28Raspberry_Pi.29
> If you follow the build instruction, you should be able to build and run the .Net Core console app under "Emgu.CV.Example\BuildInfo.NetCore.Console"
> 
> The "libcvextern.so" file should be under the "libs\arm" folder in raspbian. It is best to build the ".so" file from source from your source code check out. That will make sure the managed code matched the unmanaged code.
> 
> Debug instructions are provided in case you ran into DllNotFoundException:
> http://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException
the "libs\arm" dirrectory is in my app folder or in the root of raspbian?

**Comment by emgucv** [comment]
It should be under "{emgucv_root}\libs\arm"

**Comment by werddomain** [comment]
I have ben able to run the samble from linux, but i can't run it from windows.
I get errors about CvInvoke.ExternLibrary .

> **In Visual studio 2019 Version 16.5.4**
> 'CvInvoke' does not contain a definition for 'ExternLibrary'	Emgu.CV.Platform.NetStandard	D:\emgucv\Emgu.CV.Contrib\Aruco\ArucoInvoke.cs

I still dont understand how to configure my project to run in windows and compile in linux.
My project run in windows, but not in linux. Even if i build it in linux. I get the same error as before.

Is my .net core console project expect files to be in a specific dirrectory in linux?

I wish i have some instructions or sample to start with :(

**Comment by werddomain** [comment]
i have created a Fork of the repository and added a test console app there : 
https://github.com/werddomain/emgucv/tree/master/NetCore_Console

**Comment by emgucv** [comment]
Unless you do a cross compilation of Windows binary on Linux system, you won't be able to take the "libcvextern.so" binary compiled on Linux targeting Linux ARM architecture and run it on Windows. In order to run the .Net Core project on Windows, you need to compile the native binary (cvextern.dll) targeting Windows. If you need to target both windows and raspbian, compile 3 different native binaries: "libs\x86\cvextern.dll", "libs\x64\cvextern.dll", "libs\arm\libcvextern.so". Then add both "Emgu.CV.Windows\Emgu.CV.Runtime.Windows.shproj" and "Emgu.CV.Runtime.Raspbian.shproj" as reference to your dot net core project. As it was done in our dot net core demo project here:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/BuildInfo.NetCore.Console/BuildInfo.NetCore.Console.csproj

**Comment by emgucv** [comment]
Closing ticket now.
