### ISSUE TITLE
4.1 up to 4.2.0.3662 can't  _frame.Bitmap

### ISSUE THREAD

**Issue by jackswei** [emgucv/emgucv#318]
how to fix it
it in 4.1 work ok,but up 4.2 error
 var varrayShow = BitmapToBytes(_frame.Bitmap);
public static byte[] BitmapToBytes(Bitmap Bitmap)
        {
            try
            {
                System.IO.MemoryStream ms = new System.IO.MemoryStream();
                Bitmap.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                byte[] b = ms.GetBuffer();
                return b;
            }
            catch (ArgumentNullException ex)
            {
                throw ex;
            }
        }
thank

**Comment by emgucv** [comment]
See v4.2 release note here:
http://www.emgu.com/wiki/index.php/Version_History#Emgu.CV-4.2.0

For `Image<,>.Bitmap` property in 4.1.x and older release, its equivalent in v4.2.0 is `Image<,>.AsBitmap()`

**Comment by jackswei** [comment]
thk,it's ok.
