### ISSUE TITLE
Ellipse shifted with 90 degrees (when drawing)

### ISSUE THREAD

**Issue by FatalError2000** [emgucv/emgucv#32]
It seems to have a bug in CvInvokeCore.cs when calling the Ellipse method: 
```
      public static void Ellipse(
          IInputOutputArray img,
          RotatedRect box,
          MCvScalar color,
          int thickness = 1,
          CvEnum.LineType lineType = CvEnum.LineType.EightConnected,
          int shift = 0)
      {
         Size axes = new Size();
         axes.Width = (int)Math.Round(box.Size.Height * 0.5);
         axes.Height = (int)Math.Round(box.Size.Width * 0.5);

         Ellipse(img, Point.Round(box.Center), axes, box.Angle, 0, 360, color, thickness, lineType, shift);
      }
```
axes.Width shoud be defined like this instead : axes.Width = (int)Math.Round(box.Size.Width* 0.5);
axes.Height shoud be defined like this instead : axes.Height = (int)Math.Round(box.Size.Height * 0.5);$

Otherwise the ellipse will be drawn with a 90 degrees offset

**Comment by DiebBlue** [comment]
Yes, I also stumbled across this bug today. In Version 4.7.0 the bug is still there.

**Comment by emgucv** [comment]
Fixed in the commit above: 2a415af

Used the Open CV native implementation instead. Tested and works. Will be included in the next release (4.8.0)

**Comment by DiebBlue** [comment]
This issue should be closed.

**Comment by emgucv** [comment]
Closing ticket now.
