### ISSUE TITLE
Cannot generate solution file with Windows 10

### ISSUE THREAD

**Issue by Lotte1990** [emgucv/emgucv#323]
Running the .bat file in platforms/windows and using the CMake GUI gives me the same error about a macro. I also get an error when running the icl .bat file. The Intel C++ compiler is installed on this machine and I can successfully compile other code with it.
Link to outputs: https://drive.google.com/file/d/1A3bv0807hdcjxRuDrjGXgIjx7Fp_Wnig
What am I doing wrong?
Edit: I'm adding the CMake output: https://drive.google.com/file/d/1lMYf1bedXpQgAQEa3B7mJhRpkoRgv5as

**Comment by emgucv** [comment]
The error said that the sub-modules has not been checked out.

Run a "git submodule update --init --recursive" after you have checkout the emgucv repo.

**Comment by emgucv** [comment]
Closing ticket now.
