### ISSUE TITLE
Raspian cmake FindCSharp error

### ISSUE THREAD

**Issue by Int32Overflow** [emgucv/emgucv#324]
![grafik](https://user-images.githubusercontent.com/20139038/80944032-e1e48380-8de8-11ea-8c58-910c3ab95637.png)

I think he can't find my .Net Core 3.1 SDK installation. Is there a manual how to install the SDK on Raspberry Pi 3 (Raspian Buster)?

[CMakeOutput.log](https://github.com/emgucv/emgucv/files/4573239/CMakeOutput.log)

**Comment by emgucv** [comment]
Here is the instruction from microsoft to manually install dotnet for Raspbian Buster:
https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-linux#download-and-manually-install
There is no automatic dotnet package installer available for ARM architecture yet. 
You need to be able to use dotnet on the commandline before you can compile Emgu CV on raspbian.

**Comment by Int32Overflow** [comment]
@emgucv Thanks for the answer. I will test it again the next days. I guess something went wrong with the EXPORT.

**Comment by Int32Overflow** [comment]
It is working :-)
