### ISSUE TITLE
SURF class is not available in commercial release?

### ISSUE THREAD

**Issue by Dragonheart91** [emgucv/emgucv#325]
Hi!

We have Emgu.CV-CR 3662 and Emgu.CV.runtime.windows-CR packages installed. However under XFeatures2D I do not see the SURF type.  From what I see in source code it's marked with #if NONFREE directive, but we are already using CR packages.
Any ideas?

**Comment by emgucv** [comment]
Open CV's NONFREE module refers to patented algorithm, that requires the commercial application user to contact the patent owner to negotiate a fee on based on each individual use case. 

Emgu CV's commercial license only covers the C# layer that interact with Open CV. It does not covered usage on any non-Emgu implemented binary. It was mention in the commercial license as well as here:
http://www.emgu.com/wiki/index.php/Licensing:#Terms

License to patent could be priced exponential higher than our Emgu CV license. For SURF, the link to the patent can be found here:
https://worldwide.espacenet.com/patent/search/family/036954920/publication/US2009238460A1?q=pn%3DUS2009238460
You can contact the license owner to find out the price if that is what you want. We can custom build a commercial release for a relatively small fee compares to the patent fee you paid to use SURF. 

Open CV's NONFREE module are disabled by default. Open CV's team do not recommend using algorithms in the NONFREE module. They already have better alternative included in the library. 

Checkout the Open CV release notes:
https://github.com/opencv/opencv/wiki/ChangeLog

Notes on 2.4 beta mentions:

> SIFT and SURF have been moved to a separate module named nonfree to indicate possible legal issues of using those algorithms in user applications.

> FAST/ORB which is patent free replacement of SURF.

Release Notes on 2.4.2 mentions:

> New keypoint descriptor FREAK has been contributed by EPFL group: Kirell Benzi, Raphael Ortiz, Alexandre Alahi and Pierre Vandergheynst. It’s claimed to be superior to ORB and SURF descriptors, yet it’s very fast (comparable to ORB). 

Release Notes on 3.0 mentions:

> Gil Levi contributed very nice LATCH binary descriptor that outperforms all presently available in OpenCV binary descriptors (ORB, BRIEF, AKAZE etc.) and is comparable with heavier and slower SURF.

**Comment by Dragonheart91** [comment]
Thanks a lot for an overwhelming explanation! Absolutely makes sense.

**Comment by vmgolubev** [comment]
Hi, I have tried to use FREAK or BEBLID The function/feature is not implemented, BRISK or SIFT are working fine. According to source code FREAK or BEBLID are not marked as a NONFREE...
![image](https://user-images.githubusercontent.com/45319174/206907054-2fc5db6c-2980-436c-a6c4-9b8425231887.png)

**Comment by emgucv** [comment]
Freak & BEBLID are Feature Extractors, not Feature Detector. You can only call the "Compute" function on them. You cannot call the DetectorAndCompute function because they are not Feature Detectors.

You can use FAST as feature detector to detect the keypoints, then use Freak or BEBLID to compute the descriptors.
