### ISSUE TITLE
WPF example not up to date with current version

### ISSUE THREAD

**Issue by sekulicb** [emgucv/emgucv#327]
Hi. I'm trying to create a simple demo for a client, where we need a camera capture feature, but yet I failed to find anything related to this, for this current version, that is not a 7-year-old tutorial on how to do this. For example:

var capture = new VideoCapture(1, VideoCapture.API.DShow); //create a camera capture
var image = capture.QueryFrame(); //take a picture

This should be the standard way to go but:

- How to convert this to the WPF Image source? All tutorials point to : [docs example](http://www.emgu.com/wiki/index.php/WPF_in_CSharp) but where is the **IImage** type that ToBitmapSource should accept? It's not in the latest version. Official WPF example also points to [same thing](https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/WPF/Window1.xaml.cs)
- Where is the **Bitmap** property on image variable from above? I should be able to just pass it to my own method but still, it's not there!
- Is there a more complete (modern) way or tutorial to let say capture an image from a webcam for WPF running on top of .NET CORE 3.1, then just writing down two lines of code?

**Comment by AeroClassics** [comment]
Let me preface by saying I do not work with .NET Core at all. But, with EmguCV 4.2 [As shown here](http://www.emgu.com/wiki/index.php/Version_History#Emgu.CV-4.2.0) no longer has bitmaps in the Mats and Images. If you need a bitmap then you need to use the BitmapExtension class that is located in Emgu.CV.UI, which is the Windows specific library. 

As for getting a BitmapSource object you can try the following:

`        public static BitmapSource ToBitmapSource(Mat image)
        {
            System.Drawing.Bitmap source;

            source = Emgu.CV.BitmapExtension.ToBitmap(image);
            IntPtr ptr = source.GetHbitmap(); //obtain the Hbitmap

            BitmapSource bs = System.Windows.Interop.Imaging.CreateBitmapSourceFromHBitmap(
                ptr,
                IntPtr.Zero,
                Int32Rect.Empty,
                System.Windows.Media.Imaging.BitmapSizeOptions.FromEmptyOptions());

            DeleteObject(ptr); //release the HBitmap
            return bs;
        }
`
This works very well for me in .NET 4.7.2.

Doug

**Comment by sekulicb** [comment]
Hi @AeroClassics.

I don't need Bitmap. I need something that can be used as source property on Image control in WPF. If Bitmap is the way to go, then I'm fine with it. I don't want you to think that Bitmap is requirement. All I see online are tutorials that first convert mat to Bitmap, and then Bitmap to ImageSource or BitmapSource.

I see no reason why this library should not be compatible 100% with .NET core 3.1 when dlls are ported to NetStandard 2.0.

I tried your code but where do I get Emgu.CV.BitmapExtension namespace?

![emgudemo](https://user-images.githubusercontent.com/20758693/81472618-928fc000-91f9-11ea-80db-823d37ff4702.PNG)

**Comment by sekulicb** [comment]
If **BitmapExtension** is located in Emgu.CV.UI, which is the Windows-specific library, then obviously this will not work for .NET Core. I just can't believe that there are no real-world examples of modern WPF apps using this library. It's not like .NET Core was born yesterday.

**Comment by emgucv** [comment]
Here is a demo for using Emgu CV with WPF in .net core:
https://github.com/emgucv/emgucv/tree/4.5.1/Emgu.CV.Example/WPF.NetCore

It is included in the ".zip" release file. You can download the 4.5.1 release here:
https://github.com/emgucv/emgucv/releases/tag/4.5.1

Open the solution file under "Solution\Windows.Desktop\Emgu.CV.Example.sln" and look for the WPF.NetCore project.

**Comment by emgucv** [comment]
Closing ticket now.
