### ISSUE TITLE
 real-time eye blink detection

### ISSUE THREAD

**Issue by NimaZare** [emgucv/emgucv#329]
Hello
Please provide a sample code that includes eye blink detection.
Real time for photos and videos.
thank you

**Comment by emgucv** [comment]
The issue tracker is for bug tracking. If you are seeking help for implementation please post it in Discussions.

For you question, you can look at this Open CV eye blinking implementation in python and migrate that to C#:
https://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/

FYI, Facial Landmark recognition in the above sample is implemented in our Xamarin Forms demo.

Closing ticket now.
