### ISSUE TITLE
DisparityWLSFilter exception

### ISSUE THREAD

**Issue by nombrote** [emgucv/emgucv#332]
HI,

I'm trying to use DisparityWLSFilter
(like that example of OpenCV)
But when i call to to Filter method, it throw an exception (AccessViolationException)

It is a bug on emgu? Has an example that work?

**Comment by emgucv** [comment]
This unit test use the DisparityWLSFilter.Filter method and passed the test:

https://github.com/emgucv/emgucv/blob/4.5.1/Emgu.CV.Test/AutoTestVarious.cs#L1704

**Comment by emgucv** [comment]
Closing ticket now.
