### ISSUE TITLE
SURF or SHIFT detector not on current versión (4.2)

### ISSUE THREAD

**Issue by nombrote** [emgucv/emgucv#333]
On last versions it has SURF, but on that versión i cant find it.
That feature of openCV is not present yet?

http://www.emgu.com/wiki/index.php/SURF_feature_detector_in_CSharp

**Comment by emgucv** [comment]
Duplicate of issue https://github.com/emgucv/emgucv/issues/325

Please see detail about SURF there.

Do you means SIFT when you mention SHIFT? 

SIFT will be added back in 4.3 due to patent expiration. See this commit:
https://github.com/emgucv/emgucv/commit/6c87e76e3213dbf0385beb3a4407f49582d6b5e6

**Comment by nombrote** [comment]
It's present on 4.4. I will close the issue
