### ISSUE TITLE
FileStorage and FileNode:  loading from memory

### ISSUE THREAD

**Issue by vpenades** [emgucv/emgucv#336]
Hi

I want to use `CascadeClassifier`, but instead of loading the XMLs from the file system I want to load them from memory. Is this possible?

`CascadeClassifier `only accepts a filePath as an input, and I guess it can also accept a `FileNode`, which can be provided by `FileStorage`... which, again, it seems it can only load from the FileSystem.

I am surprised there's no way to load the file from a `System.IO.Stream` or something like that.

**Comment by emgucv** [comment]
Here is how to load a string in memory into File storage
```
                string s = .... //your xml as a string
                FileStorage fs = new FileStorage(s, FileStorage.Mode.Read | FileStorage.Mode.Memory);
```
