### ISSUE TITLE
Does it support ScaleAdd function?

### ISSUE THREAD

**Issue by gaessanty** [emgucv/emgucv#338]
https://docs.opencv.org/master/d2/de8/group__core__array.html#ga9e0845db4135f55dcf20227402f00d98

Does it support ScaleAdd function?

**Comment by emgucv** [comment]
Added in this commit:
https://github.com/emgucv/emgucv/commit/5a47cef345d9fd8cd3e094aac203b8936907023d

For existing 4.3 release, use CvInvoke.AddWeighted function with betas = 1.0 and gamma = 0.0:
http://www.emgu.com/wiki/files/4.3.0/document/html/180ae243-ff3c-f59c-7e3a-a8e474583e8e.htm
