### ISSUE TITLE
Border detection

### ISSUE THREAD

**Issue by petrasvestartas** [emgucv/emgucv#340]
Hi,

I am new to ImageSharp, I was using Accord.NET, Aforge but these libraries became outdated.

I am searching for a method to get multiple borders of a Bitmap that contains white shapes.

I would like to get not one but all of possible borders:

![border-following](https://user-images.githubusercontent.com/18013985/84684089-74c02400-af38-11ea-87e5-b92bcffa614a.jpg)

**Comment by emgucv** [comment]
First apply CvInvoke.Canny to extract the edges. Then you can use CvInvoke.FindContours finction to extract all the contours.

See the shape detection demo for how to use CvInvoke.FindContours in your project:
http://www.emgu.com/wiki/index.php/Shape_(Triangle,_Rectangle,_Circle,_Line)_Detection_in_CSharp#Source_Code

**Comment by emgucv** [comment]
Closing ticket now.
