### ISSUE TITLE
System.Drawing.Common version conflict with Emgu.CV

### ISSUE THREAD

**Issue by vpenades** [emgucv/emgucv#342]
When using these two libraries within the same project I have version conflicts:

Emgu.CV 4.3.0.3890 -> System.Drawing.Common (>= 4.7.0) 
Emgu.TF.Lite.Models 2.2.0.932 -> System.Drawing.Common (= 4.5.1)

Please, Update Emgu.TF.Lite.Models to the latest version of System.Drawing.Common (or remove it altogether if it's not really needed)

**Comment by emgucv** [comment]
Fixed in this commit: https://github.com/emgucv/emgutf/commit/81540886641b3124e04fffa3d786de5e7362f9a9
Thanks for pointing out.
