### ISSUE TITLE
SEHException in net.Forward() with CUDA background.

### ISSUE THREAD

**Issue by Feodoros** [emgucv/emgucv#343]
Hello, everyone! I try to build project with CUDA. I installed CUDA version 10.0, NuGet package Emgu.CV.runtime.windows version 4.3.0.3890, Emgu.CV.runtime.windows.cuda version 4.3.0.3890. When I test this with command ```CudaInvoke.HasCuda```, it is true. When I do this everything works:

    Net net = DnnInvoke.ReadNetFromTensorflow(_modelFile, _configFile);
    net.SetInput(DnnInvoke.BlobFromImage(image.Mat, 1, new System.Drawing.Size(300, 300), default(MCvScalar), false, false));
    Mat mat = net.Forward();

But when I add CUDA background and target:

    Net net = DnnInvoke.ReadNetFromTensorflow(_modelFile, _configFile);
    net.SetPreferableBackend(Emgu.CV.Dnn.Backend.Cuda);
    net.SetPreferableTarget(Emgu.CV.Dnn.Target.Cuda);                
    net.SetInput(DnnInvoke.BlobFromImage(image.Mat, 1, new System.Drawing.Size(300, 300), default(MCvScalar), false, false));                
    Mat mat = net.Forward();
it doesn't work. It fails with "System.Runtime.InteropServices.SEHException".

Exception appears in string ```Mat mat = net.Forward();``` 

My GPU is NVIDIA GeForce 940MX (Maxwell 1.0). 

May anyone help with this problem, please?

**Comment by Feodoros** [comment]
Also I tryed with CUDA 9.0 and CUDA 10.2 
Of course, I downloaded necessary cuDNN and copied files in bin, include, lib folders. It is problem that HasCud is true, but module DNN with background CUDA doesn't work. Also I got Exception: "...switching to CPU" too. 

How I can solve this problem?

**Comment by emgucv** [comment]
Open CV's CUDA backend for DNN may not support all the operations in your model. For supported operations in the CUDA DNN backend, check out the support matrix listed here:
https://github.com/opencv/opencv/pull/14827

If your model used a non-supported layer the execution may fail.

**Comment by Feodoros** [comment]
> 
> 
> Open CV's CUDA backend for DNN may not support all the operations in your model. For supported operations in the CUDA DNN backend, check out the support matrix listed here:
> [opencv/opencv#14827](https://github.com/opencv/opencv/pull/14827)
> 
> If your model used a non-supported layer the execution may fail.

I use SSD Face Detector and I use these 2 files (opencv_face_detector_uint8.pb, opencv_face_detector.pbtxt) from [here](https://github.com/opencv/opencv/tree/master/samples/dnn/face_detector). You mean that this model doesn't work with CUDA?

**Comment by emgucv** [comment]
The file:
https://raw.githubusercontent.com/opencv/opencv_3rdparty/dnn_samples_face_detector_20180220_uint8/opencv_face_detector_uint8.pb
is a quantized model (UINT8). I don't think the Open CV's DNN CUDA backend support quantized model. Feel free to point me out if I am wrong. Afaik, only Float and Float16 is supported.

Use the FP16 model if you want to use the CUDA DNN backend:
https://raw.githubusercontent.com/opencv/opencv_3rdparty/dnn_samples_face_detector_20180205_fp16/res10_300x300_ssd_iter_140000_fp16.caffemodel
Load it with the DNN caffe importer.

**Comment by Feodoros** [comment]
> 
> 
> The file:
> https://raw.githubusercontent.com/opencv/opencv_3rdparty/dnn_samples_face_detector_20180220_uint8/opencv_face_detector_uint8.pb
> is a quantized model (UINT8). I don't think the Open CV's DNN CUDA backend support quantized model. Feel free to point me out if I am wrong. Afaik, only Float and Float16 is supported.
> 
> Use the FP16 model if you want to use the CUDA DNN backend:
> https://raw.githubusercontent.com/opencv/opencv_3rdparty/dnn_samples_face_detector_20180205_fp16/res10_300x300_ssd_iter_140000_fp16.caffemodel
> Load it with the DNN caffe importer.

Now I use these 2 files: res10_300x300_ssd_iter_140000_fp16.caffemodel, deploy.prototxt. But get this Exception again :( 

What may be wrong?

![изображение](https://user-images.githubusercontent.com/23313519/87055978-a95c8e00-c20d-11ea-8688-73e4daab684a.png)

**Comment by emgucv** [comment]
Updated our Face detection demo with option to choose either 16 bit and 32 bit caffe model (old code used 32-bit model)
652ec0170c8481858118ae08b10d6359252a6ea3
Also use Cuda DNN backend when possible:
1422e4214e19c02bcddf9ea2b41959237a301dc7
Tested both 16bit model and 32 bit models on master, build with CUDA 10 and running on GTX 1080. 

Full source code can be found here:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/XamarinForms/Core/FaceLandmarkDetectionPage.cs

Works without issues.

**Comment by Feodoros** [comment]
> 
> 
> Updated our Face detection demo with option to choose either 16 bit and 32 bit caffe model (old code used 32-bit model)
> [1422e42](https://github.com/emgucv/emgucv/commit/1422e4214e19c02bcddf9ea2b41959237a301dc7)
> 
> Also use Cuda DNN backend when possible:
> [652ec01](https://github.com/emgucv/emgucv/commit/652ec0170c8481858118ae08b10d6359252a6ea3)
> 
> Tested both 16bit model and 32 bit models on master, build with CUDA 10 and running on GTX 1080.
> 
> Full source code can be found here:
> https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/XamarinForms/Core/FaceLandmarkDetectionPage.cs
> 
> Works without issues.

Many thanks for your help. But I still have the same error.
VS 2019, GPU -- 940MX, CUDA 10 + cuDNN for CUDA 10 (moved files from bin, include and lib folders to appropriate dirs in dir with CUDA).
What version of Visual Studio do you run with this? Because I found that CUDA 10.0 works only with the 2017 version. Could this be the case? However, the Emgu.CV.runtime.windows.cuda package is not installed correctly in Visual Studio 2017.

**Comment by Feodoros** [comment]
Hello! I tested my solution on other PCs. It works  without issues. So it's probably because of my hardware. If someone will meet my problem, try testing it on other machines. 
Many thanks for your helping!
