### ISSUE TITLE
Aruco Detector crashes

### ISSUE THREAD

**Issue by buluba89** [emgucv/emgucv#35]
Hello
I am trying to use the aruco detector from opencv contrib with images from a kinect, but it crashes all the time.
Even the example crashes (using a standard logitech webcam) and i tested both the precompiled executable and running from source

Has anyone succeded detecting aruco markers, if yes how ?
Thanks a lot !

**Comment by ETLang** [comment]
I'm seeing the same crash. Other demos work ok, but Aruco crashes. Easiest repro is to run the sample and click the "Print Aruco Board" button. Crash occurs on call to ArucoInvoke.cveArucoGridBoardCreate. 

Exception details:
Unhandled exception at 0x770F9AAA (ntdll.dll) in Aruco.exe: 0xC0000374: A heap has been corrupted (parameters: 0x771358E8).


Looks like the P/Invoke signature is incompatible with the definition in cvextern. I'd get the original source and try twiddling with it myself but EMGU website is apparently down and I can't access it.

**Comment by emgucv** [comment]
Fixed in the above commit. Website has a database issue yesterday and has been fixed too. 

Thanks for pointing that out.

**Comment by ETLang** [comment]
Did the trick! Thank you!

**Comment by okazolab** [comment]
The Aruco demo crashes on my PC with random exceptions, during call of various functions in Emgu.CV.Aruco namespace. I did not recompile 3.3 with the above fix, but I tried to call  cveArucoDictionaryCreate1() via the public Dictionary(int nMarkers, int markerSize) constructor with the 3.2 x86 binaries. The demo crashes there too, during the call or later, in GridBoard,Draw(), ArucoInvoke.DetectMarkers(), etc. The most typical exception is "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

**Comment by cwule** [comment]
I have the same issue like okazolab. Got EmguCV via NuGet though, will try to build the newest commit.

**Comment by cwule** [comment]
The error also occurs for the latest commit. I get the message "Attempted to read or write protected memory. This is often an indication that other memory is corrupt." for the ArucoInvoke.DetectMarkers method:
```    
     Mat mat = imageCV.Mat;
     Mat imageCopy = new Mat();
     mat.CopyTo(imageCopy);
     VectorOfInt markerIds = new VectorOfInt(); 
     DetectorParameters decParameters = new DetectorParameters();
     decParameters.AdaptiveThreshWinSizeMax = 23;
     VectorOfVectorOfPoint markerCorners = new VectorOfVectorOfPoint();
     ArucoInvoke.DetectMarkers(mat, dictionary, markerCorners, markerIds, decParameters);

**Comment by emgucv** [comment]
This commit should have it fixed:
24d44b45d9abe701144fb28005a33bf865542bf8

**Comment by cwule** [comment]
Awesome, that works! 
Thanks a lot.

**Comment by emgucv** [comment]
Closing issue now.
