### ISSUE TITLE
Serialize  problem

### ISSUE THREAD

**Issue by qq61786631** [emgucv/emgucv#351]
Whenever I try to serialize  **VectorOfMat/VectorOfRect**  object, it throw the exception:

Type 'Emgu.Util.UnmanagedObject' in Assembly 'Emgu.CV.Platform.NetStandard, Version=4.3.0.3890, Culture=neutral,PublicKeyToken=7281126722ab4438' is not marked as serializable.

how to solve this problem?

**Comment by emgucv** [comment]
Neither VectorOfMat or VectorOfRect implemented serialization. You can use the `VectorOfMat.Values` or `VectorOfRect.ToArray()` functions to get `Mat[]` or `Rect[]`, both are serializable.

**Comment by emgucv** [comment]
Closing ticket now.
