### ISSUE TITLE
VideoCapture using MSMF backend doesn't populate all properties

### ISSUE THREAD

**Issue by HEBOS** [emgucv/emgucv#357]
Hi,

Here are three different initializations of VideoCapture object.
First with backend not specified, second with FFMPEG specified and finally MSMF.
Notice that only if FFMPEG backend populates the height and width correctly.
Am I missing something, or this is a bug?

Thanks

_capture1 = new VideoCapture(@"c:\t\x.mp4");
{Emgu.CV.VideoCapture}
    BackendName: "FFMPEG"
    CaptureSource: Highgui
    FlipHorizontal: false
    FlipType: None
    FlipVertical: false
    Height: 2160
    IsOpened: true
    Ptr: 0x000001717a421150
    Width: 3840
    _ptr: 0x000001717a421150

_capture1 = new VideoCapture(@"c:\t\x.mp4");
{Emgu.CV.VideoCapture}
    BackendName: "FFMPEG"
    CaptureSource: Highgui
    FlipHorizontal: false
    FlipType: None
    FlipVertical: false
    Height: 2160
    IsOpened: true
    Ptr: 0x00000170c53c9980
    Width: 3840
    _ptr: 0x00000170c53c9980

_capture1 = new VideoCapture(@"c:\t\x.mp4", VideoCapture.API.Msmf);
{Emgu.CV.VideoCapture}
    BackendName: "MSMF"
    CaptureSource: Highgui
    FlipHorizontal: false
    FlipType: None
    FlipVertical: false
    Height: 0
    IsOpened: true
    Ptr: 0x00000170c52ff4c0
    Width: 0
    _ptr: 0x00000170c52ff4c0

**Comment by emgucv** [comment]
Not all properties are supported by all backends. See Open CV documentation:
https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html#aa6480e6972ef4c00d74814ec841a2939

> Returns
> Value for the specified property. Value 0 is returned when querying a property that is not supported by the backend used by the VideoCapture instance.

**Comment by emgucv** [comment]
Closing ticket now.
