### ISSUE TITLE
Mish activation

### ISSUE THREAD

**Issue by chrisn1983** [emgucv/emgucv#360]
Hi, I was porting an OpenCV DNN Darknet/Yolo detection program from C++ over to C# , and found that the 'ReadNetFromDarknet' function wasn't able to load Yolo v4 config files as it doesn't recognise the 'mish' activation function.  Will this be included in the next release of EMGU?  Thanks

**Comment by emgucv** [comment]
Looks like it has been fixed in Open CV:
https://github.com/opencv/opencv/issues/17148

If it is part of OpenCV v4.4, it will be included in Emgu CV v4.4

**Comment by emgucv** [comment]
Emgu CV v4.4 has been released. This should have been fixed in the new release. Please give it a try.
