### ISSUE TITLE
CR release of EmguCV 4.4

### ISSUE THREAD

**Issue by john-tenney-home** [emgucv/emgucv#366]
With Emgu 4.3, we installed Emgu.CV.runtime.windows-CR and Emgu.CV-CR NuGet packages (in addition to your TF code that we use!). We got these from the download location you gave us access to when we paid the commercial fee.

In Emgu 4.4, it seems we are supposed to use the standard Emgu.CV and Emgu.CV.runtime.windows NuGet packages? Usually there’s some performance enhancements that come from using the CR versions (either CUDA or TBB, etc). How do we get access to those? I go to the download location and only see the older 4.3 code.

**Comment by emgucv** [comment]
There are quite a few significant changes in the nuget packages structure in the v4.4 release. Details can be found on the release note:
http://www.emgu.com/wiki/index.php/Version_History#Change_Log

> Change in nuget packages:
> Both commercial and open source nuget package now use the Emgu.CV nuget package from nuget.org. The commercial release provide runtime nuget packages that are built with OpenVino and have IPP and CPU dispatch enabled.
> No longer append "-CR" to commercial nuget package. Add "dldt" to nuget package compiled with openvino. This is to make clear what was in the commercial release and matches the Open CV package naming scheme (such as opencv-4.4.0-dldt-2020.4-vc16-avx2.zip). For example, the Emgu.CV.windows.runtime-CR package in v4.3 has been renamed to Emgu.CV.windows.runtime.dldt in v4.4. The Emgu.CV.windows.runtime.cuda-CR package in v4.3 has been renamed to Emgu.CV.windows.runtime.cuda.dldt in v4.4.
> Added Emgu.CV.Bitmap nuget package that contains the conversion code from Emgu CV images to Bitmap. This package targets .NetStandard platform. If you are running on Linux / Mac OS platform, you will need to make sure native GDI+ is installed in your system, or it will failed on dependency when Bitmap is used.
> Added Emgu.CV.UI nuget package. This package contains Emgu.CV.Platform.NetFramework.dll and Emgu.CV.Platform.NetCore.dll originally contained in Emgu.CV nuget pacakge in v4.3. These two dlls are only compatible with Windows platform.
> Emgu.CV nuget package now only targets .NetStandard platform.
> Split up Emgu.CV.runtime.cuda.dnn nuget packages into 3: Emgu.CV.runtime.cuda.dnn.cnn, Emgu.CV.runtime.cuda.dnn.ops & Emgu.CV.runtime.cuda.dnn. No changes is needed on the user side, the installation and dependency will be handled automatically by nuget package manager.

**Comment by JohnTenney** [comment]
Thanks, resolved. Works great!

**Comment by emgucv** [comment]
Closing issue now.
