### ISSUE TITLE
CudaCascadeClassifier missing Properties on v4.4

### ISSUE THREAD

**Issue by neonleo** [emgucv/emgucv#367]
Hi everyone,
My project build by v4.2 and everything work fine, after upgrade to v4.4, 
VS2017 found some properties below not defined, error appear and cause by CudaCascadeClassifier

- ClassifierSize	
- FindLargestObject	
- MaxNumObjects	
- MaxObjectSize	
- MinNeighbors	
- MinObjectSize	

I have a look the repo, possible reason is the CvExtern is not load by CudaCascadeClassifier, VS2017 report :
'This package do not contain necessary binary for Windows runtime. X86 is targeted, but file C:\Users\neonleo\source\repos\EmguProject\packages\Emgu.CV.runtime.windows.cuda.4.4.0.4061\build\\x86\cvextern.dll is missing. PInvoke may fail on Windows X86 platform.'	

In the [v4.4 doc](http://www.emgu.com/wiki/files/4.4.0/document/html/e7e6ecb0-66e7-04cb-dd6c-a939e434a88a.htm) also missing the field, so I believe it is official update, but how can I define the properties above?

**Comment by emgucv** [comment]
Forgotten to generate the properties for CudaCascadeClassifier. Fixed in this commit: cff36efd7140ae5bcb48cc996347e21f4a87a6eb

Thanks for pointing out.

**Comment by neonleo** [comment]
> Forgotten to generate the properties for CudaCascadeClassifier. Fixed in this commit: [cff36ef](https://github.com/emgucv/emgucv/commit/cff36efd7140ae5bcb48cc996347e21f4a87a6eb)
> 
> Thanks for pointing out.

Thank you and we always support emgucv. 😊
