### ISSUE TITLE
FPS bug in VideoWriter Constructor

### ISSUE THREAD

**Issue by AutonomousOne** [emgucv/emgucv#37]
The VideoWriter constructor incorrectly uses an int for fps. The OpenCV equivalent correctly uses a double.

This means that 30 fps videos, commonly actually 29.97 fps or so it would appear, are written at 29 fps due to truncation.

This means that any extracted audio from the source video cannot be re-inserted without sync issues post OpenCV processing. It also means the output video is at a different frame rate from the unprocessed source.

**Comment by emgucv** [comment]
Fixed in commit 88f61426288c6c57d141d7dc107ef38b45b40f73

Thanks.
