### ISSUE TITLE
Strange Mat behaviour with tons of noise when not using SetTo(new MCvScalar(0)) before mat construction from code

### ISSUE THREAD

**Issue by sn4k3** [emgucv/emgucv#373]
I'm having a issue that i was able to fix by simple call mat.SetTo(new MCvScalar(0)) just after a new Mat().
But this seens like a bug, because mat by default comes all zeroed right?
On windows it seen to work right, but on rare cases with small images it also comes with noise and random outcomes, eg: if i refresh image, chances are each refresh image noise is diferent each refresh. My program takes x encoded Layers and turn them into visible images, each layer  is parallelized but i tried without parallel with a single sync for loop and the outcome is the same, so no parallel to blame.
On Linux this problem happens 100% of the times and very severe! So on windows works well but with rare cases, on linux 100% of the time excluding first layer, the first layer (image 0) always decode and shows well, but subsquent images are with noise

Code below:

```C#
public static unsafe Mat DecodeCbddlpImage(ChituboxFile parent, uint layerIndex)
            {
                var image = new Mat(new Size((int)parent.HeaderSettings.ResolutionX, (int)parent.HeaderSettings.ResolutionY), DepthType.Cv8U, 1);
                //image.SetTo(new MCvScalar(0));
                var span = image.GetBytePointer();
                var imageLength = image.GetLength();

                for (byte bit = 0; bit < parent.AntiAliasing; bit++)
                {
                    var layer = parent.LayersDefinitions[bit, layerIndex];

                    int n = 0;
                    for (int index = 0; index < layer.DataSize; index++)
                    {
                        // Lower 7 bits is the repeat count for the bit (0..127)
                        int reps = layer.EncodedRle[index] & 0x7f;

                        // We only need to set the non-zero pixels
                        // High bit is on for white, off for black
                        if ((layer.EncodedRle[index] & 0x80) != 0)
                        {
                            for (int i = 0; i < reps; i++)
                            {
                                span[n + i]++;
                            }
                        }

                        n += reps;

                        if (n == imageLength)
                        {
                            break;
                        }

                        if (n > imageLength)
                        {
                            image.Dispose();
                            throw new FileLoadException("Error image ran off the end");
                        }
                    }
                }

                for (int i = 0; i < imageLength; i++)
                {
                    int newC = span[i] * (256 / parent.AntiAliasing);

                    if (newC > 0)
                    {
                        newC--;
                    }

                    span[i] = (byte) newC;


                }

                return image;
            }
```

note that i have //image.SetTo(new MCvScalar(0)); commented, by just uncomment that the problem is fixed and noise goes away with a good formed image. While i can go away with it i want to know why this happen and if i always need to init the Mat with blacks? Right now it seens Mat is init with noise there.

Here the results:

**// image.SetTo(new MCvScalar(0));** 
![VirtualBoxVM_2020-10-10_19-19-30](https://user-images.githubusercontent.com/113281/95662447-eb5bdf80-0b2e-11eb-8ea2-a2e276292a1c.png)

**image.SetTo(new MCvScalar(0));**
![VirtualBoxVM_2020-10-10_19-18-19](https://user-images.githubusercontent.com/113281/95662436-d8490f80-0b2e-11eb-89b2-07eb18e085a0.png)

Version: 4.4.0.4099, but also happens with 4.3.x

**Comment by emgucv** [comment]
This is the expected behavior. Same to Open CV's Mat constructor, which allocate unmanaged memory.

Allocating a Mat of certain size does not guarantee all 0 pixels values. It can contain random values. It is a standard behavior of the C language's "malloc" function. If you need it to be all zeros, you need to call "SetTo(new MCvScalar(0,0,0))".

Image<,> class is different, it use managed memory and in the managed word, creating a new empty array guarantee 0 pixel value. Allocating a new Image<,> object will have all pixels set to 0.

**Comment by sn4k3** [comment]
Thank you for the explanation, i will now review my code to ensure all pixels are set (blacks). 
I had a really bad time trying to figure out what was the problem...
But i still have a question about this: for example on noised image we can see noise on white pixels path. If the pixels were overwritten with white (255) on that Mat why noise are still present on that path?

**Comment by emgucv** [comment]
I wasn't sure what is in the "ChituboxFile" class. But if you are performing Binary operation with the pixels from Mat, and they contain random value (or noise), the output from the binary operation will have random value as well.

**Comment by sn4k3** [comment]
You are right, i forget that fact.
Already ajusted the code, everything seens correct now both windows and linux, and i guess it will also fix other bugs i was aware of since i use "new Mat" other than to decode images.
Thanks and keep the good work!
I'm heavy using your library for process MSLA images and apply some fixes, whole project here: https://github.com/sn4k3/UVtools
I also have an set of extensions which can be usefull for someone else: https://github.com/sn4k3/UVtools/blob/master/UVtools.Core/Extensions/EmguExtensions.cs
