### ISSUE TITLE
Video Camera Enumeration.

### ISSUE THREAD

**Issue by vpenades** [emgucv/emgucv#374]
VideoCamera class has an argument called camIndex, which seems to indicate the index of the camera to use if there's more than one available.

Is there a way to enumerate the DirectShow cameras available in the computer? if possible, with some basic metadata, like name, whether if it's in-built (laptop) or external, etc.

I'm surprised this funcionality is not available in the VideoCamera class itself as a static method.

**Comment by armin-git** [comment]
You have to use another SDK to find and use the camera index, like VLC

**Comment by vpenades** [comment]
The problem I see with that approach is that there's no guarantee that the index provided by a third party SDK matches what OpenCV videoCamera is enumerating. So doing that and expecting to work is a matter to sheer luck.

In the end, I've ended using the third party SDK solution, but not only for enumeration, but also for camera acquisition, skipping completely OpenCV code
