### ISSUE TITLE
Ubuntu runtime missing libraries

### ISSUE THREAD

**Issue by rongcuid** [emgucv/emgucv#375]
I get this in OmniSharp when trying to develop with Emgu:

```
.nuget/packages/emgu.cv.runtime.ubuntu/4.4.0.4099/build/Emgu.CV.runtime.ubuntu.targets(28,7): Error: 'This package do not contain necessary binary for Ubuntu. X86 is targeted, but file /home/rongcuid/.nuget/packages/emgu.cv.runtime.ubuntu/4.4.0.4099/build/x86/libcvextern.so is missing. PInvoke may fail on Ubuntu X86 platform.'
```
And this error is confirmed when I try to run the program, which says such libraries are not found. When I look at binary output folder, I don't see `libcvextern.so` either.

I am using Ubuntu 20.04, with Mono + MSBuild.

**Comment by emgucv** [comment]
Our Emgu.CV.runtime.ubuntu nuget package only contains 64 bit native binary. 

Ubuntu is dropping 32-bit support, according to this:
https://www.omgubuntu.co.uk/2019/06/ubuntu-is-dropping-all-32-bit-support-going-forward#:~:text=Ubuntu%20has%20confirmed%20plans%20to,on%20newer%20versions%20of%20Ubuntu.

The error message is there to make sure you are compiling your Ubuntu application targeting "x64", not "x86" or "AnyCPU", which may run in 32-bit mode and failed on 64bit Ubuntu.

Changing the compilation target to "x64" for Ubuntu build will make the error message goes away.

**Comment by emgucv** [comment]
Closing ticket now.
