### ISSUE TITLE
Invalid device symbol

### ISSUE THREAD

**Issue by lordard** [emgucv/emgucv#376]
Hi
I try to use the emgu.cv.cuda in my project 
But I got an error {"OpenCV: invalid device symbol"}  on the line x.Detect(...)

`Emgu.CV.Cuda.GpuMat ImgGpu = new Emgu.CV.Cuda.GpuMat();
 ImgGpu.Upload(img);
 VectorOfPointF lines = new VectorOfPointF();
 var x = new Emgu.CV.Cuda.CudaHoughLinesDetector(1.0,1.0, 10);
 x.Detect(ImgGpu, lines);`

I could not found useful information on the web.
But , I noticed  the IsCompatible in CudaDeviceInfo is false.
Is that the root cause ?

Please help .

Video Card : GTX950
EmguCv.cuda : 4.4.0.4077

**Comment by emgucv** [comment]
Emgu CV v4.4 is compiled with CUDA 11.0 and targeted compute 6.0 and higher. GTX 950 use compute 5.2 and is not compatible with Emgu CV v4.4.

**Comment by lordard** [comment]
Thanks
