### ISSUE TITLE
toBitmap causes System.AccessViolationException

### ISSUE THREAD

**Issue by Lyror** [emgucv/emgucv#379]
Hello,

I am trying to modify a png file that is in the stream "image" (the source Image is a png file). For this I use threshold, dilate and erode. After I have successfully processed the image I try to convert it to a bitmap. Unfortunately this doesn't work because he always tells me: "I tried to read or write to protected memory. This is often an indication that other memory is corrupted".

```csharp 
public static Bitmap ImproveImageToBitmap(MemoryStream image, int? threshold, int? dilate, int? erode)
{
	image.Position = 0;
	var img = GetImg(image);
	if (threshold.HasValue)
		img = img.ThresholdBinary(new Gray(threshold.Value), new Gray(255));

	if (dilate.HasValue)
		img = img.Dilate(dilate.Value);

	if (erode.HasValue)
		img = img.Erode(erode.Value);

	return img.ToBitmap();
}

private static Image<Gray, byte> GetImg(MemoryStream imgStream)
{
	int stride = 0;
	Bitmap bitmapImage = new Bitmap(imgStream);

	Rectangle rectangle = new Rectangle(0, 0, bitmapImage.Width, bitmapImage.Height);
	BitmapData bmpData = bitmapImage.LockBits(rectangle, ImageLockMode.ReadWrite, bitmapImage.PixelFormat);

	PixelFormat pixelFormat = bitmapImage.PixelFormat;
	if (pixelFormat == PixelFormat.Format32bppArgb)
	{
		stride = bitmapImage.Width * 4;
	}
	else
	{
		stride = bitmapImage.Width * 3;
	}
	return new Image<Gray, byte>(bitmapImage.Width, bitmapImage.Height, stride, bmpData.Scan0);
}
```

My PC has a ram usage of 10GB from 16GB. So I think this should not be the problem. Is there a safer way to convert it to a png? Any other format is fine, as long as it works and won't crash. I would like to display the image in WPF Image Property

**Comment by emgucv** [comment]
On exit of your GetImg() function, there is no more reference to the "Bitmap" object, C#'s garbage collector can dispose the Bitmap. The Image<,> returned by GetImg function use the unmanaged memory in the Bitmap object, which is now disposed by GC. You will get a System.AccessViolationException.

Please consider using CvInvoke.ImDecode to decode memory stream into Mat object:
http://www.emgu.com/wiki/files/4.4.0/document/html/40e7c156-410d-4471-586c-5da82e5c7fe8.htm

**Comment by emgucv** [comment]
Closing ticket now.
