### ISSUE TITLE
Got issue about shape recognition

### ISSUE THREAD

**Issue by AsuwaInc** [emgucv/emgucv#38]
I'm working on a program which have to recognize rectangles in image,but it doesn't works clearly.
Could you give me some advices or help me about this issue?I've tried some methods of image preprocessing but it doesn't help strongly.

**Comment by emgucv** [comment]
Would you like to share the images, the source code, the expected result and the actual result from running the code?

Thanks.

**Comment by AsuwaInc** [comment]
I am sorry for disturbing you,we have already solved the problem,thank you
for quick recall.
With regards.
Eshsou Chkua

2017-07-14 6:06 GMT+03:00 Emgu CV <notifications@github.com>:

**Comment by emgucv** [comment]
Thanks for letting me know.

Closing issue now.
