### ISSUE TITLE
Cuda 11.1 + rtx3090 support

### ISSUE THREAD

**Issue by AlgirdasKartavicius** [emgucv/emgucv#380]
Does EMGU CV support Cuda 11.1 and NVIDIA GeForce RTX 30 Series GPUS?

**Comment by AlgirdasKartavicius** [comment]
Is Emgu.CV.runtime.windows.cuda compiled with CUDA 11.1 and cuDNN 8.6?

**Comment by emgucv** [comment]
The Emgu.CV.runtime.windows.cuda nuget 4.4.0.4099 release is compiled with CUDA 11.0 and CUDNN 8.

**Comment by AlgirdasKartavicius** [comment]
Do you plan to recompile it with CUDA 11.1? RTX 30 Series should work faster with CUDA 11.1.

**Comment by emgucv** [comment]
Yes, the 4.5 release will be compiled with CUDA 11.1.

**Comment by AlgirdasKartavicius** [comment]
Do you any possible date for 4.5 release? This or next year?

**Comment by solarflarefx** [comment]
So it appears that there is a mention of 4.5 on this page: http://www.emgu.com/wiki/index.php/Version_History#Emgu.CV-4.5.0

However, the link to the documentation seems to be broken.  Does not seem like you can download it yet either.

**Comment by emgucv** [comment]
We are working on the 4.5 release, it might be ready in the coming week.

**Comment by emgucv** [comment]
4.5.1 release is out on GitHub:
https://github.com/emgucv/emgucv/releases/tag/4.5.1

Note that the cuda runtime is not available on nuget.org for v4.5.1. Our release note has details on this issue:

> Emgu.CV.runtime.windows.cuda package for this release is not available from nuget.org. If you need to use the Emgu.CV.runtime.windows.cuda package, you can download two large nuget packages ( Emgu.CV.runtime.windows.cuda.4.5.1.4349.nupkg; Emgu.runtime.windows.cuda.dnn.cnn.8.0.4.nupkg ) and hosted it on your local nuget repository. The latest CUDA DNN package has a file "cudnn_cnn_infer64_8.dll" in v8.0.4 that is 688MB in size, after the nuget package compression the nupkg file is still 287MB. Nuget.org has a hard limit in package size of 250MB, this prevent the package being uploaded to nuget.org. Unless NVidia break up "cudnn_cnn_infer64_8.dll" into multiple smaller files, or nuget.org increase the file limit, we will not be able to upload the latest cuda nuget packages into nuget.org. The existing 4.4 release use older version of CUDNN and has nuget package reaching 248MB, we have moved onto newer version of CUDA and CUDNN to support the RTX 30xx series of graphic card and is no longer using the previous version of CUDNN. Commercial license holder will not be affected, we have the Emgu.CV.runtime.windows.cuda package uploaded to our commercial nuget repository which have larger nupkg size limit (500MB).
