### ISSUE TITLE
Loading x86/x64 native DLLs briefly change Environment.CurrentDirectory which leads to RANDOM CRASHES

### ISSUE THREAD

**Issue by vpenades** [emgucv/emgucv#383]
This issue is a replica of the same issue affecting Emgu.TF: https://github.com/emgucv/emgutf/issues/44

Briefly: changing Environment.CurrentDirectory to point to the natives to load them is a bad design and can break an application.

I've just confirmed it also affects Emgu.CV

**Comment by emgucv** [comment]
Fixed in this two commits:
https://github.com/emgucv/emgucv/commit/0b2369d4776c447ccbc270fddfd954d816ef20fa
https://github.com/emgucv/emgucv/commit/82715cf4446a2c6b1147d90df9885ec4828a01b4
