### ISSUE TITLE
有方法設定相機焦距嗎？

### ISSUE THREAD

**Issue by 46159100** [emgucv/emgucv#384]

**Comment by nombrote** [comment]
我也不是英语，但是如果我想被理解，我会用英语问。

**Comment by emgucv** [comment]
If you are asking about setting focus for the VideoCapture class, you can try VideoCapture.SetCaptureProperty Method:
http://www.emgu.com/wiki/files/4.5.1/document/html/562586c1-1319-fdb3-9121-ed2f81a53f9d.htm

and pass CapProp.Focus as the first parameter.

Note that setting CapProp.Focus may not be support on your platform.

**Comment by emgucv** [comment]
Closing ticket now.
