### ISSUE TITLE
CvInvoke.FindContours: Retrieval type equivalent for cv::RETR_FLOODFILL is missing but works

### ISSUE THREAD

**Issue by rutgerkra** [emgucv/emgucv#385]
Ran into this when trying to get the contours that resulted from CvInvoke.Watershed using CvInvoke.FindContours.

OpenCV documentation lists five types for cv::RetrievalModes, while the equivalent Emgu enum RetrType only has four, with RETR_FLOODFILL being the difference. The floodfill enum value is 4, and type casting that as RetrType seems to work completely fine.

It's not a very well documented function in OpenCV documentation to begin with, so perhaps that is why it is not part of the enum in Emgu. Either way, it seems to work and it would be a very simple change to add it.

[OpenCV doc link](https://docs.opencv.org/4.5.0/d3/dc0/group__imgproc__shape.html#ga819779b9857cc2f8601e6526a3a5bc71)
[Emgu doc link](http://www.emgu.com/wiki/files/4.4.0/document/html/6df2b50a-ffda-294a-7a3c-a520f0fe8ab7.htm)

**Comment by emgucv** [comment]
Thanks for pointing that out. 

Just added the Floodfill option in this commit:
https://github.com/emgucv/emgucv/commit/ff01621af821c8f6a8117fc38f6382b8740af1e0

**Comment by rutgerkra** [comment]
Thanks!
