### ISSUE TITLE
DisparityWLSFilter.filter Incorrect reference

### ISSUE THREAD

**Issue by nombrote** [emgucv/emgucv#393]
Hi, 

I want to use that method any time ago i update to the new Emgu version, but it's the some, 

Never work, it give a System.AccessViolationException when call the method. I suppuse it's not correctly referenced the call of the dlls.

**Comment by emgucv** [comment]
Fixed in the following commits:
4f7dd31bbc738e9d915420f097dfba5c758f11a7
712555ad0673db1189f0e4fe2b6eeb8af8cd70fd

Thanks for point that out.

**Comment by nombrote** [comment]
Thanks, how to use it? I must to download a branch, recompile it and reference a dll, or it will be upload soon to nuget?

**Comment by emgucv** [comment]
You can use one of the nightly build, such as:
https://github.com/emgucv/emgucv/actions/runs/470234198 

Go to the bottom of the page where it says "Artifacts" and download

emgucv-windows-zip-package

The Xamarin Form Demo's Simple3DRecognstruction page now also use DisparityWLSFilter:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/XamarinForms/Core/Simple3DReconstruct.cs#L121

The fix will be included in the up-coming 4.5.1 release.

**Comment by emgucv** [comment]
v4.5.1 release is out. I am closing this ticket now.
