### ISSUE TITLE
Upgrading on .NET from older NuGet packages

### ISSUE THREAD

**Issue by solarflarefx** [emgucv/emgucv#395]
I am working with some code that seems to be using older NuGet packages:
- Emgu.Cv.Cudnn
- Emgu.Cv.Cufft
- Emgu.Cv.Native
- Emgu.Cv-Cuda

These seem to be using CUDA 10.1.  I am trying to update to a higher version of EMGU / CUDA but in searching the NuGet database, I do not see any of the above packages and now see:
- Emgu.Cv
- Emgu.Cv.runtime.windows

There are also some other packages like Emgu.TF but I do not think they are relevant.

So my question is did the NuGet package structure change in the last couple years?  If I wanted to upgrade the code what would I need?  Only Emgu.Cv or any additional packages (Emgu.Cv.runtime.windows)?

**Comment by solarflarefx** [comment]
It looks like there is also an Emgu.Cv.runtime.windows.cuda, but looks like it depends on some packages that are deprecated like: https://www.nuget.org/packages/Emgu.runtime.windows.cuda.rt/

**Comment by solarflarefx** [comment]
OK so to my understanding I need:
- Emgu.Cv
- Emgu.Cv.runtime.windows.cuda

My issue with the second package is that I get this error for the latest version: 

Could not install package 'Emgu.runtime.windows.cuda.rt 11.1.218'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by solarflarefx** [comment]
Looks like I can run Emgu.Cv.runtime.windows.cuda v4.4.0.4077 but not v4.4.0.4099 (which gives the error above).  Basically the NuGet package manager tries to install but then fails.

**Comment by emgucv** [comment]
Usually, installing Emgu.CV.runtime.windows.cuda will automatically handle the dependency using package manager.

You can check the dependency of the package on nuget.org:
https://www.nuget.org/packages/Emgu.CV.runtime.windows.cuda/

For 4.4.0.4099, if you expand the "Dependency" tab it will show:

 Dependencies
.NETStandard 2.0
Emgu.CV (>= 4.4.0 && < 4.4.1)
Emgu.runtime.windows.cuda.blas (= 11.1.218)
Emgu.runtime.windows.cuda.dnn (= 8.0.1)
Emgu.runtime.windows.cuda.dnn.adv (= 8.0.1)
Emgu.runtime.windows.cuda.dnn.cnn (= 8.0.1)
Emgu.runtime.windows.cuda.dnn.ops (= 8.0.1)
Emgu.runtime.windows.cuda.fft (= 11.1.218)
Emgu.runtime.windows.cuda.npp (= 11.1.218)

**Comment by solarflarefx** [comment]
@emgucv Thanks for the reply. 
So in the list you mentioned I do not see Emgu.runtime.windows.cuda.rt 11.1.218
Visual Studio seems to try to install it and it fails.  Again this only occurs for v4.4.0.4099 but not v4.4.0.4077.

Out of curiosity, when will the NuGet package for Emgu.Cv 4.5 be available?  Looks like the Github has been updated?  I wonder if upgrading to that may solve my problem.

**Comment by emgucv** [comment]
Nuget package manager will build a dependency tree. Emgu.runtime.windows.cuda.rt is the dependency of packages such as Emgu.runtime.windows.cuda.blas

FYI, the nuget packages for Emgu CV v4.5.1 will be available soon. However, the runtime with CUDA support may not be available from nuget.org. The latest CUDNN package has a file "cudnn_cnn_infer64_8.dll" in cudnn 8.0.4 release that is 688MB in size, even after the nuget package compression the nupkg file is still 287MB. Nuget.org has a hard limit in package size of 250MB, this prevent the package being uploaded to nuget.org. Unless NVidia break up "cudnn_cnn_infer64_8.dll" into multiple smaller files, or nuget.org increase the file limit, we will not be able to upload the latest cuda nuget packages into nuget.org. The existing 4.4 release use older version of CUDNN and has nuget package reaching 248MB, we have moved onto newer version of CUDA and CUDNN to support the RTX 30xx series of graphic card and is no longer using the previous version of CUDNN. 

FYI, commercial license holder will not be affected for v4.5.1 release, we will have the latest nuget package with CUDA runtime uploaded to our commercial nuget repository, which have larger nupkg size limit (500MB).

**Comment by solarflarefx** [comment]
Thanks for the info.  

Is there any reason you can think of as to why v4.4.0.4077 gives me no problem on NuGet but v4.4.0.4099 does?

One thing I could try to do is download the pre-built Windows binaries for Emgu v4.5.1.  

I was looking at the instructions: http://www.emgu.com/wiki/index.php/Download_And_Installation#Using_the_Downloadable_packages

I am guessing the wiki is somewhat outdated as it refers to an exe or zip file.  I can just download from Github, correct?  There include pre-built binaries for Windows that use CUDA 11.1 and cudnn 8.0.4?  Or must I build from source?

**Comment by solarflarefx** [comment]
It looks like there may be an issue with the latest NuGet package and the .NET Framework.  If I wanted to use a build with CUDA (let's say I downloaded the Emgu 4.4 file from SourceForge), reading the directions it says I would have to include the shared project Emgu.CV.Runtime\Windows\Emgu.CV.Runtime.Window, which would then deploy all the native files.  But to use CUDA do I also need to include anything else like Emgu.CV.Cuda?

**Comment by solarflarefx** [comment]
So it looks like the root cause is that the NuGet package includes Emgu.CV.Platform.NetStandard.dll but not Emgu.CV.Platform.NetFramework.dll.  So I downloaded Emgu v4.4 from SourceForge.  

I added references to: 
- Emgu.CV.Platform.NetStandard.dll
- Emgu.CV.Platform.NetFramework.dll.  

I also added the following shared projects:
- Emgu.CV.Runtime.Windows
- Emgu.CV.Cuda

However it seems like I am still missing something as I get many errors relating to CvInvoke not having definitions.

**Comment by solarflarefx** [comment]
I tried following the directions here: http://www.emgu.com/wiki/index.php/Download_And_Installation#CUDA_.28GPU.29_package

If I only include the following:
- Emgu.CV.Platform.NetStandard.dll
- Emgu.CV.Platform.NetFramework.dll
- Emgu.CV.Runtime.Windows

When I try running the code I get an error saying that this version of Emgu.Cv was not built with CUDA.

**Comment by emgucv** [comment]
The package with CUDA support has "-cuda" in the pacakge name. If the pacakge name does not contains "-cuda" it doesn't support CUDA.

If you download the 4.5.1 release from GitHub, 

https://github.com/emgucv/emgucv/releases/tag/4.5.1

the file with CUDA support is:

libemgucv-windesktop_x64-cuda-4.5.1.4349.zip.selfextract.exe

**Comment by emgucv** [comment]
Closing ticket now.
