### ISSUE TITLE
OpenCV: The library is compiled without CUDA support

### ISSUE THREAD

**Issue by lezzi** [emgucv/emgucv#4]
> OpenCV: The library is compiled without CUDA support

I receive this message trying to use CUDA with EmguCV 3.1.0.1. Should I recompile OpenCV myself?

**Comment by emgucv** [comment]
Hi lezzi, 

Please make sure you are downloading the binary package that contains "-cuda" in its name. Emgu CV release packages that are build with cuda and build without cuda. The package that is without cuda is the default download because the binary size is much smaller, but will always return false when calling CudaInvoke.HasCuda.

**Comment by jcramer** [comment]
Hi, would it be feasible to have a nuget package version with the CUDA support?  That would be much easier than having to go to sourceforge for the CUDA version and then manually adding the Emgucv reference.

**Comment by emgucv** [comment]
Thanks for the suggestion. We are working on it and CUDA compatible nuget package will be included for the next v3.3 release.

**Comment by dtanh72** [comment]
I have downloaded the package emgucv-windesktop_x64-cuda 3.3.0.2826.
CUDA function is not working. 

OS : windows10 64bit
Env : visual Studio 2012
Gpu : GTX 570

Can you help me?

**Comment by emgucv** [comment]
GTX 570 is based on CUDA Compute 2.0, see https://en.wikipedia.org/wiki/CUDA
Emgu CV 3.3 release is build with CUDA 9.0
CUDA 9.0 no longer support Compute 2.0 device. 

If you need to use Emgu CV with your graphic card, you should use Emgu CV v3.2 release, which is built with CUDA 8.0. CUDA 8.0 is the last CUDA release that support Compute 2.0 device.

**Comment by rigoletiny** [comment]
What would be the initial configuration for a new project Using cuda?. I can run the examples, but not the new project: CudaInvoke.HasCuda= false. Already add references Emgu.Cv.UI and Emgu.Cv.World from path C:\Emgu\emgucv-windesktop 3.3.0.2824\libs\. Im using Nvidia Quadro K620
