### ISSUE TITLE
Video memory leak in C# Quality wrappers

### ISSUE THREAD

**Issue by benbutle** [emgucv/emgucv#402]
When I try to run the Quality algorithms (e.g. QualityMSE) over several images in a row, I get the following error:

OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueNDRangeKernel('KF', dims=2, globalsize=2560x1920x1, localsize=NULL) sync=false
Unhandled exception. Emgu.CV.Util.CvException: OpenCV: OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueReadBuffer(q, handle=0000021C77C22240, CL_TRUE, 0, sz=58982400, data=0000021CD108A080, 0, 0, 0)
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.Quality.QualityInvoke.cveQualityBaseCompute(IntPtr qualityBase, IntPtr cmpImgs, MCvScalar& score)
   at Emgu.CV.Quality.QualityInvoke.Compute(IQualityBase qualityBase, IInputArrayOfArrays cmpImgs)

I've noticed that every time I create a new QualityMSE object, my video memory usage goes up, and the used memory is not reclaimed when disposing the object. It looks like the Quality algorithm wrapper objects in emgucv/Emgu.CV.Contrib/Quality/ never actually clean up their unmanaged resources. This is the implementation of DisposeObject in QualityMSE.cs:

`protected override void DisposeObject()`
`{`
`    if (_sharedPtr == IntPtr.Zero)`
`            {`
`                QualityInvoke.cveQualityMSERelease(ref _sharedPtr);`
`                _ptr = IntPtr.Zero;`
`                _algorithmPtr = IntPtr.Zero;`
`                _qualityBasePtr = IntPtr.Zero;`
`            }`
`}`

Looks to me like a typo in the if statement - I think it should be checking if _sharedPtr != IntPtr.Zero so the pointer gets released when it **isn't** null.

As a workaround, if I manually invoke cveQualityMSERelease on the SharedPtr object, the allocated memory does appear to be freed correctly.

This same pattern is present in all the other Quality classes in the same directory.

**Comment by emgucv** [comment]
Fixed in this commit: 0ab2f9d897200ca4c1508e715ad148479be60180

Thanks for pointing out.

**Comment by emgucv** [comment]
Closing ticket now.
