### ISSUE TITLE
Emgu.CV.runtime.windows.cuda.4.5.1.4349

### ISSUE THREAD

**Issue by AlgirdasKartavicius** [emgucv/emgucv#403]
Hello,
I tried to install  [Emgu.CV.runtime.windows.cuda.4.5.1.4349](http://www.emgu.com/wiki/files/4.5.1/release/Emgu.CV.runtime.windows.cuda.4.5.1.4349.nupkg).
I got this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Emgu.runtime.windows.cuda.blas with version (= 11.1.301)
  - Found 1 version(s) in nuget.org [ Nearest version: 11.1.218 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in Local	EmguInference	C:\Users\Vartotojas\Desktop\Bandymai\EmguInference\EmguInference\EmguInference\EmguInference.csproj

**Comment by emgucv** [comment]
Thanks for pointing that out. The packages has been uploaded to nuget.org just now.

**Comment by AlgirdasKartavicius** [comment]
I successfully installed Emgu.CV.runtime.windows.cuda.4.5.1.4349, but i get this warning:

[ WARN:0] global D:\bb\cv_x64\build\opencv\modules\dnn\src\dnn.cpp (1442) cv::dnn::dnn4_v20201117::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU

**Comment by nombrote** [comment]
Why i havent got this package on nuget? :|
The last one for me is 4.4 (i was clean the nuget cache, but it's the some)

**Comment by AlgirdasKartavicius** [comment]
> Why i havent got this package on nuget? :|
> The last one for me is 4.4 (i was clean the nuget cache, but it's the some)

You can install it from local nuget package. (http://www.emgu.com/wiki/index.php/Version_History#Emgu.CV-4.5.1)

**Comment by emgucv** [comment]
@AlgirdasKartavicius Can you print the String from the "GetDNNInfo()" function below to check what DNN backend is supported in the runtime, in your enviroment?

https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/BuildInfo.NetCore.Console/Program.cs

**Comment by AlgirdasKartavicius** [comment]
DNN backends:
OpenCV - OpenCL
OpenCV - OpenCLFp16
OpenCV - Cpu
VkCom - Vulkan

I can successfully run Cuda backend with 4.4 version.

**Comment by AlgirdasKartavicius** [comment]
DNN backends:
OpenCV - OpenCL
OpenCV - OpenCLFp16
OpenCV - Cpu
Cuda - Cuda
Cuda - CudaFp16

Got this with 4.4 version.

**Comment by emgucv** [comment]
Using Emgu.CV.runtime.windows.cuda.4.5.1.4349 package, I also got this:

DNN backends:
OpenCV - OpenCL
OpenCV - OpenCLFp16
OpenCV - Cpu
VkCom - Vulkan
Cuda - Cuda
Cuda - CudaFp16

Cuda backend is compiled into Emgu.CV.runtime.windows.cuda.4.5.1.4349 package.

Note that the DNN CUDA backend has a smaller subset of supported operation. If your DNN network has an operation that is not supported by the CUDA DNN backend, it will automatically fallback to the CPU backend.

**Comment by emgucv** [comment]
Btw, the 4.5.1 release use CUDA 11.1 and need a more recent graphic card driver. 

If you have not upgraded your graphic card driver for a while, upgrade the driver. I am using nvidia driver version 460.89. Any version greater than that should work.

**Comment by AlgirdasKartavicius** [comment]
I had Emgu.CV.runtime.windows 4.5.1.4349 installed. I deleted this package and everything works fine now.

Should  Emgu.CV.runtime.windows.cuda.4.5.1.4349 work faster than  Emgu.CV.runtime.windows.cuda.4.4 with RTX3090?

**Comment by emgucv** [comment]
Execution speed wise there should not be a significant difference. 

There will be no delay for the first time start up of using Emgu CV 4.5.1, because native device binary is included to target RTX3090 in 4.5.1.4349. 

For 4.4, the first time Emgu CV is started up, a device binary compilation is needed and may take some time, afterwards there will be no delays as the native device binary is cached on disk.

**Comment by nombrote** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.InvalidOperationException: Unable to find metadata of Emgu.CV.runtime.windows.cuda.4.5.1.4349
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckLicenseAcceptanceAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass11_0.<<PerformActionImplAsync>b__0>d.MoveNext()				


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Emgu.CV.runtime.windows.cuda with version (>= 4.5.1.4349)
  - Found 6 version(s) in nuget.org [ Nearest version: 4.4.0.4099 ]
  - Found 0 version(s) in DevExpress 18.2 Local
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in Local Emgu	Vision.EmguCV	C:\Users\user\Documents\Arduino\src\Robot\Backend\Sentidos\Vision.Componentes\VisionEmguCV\Vision.EmguCV.csproj	1
