### ISSUE TITLE
Error with emgu.CV.runtime.windows - "package does not contain any assembly references or content files that are compatible with that framework"

### ISSUE THREAD

**Issue by PAMonkeyTech** [emgucv/emgucv#409]
I'm trying to install emgu.CV.runtime.windows from within Visual Studio 2017, and installing by the recommeded method of right-clicking references and installing via NuGet.

However I am getting the error below.

Could not install package 'Emgu.runtime.windows.msvc.rt.x64 19.28.29336'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

According to the package information, its de[ememcoes are
.NetStandardVersion=2.0
.Engu.CV (> 4.5.1 && < 4.5.2)
.Engu.runtime.windows.msvc.rt.x86 (= 19.28.29336)
.Engu.runtime.windows.msvc.rt.x64 (= 19.28.29336)

I checked and c:\windows\Microsoft.NET\Framework contains a folder for v2.0.50727, so it seem .net 2.0 is installed (as is v3.0, v3.5, v4.0.30319)

I have emgu.CV 4.5.1.4349 installed.

I need this library so that I can have the bitmap.ToImage<Bgr, byte>(); function.

Why am I getting this error?

**Comment by emgucv** [comment]
Is your project using "package.config" instead of "package reference" to manage nuget packages?

If so, please following this instruction to upgrade "package.config" to "package refenrece":
https://github.com/emgucv/emgucv/issues/399#issuecomment-767571013

Nuget manager seems to be broken when using "package.config"

**Comment by emgucv** [comment]
Closing ticket now

**Comment by Nevillested** [comment]
> Is your project using "package.config" instead of "package reference" to manage nuget packages?
> 
> If so, please following this instruction to upgrade "package.config" to "package refenrece": [#399 (comment)](https://github.com/emgucv/emgucv/issues/399#issuecomment-767571013)
> 
> Nuget manager seems to be broken when using "package.config"

i tried it. Don't work.

**Comment by emgucv** [comment]
A more detail instruction can be found here:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Nuget

Can you elaborate what doesn't work? Is it the part where you migrate from package.config to package reference failed? 

What .net version are you using and which specific Emgu CV package did you try to install?
