### ISSUE TITLE
Missing BitmapExtension class in Emgu version 4.5.1.4349

### ISSUE THREAD

**Issue by DatCorno** [emgucv/emgucv#435]
I am trying to convert from a Bitmap to an Emgu Image. I have learned that the Bitmap constructor is no longer available and that an extension method is provided instead inside the `Emgu.CV.BitmapExtension` class. Unfortunately, for some reasons, this class is not present in my installation of Emgu.

I have installed Emgu through Visual Studio NuGet and I have verified that the current version I am using is 4.5.1.4349.

**Comment by DatCorno** [comment]
I have found a solution: the class actually resides in the Emgu.CV.UI NuGet package.

**Comment by emgucv** [comment]
It is in the Emgu.CV.Bitmap nuget package:
https://www.nuget.org/packages/Emgu.CV.Bitmap/

Emgu.CV.UI has a dependency on Emgu.CV.Bitmap, if you install Emgu.CV.UI nuget package it will install Emgu.CV.Bitmap as well.

**Comment by emgucv** [comment]
Closing ticket now.
