### ISSUE TITLE
VideoCapture ImageGrabbed event only has one valid frame on linux

### ISSUE THREAD

**Issue by davidscherf** [emgucv/emgucv#439]
Pc: Raspberry Pi 4
OS: Raspbian

Startup code
captureDevice = new VideoCapture(fileName, VideoCapture.API.V4L);
captureDevice.SetCaptureProperty(Emgu.CV.CvEnum.CapProp.Fps, 30);
captureDevice.SetCaptureProperty(Emgu.CV.CvEnum.CapProp.FrameHeight, 480);
captureDevice.SetCaptureProperty(Emgu.CV.CvEnum.CapProp.FrameWidth, 640);
captureDevice.ImageGrabbed += Got_Frame_Event;
captureDevice.Start();

The following code fails on ToBitmap after the first frame "Parameter is not valid"

        private void Got_Frame_Event(object sender, EventArgs e)
        {
            try
            {
                VideoCapture thisCamera = (VideoCapture)sender;
                using Mat frame = new Mat();
                if (thisCamera.Retrieve(frame, 0))
                {
                    Image<Bgr, byte> image = frame.ToImage<Bgr, byte>();
                    using Bitmap thisImage = image.ToBitmap();
                    using var ms = new System.IO.MemoryStream();
                    thisImage.Save(ms, System.Drawing.Imaging.ImageFormat.Bmp);
                    New_Frame.Invoke(this, (byte[])ms.ToArray().Clone());
                }
                else
                {
                    //Console.WriteLine("No frame");
                }
            }
            catch
            {

            }
        }

**Comment by emgucv** [comment]
Did you installed GDI+ on your raspberry pi OS?

The Bitmap class required GDI+ to be installed to work, or it will crash / error. FYI, GDI+ is not quite stable on platforms other than Windows, you should avoid using it on Raspberry Pi. 

What is the size of "image"? As a debug step, you can print out the image size to make sure that the image is valid. There is a possible chance that the video capture is not valid / not capturing images.

**Comment by davidscherf** [comment]
It is capturing a valid image for the first frame, 640x480, I am guessing any required components are installed else the first frame wound not be valid.

Is there another way to convert the image to a byte array?

**Comment by emgucv** [comment]
Imencode should be much more efficient and do not require GDI+:
https://www.emgu.com/wiki/files/4.5.1/document/html/374e5128-e2bc-4ffe-c250-c20fb45788f0.htm

If you want to know how to convert a VectorOfByte to byte array, we just added a Imencode function overload in our repo:
https://github.com/emgucv/emgucv/commit/0983df9ccf832e9d377fe03806f1b6c72d05c640

**Comment by davidscherf** [comment]
have changed to reusing the Mat object, this randomly gives me a valid frame, that can be saved and viewed, every up to 65 seconds, with so many failed bad frames, the bad frames are saying they are 640x480 as per the setup
So with 118-1301 fails to every good frame something is wrong in the ToBitmap, I am using the current System.Drawing.Common 5.0.1, and Bitmap works flawlessly everywhere else in my app, in fact I am using Bitmap on the Intel Realsense library with no issues.

No idea on how to use Imencode to get a bitmap byte array. Any samples on this?

        private Int64 failFrameCount;
        private Size? lastFailSize = null;

        private void Got_Frame_Event(object sender, EventArgs e)
        {
            try
            {
                VideoCapture thisCamera = (VideoCapture)sender;
                if (thisCamera.Retrieve(frame, 0))
                {
                    Size? lastSize = lastFailSize;
                    lastFailSize = frame.Size;
                    using Bitmap thisImage = frame.ToBitmap();
                    using var ms = new System.IO.MemoryStream();
                    thisImage.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                    if (failFrameCount > 0)
                    {
                        Console.WriteLine("Fail frame count " + failFrameCount.ToString());
                        if (lastSize != null) { Console.WriteLine("Last fail size = " + lastSize.Value.Width.ToString() + "x" + lastSize.Value.Height.ToString()); }
                    }
                    failFrameCount = 0;
                    New_Frame.Invoke(this, (byte[])ms.ToArray());
                }
                else
                {
                    //Console.WriteLine("No frame");
                }
            }
            catch
            {
                failFrameCount += 1;
            }
        }

**Comment by davidscherf** [comment]
You are thinking of older versions of C#
using ending in ; will dispose at the end of the block, in my case the if statement
also ToBitmap() crashes at ToBitmap() regardless of if you dispose or not

**Comment by emgucv** [comment]
> You are thinking of older versions of C#
> using ending in ; will dispose at the end of the block, in my case the if statement

You are right. Just looked it up, it is a C# 8 feature. Thanks for pointing that out, learned a new thing today. 

Is the ToBitmap function only failed on Linux? As I mention before, Bitmap and GDI+ are not stable on Linux.

If you need an Bitmap byte array on Linux, use CvInvoke.Imencode.

**Comment by davidscherf** [comment]
Changed to CvInvoke.Imencode, and it works, now using less code, Thanks

**Comment by emgucv** [comment]
Closing ticket now.
