### ISSUE TITLE
cannot increase CV_IO_MAX_IMAGE_PIXELS

### ISSUE THREAD

**Issue by DeleeTech** [emgucv/emgucv#443]
Hi I'm trying to open an image BGR of 35516 px x 34656 px and I'm getting this exception message : "pixels <= CV_IO_MAX_IMAGE_PIXELS"

How can I increase this image limit ?

**Comment by emgucv** [comment]
According to Open CV documentation: 
https://docs.opencv.org/4.5.1/d4/da8/group__imgcodecs.html#ga5a0acefe5cbe0a81e904e452ec7ca733

> By default number of pixels must be less than 2^30. Limit can be set using system variable OPENCV_IO_MAX_IMAGE_PIXELS

**Comment by emgucv** [comment]
Closing ticket now.
