### ISSUE TITLE
Running Application from Window to Linux

### ISSUE THREAD

**Issue by Junaid-Amjad** [emgucv/emgucv#444]
Hi, i have created the application on windows and i added libraries from nuget
1. Emgu.CV (4.5.1.4349)
2. Emgu.CV.runtime.windows(4.5.1.4349)

and it worked fine but when i tried to run on linux machine then following exception occurs 

> Unhandled exception. System.TypeInitializationException: The type initializer for 'VideoViewControlinAvaloniaIDrawable.MainWindow' threw an exception.
>  ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
>  ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
> 

I added ubuntu library Emgu.CV.runtime.ubuntu.20.04-x64(4.5.1.4349) and i can found the .so file in the folder but issue still exist. Can you share the solution of this problem?

**Comment by emgucv** [comment]
Quite likely you have missing dependencies. Follow this step to touble shot:
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

**Comment by emgucv** [comment]
Closing ticket now.
