### ISSUE TITLE
IMWRITE_JPEG2000_COMPRESSION_X1000 missing from ImwriteFlags

### ISSUE THREAD

**Issue by WalkerCodeRanger** [emgucv/emgucv#445]
The [docs show an IMWRITE_JPEG2000_COMPRESSION_X1000 flag](https://docs.opencv.org/4.1.0/d4/da8/group__imgcodecs.html#ga292d81be8d76901bff7988d18d2b42ac) for OpenCV 4.1.0 and later. However the `ImwriteFlags` enumeration doesn't have a matching value.

**Comment by emgucv** [comment]
Fixed in 3a007a9eb5c29eee519112a40fd93daed1ea3bdf
Thanks for pointing out.

**Comment by emgucv** [comment]
Closing ticket now.
