### ISSUE TITLE
How to deploy emgucv on Ubuntu 20.04 ?

### ISSUE THREAD

**Issue by timiil** [emgucv/emgucv#447]
hello, i am trying deploy a .NET 5 console app which using EmguCV on Ubuntu 20.04, my steps are here:

a. new computer (intel J5005 cpu) , install Ubuntu 20.04.1 Desktop Version,

b. update 
```
apt-get update -y && apt-get upgrade -y
```

c. install .NET 5 sdk
```
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb

apt-get update; \
 apt-get install -y apt-transport-https && \
 apt-get update && \
 apt-get install -y dotnet-sdk-5.0

```

d. test code:
```
mkdir /home/hello
cd /home/hello
dotnet new console

```

e.  modify hello.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.5.1.4349" />
    <PackageReference Include="Emgu.CV.runtime.ubuntu.20.04-x64" Version="4.5.1.4349" />
  </ItemGroup>

</Project>
```

f. run the code :
```
dotnet run
```

the code is very OK to response Hello World.

g. modify the 'Program.cs':
```
using System;

namespace hello
{
        class Program
        {
                static void Main(string[] args)
                {
                         Emgu.CV.Mat mat = new Emgu.CV.Mat();
                         Console.WriteLine("Hello World!");
               }
        }
}
```

run the code and then failed:
```
root@oem-GK55:/home/hello# dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.MatInvoke' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory
   at Emgu.Util.Toolbox.Dlopen(String dllname, Int32 mode)
   at Emgu.Util.Toolbox.LoadLibrary(String dllname)
   at Emgu.CV.CvInvoke.LoadUnmanagedModules(String loadDirectory, String[] unmanagedModules)
   at Emgu.CV.CvInvoke.DefaultLoadUnmanagedModules(String[] modules)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.Init()
   at Emgu.CV.MatInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.MatInvoke.cveMatCreate()
   at Emgu.CV.Mat..ctor()
   at hello.Program.Main(String[] args) in /home/hello/Program.cs:line 9
```

Please let us know how to do any more ... thanks.

**Comment by emgucv** [comment]
Please follow the detail instruction here:
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

Most likely it is missing dependency, have you run this script below? (as part of the installation instruction above):
https://github.com/emgucv/emgucv/blob/master/platforms/ubuntu/20.04/apt_install_dependency.sh

If yes, follow further instruction by running:
`LD_DEBUG=libs dotnet run`

**Comment by timiil** [comment]
thanks very much .  

i have execute the command :
```
./apt_install_dependency.sh
```

still missing the 'libgeotiff' lib, so :

```
apt-get install -y libgeotiff-dev
```

that will OK now!

**Comment by emgucv** [comment]
Added libgeotiff dependency for ubuntu 20.04 in commit 13dc6bbe1231276c7d984c86de234f84a50342f8

Thanks for pointing that out.

**Comment by Bonzatina** [comment]
Thanks for fixing. Stuck on it for a while.
https://emgu.com/wiki/index.php/Hello_World_for_Ubuntu
here link (https://github.com/emgucv/emgucv/blob/4.5.1/platforms/ubuntu/20.04/apt_install_dependency.sh) point to version of apt_install_dependency.sh without libgeotiff , could worth to fix it.

**Comment by emgucv** [comment]
Closing ticket now with the new 4.5.2 release tagged.
