### ISSUE TITLE
CvInvoke.Imencode should return a bool

### ISSUE THREAD

**Issue by WalkerCodeRanger** [emgucv/emgucv#449]
The [OpenCV docs](https://docs.opencv.org/4.5.1/d4/da8/group__imgcodecs.html#ga461f9ac09887e47797a54567df3b8b63) show that `cv::imencode` returns a bool. I have confirmed that in the OpenCV code. So the `CvInvoke.Imencode(String ext, IInputArray image, VectorOfByte buf, params KeyValuePair<CvEnum.ImwriteFlags, int>[] parameters)` method should return `bool` instead of `void`.

**Comment by emgucv** [comment]
Fixed in commit 7928336897eb48990d36e34302600107b3824f19

Thanks for pointing out.

**Comment by emgucv** [comment]
Closing ticket now
