### ISSUE TITLE
How to bulid emgucv on Ubuntu for CUDA

### ISSUE THREAD

**Issue by hello-web** [emgucv/emgucv#454]
I am attempting to use Emgucv on linux for CUDA, but getting the error message:

[ 91%] Building CXX object opencv/modules/videostab/CMakeFiles/opencv_videostab.dir/src/global_motion.cpp.o
[ 91%] Linking CXX static library ../../../bin/x64/libopencv_stitching.a
[ 92%] Built target opencv_stitching
[ 92%] Linking CXX static library ../../../bin/x64/libopencv_videostab.a
[ 92%] Built target opencv_videostab
[ 92%] Linking CXX static library ../../../bin/x64/libopencv_superres.a
[ 92%] Built target opencv_superres
[ 92%] Linking CXX shared library ../../../../../libs/x64/libcvextern.so
/usr/local/cuda-10.1/lib64/libcudart_static.a(libcudart_static.a.o): in the function `cudaSetDevice`:
(.text+0x3ce50): `cudaGetDevice` is defined more than once
CMakeFiles/cvextern.dir/core/core_cuda_c.cpp.o:core_cuda_c.cpp:(.text+0x20): defined here for the first time
/usr/local/cuda-10.1/lib64/libcudart_static.a(libcudart_static.a.o): in the function `cudaSetDevice`:
(.text+0x3cff0): `cudaSetDevice` is defined more than once
CMakeFiles/cvextern.dir/core/core_cuda_c.cpp.o:core_cuda_c.cpp:(.text+0x10): defined here for the first time
collect2: error: ld returned 1 exit status
Emgu.CV.Extern/CMakeFiles/cvextern.dir/build.make:4759: recipe for target '../../../../libs/x64/libcvextern.so' failed
make[2]: *** [../../../../libs/x64/libcvextern.so] Error 1
CMakeFiles/Makefile2:7769: recipe for target 'Emgu.CV.Extern/CMakeFiles/cvextern.dir/all' failed
make[1]: *** [Emgu.CV.Extern/CMakeFiles/cvextern.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Bonzatina** [comment]
I had problems with libcvextern on Ubuntu that helped me - https://github.com/emgucv/emgucv/issues/447

**Comment by hello-web** [comment]
> I had problems with libcvextern on Ubuntu that helped me - #447

The default configuration is passed, for cuda is error. 
Linking CXX shared library ../../../../../libs/x64/libcvextern.so
cudaGetDevice is defined more than once.
cudaGetDevice Duplicate definition in libcudart_static.a.o And core_cuda_c.cpp.o

-----------------------------------------------
My configuration:

 ANT_EXECUTABLE                   ANT_EXECUTABLE-NOTFOUND                                                                                                                                                         
 Atlas_BLAS_LIBRARY               Atlas_BLAS_LIBRARY-NOTFOUND                                                                                                                                                     
 Atlas_CBLAS_INCLUDE_DIR          Atlas_CBLAS_INCLUDE_DIR-NOTFOUND                                                                                                                                                
 Atlas_CBLAS_LIBRARY              Atlas_CBLAS_LIBRARY-NOTFOUND                                                                                                                                                    
 Atlas_CLAPACK_INCLUDE_DIR        Atlas_CLAPACK_INCLUDE_DIR-NOTFOUND                                                                                                                                              
 Atlas_LAPACK_LIBRARY                                                                                                                                                                                             
 BUILD_CUDA_STUBS                 ON                                                                                                                                                                              
 BUILD_DOCS                       OFF                                                                                                                                                                             
 BUILD_EXAMPLES                   OFF                                                                                                                                                                             
 BUILD_FAT_JAVA_LIB               OFF                                                                                                                                                                             
 BUILD_IPP_IW                     ON                                                                                                                                                                              
 BUILD_ITT                        ON                                                                                                                                                                              
 BUILD_JASPER                     ON                                                                                                                                                                              
 BUILD_JAVA                       ON                                                                                                                                                                              
 BUILD_JPEG                       ON                                                                                                                                                                              
 BUILD_LIST                                                                                                                                                                                                       
 BUILD_OPENEXR                    ON                                                                                                                                                                              
 BUILD_OPENJPEG                   OFF                                                                                                                                                                             
 BUILD_PACKAGE                    ON                                                                                                                                                                              
 BUILD_PERF_TESTS                 OFF                                                                                                                                                                             
 BUILD_PNG                        ON                                                                                                                                                                              
 BUILD_PROTOBUF                   ON                                                                                                                                                                              
 BUILD_SHARED_LIBS                OFF                                                                                                                                                                             
 BUILD_TBB                        ON                                                                                                                                                                              
 BUILD_TESTS                      OFF                                                                                                                                                                             
 BUILD_TIFF                       ON                                                                                                                                                                              
 BUILD_USE_SYMLINKS               OFF                                                                                                                                                                             
 BUILD_WEBP                       OFF                                                                                                                                                                             
 BUILD_WITH_DEBUG_INFO            OFF                                                                                                                                                                             
 BUILD_WITH_DYNAMIC_IPP           OFF                                                                                                                                                                             
 BUILD_ZLIB                       OFF                                                                                                                                                                             
 BUILD_opencv_alphamat            ON                                                                                                                                                                              
 BUILD_opencv_apps                OFF                                                                                                                                                                             
 BUILD_opencv_aruco               ON                                                                                                                                                                              
 BUILD_opencv_bgsegm              ON                                                                                                                                                                              
 BUILD_opencv_bioinspired         ON                                                                                                                                                                              
 BUILD_opencv_calib3d             ON                                                                                                                                                                              
 BUILD_opencv_ccalib              ON                                                                                                                                                                              
 BUILD_opencv_core                ON                                                                                                                                                                              
 BUILD_opencv_cudaarithm          ON                                                                                                                                                                              
 BUILD_opencv_cudabgsegm          ON                                                                                                                                                                              
 BUILD_opencv_cudacodec           ON                                                                                                                                                                              
 BUILD_opencv_cudafeatures2d      ON                                                                                                                                                                              
 BUILD_opencv_cudafilters         ON    
 BUILD_opencv_cudaimgproc         ON                                                                                                                                                                              
 BUILD_opencv_cudalegacy          ON                                                                                                                                                                              
 BUILD_opencv_cudaobjdetect       ON                                                                                                                                                                              
 BUILD_opencv_cudaoptflow         ON                                                                                                                                                                              
 BUILD_opencv_cudastereo          ON                                                                                                                                                                              
 BUILD_opencv_cudawarping         ON                                                                                                                                                                              
 BUILD_opencv_cudev               ON                                                                                                                                                                              
 BUILD_opencv_datasets            ON                                                                                                                                                                              
 BUILD_opencv_dnn                 ON                                                                                                                                                                              
 BUILD_opencv_dnn_objdetect       ON                                                                                                                                                                              
 BUILD_opencv_dnn_superres        ON                                                                                                                                                                              
 BUILD_opencv_dpm                 ON                                                                                                                                                                              
 BUILD_opencv_face                ON                                                                                                                                                                              
 BUILD_opencv_features2d          ON                                                                                                                                                                              
 BUILD_opencv_flann               ON                                                                                                                                                                              
 BUILD_opencv_freetype            ON                                                                                                                                                                              
 BUILD_opencv_fuzzy               ON                                                                                                                                                                              
 BUILD_opencv_gapi                ON                                                                                                                                                                              
 BUILD_opencv_hdf                 ON                                                                                                                                                                              
 BUILD_opencv_hfs                 ON                                                                                                                                                                              
 BUILD_opencv_highgui             ON                                                                                                                                                                              
 BUILD_opencv_img_hash            ON                                                                                                                                                                              
 BUILD_opencv_imgcodecs           ON                                                                                                                                                                              
 BUILD_opencv_imgproc             ON                                                                                                                                                                              
 BUILD_opencv_intensity_transfo   ON                                                                                                                                                                              
 BUILD_opencv_java                OFF                                                                                                                                                                             
 BUILD_opencv_java_bindings_gen   ON                                                                                                                                                                              
 BUILD_opencv_js                  OFF                                                                                                                                                                             
 BUILD_opencv_js_bindings_gener   ON                                                                                                                                                                              
 BUILD_opencv_line_descriptor     ON                                                                                                                                                                              
 BUILD_opencv_mcc                 ON                                                                                                                                                                              
 BUILD_opencv_ml                  ON                                                                                                                                                                              
 BUILD_opencv_objc_bindings_gen   ON                                                                                                                                                                              
 BUILD_opencv_objdetect           ON                                                                                                                                                                              
 BUILD_opencv_optflow             ON                                                                                                                                                                              
 BUILD_opencv_phase_unwrapping    ON                                                                                                                                                                              
 BUILD_opencv_photo               ON                                                                                                                                                                              
 BUILD_opencv_plot                ON                                                                                                                                                                              
 BUILD_opencv_python2             OFF                                                                                                                                                                             
 BUILD_opencv_python3             OFF                                                                                                                                                                             
 BUILD_opencv_python_bindings_g   ON                                                                                                                                                                              
 BUILD_opencv_python_tests        ON                                                                                                                                                                              
 BUILD_opencv_quality             ON                                                                                                                                                                              
 BUILD_opencv_rapid               ON   
 BUILD_opencv_reg                 ON                                                                                                                                                                              
 BUILD_opencv_rgbd                ON                                                                                                                                                                              
 BUILD_opencv_saliency            ON                                                                                                                                                                              
 BUILD_opencv_sfm                 ON                                                                                                                                                                              
 BUILD_opencv_shape               ON                                                                                                                                                                              
 BUILD_opencv_stereo              ON                                                                                                                                                                              
 BUILD_opencv_stitching           ON                                                                                                                                                                              
 BUILD_opencv_structured_light    ON                                                                                                                                                                              
 BUILD_opencv_superres            ON                                                                                                                                                                              
 BUILD_opencv_surface_matching    ON                                                                                                                                                                              
 BUILD_opencv_text                ON                                                                                                                                                                              
 BUILD_opencv_tracking            ON                                                                                                                                                                              
 BUILD_opencv_ts                  OFF                                                                                                                                                                             
 BUILD_opencv_video               ON                                                                                                                                                                              
 BUILD_opencv_videoio             ON                                                                                                                                                                              
 BUILD_opencv_videostab           ON                                                                                                                                                                              
 BUILD_opencv_world               OFF                                                                                                                                                                             
 BUILD_opencv_xfeatures2d         ON                                                                                                                                                                              
 BUILD_opencv_ximgproc            ON                                                                                                                                                                              
 BUILD_opencv_xobjdetect          ON                                                                                                                                                                              
 BUILD_opencv_xphoto              ON                                                                                                                                                                              
 CCACHE_PROGRAM                   CCACHE_PROGRAM-NOTFOUND                                                                                                                                                         
 CLAMDBLAS_INCLUDE_DIR            CLAMDBLAS_INCLUDE_DIR-NOTFOUND                                                                                                                                                  
 CLAMDBLAS_ROOT_DIR               CLAMDBLAS_ROOT_DIR-NOTFOUND                                                                                                                                                     
 CLAMDFFT_INCLUDE_DIR             CLAMDFFT_INCLUDE_DIR-NOTFOUND                                                                                                                                                   
 CLAMDFFT_ROOT_DIR                CLAMDFFT_ROOT_DIR-NOTFOUND                                                                                                                                                      
 CMAKE_BUILD_TYPE                 Release                                                                                                                                                                         
 CMAKE_CONFIGURATION_TYPES        Debug;Release                                                                                                                                                                   
 CMAKE_CXX_STANDARD               11                                                                                                                                                                              
 CMAKE_FIND_ROOT_PATH             /home/samer/data/src/Video/emgucv-gpu/emgucv/platforms/ubuntu/20.04/build/install                                                                                               
 CMAKE_INSTALL_PREFIX             /home/samer/data/src/Video/emgucv-gpu/emgucv/platforms/ubuntu/20.04/build/install                                                                                               
 CMAKE_POSITION_INDEPENDENT_COD   ON                                                                                                                                                                              
 CPU_BASELINE                     SSE3                                                                                                                                                                            
 CPU_DISPATCH                     SSE4_1;SSE4_2;AVX;FP16;AVX2;AVX512_SKX                                                                                                                                          
 CSC_EXECUTABLE_120               CSC_EXECUTABLE_120-NOTFOUND                                                                                                                                                     
 CSC_EXECUTABLE_140               CSC_EXECUTABLE_140-NOTFOUND                                                                                                                                                     
 CSC_EXECUTABLE_150               CSC_EXECUTABLE_150-NOTFOUND                                                                                                                                                     
 CSC_EXECUTABLE_160               CSC_EXECUTABLE_160-NOTFOUND                                                                                                                                                     
 CSC_EXECUTABLE_20                CSC_EXECUTABLE_20-NOTFOUND                                                                                                                                                      
 CSC_EXECUTABLE_35                CSC_EXECUTABLE_35-NOTFOUND                                                                                                                                                      
 CSC_EXECUTABLE_40                CSC_EXECUTABLE_40-NOTFOUND                                                                                                                                                      
 CSC_MSCORLIB_35                  CSC_MSCORLIB_35-NOTFOUND                                                                                                                                                        
 CSC_TARGET_FRAMEWORK                                                                                                                                                                                             
 CUDA_ARCH_BIN                    3.0;3.5;3.7;5.0;5.2;6.0;6.1;7.0;7.5 
 CUDA_ARCH_PTX                                                                                                                                                                                                    
 CUDA_ENABLE_DEPRECATED_GENERAT   OFF                                                                                                                                                                             
 CUDA_FAST_MATH                   OFF                                                                                                                                                                             
 CUDA_GENERATION                                                                                                                                                                                                  
 CUDA_HOST_COMPILER               /usr/bin/x86_64-linux-gnu-gcc-7                                                                                                                                                 
 CUDA_TOOLKIT_ROOT_DIR            /usr/local/cuda-10.1                                                                                                                                                            
 CUDA_USE_STATIC_CUDA_RUNTIME     ON                                                                                                                                                                              
 CUDA_rt_LIBRARY                  /usr/lib/x86_64-linux-gnu/librt.so                                                                                                                                              
 CV_DISABLE_OPTIMIZATION          OFF                                                                                                                                                                             
 CV_ENABLE_INTRINSICS             ON                                                                                                                                                                              
 CV_TRACE                         ON                                                                                                                                                                              
 Caffe_INCLUDE_DIR                Caffe_INCLUDE_DIR-NOTFOUND                                                                                                                                                      
 Caffe_LIBS                       Caffe_LIBS-NOTFOUND                                                                                                                                                             
 Ceres_DIR                        Ceres_DIR-NOTFOUND                                                                                                                                                              
 DATE_PATH                        /bin/date                                                                                                                                                                       
 DEFAULT_CS_CONFIG                Release                                                                                                                                                                         
 EMGU_CV_BUILD                    ON                                                                                                                                                                              
 EMGU_CV_EXAMPLE_BUILD            ON                                                                                                                                                                              
 EMGU_CV_WITH_DEPTHAI             OFF                                                                                                                                                                             
 EMGU_CV_WITH_FREETYPE            OFF                                                                                                                                                                             
 EMGU_CV_WITH_TESSERACT           ON                                                                                                                                                                              
 EMGU_CV_WITH_TIFF                ON                                                                                                                                                                              
 EMGU_ENABLE_SSE                  OFF                                                                                                                                                                             
 ENABLE_BUILD_HARDENING           OFF                                                                                                                                                                             
 ENABLE_CCACHE                    ON                                                                                                                                                                              
 ENABLE_CONFIG_VERIFICATION       OFF                                                                                                                                                                             
 ENABLE_COVERAGE                  OFF                                                                                                                                                                             
 ENABLE_FAST_MATH                 OFF                                                                                                                                                                             
 ENABLE_FLAKE8                    OFF                                                                                                                                                                             
 ENABLE_GNU_STL_DEBUG             OFF                                                                                                                                                                             
 ENABLE_IMPL_COLLECTION           OFF                                                                                                                                                                             
 ENABLE_INSTRUMENTATION           OFF                                                                                                                                                                             
 ENABLE_LTO                       OFF                                                                                                                                                                             
 ENABLE_NOISY_WARNINGS            OFF                                                                                                                                                                             
 ENABLE_OMIT_FRAME_POINTER        ON                                                                                                                                                                              
 ENABLE_PIC                       ON                                                                                                                                                                              
 ENABLE_PROFILING                 OFF                                                                                                                                                                             
 ENABLE_PYLINT                    OFF                                                                                                                                                                             
 ENABLE_SOLUTION_FOLDERS          OFF                                                                                                                                                                             
 EXECUTABLE_OUTPUT_PATH           /home/samer/data/src/Video/emgucv-gpu/emgucv/platforms/ubuntu/20.04/build/bin                                                                                                   
 Eigen3_DIR                       /home/samer/data/src/Video/emgucv-gpu/emgucv/eigen/build                                                                                                                        
 GENERATE_ABI_DESCRIPTOR          OFF                                                                                                                                                                             
 GEOTIFF_INCLUDE_DIR              /usr/include/geotiff                                                                                                                                                            
 GEOTIFF_LIBRARY                  /usr/lib/x86_64-linux-gnu/libgeotiff.so 
 Gflags_DIR                       /usr/lib/x86_64-linux-gnu/cmake/gflags                                                                                                                                          
 Glog_DIR                         Glog_DIR-NOTFOUND                                                                                                                                                               
 Glog_LIBS                        /usr/lib/x86_64-linux-gnu/libglog.so                                                                                                                                            
 HDF5_C_LIBRARY_dl                /usr/lib/x86_64-linux-gnu/libdl.so                                                                                                                                              
 HDF5_C_LIBRARY_hdf5              /home/samer/anaconda3/lib/libhdf5.so                                                                                                                                            
 HDF5_C_LIBRARY_m                 /usr/lib/x86_64-linux-gnu/libm.so                                                                                                                                               
 HDF5_C_LIBRARY_pthread           /usr/lib/x86_64-linux-gnu/libpthread.so                                                                                                                                         
 HDF5_C_LIBRARY_rt                /usr/lib/x86_64-linux-gnu/librt.so                                                                                                                                              
 HDF5_C_LIBRARY_z                 /home/samer/anaconda3/lib/libz.so                                                                                                                                               
 INSTALL_CREATE_DISTRIB           OFF                                                                                                                                                                             
 INSTALL_C_EXAMPLES               OFF                                                                                                                                                                             
 INSTALL_PYTHON_EXAMPLES          OFF                                                                                                                                                                             
 INSTALL_TESTS                    OFF                                                                                                                                                                             
 LAPACKE_INCLUDE_DIR              LAPACKE_INCLUDE_DIR-NOTFOUND                                                                                                                                                    
 LAPACK_CBLAS_H                   mkl_cblas.h                                                                                                                                                                     
 LAPACK_IMPL                      MKL                                                                                                                                                                             
 LAPACK_INCLUDE_DIR               /opt/intel/mkl/include                                                                                                                                                          
 LAPACK_LAPACKE_H                 mkl_lapack.h                                                                                                                                                                    
 LAPACK_LIBRARIES                 /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_sequential.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;/opt/intel/mkl/lib/intel64/libmkl_inte
 LSB_RELEASE_EXEC                 /usr/bin/lsb_release                                                                                                                                                            
 Lept_LIBRARY                     Lept_LIBRARY-NOTFOUND                                                                                                                                                           
 MKL_INCLUDE_DIR                  /opt/intel/mkl/include                                                                                                                                                          
 MKL_LAPACKE_INCLUDE_DIR          /opt/intel/mkl/include                                                                                                                                                          
 MKL_ROOT_DIR                     /opt/intel/mkl                                                                                                                                                                  
 MKL_USE_SINGLE_DYNAMIC_LIBRARY   OFF                                                                                                                                                                             
 MKL_VERSION_STR                  2020.0.0                                                                                                                                                                        
 MKL_WITH_OPENMP                  OFF                                                                                                                                                                             
 MKL_WITH_TBB                     OFF                                                                                                                                                                             
 MSBUILD_EXECUTABLE_120           MSBUILD_EXECUTABLE_120-NOTFOUND                                                                                                                                                 
 MSBUILD_EXECUTABLE_140           MSBUILD_EXECUTABLE_140-NOTFOUND                                                                                                                                                 
 MSBUILD_EXECUTABLE_150           MSBUILD_EXECUTABLE_150-NOTFOUND                                                                                                                                                 
 MSBUILD_EXECUTABLE_160           MSBUILD_EXECUTABLE_160-NOTFOUND                                                                                                                                                 
 MSBUILD_EXECUTABLE_20            MSBUILD_EXECUTABLE_20-NOTFOUND                                                                                                                                                  
 MSBUILD_EXECUTABLE_35            MSBUILD_EXECUTABLE_35-NOTFOUND                                                                                                                                                  
 MSBUILD_EXECUTABLE_40            MSBUILD_EXECUTABLE_40-NOTFOUND                                                                                                                                                  
 M_LIBRARY                        /usr/lib/x86_64-linux-gnu/libm.so                                                                                                                                               
 OGRE_DIR                         OGRE_DIR-NOTFOUND                                                                                                                                                               
 OPENCL_FOUND                     ON                                                                                                                                                                              
 OPENCV_CONFIG_FILE_INCLUDE_DIR   /home/samer/data/src/Video/emgucv-gpu/emgucv/platforms/ubuntu/20.04/build                                                                                                       
 OPENCV_DNN_CUDA                  ON                                                                                                                                                                              
 OPENCV_DNN_OPENCL                ON                                                                                                                                                                              
 OPENCV_DOWNLOAD_PATH             /home/samer/data/src/Video/emgucv-gpu/emgucv/opencv/.cache                                                                                                                      
 OPENCV_DUMP_HOOKS_FLOW           OFF                                                                                                                                                                             
 OPENCV_ENABLE_ALLOCATOR_STATS    ON                 
 OPENCV_ENABLE_ATOMIC_LONG_LONG   ON                                                                                                                                                                              
 OPENCV_ENABLE_MEMALIGN           ON                                                                                                                                                                              
 OPENCV_ENABLE_MEMORY_SANITIZER   OFF                                                                                                                                                                             
 OPENCV_ENABLE_NONFREE            OFF                                                                                                                                                                             
 OPENCV_EXTRA_MODULES_PATH        /home/samer/data/src/Video/emgucv-gpu/emgucv/opencv_contrib/modules                                                                                                             
 OPENCV_FORCE_3RDPARTY_BUILD      OFF                                                                                                                                                                             
 OPENCV_GENERATE_PKGCONFIG        OFF                                                                                                                                                                             
 OPENCV_GENERATE_SETUPVARS        ON                                                                                                                                                                              
 OPENCV_IPP_GAUSSIAN_BLUR         OFF                                                                                                                                                                             
 OPENCV_JAVA_SOURCE_VERSION                                                                                                                                                                                       
 OPENCV_JAVA_TARGET_VERSION                                                                                                                                                                                       
 OPENCV_MATHJAX_RELPATH           https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0                                                                                                                            
 OPENCV_PYTHON3_VERSION           OFF                                                                                                                                                                             
 OPENCV_TIMESTAMP                 2021-03-18T12:17:37Z                                                                                                                                                            
 OPENCV_WARNINGS_ARE_ERRORS       OFF                                                                                                                                                                             
 OpenCV_HAL_DIR                   OpenCV_HAL_DIR-NOTFOUND                                                                                                                                                         
 OpenJPEG_DIR                     /home/samer/anaconda3/lib/openjpeg-2.3                                                                                                                                          
 PROTOBUF_UPDATE_FILES            OFF                                                                                                                                                                             
 PYTHON2_EXECUTABLE               /usr/bin/python2.7                                                                                                                                                              
 PYTHON2_INCLUDE_DIR              /usr/include/python2.7                                                                                                                                                          
 PYTHON2_INCLUDE_DIR2                                                                                                                                                                                             
 PYTHON2_LIBRARY                  /usr/lib/x86_64-linux-gnu/libpython2.7.so                                                                                                                                       
 PYTHON2_LIBRARY_DEBUG                                                                                                                                                                                            
 PYTHON2_NUMPY_INCLUDE_DIRS                                                                                                                                                                                       
 PYTHON2_PACKAGES_PATH            lib/python2.7/dist-packages                                                                                                                                                     
 PYTHON3_EXECUTABLE               /home/samer/anaconda3/bin/python3                                                                                                                                               
 PYTHON3_INCLUDE_DIR                                                                                                                                                                                              
 PYTHON3_INCLUDE_DIR2                                                                                                                                                                                             
 PYTHON3_LIBRARY                                                                                                                                                                                                  
 PYTHON3_LIBRARY_DEBUG                                                                                                                                                                                            
 PYTHON3_NUMPY_INCLUDE_DIRS       /home/samer/anaconda3/lib/python3.8/site-packages/numpy/core/include                                                                                                            
 PYTHON3_PACKAGES_PATH            lib/python3.8/site-packages                                                                                                                                                     
 RESGEN_EXECUTABLE                RESGEN_EXECUTABLE-NOTFOUND                                                                                                                                                      
 TESSERACT_OPENCL                 OFF                                                                                                                                                                             
 Tesseract_DIR                    Tesseract_DIR-NOTFOUND                                                                                                                                                          
 Tesseract_INCLUDE_DIR            Tesseract_INCLUDE_DIR-NOTFOUND                                                                                                                                                  
 Tesseract_LIBRARY                Tesseract_LIBRARY-NOTFOUND                                                                                                                                                      
 USE_WIN32_FILEIO                 OFF                                                                                                                                                                             
 VTK_DIR                          VTK_DIR-NOTFOUND                                                                                                                                                                
 WITH_1394                        ON                                                                                                                                                                              
 WITH_ADE                         ON                                                                                                                                                                              
 WITH_ARAVIS                      OFF                                                                                                                                                                             
 WITH_ARITH_DEC                   ON                                                                                                                                                                              
 WITH_ARITH_ENC                   ON          
 WITH_CLP                         OFF                                                                                                                                                                             
 WITH_CUBLAS                      ON                                                                                                                                                                              
 WITH_CUDA                        ON                                                                                                                                                                              
 WITH_CUDNN                       ON                                                                                                                                                                              
 WITH_CUFFT                       ON                                                                                                                                                                              
 WITH_EIGEN                       ON                                                                                                                                                                              
 WITH_FFMPEG                      ON                                                                                                                                                                              
 WITH_FREETYPE                    OFF                                                                                                                                                                             
 WITH_GDAL                        OFF                                                                                                                                                                             
 WITH_GDCM                        OFF                                                                                                                                                                             
 WITH_GPHOTO2                     OFF                                                                                                                                                                             
 WITH_GSTREAMER                   ON                                                                                                                                                                              
 WITH_GTK                         ON                                                                                                                                                                              
 WITH_GTK_2_X                     OFF                                                                                                                                                                             
 WITH_HALIDE                      OFF                                                                                                                                                                             
 WITH_HPX                         OFF                                                                                                                                                                             
 WITH_IMGCODEC_HDR                ON                                                                                                                                                                              
 WITH_IMGCODEC_PFM                ON                                                                                                                                                                              
 WITH_IMGCODEC_PXM                ON                                                                                                                                                                              
 WITH_IMGCODEC_SUNRASTER          ON                                                                                                                                                                              
 WITH_INF_ENGINE                  OFF                                                                                                                                                                             
 WITH_IPP                         ON                                                                                                                                                                              
 WITH_ITT                         ON                                                                                                                                                                              
 WITH_JASPER                      ON                                                                                                                                                                              
 WITH_JPEG                        ON                                                                                                                                                                              
 WITH_JULIA                       OFF                                                                                                                                                                             
 WITH_LAPACK                      ON                                                                                                                                                                              
 WITH_LIBREALSENSE                OFF                                                                                                                                                                             
 WITH_MATLAB                      OFF                                                                                                                                                                             
 WITH_MFX                         OFF                                                                                                                                                                             
 WITH_NGRAPH                      OFF                                                                                                                                                                             
 WITH_NVCUVID                     OFF                                                                                                                                                                             
 WITH_ONNX                        OFF                                                                                                                                                                             
 WITH_OPENCL                      ON                                                                                                                                                                              
 WITH_OPENCLAMDBLAS               ON                                                                                                                                                                              
 WITH_OPENCLAMDFFT                ON                                                                                                                                                                              
 WITH_OPENCL_SVM                  OFF                                                                                                                                                                             
 WITH_OPENEXR                     ON                                                                                                                                                                              
 WITH_OPENGL                      ON                                                                                                                                                                              
 WITH_OPENJPEG                    ON                                                                                                                                                                              
 WITH_OPENMP                      OFF                                                                                                                                                                             
 WITH_OPENNI                      OFF                                                                                                                                                                             
 WITH_OPENNI2                     OFF                                                                                                                                                                             
 WITH_OPENVX                      OFF 
 WITH_PLAIDML                     OFF                                                                                                                                                                             
 WITH_PNG                         ON                                                                                                                                                                              
 WITH_PROTOBUF                    ON                                                                                                                                                                              
 WITH_PTHREADS_PF                 ON                                                                                                                                                                              
 WITH_PVAPI                       OFF                                                                                                                                                                             
 WITH_QT                          OFF                                                                                                                                                                             
 WITH_QUIRC                       ON                                                                                                                                                                              
 WITH_TBB                         OFF                                                                                                                                                                             
 WITH_TESSERACT                   ON                                                                                                                                                                              
 WITH_TIFF                        ON                                                                                                                                                                              
 WITH_UEYE                        OFF                                                                                                                                                                             
 WITH_V4L                         ON                                                                                                                                                                              
 WITH_VA                          OFF                                                                                                                                                                             
 WITH_VA_INTEL                    OFF                                                                                                                                                                             
 WITH_VTK                         ON                                                                                                                                                                              
 WITH_VULKAN                      OFF                                                                                                                                                                             
 WITH_WEBP                        ON                                                                                                                                                                              
 WITH_XIMEA                       OFF                                                                                                                                                                             
 WITH_XINE                        OFF                                                                                                                                                                             
 ZIP_CMD                          /usr/bin/zip                                                                                                                                                                    
 ccitt                            ON                                                                                                                                                                              
 logluv                           ON                                                                                                                                                                              
 lzw                              ON                                                                                                                                                                              
 mdi                              ON                                                                                                                                                                              
 next                             ON                                                                                                                                                                              
 old-jpeg                         OFF                                                                                                                                                                             
 opencv_dnn_PERF_CAFFE            OFF                                                                                                                                                                             
 opencv_dnn_PERF_CLCAFFE          OFF                                                                                                                                                                             
 packbits                         ON                                                                                                                                                                              
 thunder                          ON

**Comment by emgucv** [comment]
Added the option to build Emgu CV with CUDA in this commit:
279c3384126b4dc17fd54785dbab5dfb067f09ff
Also updated the build instruction below for building Emgu CV with CUDA 11.2 in Ubuntu 20.04:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Ubuntu_20.04_2

The key is to set the flag "-DBUILD_SHARED_LIBS:BOOL=TRUE". CUDA binary cannot be static linked, it needs to be compiled as shared library.

**Comment by hello-web** [comment]
> Added the option to build Emgu CV with CUDA in this commit:
> [279c338](https://github.com/emgucv/emgucv/commit/279c3384126b4dc17fd54785dbab5dfb067f09ff)
> Also updated the build instruction below for building Emgu CV with CUDA 11.2 in Ubuntu 20.04:
> https://www.emgu.com/wiki/index.php/Download_And_Installation#Ubuntu_20.04_2
> 
> The key is to set the flag "-DBUILD_SHARED_LIBS:BOOL=TRUE". CUDA binary cannot be static linked, it needs to be compiled as shared library.

Thanks
