### ISSUE TITLE
Can't find emgu.cv.ocl dll

### ISSUE THREAD

**Issue by tchemaly** [emgucv/emgucv#455]
The Emgu.CV.Ocl dll is missing in my bin folder, and I cannot find it online. Can someone please help? I need it for my Unity Project.

**Comment by emgucv** [comment]
What Emgu CV version are you using? 

The Emgu CV unity store asset can be found here:
https://assetstore.unity.com/packages/tools/ai/emgu-cv-v4-x-144853
There is no need to include any additional dlls beside of including the asset.

The Emgu.CV.Ocl namespace is part of the unity scripts under the "Assets\Scripts\Emgu.CV\Ocl" folder in the above asset.

**Comment by tchemaly** [comment]
Is it possible to find the dll if I did not want to use the the unity asset? I want to use the open source version of Emgu CV. I have tried downloading the zip files for the following versions and none of them has this dll:
3.4.1
4.0.1
4.4.0
4.5.1

I appreciate your help! Thank you.

**Comment by emgucv** [comment]
In the 4.5.1 release, the Emgu.CV.Ocl namespace implementation is included in the Emgu.CV.Platform.NetStandard.dll. 

Note that the open source release are not tested against Unity and we do not support using the "Emgu.CV.Platform.NetStandard.dll" in unity. It is intended to be used in non-unity environments.

Officially, for unity, we only support using the release package from unity store and our online store, which do not contains precompiled Emgu.CV.Platform.NetStandard.dll binary, but use unity scripts (C# source code format) instead. We used conditional platform compilation script to work with differnt unity targets.

FYI, if you are from a research, educational, non-commercial institution, you can reach out to support@emgu.com to get a copy of the Emgu CV for Unity release, free of charge. If you are planning to use it for a commercial application, you can also ask for an evaluation copy. Hope that helps.

**Comment by tchemaly** [comment]
That's amazing. Yes, I am actually using it for educational research. I will reach out via email. Thank you.

**Comment by tchemaly** [comment]
I just sent you an email. Thanks!
