### ISSUE TITLE
Cannot install NuGet package Emgu.CV.runtime.windows

### ISSUE THREAD

**Issue by mekatrol** [emgucv/emgucv#456]
### **Overview**

Trying to install the NuGet package **Emgu.CV.runtime.windows** fails as it appears to reference  #https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json, which is no longer valid according to Microsoft (certificate is revoked)

### **Reproduce:**

OS: Windows 10
IDE: Visual Studio 2019

Open the Package Manager Window in Visual Studio, end run the following command:

Install-Package Emgu.CV.runtime.windows -Version 4.5.1.4349

I do not get this error installing the Emgu.CV NuGet package (nor any other non emgu packages)

### **ERROR:**

Restoring packages for D:\Repos\OpenCV\OpenCVDemo\OpenCVDemo\OpenCVDemo.csproj...
  GET https://api.nuget.org/v3-flatcontainer/emgu.cv.runtime.windows/index.json
  OK https://api.nuget.org/v3-flatcontainer/emgu.cv.runtime.windows/index.json 838ms
  GET https://api.nuget.org/v3-flatcontainer/emgu.cv.runtime.windows/4.5.1.4349/emgu.cv.runtime.windows.4.5.1.4349.nupkg
  OK https://api.nuget.org/v3-flatcontainer/emgu.cv.runtime.windows/4.5.1.4349/emgu.cv.runtime.windows.4.5.1.4349.nupkg 15ms
  GET https://api.nuget.org/v3-flatcontainer/emgu.cv/index.json
  GET https://api.nuget.org/v3-flatcontainer/emgu.runtime.windows.msvc.rt.x86/index.json
  GET https://api.nuget.org/v3-flatcontainer/emgu.runtime.windows.msvc.rt.x64/index.json
  OK https://api.nuget.org/v3-flatcontainer/emgu.cv/index.json 767ms
  OK https://api.nuget.org/v3-flatcontainer/emgu.runtime.windows.msvc.rt.x86/index.json 2554ms
  GET https://api.nuget.org/v3-flatcontainer/emgu.runtime.windows.msvc.rt.x86/19.28.29336/emgu.runtime.windows.msvc.rt.x86.19.28.29336.nupkg
  OK https://api.nuget.org/v3-flatcontainer/emgu.runtime.windows.msvc.rt.x86/19.28.29336/emgu.runtime.windows.msvc.rt.x86.19.28.29336.nupkg 12ms
  OK https://api.nuget.org/v3-flatcontainer/emgu.runtime.windows.msvc.rt.x64/index.json 2776ms
Install-Package : Unable to load the service index for source 
https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.
At line:1 char:1
+ Install-Package Emgu.CV.runtime.windows -Version 4.5.1.4349
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageComman 
   d
 
Time Elapsed: 00:00:17.8779070

**Comment by emgucv** [comment]
Our nuget package do not have dependency on: 
https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json

You can check the package dependency on nuget.org:
https://www.nuget.org/packages/Emgu.CV.runtime.windows/

If you are still getting dependency issues, trying disabling all other nuget repository in Visual Studio, and only enable nuget.org repo.

**Comment by mekatrol** [comment]
Thank you for the response. I only reference nuget.org, but have tried again after updating Visual Studio and did not have the issue again (the install worked). Apologies for raising with you!
