### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by Afrrcyn** [emgucv/emgucv#457]
So I downloaded the latest build of Emgu.CV, Emgu.CV.Bitmap and Runtime.Windows, then I'm making an android application on Xamarin.Forms, I have a link to a jpg image within my cache, and I have a variable linking to this called newFile: ''folder\user\....\image.jpg'' when I then run the code:

`var newFile = Path.Combine(FileSystem.CacheDirectory, result.FileName);`
`using (var stream = await result.OpenReadAsync())`
`using (var newStream = File.OpenWrite(newFile))`
`       await stream.CopyToAsync(newStream);`

`Image<Bgr, byte> img = new Image<Bgr, byte>(newFile);`

I get this error:

>  | Name | Value | Type
> -- | -- | -- | --
> ◢ | $exception | {System.DllNotFoundException: cvextern assembly:<unknown assembly> type:<unknown type> member:(null)   > at (wrapper managed-to-native) Emgu.CV.CvInvoke.RedirectError(Emgu.CV.CvInvoke/CvErrorCallback,intptr,intptr) at  Emgu.CV.CvInvoke..cctor () [0x000db] in <e3cf65a62a7d43f391f26dd4bfeb9f34>:0 } | System.DllNotFoundException

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {System.DllNotFoundException: cvextern assembly:<unknown assembly> type:<unknown type> member:(null)   at (wrapper managed-to-native) Emgu.CV.CvInvoke.RedirectError(Emgu.CV.CvInvoke/CvErrorCallback,intptr,intptr)   at Emgu.CV.CvInvoke..cctor () [0x000db] in <e3cf65a62a7d43f391f26dd4bfeb9f34>:0 } | System.DllNotFoundException

**Comment by emgucv** [comment]
The Emgu.CV.runtime.windows is a "Windows" only runtime. 

To run Emgu CV programs on Android, you will need a runtime package for Android, it is available as part of the Emgu CV Professional (/Android) commercial release.

**Comment by Afrrcyn** [comment]
> The Emgu.CV.runtime.windows is a "Windows" only runtime.
> 
> To run Emgu CV programs on Android, you will need a runtime package for Android, it is available as part of the Emgu CV Professional (/Android) commercial release.

So If I get the license, how would I link it to my program such that it would work?

Thanks

**Comment by emgucv** [comment]
Instructions for setting up android project can be found here:

https://www.emgu.com/wiki/index.php/Download_And_Installation#Android
