### ISSUE TITLE
Xamarin.Android  Videocapture not found usb camera

### ISSUE THREAD

**Issue by llgzr** [emgucv/emgucv#459]
I'm developing a xamaring.android application but when I call Videocapture class it doesn't find the camera of the device. I've checked the camera permission.

**Comment by emgucv** [comment]
Open CV's VideoCapture class is not implemented on Android platform. You will need to use the native Android Camera to capture images from the on device camera in Android. You can check our Android demo in the release package for how this can be done.

Souce code can be found in the android commercial release package as well as here:
https://github.com/emgucv/emgucv/tree/master/Emgu.CV.Example/XamarinForms/Core/Android
