### ISSUE TITLE
Access violation when trying to use CvInvoke's CvtColor

### ISSUE THREAD

**Issue by mboekhold** [emgucv/emgucv#464]
Hello, i'm using EmguCV to capture and manipulate webcam frames.

I'm currently trying to manipulate the camera frames to grayscale. these frames are then forwarded where they will be displayed in a webrtc conference.

However I keep getting a System.AccessViolationException on the Mat object that i'm forwarding to use for the webrtc conference.

```csharp
private volatile object grabSync = new object();
        private void _localCamCapture_ImageGrabbed(object sender, EventArgs e)
        {
            if(Monitor.TryEnter(grabSync))
            {
                try
                {
                    Mat image = new Mat();
                    _localCamCapture.Retrieve(image);
                    Mat output = new Mat();
                    CvInvoke.CvtColor(image, output, Emgu.CV.CvEnum.ColorConversion.Bgr2Gray);

                    _frameQueue.Enqueue(output);
                    if (_videoStream != null)
                    {
                        _videoStream.SendToDataStream(output);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
        }
```

the exceptions occurs in the video stream class here

![image](https://user-images.githubusercontent.com/21144386/113292869-596eab80-92f5-11eb-977c-8269deb1b6f9.png)

This doesn't happen when I use this for example
```csharp
CvInvoke.BitWiseNot(image, output);
```

Any help or information would be greatly appreciated,

Thanks

**Comment by emgucv** [comment]
The code wasn't runable. Will you be able to produce the bug with a few lines of code that is self-contained?

**Comment by mboekhold** [comment]
Hi, after some debugging realised it was not a bug on emgu's side. thanks for the attention anyway :)
