### ISSUE TITLE
CvInvoke.UseOpenCL always false

### ISSUE THREAD

**Issue by luisrr1590** [emgucv/emgucv#465]
I'm trying to process an RTSP h.264 stream using OpenCL. So I made two versions of the code one using Image<Bgr, byte> and another using UMat and set CvInvoke.UseOpenCL = true.
Both versions run fine but CPU usage and times are the same for both versions, even with UMat the CPU usage ramps to 30% while the GPU stays at less than 1% (guessing not running in OpenCL). So I checked and while CvInvoke.HaveOpenCL and CvInvoke.HaveOpenClCompatibleGpu are both true CvInvoke.UseOpenCL is always false even if I change it.

*Using Nuget Emgu.CV 4.5.1.4349 and Emgu.CV.runtime.windows 4.5.1.4349

What am I doing wrong??? can someone help me??

**Comment by emgucv** [comment]
What OpenCL device are you using?

You can find out with this code below:
```
        private static String GetOpenCLInfo()
        {
            String openCLText = String.Format("Has OpenCL: {0}", CvInvoke.HaveOpenCL);

            String lineBreak = System.Environment.NewLine;
            if (CvInvoke.HaveOpenCL)
            {
                openCLText = String.Format("{0}{1}Use OpenCL: {2}{1}{3}{1}",
                    openCLText, lineBreak,
                    CvInvoke.UseOpenCL,
                    CvInvoke.OclGetPlatformsSummary());
            }

            return openCLText;
        }
```
On my workstation the output is:
```
Has OpenCL: True
Use OpenCL: True
Platform 0: NVIDIA CUDA
   Device 0 (Default): GeForce RTX 3070 1.2 (Gpu):Version - OpenCL 1.2 CUDA; Global memory - 8589934592; Local memory - 49152; Max image size - 32768x32768; DoubleFpConfig: Denorm, InfNan, RoundToNearest, RoundToZero, RoundToInf, Fma
```
CvInvoke.UseOpenCL is true when Emgu CV runtime is loaded.

**Comment by luisrr1590** [comment]
Thanks for answering (nice GPU by the way), I tested my code on two computers, one is a laptop and the other is a Desktop pc with an RX 580. Unfortunately I'm not near the desktop to test your code but at least in the laptop the output is:

Has OpenCL: True
Use OpenCL: False
Platform 0: Intel(R) OpenCL
   Device 0 :       Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz 2.1 (Cpu):Version - OpenCL 2.1 (Build 0); Global memory - 8499290112； Local memory - 32768; Max image size - 16384x16384; DoubleFpConfig: Denorm, InfNan, RoundToNearest, RoundToZero, RoundToInf, Fma 

Given that my only OpenCL device is the processor I would understand why in my laptop the processing is similar for both instances (even though Use OpenCL is still false). However in the case of my desktop the videocard is the default OpenCL device. I'll test your code and reply with the output.

**Comment by emgucv** [comment]
Right, on the laptop, given that the only OpenCL device is a CPU, it make sense for OpenCV to disable OpenCL for the laptop.

**Comment by luisrr1590** [comment]
I tested your code in my desktop pc with an RX 580 and the output is as follows:
Has OpenCL: True
Use OpenCL: True
Platform 0: AMD Accelerated Parallel Processing
   Device 0 (Default): Ellesmere 2.0 (Gpu):Version - OpenCL 2.0 AMD-APP (3188.4); Global memory - 8589934592; Local memory - 32768; Max image size - 16384x16384; DoubleFpConfig: Denorm, InfNan, RoundToNearest, RoundToZero, RoundToInf, Fma

However I still don't understand why my CPU usage ramps up to 30% while my GPU usage is only 1%. Shouldn't it be the other way around?

**Comment by luisrr1590** [comment]
haha it is actually using the GPU I double checked and turns out that GPU load in Task manager is only for 3D usage or at least that's what it looks like I checked with GPU-Z and every time I run the code the GPU clock ramps up as well as temperature, Power Draw and allocated memory. 
Didn't expect to see elevated CPU usage as well.
