### ISSUE TITLE
EmguCV 4.4.0 - VideoCapture not working on Android with ip camera

### ISSUE THREAD

**Issue by MssGpr75** [emgucv/emgucv#480]
I need to use VideoCapture on Android/iOS to get a MJPEG stream from a network camera.

This is my code:

```
string url = "http://user:password@172.31.254.120/axis-cgi/mjpg/video.cgi";
VideoCapture cap = new VideoCapture(url, VideoCapture.API.Any);
if( cap.IsOpened )
{
	... do stuff ...
}
```

This code works on Windows, instead on Android I get an unhandled exception:
OpenCV: CAP_IMAGES: can't find starting number (in the name of file): http://user:password@172.31.254.120/axis-cgi/mjpg/video.cgi'

I tried to append a dummy parameter "?1", the exception disappear but the VideoCapture object is not opened. I tried also with RTSP and Ffmpeg but same behavior.

Thank you for any comment.

**Comment by emgucv** [comment]
Open CV's VideoCapture class do not have implementation to decode network camera stream for Android / iOS.

**Comment by emgucv** [comment]
Closing ticket now.
