### ISSUE TITLE
missing libraries in Docker.

### ISSUE THREAD

**Issue by jupelag** [emgucv/emgucv#483]
Hi, im triying to dockerize my emgu proyect but i have a problem.
When I run muy app out of a docker it works correctly but when i dockerize it emgu can't load the Unmanaged libraries.

I depure my docker and the files exists but this emgu lines         [DllImport("Kernel32.dll", SetLastError = true)]
        private static extern IntPtr LoadPackagedLibrary(
            [MarshalAs(UnmanagedType.LPStr)]
            String fileName,
            int dwFlags);
returns 0x00000000 and emgu throws a missing libraries exception.

**Comment by emgucv** [comment]
Emgu CV's windows release is build with MSMF (Microsoft Media foundation) support for video IO. If you are using docker, please make sure  to install MediaFeaturePack similar to this Dockerfile here (The last 7 lines):
https://github.com/emgucv/docker/blob/master/vs2019_buildtools_cuda_openvino/Dockerfile

**Comment by emgucv** [comment]
Build your docker image based on 

`FROM mcr.microsoft.com/windows:10.0.18363.1500-amd64`

and install dotnet SDK, there is no need to install MSMF in this case. (it is included in the above image). Afterwards, you should be able to run Emgu CV in it.

We have added a demo that used our development docker image (with Visual Studio, CUDA, OpenVino etc) to run Emgu CV in docker:
https://github.com/emgucv/emgucv/tree/master/Emgu.CV.Example/Docker/Windows

Note that the image is big (~50GB), you will need to raised your default docker image size limit to use it.

**Comment by emgucv** [comment]
Closing ticket now.
