### ISSUE TITLE
FFMPEG Logging with NLog

### ISSUE THREAD

**Issue by luisrr1590** [emgucv/emgucv#494]
I know FFPMPEG logs to stderr....but is there a way to redirect this through EmguCV and capture the logs with NLog.
I cant find much information on this....any recommendation is welcome.

Thanks

**Comment by emgucv** [comment]
I am not sure if there is  any enviroment variable that can control where FFMPEG logs. You can probably ask the FFMPEG community to find out.

**Comment by emgucv** [comment]
Closing ticket now.
