### ISSUE TITLE
HistogramBox.GenerateHistogram()

### ISSUE THREAD

**Issue by ThunderChild-001** [emgucv/emgucv#500]
Currently experiencing problems with the HistogramBox class when upgrading from 4.1.1.
A call to GenerateHistogram() followed by Refresh() using the below code did display the histogram curve using ZedGraph.

HistogramBoxR.ClearHistogram();
HistogramBoxR.GenerateHistogram("Red Channel", Color.Red, m, 256, new float[] { 0f, 255f });
HistogramBoxR.Refresh();

When using the EMGU.CV Nuget package @ 4.1.1.3497 the code works.
For any version onwards the package when installed with the matching EMGU.CV.UI and EMGU.CV:Bitmap packages the 
HistogramBox just remains blank. The original OpenCV binaries also do not seem to be copied when using these later packages either? They have to be placed in the build manually.

Does anyone else have this problem?

Many thanks,
Karl

**Comment by emgucv** [comment]
For the latest 4.5.1 release, you will need to install one of the runtime libraries besides of Emgu.CV nuget package. e.g. 
https://www.nuget.org/packages/Emgu.CV.runtime.windows/

We have dropped ZedGraph as a dependency in version 4.3.0:
https://www.emgu.com/wiki/index.php/Version_History#Emgu.CV-4.3.0

The GenerateHistogram function **return** a drawing of the historgram in Mat, you need to add code to draw it on an ImageBox:
https://www.emgu.com/wiki/files/4.5.1/document/html/9d1a9c84-8d45-606f-206c-77478e4a491a.htm
e.g. 
`Mat hist = HistogramBoxR.GenerateHistogram("Red Channel", Color.Red, m, 256, new float[] { 0f, 255f });`

If you want to render the histogram directly on the HistogramBox, use this function instead:
https://www.emgu.com/wiki/files/4.5.1/document/html/eec7a6ed-1710-7841-daaf-bf6bd2744955.htm

**Comment by ThunderChild-001** [comment]
Thanks for the quick reply. I'm sure that I can display the histogram now.

As far as the runtime-library goes, I see that this Nuget package targets .NETStandard 2.0. We are using .NET Framework 7.0.
I know of a few ways of using both .NET Framework and .NET Core together but I would rather avoid this unless there is no other way. The solution is complicated enough ;-) If it is just used to add the opencv .dlls I would do this in another way.

**Comment by ThunderChild-001** [comment]
Very sorry,  I meant .Net Framework 4.7 and that when you try to install this runtime nuget package it fails with 4.7 projects saying that it does not target this framework.

I will add the required open cv files in another way.

Once again, thanks for the help.

**Comment by emgucv** [comment]
As long as you are using "PackageReference" and not "pacakge.config", the 4.5.1 runtime pacakges will install on .Net Framework 4.7. 

"package.config" is broken when resolving nuget package dependency. 

To upgrade from "package.config" to "PackageReference", see this for instruction:
https://github.com/emgucv/emgucv/issues/399#issuecomment-767571013

**Comment by ThunderChild-001** [comment]
That's perfect! He's installed and working.
Thanks again.
