### ISSUE TITLE
Add continuous code security analysis using GitHub CodeQL

### ISSUE THREAD

**Issue by aleks-ivanov** [emgucv/emgucv#501]
- [CodeQL](https://github.com/github/codeql) is an open source code scanning tool for discovering vulnerabilities across a codebase

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by emgucv** [comment]
Wow, that looks great. Thanks for the contribution. 

I am trying to make sure that Emgu CV is compatible with the CodeQL license ( https://securitylab.github.com/tools/codeql/license/ ). It wasn't quite clear if it is compatible with dual license software like Emgu CV (licensed under both GPL v3 and commercial license). GPL v3 is compatible with CodeQL based on the terms, I will need to make sure dual license is also ok with them.

Are you part of the CodeQL team or are you in touch with them? If not, I will try to sent them an email to make sure it is compatible with dual license software before merging the pull request.

**Comment by aleks-ivanov** [comment]
@emgucv our pleasure entirely 🙂 

If there is any way you think we can make the pipeline better, please don't hesitate to let us know.

[Pipeline Foundation](https://pipeline.foundation) is not affiliated with GitHub in any way, but we will try to provide assistance.

**Comment by emgucv** [comment]
I have asked the CodeQL team to make sure we can integrate CodeQL into our CI pipeline. I am concern about the codeql license term's compatibility with Emgu CV's license term (both OSI and commercial):
https://github.com/github/codeql/discussions/5886
