### ISSUE TITLE
Video Decode using GPU

### ISSUE THREAD

**Issue by coccoalberto97** [emgucv/emgucv#509]
Hello,
I'm trying to decode videos in real-time using VideoCapture but I'm not able to make it use my GPU, I have an RTX 4000 and I can potentially decode at 600 fps, I need this power so I can output 8 videos simultaneously using a Blackmagic card.
CudaInvoke.HasCuda is true, and FFmpeg is able to use hwaccel Cuda.

I can't use CudaVideoReader but this is related to #408 .

thanks in advance for your attention.

**Comment by coccoalberto97** [comment]
Hello,
thank you for replying, is there any eta for 4.5.2. release?

**Comment by emgucv** [comment]
We are working on it. Probably in the next two weeks but we can't gurantee.

**Comment by coccoalberto97** [comment]
Thank you for the fast replies, this project is amazing!
