### ISSUE TITLE
SolvePnPRefine got error with null distCoeffs

### ISSUE THREAD

**Issue by sdrest** [emgucv/emgucv#515]
It will cause System.AccessViolationException error when use SolvePnPRefineLM/SolvePnPRefineVVS with null distCoeffs.
And it works fine if it's with distCoeffs.
It should be fine by the note:
"If the vector is NULL/empty, the zero distortion coefficients are assumed."
I can use null distCoeffs when use SolvePnPRansac.

**Comment by emgucv** [comment]
Thanks for pointing that out. 

Should be fixed by this commit: 97a96ddd9c148253a475a6b779f66f10b6008221

**Comment by emgucv** [comment]
Closing ticket now. 

4.5.2 release is out with the fix included.
