### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.  ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WREpic** [emgucv/emgucv#517]
Any idea how to solve this issue?
I'm trying to deploy my project in an environment in Elastic Beanstalk AWS, Platform: Docker running on 64bit Amazon Linux/2.16.8
When I run the project locally in a windows machine, it works properly, bu in server I get this error:
System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
I already tried copying files directly in the project with "Copy always" property, but not luck.
This is my docker file:
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["ProcessingFaceDetection.Worker/ProcessingFaceDetection.Worker.csproj", "ProcessingFaceDetection.Worker/"]
RUN dotnet restore "ProcessingFaceDetection.Worker/ProcessingFaceDetection.Worker.csproj"
COPY . .
WORKDIR "/src/ProcessingFaceDetection.Worker"
RUN dotnet build "ProcessingFaceDetection.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProcessingFaceDetection.Worker.csproj" -c Release -o /app/publish

FROM base AS final
RUN apt-get update && apt-get install -y libgdiplus libc6-dev libx11-dev && ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProcessingFaceDetection.Worker.dll"]

I don't know what else to try.

**Comment by emgucv** [comment]
Are you using "Emgu.CV.runtime.windows" nuget package in your windows application? If that is the case, you can only deploy the project to Windows (or docker image based on windows). 

If you add "Emgu.CV.runtime.ubuntu.20.04-x64" nuget package to your project, you can deploy the package to Ubuntu 20.04 or docker images based on Ubuntu 20.04.
https://www.nuget.org/packages/Emgu.CV.runtime.ubuntu.20.04-x64/
You will need to call this script in your Dockerfile to make sure the dependency is installed:
https://github.com/emgucv/emgucv/blob/master/platforms/ubuntu/20.04/apt_install_dependency

We do not have a nuget package for AWS Linux - x64. However, your docker image seems to be based on generic Debian x64 (and not AWS Linux, which use "yum" for package management). You can try the above Ubuntu package, it may or may not work.

**Comment by emgucv** [comment]
Closing ticket now.
