### ISSUE TITLE
CvBlob

### ISSUE THREAD

**Issue by odalet** [emgucv/emgucv#518]
I'm in the process of migrating from emgucv 3 to emgucv 4.5. A large part of our code base makes use of blobs detection and at the same time, I'd like to target .NET Standard 2. I've read the release notes that state it was discarded in v4.3 because the code is not maintained anymore.

Anyway, is there a chance we'd have `CvBlob` and friends back?

**Comment by emgucv** [comment]
Sorry, CvBlob has been removed from Emgu CV. As mention in the release note, it has not been updated for a very long time and Open CV's Tracker is a very good replacement. Seem the sample code here:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/VideoSurveillance/VideoSurveillance.cs

**Comment by odalet** [comment]
Thanks for your reply.
I've had a look at the sample and I see how this could inspire us (the important function here is `FindContours`). However, in our code we also use the `Centroid` and the `Moments` properties that were part of `CvBlob`. Do you have any insight on how I could find (or compute) these properties based on the detected contour?

**Comment by 2r2d** [comment]
We use this method:
```
public static PointF GetCenterOfGravity(VectorOfPoint contour)
{
      var m = CvInvoke.Moments(contour);
      return new PointF((float) (m.M10 / m.M00), (float) (m.M01 / m.M00));
}
```
And please check https://docs.opencv.org/master/dd/d49/tutorial_py_contour_features.html and https://www.emgu.com/wiki/files/4.5.1/document/html/fff6604e-4f76-0dad-fbb7-b549b72e1b68.htm for other features.

**Comment by odalet** [comment]
@2r2d Thanks! That's exactly what I was looking for!
