### ISSUE TITLE
Mat gets garbage collected: Bitmap.ToMat() / Format1bppIndexed

### ISSUE THREAD

**Issue by 2r2d** [emgucv/emgucv#520]
When I convert [1bpp.tif](https://github.com/emgucv/emgucv/files/6615400/1bpp.zip) with `bitmap.ToMat()` the data became blank or an **System.AccessViolationException** is thrown.
With this code I can force the exception. The `bitmap`'s data is still fine. 

```
using (var bitmap = new Bitmap("C:\\Temp\\1bpp.tif"))
{
    using (var mat = bitmap.ToMat())
    {
        var a = CvInvoke.Mean(mat).V0;          // ok
        GC.Collect();
        var b = CvInvoke.Mean(mat).V0;          // System.AccessViolationException
    }
}
```

I've also tried `GC.KeepAlive(mat)` but makes no difference. The same code works fine for a 24-bit or a tiny 1-bit image with 1KB size. I need a conversion from Bitmap. As workaround `new Mat("C:\\Temp\\1bpp.tif", ImreadModes.Grayscale)` or `bitmap.ToImage<Gray, byte>().Mat` are working.

I see a different implementation between [ToMat()](https://github.com/emgucv/emgucv/blob/e543feb66c130ee691374762359e1275bd0db0d6/Emgu.CV.Platform/Emgu.CV.Bitmap/BitmapExtension.cs#L395) and [ToImage()](https://github.com/emgucv/emgucv/blob/e543feb66c130ee691374762359e1275bd0db0d6/Emgu.CV.Platform/Emgu.CV.Bitmap/BitmapExtension.cs#L576).
Maybe it's something related to [pinned objects](https://stackoverflow.com/questions/26927243/gc-behavior-when-pinning-an-object)?

Thanks for your help!

PS: 
In 4.1. a bitmap stayed locked after `new Image<Gray, byte>(bitmap)`. In 4.5. it's fixed.

**Comment by emgucv** [comment]
Can you also share the "1bpp.tif" file used for testing?

**Comment by 2r2d** [comment]
It's in the description as zipped file.

**Comment by 2r2d** [comment]
I guess the default image format case on line 439 will have this problem too (like the 1bpp format). In both cases the data is copied. For all other format the data is shared with the bitmap. The bitmap lives outside the method too. Everything is fine.

Please have a closer look at BitmapExtension.ToMat() [line 409/429/432](https://github.com/emgucv/emgucv/blob/e543feb66c130ee691374762359e1275bd0db0d6/Emgu.CV.Platform/Emgu.CV.Bitmap/BitmapExtension.cs#L409). It seems the local variable `imagedata` gets collected to early and it's address becomes invalid. Unfortunately I'm not familiar with pinned objects. 
```
Byte[,] imagedata = new byte[rows, cols];
..
GCHandle imageDataHandle = GCHandle.Alloc(imagedata, GCHandleType.Pinned);        
..
return new Mat(new int[] { rows, cols }, DepthType.Cv8U, imageDataHandle.AddrOfPinnedObject());
```

**Comment by emgucv** [comment]
You are right, thanks for pointing that out. Fixed in this commit:
https://github.com/emgucv/emgucv/commit/f5d26dc689296ed8e80d2da0c79d930dee772843

Tested with your code and no longer throw System.AccessViolationException. 

Will be included in the up coming 4.5.2 release.

**Comment by 2r2d** [comment]
Amazing! Thank you very much.

Probably you like to do the same change on this line 454 too: https://github.com/emgucv/emgucv/blob/e543feb66c130ee691374762359e1275bd0db0d6/Emgu.CV.Platform/Emgu.CV.Bitmap/BitmapExtension.cs#L454

**Comment by emgucv** [comment]
You are right. Fixed in this commit:

**Comment by 2r2d** [comment]
Thank you very much
