### ISSUE TITLE
NUnit: Unable to load DLL 'cvextern'

### ISSUE THREAD

**Issue by 2r2d** [emgucv/emgucv#521]
NuGet Emgu.CV.runtime.windows is installed but DLL's are not copied to \bin\. 
I've set TestRunner|Options|Platform to x86 and it works when I copy the DLL manually.

**Comment by giamuhammad** [comment]
Yes, always show
Failed to load cvextern.dll using default path
!!! Failed to load cvextern.dll.

**Comment by emgucv** [comment]
Is your NUnit test targeting .Net Framework, .Net Core or .Net 5?

**Comment by emgucv** [comment]
Which version of Emgu.CV.runtime.windows nuget package do you use?

**Comment by 2r2d** [comment]
Emgu.CV.runtime.windows 4.5.1.4349
.net Framework 4.8
NUnit 3.13.2
NUnit3TestAdapter 3.13 (3.17 is newest but does not work in VS2019)

**Comment by emgucv** [comment]
Tested to work quite well:

![image](https://user-images.githubusercontent.com/2035816/121363065-9910cf80-c904-11eb-9b2d-05e55e9777ce.png)

For .NetFramework, you need to make sure you are build target is either "x86" or "x64" and not "AnyCPU". 
I am talking about the build settting and not unit test setting:  

> I've set TestRunner|Options|Platform to x86

Not this, but the red circle in the above screen shot.

Your configuration should look like this:
![image](https://user-images.githubusercontent.com/2035816/121363746-37049a00-c905-11eb-90ae-3471d8a3cb2f.png)


For details see here for the explanation:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Targeting_.Net_Framework

**Comment by 2r2d** [comment]
Thanks a lot for your fast response! Your small example is working on my side.
I guess one problem was that I included Emgu.CV and Emgu.CV.runtime.windows too and maybe some other differences
