### ISSUE TITLE
System.DllNotFoundException on Ubuntu 20.04

### ISSUE THREAD

**Issue by Szpoti** [emgucv/emgucv#524]
How can this be resolved?

## How to reproduce
Either copy [this](https://github.com/Szpoti/EmguTest) repository and go to step 5 or reproduce manually:
1. Create a Console Application
2. Add the following NuGet Packages:
 - **Emgu.CV**
 - **Emgu.CV.runtime.windows**
 - **Emgu.CV.runtime.ubuntu.20.04-x64**
3. Insert [this](https://github.com/Szpoti/EmguTest/blob/main/Program.cs) code in the Program.cs
4. Publish your application as a self contained application:

`dotnet publish -c release -r ubuntu.20.04-x64`

5. Copy the project to ubuntu 
6. In ubuntu CLI, navigate to the publish folder

 `cd EmguTest/bin/Release/net5.0/ubuntu.20.04-x64/publish`

7. Provide execute permissions:

`chmod 777 ./EmguTestUbuntu`

8. Execute application and see the error

`./EmguTestUbuntu`

## Information
The application was created in _Visual Studio Community 2019 on Windows 10_.
The OS the code was executed on is a fresh _Ubuntu 20.04_ on _Oracle VM VirtualBox_ with dotnet and git installed.
## Logs
```
Started!
Unhandled exception. System.TypeInitializationException: The type initializer for 'ConsoleApp1.Program' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory
   at Emgu.Util.Toolbox.Dlopen(String dllname, Int32 mode)
   at Emgu.Util.Toolbox.LoadLibrary(String dllname)
   at Emgu.CV.CvInvoke.LoadUnmanagedModules(String loadDirectory, String[] unmanagedModules)
   at Emgu.CV.CvInvoke.DefaultLoadUnmanagedModules(String[] modules)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.cveVideoCaptureCreateFromDevice(Int32 index, API apiPreference)
   at Emgu.CV.VideoCapture..ctor(Int32 camIndex, API captureApi)
   at ConsoleApp1.Program..cctor() in E:\Vsprojects\EmguTestV2\EmguTestUbuntu\Program.cs:line 10
   --- End of inner exception stack trace ---
   at ConsoleApp1.Program.Main(String[] args) in E:\Vsprojects\EmguTestV2\EmguTestUbuntu\Program.cs:line 16
Aborted (core dumped)

```

**Comment by emgucv** [comment]
You can trouble shot by following this instruction:
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

It is quite likely your ubuntu installation do not have one of the dependency package installed:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Ubuntu_20.04_2
Here is the link to the script:
https://github.com/emgucv/emgucv/tree/master/platforms/ubuntu/20.04

**Comment by Szpoti** [comment]
Thank you, I was able to resolve the problem by indicating the missing dependencies with `ldd libcvextern.so` and installing them with `sudo apt-get install ...`
