### ISSUE TITLE
DetectorParameters not finding markers

### ISSUE THREAD

**Issue by benc1223** [emgucv/emgucv#525]
I'm running a net5.0 console app, x64 configuration using Emgu.CV version 4.5.1.4349. When trying to use DetectorParameters.GetDefault() method, I get the exit code -1073741819 (0xc0000005) 'Access Violation'. This happens when I try to detect an ArUco Marker on an image I have created. When running a unit test for this, I get the following message:

The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by benc1223** [comment]
We are also using the commercial license for our product and still get this issue.

**Comment by emgucv** [comment]
Thanks for pointing that out. A field is missing and has been added in this commit: c10d224964804626fcdab2a938f3419257304bee

Will be included in the up coming 4.5.2 release.

**Comment by benc1223** [comment]
Awesome! Thank you for looking into that! I'll give that a go once 4.5.2 is released.

**Comment by benc1223** [comment]
@emgucv We went ahead and rebuilt this code with the updated fix, but we still get the error message System.AccessViolationException. We cloned the repo, followed the build steps listed, and created a local package to use. We then looked inside of the dlls that we had created and confirmed that the updated code was there. After that, we manually swapped the dlls and ran a test from the command line and got the error message still.

**Comment by emgucv** [comment]
Our unit test here:
https://github.com/emgucv/emgucv/blob/b57c620f86e9b201780819d935132db334256fe5/Emgu.CV.Test/AutoTestVarious.cs#L3924
passed in "Release" mode compilation after commit c10d224964804626fcdab2a938f3419257304bee

It failed in "Release" mode before the commit c10d224964804626fcdab2a938f3419257304bee
