### ISSUE TITLE
[BUG] Deploying with .Net Core to linux Docker results in cvextern lib not found error

### ISSUE THREAD

**Issue by Webreaper** [emgucv/emgucv#544]
Building a simple solution for .Net 5 using EmguCV and deploying via Linux results in cvextern failing to load on a Synology OS (which is based on Ubuntu), it fails with a cvextern dependency failure.

I've created a sample project here:  https://github.com/Webreaper/EmguCVFaceSample

If you run the resulting docker image using:
```
docker run \
  --name emgusample \
  -v /volume1/dockerdata/emgusample:/config \
  -p 6360:6360 \
  -d \
  webreaper/emgusample:dev
```
you get the error:

```
  Exception: System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
    ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help 
   diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object f 
   file: No such file or directory
      at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
      at Emgu.CV.CvInvoke..cctor()
      --- End of inner exception stack trace ---
      at EmguCVSample.Program.Main(String[] args)
```

* OS: Synology Linux, running docker
* .Net 5.0
* CPU Architecture: x86_64
* Emgu CV package used: see source code

**Comment by emgucv** [comment]
If you are using docker with Liunx base image, you should use the package corresponding to the Linux distribution, regardless of which OS platform docker is running on. 

An example of running Emgu CV with docker image can be found here:
https://github.com/emgucv/emgucv/tree/master/Emgu.CV.Example/Docker/Ubuntu
The docker image is based on Ubuntu 20.04 x64 so it use Emgu.CV.runtime.ubuntu.20.04-x64 runtime package, even when you build the docker image on MacOS. Using a MacOS runtime inside a Linux based docker distribution will fail with the error you have pointed out.

**Comment by Webreaper** [comment]
I'm not using a runtime - ignore the comment in the readme. If you look at the csproj I have all the runtime included (since I'm building cross platform). And whilst I'm building the image on Macos, I'm using buildx and specifying Linux as the target, so it should be building a proper linux image.

I'll add github actions to explicitly build on a Linux runner if you think that'll help, but I'm not convinced that's the issue.

**Comment by Webreaper** [comment]
Okay, just to confirm my previous comment, I've added a github action to build the Docker image on a linux runner, and the resulting file has exactly the same issue. 

If you run the docker image on a linux host, does it work? If it does, then it's something to do with (or lacking from) Synology's Linux distro. If it doesn't work, then there's something missing from EmguCV's runtime packages. I note there used to be a bug where the runtime package didn't copy all the dependencies properly (can't find the link right now, but saw it on an SO question) - has this definitely been fixed now?

**Comment by emgucv** [comment]
I am not familiar with Synology Linux, it may have differenty dependency compares with Ubuntu-20.04 x64. 

You can debug the "System.TypeInitializationException" error following this instruction:
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException
e.g.
`LD_DEBUG=libs dotnet run`
to run the project and it will tell you the missing dependency on your docker image.

The demo docker project I posted 
https://github.com/emgucv/emgucv/tree/master/Emgu.CV.Example/Docker/Ubuntu
has been tested to work on both Ubnutu 20.04 and Windows 10 host.

**Comment by Webreaper** [comment]
I'll have a go at debugging, but I've had a friend with non-Synology Ubuntu 20.04 LTS test the container and he sees the same thing.

I'll see if I can figure out what's different between your samples and mine, but it seems like this should Just Work without me having to debug it, if the runtime libs are working as expected....

**Comment by emgucv** [comment]
The base docker image "emgu/bazel-android:dotnet-5.0-bazel-4.0" already has all the dependencies installed.

You can check the layers here and see the dependencies are installed:
https://hub.docker.com/layers/emgu/bazel-android/dotnet-5.0-bazel-4.0/images/sha256-6e62bd24b26ce11c130799a3d7afebeedef7fb7781d99511a18e316d597d60af?context=repo

The function call to "CvInvoke.BuildInformation" will load "libcvextern.so". If any dependency is missing, it will not be able to produce the expected output.

**Comment by Webreaper** [comment]
I've tried running my sample using the `emgu/bazel-android:dotnet-5.0-bazel-4.0` base image, but I get exactly the same issue (`The type initializer for 'Emgu.CV.CvInvoke' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies.`). I've tried it both with and without my built image calling 

```
RUN apt-get install -y build-essential libgtk-3-dev libgstreamer1.0-dev libavcodec-dev libswscale-dev libavformat-dev libdc1394-22-dev libv4l-dev cmake-curses-gui ocl-icd-dev freeglut3-dev libgeotiff-dev libusb-1.0-0-dev
```
So I'm really at a loss to understand what's going wrong here. The changes are committed to head of the sample project above. Could you try it? Or update your sample to include code to call the `CascadeClassifier` (as my source does) and confirm it works for you?

**Comment by Webreaper** [comment]
One last test - I took your emgu/ubuntu_demo and added it into my project, to build my own image of that ([webreaper/emgu_ubuntu_demo](https://hub.docker.com/repository/docker/webreaper/emgu_ubuntu_demo) which I then ran locally. It worked fine. 

So this demonstrates that your demo doesn't actually represent a test of Emgu in action (as I mentioned in an earlier comment) because it doesn't actually execute any code that forces cvextern.so to load. So it doesn't prove that ubunto deployment works for the EmguCV code.... :)

**Comment by emgucv** [comment]
In the Program.cs file that is in the docker demo.

This linke of code:
`System.Console.WriteLine(CvInvoke.BuildInformation);`
https://github.com/emgucv/emgucv/blob/4.5.2/Emgu.CV.Example/BuildInfo.NetCore.Console/Program.cs#L25

called this line of code:
`cveGetBuildInformation(bi);`
https://github.com/emgucv/emgucv/blob/4.5.2/Emgu.CV/PInvoke/CvInvokeCore.cs#L2387

which has an entry point defintiion of:

```
[DllImport(ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
private static extern void cveGetBuildInformation(IntPtr buildInformation);
```
https://github.com/emgucv/emgucv/blob/4.5.2/Emgu.CV/PInvoke/CvInvokeCore.cs#L2395

and "CvInvoke.ExternLibrary" is defined as "cvextern".

If "libcvextern.so" is not loaded, nothing will be printed out and there will be an exception. If you got the print out of the build information, "libcvextern.so" is loaded.

Have you follow the steps here to trouble shot your app running on ubuntu?
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

What is the output of the following command in your docker image when it throw the exception?
`LD_DEBUG=libs dotnet run`

**Comment by emgucv** [comment]
Btw, in the docker demo I posted:
https://github.com/emgucv/emgucv/tree/master/Emgu.CV.Example/Docker/Ubuntu

From a ubuntu 20.04 host, you build the "emgu/ubuntu_demo" docker image by calling the "build_docker" script. Then run the docker image by calling the "run_docker" script.

**Comment by Webreaper** [comment]
Okay, thanks. Well, it's promising that the cvextern load is working, as it just means I need to figure out what's different between the sample image and mine. Will keep digging!

**Comment by Webreaper** [comment]
Okay, I've run with LD_DEBUG and here's the output. I've no idea how to read it though - can you see any clues on what the problem is? :)

[LD_DEBUG.log](https://github.com/emgucv/emgucv/files/6842261/LD_DEBUG.log)

**Comment by Webreaper** [comment]
I think that's a red herring. The source is here: https://github.com/Webreaper/EmguCVFaceSample/blob/main/EmguCVSample/Program.cs
and you can see it has a Main(), and the log output from the EmguCVSample (attached) shows it's getting past 'Starting...', but crashes in the line:
```
     var img = CvInvoke.Imread(path); 
```

[emgucv.log](https://github.com/emgucv/emgucv/files/6842333/emgucv.log)

**Comment by emgucv** [comment]
> 
[docker.zip](https://github.com/emgucv/emgucv/files/6849172/docker.zip)

Unzip these 3 files into your repo, under "UbuntuSample/Ubuntu" folder, run
`build_docker`
follow by 
`run_docker`
on ubuntu 20.06 x64 docker host. Works without issues:

```
~/tmp/EmguCVFaceSample/UbuntuSample/Ubuntu$ ./run_docker
#!/usr/bin/bash -v

docker run emgu/ubuntu_demo
/emgu/emgu.csproj : warning NU1602: Emgu.CV.runtime.ubuntu.20.04-x64 4.5.1.4349 does not provide an inclusive lower bound for dependency Emgu.CV (> 4.5.1 && < 4.5.2). An approximate best match of Emgu.CV 4.5.1.4349 was resolved.
/emgu/emgu.csproj : warning NU1602: Emgu.CV.runtime.ubuntu.20.04-x64 4.5.1.4349 does not provide an inclusive lower bound for dependency Emgu.CV (> 4.5.1 && < 4.5.2). An approximate best match of Emgu.CV 4.5.1.4349 was resolved.
Starting....
Initialising face detector....
Initialising grayscale image....
Detecting faces....
Processing 4 faces...
Found face: 273 33 59 59
Found face: 197 28 73 73
Found face: 184 136 103 103
Found face: 288 143 137 137
Processing complete.


```

**Comment by Webreaper** [comment]
SUCCESS!

Okay, so this works. Now I just need to figure out:

a) What was causing it to break previously and 
b) What I need to do to make this work with my own base image (I can't use the emgu-android one for various reasons). 

But now I have a working baseline, I can figure that out myself, so you can close this ticket. 

Thanks for all your help, and all your patience.....

**Comment by emgucv** [comment]
Good to know. Closing ticket now.

**Comment by Webreaper** [comment]
So.... just in case you're interested, I tracked down the _exact_ thing that makes this work (or not) - and it's the base image. If I use:
```
   FROM ubuntu:20.04 as final
```
then it works fine. If I use any of the MSFT base images, like this:
```
    FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS final
```
then it fails with the `cvextern` dependency exception. I'm not sure what MSFT use for their base images, but clearly there's something important in it that's required for EmguCV to work... would be interesting to figure out what/why that is, so that EmguCV can be made to work regardless of the base image. 

But that's for another day....

**Comment by NkhilKajrekar** [comment]
[Dockerfile-my-app.txt](https://github.com/emgucv/emgucv/files/13415973/Dockerfile-my-app.txt)
we are getting System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable please let us know what to change in docker
