### ISSUE TITLE
Pedestrian Detection in CSharp Needs Update

### ISSUE THREAD

**Issue by gferrell** [emgucv/emgucv#560]
The "Pedestrian Detection in CSharp" example is out of date and is not compatible with the latest EMGU.
https://www.emgu.com/wiki/index.php/Pedestrian_Detection_in_CSharp

Windows

.NET Core 3.1

x86_64

4.5.3.4721

Using the provided code from the code gallery.  
using Emgu.CV.GPU;

There is no GPU namespace, so there are a lot of intellisense errors. 

There might be more issues, I haven't gotten past this issue.

**Comment by gferrell** [comment]
Can someone rework this example for EMGU v4.5?  I am considering purchasing, but need to run this demo, thanks.

**Comment by emgucv** [comment]
The render function will only render the Rectangle area if a pedestrian is detected. If no pedestrian is detected, the destination image will remains unchanged. e.g. If the output image is blank, it will remain blank if no pedestrina is detected.
