### ISSUE TITLE
Anisotropic diffusion filter

### ISSUE THREAD

**Issue by jeremejevs** [emgucv/emgucv#57]
Any chance of wrapping [this](https://github.com/opencv/opencv_contrib/pull/1176) in Emgu CV?

**Comment by emgucv** [comment]
Fixed in 7fa13a3d10bda9450cf70d45e18fd6b3f5503778 . 

Closing ticket now. 

Thanks for the suggestion.

**Comment by jeremejevs** [comment]
Thanks!
