### ISSUE TITLE
GrayCodePattern::getImagesForShadowMasks

### ISSUE THREAD

**Issue by ahyow** [emgucv/emgucv#575]
Hi, would like to ask will it be include  cv::structured_light::GrayCodePattern::getImagesForShadowMasks soon for EMGUcv? 

reference from https://docs.opencv.org/3.4/db/d56/tutorial_capture_graycode_pattern.html

Thanks in advance

**Comment by ahyow** [comment]
Sorry for additional but is there any example regarding the generate graycode pattern to decode graycode from

https://docs.opencv.org/3.4/dc/da9/tutorial_decode_graycode_pattern.html

**Comment by emgucv** [comment]
Thanks for pointing that out.

GetImagesForShadowMasks has been added in this commit:
https://github.com/emgucv/emgucv/commit/d2263ce9d37cd4703eb897c7bdf88e92a041adb9

**Comment by ahyow** [comment]
Thanks for you quick reply! Its very helpful im totally appreciate!

**Comment by ahyow** [comment]
Hi, i had tried initialize VectorOfVectorOfMat , but once i push any image in mat form to is, it show the error
System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

and the error is shown from vectorofvectorofmat.cs -> push->  VectorOfVectorOfMatPush(_ptr, value.Ptr);

**Comment by emgucv** [comment]
Thanks again for pointing that out. Fixed in this commit, also added a unit test for it:
https://github.com/emgucv/emgucv/commit/a190fb1f9f610a41d74874a1e7f2bb24e0510162

**Comment by ahyow** [comment]
Thank you so much for the reply.

May i ask is there any example images for the example Decode Gray Code 
https://docs.opencv.org/3.4/dc/da9/tutorial_decode_graycode_pattern.html

as i do exactly the same with all the images input but my disparity map is black

**Comment by emgucv** [comment]
no, we don't have the Emgu CV tutorial for decode graycode pattern.

**Comment by ahyow** [comment]
ok noted, thank so much for the reply!
