### ISSUE TITLE
Need help for using new version of EmguCV for playing video file.

### ISSUE THREAD

**Issue by zydjohnHotmail** [emgucv/emgucv#587]
Hello:
I am new to this repo., I want to write a simple C# winform project to play a MP4 video in my local drive.
I have searched around, but I found most of the examples are at least a few years old, and many things changed.
So, I have done the following:
1) I created one C# WinFroms App with Visual Studio 2019, targeting .NET 5.0 on Windows 10
2) I installed the following NUGET packages:
PM> Install-Package Emgu.CV -Version 4.5.3.4721
PM> Install-Package Emgu.CV.UI -Version 4.5.3.4721
PM> Install-Package Emgu.CV.runtime.windows -Version 4.5.3.4721
PM> Install-Package Emgu.CV.Bitmap -Version 4.5.3.4721
3) The following is my C# code:

using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.CV.CvEnum;
using Emgu.CV.Util;
using Emgu.Util;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace EmguCVUIPLayVideoForm
{
    public partial class Form1 : Form
    {
        public const string MP4_File = @"C:\Videos\1.mp4";

        private VideoCapture _capture;

        public Form1()
        {
            InitializeComponent();
        }

        private void ProcessFrame(object sender, EventArgs arg)
        {
            try
            {
                Framesno = _capture.GetCaptureProperty(Emgu.CV.CvEnum.CAP_PROP.CV_CAP_PROP_POS_FRAMES);
                frame = _capture.QueryFrame();
                if (frame != null)
                {
                    pictureBox1.Image = frame.ToBitmap();
                    if (cam == 0)
                    {
                        Video_seek.Value = (int)(Framesno);
                        double time_index = _capture.GetCaptureProperty(Emgu.CV.CvEnum.CAP_PROP.CV_CAP_PROP_POS_MSEC);
                        Time_Label.Text = "Time: " + TimeSpan.FromMilliseconds(time_index).ToString().Substring(0, 8);
                        double framenumber = _capture.GetCaptureProperty(Emgu.CV.CvEnum.CAP_PROP.CV_CAP_PROP_POS_FRAMES);
                        Frame_lbl.Text = "Frame: " + framenumber.ToString();
                        Thread.Sleep((int)(1000.0 / FrameRate));
                    }
                    if (cam == 1)
                    {
                        Frame_lbl.Text = "Frame: " + (webcam_frm_cnt++).ToString();
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message.ToString());
            }
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            try
            {
                _capture = null;
                _capture = new VideoCapture(MP4_File);
                button1.Text = "Stop";
                Application.Idle += ProcessFrame;
            }
            catch (NullReferenceException ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
    }
}

But my code didn’t get complied, as the old method:  _capture.GetCaptureProperty is gone.
What I can do to fix it?

By the way, I have done more testings before I ask questions here.
First, I downloaded libemgucv-windesktop-4.5.3.4721.zip, unzip it, then use Visual Studio 2019 to open the solution, I can compile the solution, but when I run it, I got at least the following 2 errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Emgu\emgucv-windesktop 4.5.3.4721\libs\Build\Emgu.CV.Platform.NetFramework\AnyCPU\Debug\Emgu.CV.Platform.NetFramework.dll' could not be found	Aruco	C:\Emgu\emgucv-windesktop 4.5.3.4721\Emgu.CV.Example\Aruco\CSC

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Emgu\emgucv-windesktop 4.5.3.4721\libs\Build\Emgu.CV.Platform.NetCore\AnyCPU\Debug\netcoreapp3.1\Emgu.CV.Platform.NetCore.dll' could not be found	TfInterop.NetCore	C:\Emgu\emgucv-windesktop 4.5.3.4721\Emgu.CV.Example\TFInterop\CSC	

Then, I also downloaded and run libemgucv-windesktop-4.5.3.4721.exe
And I can see the missing DLLs:
C:\>dir Emgu.CV.Platform.NetFramework.dll /s
 Volume in drive C has no label.
 Volume Serial Number is 8C0B-783A

 Directory of C:\Emgu\emgucv-windesktop 4.5.3.4721\libs

07/27/2021  06:49 PM           111,616 Emgu.CV.Platform.NetFramework.dll
               1 File(s)        111,616 bytes

C:\>dir Emgu.CV.Platform.NetFramework.dll /s
 Volume in drive C has no label.
 Volume Serial Number is 8C0B-783A

 Directory of C:\Emgu\emgucv-windesktop 4.5.3.4721\Emgu.CV.Platform\DotNet\Framework\obj\Debug

09/29/2021  02:28 PM           116,224 Emgu.CV.Platform.NetFramework.dll
               1 File(s)        116,224 bytes

 Directory of C:\Emgu\emgucv-windesktop 4.5.3.4721\libs

07/27/2021  06:49 PM           111,616 Emgu.CV.Platform.NetFramework.dll
               1 File(s)        111,616 bytes

C:\>dir Emgu.CV.Platform.NetCore.dll /s
 Volume in drive C has no label.
 Volume Serial Number is 8C0B-783A

 Directory of C:\Emgu\emgucv-windesktop 4.5.3.4721\Emgu.CV.Platform\DotNet\Core\obj\Debug\netcoreapp3.1

09/29/2021  02:28 PM            98,816 Emgu.CV.Platform.NetCore.dll
               1 File(s)         98,816 bytes

 Directory of C:\Emgu\emgucv-windesktop 4.5.3.4721\libs

07/27/2021  06:59 PM           106,912 Emgu.CV.Platform.NetCore.dll
               1 File(s)        106,912 bytes

But I can’t run the solution inside libemgucv-windesktop-4.5.3.4721.zip folder.

Please let me know if there is no _capture.GetCaptureProperty any more, then which method I can use to process frames?
I need recent program, for the new version of 4.5.3, as I believe the old version is different, but from Internet, I can only find old version examples.
Please advise,
Thanks,

**Comment by emgucv** [comment]
You can use VideoCapture.Get function (replace VideoCapture.GetCaptureProperty to be inline with the C++ implementation):
https://www.emgu.com/wiki/files/4.5.3/document/html/63e7ab7a-58c0-c90f-2bef-4b0c5c108853.htm

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  However, I think there are so many changes, no idea on how to do my job.
What I want to do is like this: I load/open one local MP4 file, and read each frame, then process each frame.  Process each frame is just show each frame in one picture box, show its image.  Then that is it, I don't need more feature for the time being.
However, I met the first difficult is:
This statment from previous version:         
Framesno = _capture.GetCaptureProperty(Emgu.CV.CvEnum.CAP_PROP.CV_CAP_PROP_POS_FRAMES);
For now:        
var Framesno = _capture.Get(CapProp.?);
I look though all the options listed by Visual Studio 2019 under CapProp.*, but I can't find anyone seems to be similar like: CV_CAP_PROP_POS_FRAMES.
If you have changed so many things, then publish a simple play video C# code is a must, right?
If you have time, please add in the document that play a local video file.
Or, if you can write some simple sample code here to answer my question is OK, it will also help others.  I am not the developer who knows how you change your code recently, all the code samples I found from internet is too old to be used with the new version!
Thanks,

**Comment by zydjohnHotmail** [comment]
I found the recent code example.
