### ISSUE TITLE
How to use the repo to do Python np.average in C#?

### ISSUE THREAD

**Issue by zydjohnHotmail** [emgucv/emgucv#594]
Hello:
I can use the Python code to find np.average for a mask, like this:

import numpy as np
import cv2

image = cv2.imread('C:/Images/1.jpg')
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
lower_blue = np.array([110,50,50])
upper_blue = np.array([130,255,255])
mask = cv2.inRange(img_hsv, lower_blue, upper_blue)
avg_mask = np.average(mask)
print (str(avg_mask))

In C#, I have the following code:
    public partial class Form1 : Form
    {
        public const string Image1_PNG_File = @"C:\Images\1.jpg";

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Mat orig = new(Image1_PNG_File, ImreadModes.Color);
            using Mat hsv = new();
            CvInvoke.CvtColor(orig, hsv, ColorConversion.Bgr2Hsv);
            Mat mask = new();
            ScalarArray lower_blue = new(new MCvScalar(110, 50, 50));
            ScalarArray upper_blue = new(new MCvScalar(130, 255, 255));
            CvInvoke.InRange(hsv, lower_blue, upper_blue, mask);
            Mat[] channels = mask.Split();
            RangeF H = channels[0].GetValueRange();
            RangeF S = channels[1].GetValueRange();
            RangeF V = channels[2].GetValueRange();
            MCvScalar mean = CvInvoke.Mean(hsv);
            var avg_mask = ?
        }
}

But I can’t figure out how to calculate the NP.Average(mask) as in Python code, please advise!
Thanks,

**Comment by emgucv** [comment]
Use `MCvScalar maskMean = CvInvoke.Mean(mask);`

**Comment by zydjohnHotmail** [comment]
Thanks, it works!
