### ISSUE TITLE
Emgu.CV Bitmap property missing from .net standard 2.0

### ISSUE THREAD

**Issue by SerendipitousTesselation** [emgucv/emgucv#598]
Hello,

I'm upgrading a class library project from .NetFramework 4 to .Net5. The library depends on Emgu.CV. So, I've installed Emgu.CV and Emgu.CV.UI from Nuget but the project fails to compile.

It fails because it is referencing a Bitmap property from the Emgu.CV.Image class as well as a constructor that accepts a Bitmap that is no longer there. I'm guessing the API has changed and my class library needs to change accordingly.  I'm looking for advice on where to look for the Bitmap related functions.

Thanks

**Comment by SerendipitousTesselation** [comment]
As soon as I raised the issue I discovered the Emgu.CV.Btimap package and BitmapExtension class. Problem solved.

**Comment by emgucv** [comment]
Good to know. Yes, the Bitmap related functions are in the Emgu.CV.Bitmap nuget package. Closing ticket now.
