### ISSUE TITLE
?

### ISSUE THREAD

**Issue by djarik** [emgucv/emgucv#6]
Hello! It is impossible to compile! Whether could lay out you on sourceforge.net all of library (x86, x64 Windows).

**Comment by emgucv** [comment]
Hi, are you not able to compile the release package or not able to compile from Git repo?
What are the compilation errors?
FYI, we did test compilation of our release packages before they are uploaded to sourceforge.

**Comment by djarik** [comment]
Lay out please release dll opencv 3.2 and Emgu with Contrib. Cmake doesn't build projects for VS2010

**Comment by emgucv** [comment]
I am able to build the git repo from source code using the instructions here:
http://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git

What errors do you have during the configuration and compilation steps?

**Comment by emgucv** [comment]
I am assuming you are trying to build from the Git repo because you mention CMake.
FYI, CMake is used to configure the VS project, but you will need to use Visual Studio to compile it.

**Comment by jbraun27** [comment]
In the link to the wiki above, there are 2 minor fixes: Emgu.CV.sln is in the Solution/Windows.Desktop folder, and the cvextern project is in the emgu folder. Building cvextern should have 103 successful builds... and it does.  I'm just getting started with this. Great work guys!

**Comment by emgucv** [comment]
Thanks for pointing that out. The wiki has been updated.
