### ISSUE TITLE
VideoWriter memory leak

### ISSUE THREAD

**Issue by marianvoicu2002** [emgucv/emgucv#60]
I use Emgu Cv 3.1.0.1 and there is a memory leak on VideoWriter class, if you take 30 frames of 10 seconds the memory are incise.

using (var fileVideo = intCaptureCompresion == -1
                        ? new VideoWriter(strPathFileVideo, fps, new Size(height, width), true)
                        : new VideoWriter(strPathFileVideo, intCaptureCompresion, fps, new Size(height, width), true))               {   
						int i = 0;
						do
                        {
                            var mat = _capture.QueryFrame();
							fileVideo.Write(mat);
							i ++;
                        } while (i < 30 * 10);// 30 fps - 10 seconds
                    }

**Comment by marianvoicu2002** [comment]
I think must be wait after Queryframe, if I wait I saw everything is ok, the timer is 1000/fps.

**Comment by berndb5** [comment]
You should dispose the created mat ...
The best way would be to use "using":

```
using (var mat = _capture.QueryFrame()){
  fileVideo.Write(mat);
}

```

**Comment by marianvoicu2002** [comment]
Thank you for response! Of coarse I forgot to copy dispose. I think is my mistake, I will back with the results...

**Comment by marianvoicu2002** [comment]
I can confirm, after query a frame you should wait 1000/fps milliseconds, if not the memory are increase, so there in not an issue!
