### ISSUE TITLE
Parameter not valid

### ISSUE THREAD

**Issue by bhrigwish** [emgucv/emgucv#61]
I need immediate assistance.
I am using Emgu Cv 3.1

![exception](https://user-images.githubusercontent.com/31668594/30983961-9469f82c-a4a9-11e7-87b0-cd8f62ba170f.png)

**Comment by rold2007** [comment]
If you need immediate assistance, better call 9-1-1.

From your screenshot it is impossible to even know the type of your imgSurveillance variable. Tell us what you have tried. What is the value of clone, is it null ?

**Comment by marianvoicu2002** [comment]
Do you want to convert a Mat to Bitmap? Try use clone.Bitmap for that. Or convert Mat to image using GetBytes

**Comment by emgucv** [comment]
Closing ticket now.
