### ISSUE TITLE
Unable to load DLL 'cvextern' or one of its dependencies in Docker Windows container 

### ISSUE THREAD

**Issue by kumartest1981** [emgucv/emgucv#612]
Hi,
We are getting the following error when trying to call Emgu.CV.VideoCapture within Docker Windows container. Can you please help us to resolve this issue?

**Exception:** 
System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
---> System.DllNotFoundException: Unable to load DLL 'cvextern' or one of its
ependencies: The specified module could not be found. (0x8007007E)
at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userd
ta, IntPtr prevUserdata) at Emgu.CV.CvInvoke..cctor()

**Emgucv version :** 4.5.1.4349

The following dlls are present in the runtimes\win-x64\native\ directory

concrt140.dll
cvextern.dll
Microsoft.Data.SqlClient.SNI.dll
msvcp140.dll
msvcp140_1.dll
msvcp140_2.dll
msvcp140.dll
msvcp140_1.dll
msvcp140_2.dll
msvcp140_atomic_wait.dll
msvcp140_codecvt_ids.dll
opencv_videoio_ffmpeg451_64.dll
vccorlib140.dll
vcruntime140.dll
vcruntime140_1.dll

**Docker file**
FROM mcr.microsoft.com/dotnet/aspnet:5.0
COPY testproj/bin/Release/net5.0/publish/ App/
WORKDIR App/
ENTRYPOINT ["dotnet", "testproj.dll"]

**Comment by emgucv** [comment]
Closing ticket now.
