### ISSUE TITLE
EMGU CV v3.4.3 with CUDA toolkit 11.4 & compute capability 8.6

### ISSUE THREAD

**Issue by WeiMing-Chai** [emgucv/emgucv#616]
I am trying to use emgucv of version 3.4.3 with cuda 11.4 on a device with compute capability of 8.6, but apparently this is not supported as shown in the following script:

https://github.com/emgucv/emgucv/blob/EMGUCV_3_4_3/platforms/windows/Build_Binary_x86.bat#:~:text=IF%20NOT%20%22%259,GOTO%20END_GPU_ARCH_BIN

For some reason, I need to keep using emgucv version 3.4.3 for the time being, so is it feasible if I add a new line 
`IF "%CUDA_SDK_DIR%" == "%CUDA_PATH_V11_4%" SET CUDA_ARCH_BIN_OPTION="8.6"`
and recompile it using cmake as discussed in #578

**Comment by emgucv** [comment]
Closing ticket now.
