### ISSUE TITLE
Raspberry Pi4 is giving exception when the image capture code runs

### ISSUE THREAD

**Issue by kodithuwa** [emgucv/emgucv#622]
Hi, 
I m new to emgucv, I have try to capture image using below code, the code is working fine in windows 10, but when i send it to raspberry pi 4 board, which is giving below error. i have try to figure out this, but still giving same issue, how can i resolve this?

namespace Raspberry.ImageCapture
{
    using Emgu.CV;
    using System;
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                for (int i = 0; i < 10; i++)
                {
                    var filename = $"{Guid.NewGuid()}.jpg";
                    using var capture = new VideoCapture(0, VideoCapture.API.DShow);
                    var image = capture.QueryFrame(); //take a picture
                    image.Save(filename);
                }
            }
            catch(Exception ex)
            {
                System.Console.WriteLine($"Error Start {ex.Message} Error End");
            }
        }
    }
}

Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.Util.VectorOfInt' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object f                                  ile: No such file or directory
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.Init()
   at Emgu.CV.Util.VectorOfInt..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.VideoCapture.ConvertCaptureProperties(Tuple`2[] captureProperties)
   at Emgu.CV.VideoCapture..ctor(Int32 camIndex, API captureApi, Tuple`2[] captureProperties)

**Comment by emgucv** [comment]
Are you using nuget package? Did you reference Emgu.CV.runtime.linux-arm nuget package:
https://www.nuget.org/packages/Emgu.CV.runtime.linux-arm/
Which version of the nuget package do you use?

**Comment by DatBear** [comment]
I'm having the same issue. To add some more info, I'm using Emgu.CV, Emgu.CV.Bitmap, and  Emgu.CV.runtime.linux-arm, all on v4.5.4.4788. Adding Emgu.CV.runtime.windows makes it run fine on windows, but the same thing on the raspberry pi gives this DllNotFoundException:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.Util.VectorOfInt' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.Init()
   at Emgu.CV.Util.VectorOfInt..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.VideoCapture.ConvertCaptureProperties(Tuple`2[] captureProperties)
   at Emgu.CV.VideoCapture..ctor(Int32 camIndex, API captureApi, Tuple`2[] captureProperties)
```

Running ` ldd libcvextern.so | grep "not found"` gives this from a fresh raspbian install:
```
libgeotiff.so.2 => not found
libdc1394.so.22 => not found
libOpenGL.so.0 => not found
```

`uname -a` gives me `Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux`

**Comment by emgucv** [comment]
Thanks for the detail information. Closing ticket now.
