### ISSUE TITLE
Build EmguCV source Max OS x

### ISSUE THREAD

**Issue by amdlopes** [emgucv/emgucv#63]
I have:

- Mac OS X Sierra 10.12.6 (16G29)
- Mono JIT compiler version 5.2.0.224 (d15-3/14f2c81 Thu Aug 24 10:33:52 EDT 2017)
- cmake version 3.4.3
- Xcode 9.0 (9A235)
- XS 6.3 (build 864)
- Xamarin.Android Version: 7.4.5.1 (Xamarin Studio Community)
- Xamarin.iOS Version: 11.0.0.0 (Xamarin Studio Community)
- Xamarin.Mac - Xamarin.Mac not installed .

I want to build from source. I checked out most recent master.

After building vtk and opencv (which takes a while) and when it starts to build EmguCV:

[100%] Built target cvextern
Scanning dependencies of target cvextern_test
[100%] Building CXX object tests/cvextern_test/CMakeFiles/cvextern_test.dir/cvextern_test.cpp.o
[100%] Linking CXX executable ../../bin/osx/cvextern_test
[100%] Built target cvextern_test
Scanning dependencies of target Emgu.CV.World
Building Emgu.CV.World
Microsoft (R) Build Engine version 15.3.0.0 (d15.3/17f02c2 Thu Jul 20 17:17:06 EDT 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 09/10/2017 17:42:09.
Project "/Users/antoniolopes/Documents/emgucv/Emgu.CV.World/Emgu.CV.World.Mac.csproj" on node 1 (Build target(s)).
/Users/antoniolopes/Documents/emgucv/Emgu.CV.World/Emgu.CV.World.Mac.csproj(54,11): error MSB4226: The imported project "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/xbuild/Xamarin/Mac/Xamarin.Mac.ObjcBinding.CSharp.targets" was not found. Also, tried to find "Xamarin/Mac/Xamarin.Mac.ObjcBinding.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "/Library/Frameworks/Mono.framework/External/xbuild/" . These search paths are defined in "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/MSBuild.dll.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
Done Building Project "/Users/antoniolopes/Documents/emgucv/Emgu.CV.World/Emgu.CV.World.Mac.csproj" (Build target(s)) -- FAILED.

Build FAILED.

"/Users/antoniolopes/Documents/emgucv/Emgu.CV.World/Emgu.CV.World.Mac.csproj" (Build target) (1) ->
  /Users/antoniolopes/Documents/emgucv/Emgu.CV.World/Emgu.CV.World.Mac.csproj(54,11): error MSB4226: The imported project "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/xbuild/Xamarin/Mac/Xamarin.Mac.ObjcBinding.CSharp.targets" was not found. Also, tried to find "Xamarin/Mac/Xamarin.Mac.ObjcBinding.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "/Library/Frameworks/Mono.framework/External/xbuild/" . These search paths are defined in "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/MSBuild.dll.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.54
make[2]: *** [Emgu.CV.World] Error 1
make[1]: *** [Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/all] Error 2
make: *** [all] Error 2

I don't want to commit to another build attempt so it would be nice if you could help me understand why it doesn't build.

**Comment by emgucv** [comment]
There error is due to:

> Xamarin.Mac - Xamarin.Mac not installed .

**Comment by amdlopes** [comment]
Thanks. I'll retry.

But if Xamarin (and specially Xamarin.Mac) is required for build shouldn't that be in the list of the requirements of "Building from source"? All listed there is Mono and Cmake...

**Comment by amdlopes** [comment]
This was indeed the issue.

Now i can build from source.

Im happy to close the issue.

**Comment by AdithyaVenkateshMohan** [comment]
hi can give me detailed steps on how you solved it
