### ISSUE TITLE
Missing DLLs when building class library[BUG]

### ISSUE THREAD

**Issue by illiteratePhD** [emgucv/emgucv#647]
**Describe the bug**
Different DLLs are added to bin directory when building class library and when building application. This causes issues when compiling nuget packages and for unit test projects because the necessary DLLs are missing, leading to e.g. cvextern errors. 

Problem arose when migrating from 3.4 to 4.5.4. We are hoping that this is something that can be solved through configuration and not require manual copying of DLLs as that is an error prone approach. 

** OS / Platform **
Windows 10 Pro (19043)

** .Net version **
Framework 4.7.2

**CPU Architecture**
x64

** Emgu CV package used**
CV, CV.runtime.windows, CV.UI (4.5.4.4788)

**To Reproduce**
Solution with class library and application project. Application project depends on class library. Class library depend on the three Emgu packages listed above. Once built the following DLLs are present in the class library bin:

- Emgu.CV.Bitmap.dll
- Emgu.CV.Platform.NetFramework.dll
- Emgu.CV.Platform.NetStandard.dll

Whereas in the application bin the following libraries are present:

- concrt140.dll
- cvextern.dll
- Emgu.CV.Bitmap.dll
- Emgu.CV.Platform.NetFramework.dll
- Emgu.CV.Platform.NetStandard.dll
- opencv_videoio_ffmpeg454_64.dll
- ...and more.

**Expected behavior**
All DLLs relevant to run Emgu functions should be found in the Class Library bin folder.

**Screenshots**

**Additional context**

**Comment by emgucv** [comment]
It may be easier to use the nuget package, which will deploy both the managed and native binary into the correct location:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Nuget

If you have a class library and an application project, you should reference the nuget packages as follows:

MyLibrary -> Add Reference to "Emgu.CV" nuget pacakge
MyWindowsApp -> Add Reference to "MyLibrary" and "Emgu.CV.runtime.windows" nuget pacakge
MyMacApp -> Add Reference to "MyLibrary" and "Emgu.CV.runtime.mac" nuget pacakge
MyAndroidApp -> Add Reference to "MyLibrary" and "Emgu.CV.runtime.android" nuget package
MyIOSApp -> Add Reference to "MyLibrary" and "Emgu.CV.runtime.ios" nuget package

**Comment by Trueber** [comment]
Hello
I have a very similar issue:
On unit test projects (nunit), the cvextern.dll is not included in the build output, however it is included in the build output of winexe projects.
This leads to tests failing with `Unable to load DLL 'cvextern': The specified module could not be found`.
If i manually copy the dll, the tests work.

** OS / Platform **
Windows 10 Enterprise (19041)

**.Net version**
Framework 4.7.2

CPU Architecture
x64

** Emgu CV package used** 
All  4.5.4.4788 and installed with nuget
Emgu.CV
Emgu.CV.runtime.windows
Emgu.CV.UI
Emgu.CV.Bitmap

As a workaround, I downgraded to 4.3.0.3890, but this can not be a long term solution...

**Comment by emgucv** [comment]
Given that you are targetting .Net Framework 4.7.2, can you double check the following?

1. You are targeting "x64" architecture when running UnitTest. 
2. In the "Configuration Manager", for "x64" solution configuration, the unit test is compiled to target "x64" (instead of "AnyCPU").

Detail explanation can be found here:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Targeting_.Net_Framework

We just tested with a UnitTest targeting .NetFramework 4.7.2, using Emgu.CV.runtime.windows (v4.5.4.4788) nuget package from nuget.org, on Windows 11 Professional, having a Solution target of "x64" and the project target of "x64" in configuration manager. "cvextern.dll" is copied over to the same folder as the executable. The Unit Test work without any issues.

**Comment by Trueber** [comment]
I found the solution:
I was specifying the Platform and RuntimeIdentifier in a solution-global Directory.Build.props, so everything was building to x64. However, I was specifying `<Platforms>x64</Platforms>
    <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>` (plural) instead of the singular `<Platform>x64</Platform>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>`, now it works as expected.

Thank you for your efforts!

**Comment by emgucv** [comment]
Good to know. Closing ticket now.
