### ISSUE TITLE
Question: How do i find multiple same objects in a single image?

### ISSUE THREAD

**Issue by Whatareyoulaughingat** [emgucv/emgucv#648]
Hello!

I am new to EmguCV and i would like to know how to find multiple same objects in a single image. I have some experience with the OpenCvSharp library but i couldn't figure out how to make the thing im asking for to work. Is it possible to do that in this particular library and if yes, how can it be implemented?

**Comment by emgucv** [comment]
Dependents on if you are looking to identify the same class of object (use MobileNet/Yolo/MaskRcnn with DNN module):
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Models/Dnn/Yolo.cs

Or if you are looking to find the exact same image patterns (use feature extraction and matching): https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/XamarinForms/Core/DrawMatches.cs 

There are demo programs on the ".zip" release package, you can download, unzip, open the solution under "Solution" folder, compile, run the programs and give it a spin.

**Comment by emgucv** [comment]
Not bug here, you should create this ticket under "discussions" instead of "issues".

**Comment by Whatareyoulaughingat** [comment]
Okay i'll post it there. Thanks for giving me some advice by the way.
