### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dommy1C** [emgucv/emgucv#649]
**Describe the bug**
Building so file gives multiple errors.

** OS / Platform **
Raspberry Pi 4

** .Net version **
Net 6

**CPU Architecture**
ARMx86

** Emgu CV package used**
nuget package from nuget.org, Git commit bf999b39fcd0a0bb6a78c35772cc1493ef3c011a

**To Reproduce**
sudo apt-get -y install build-essential cmake pkg-config
sudo apt -y install git
sudo git clone https://github.com/emgucv/emgucv emgucv 
cd emgucv
sudo git submodule -y update --init --recursive
cd platforms
cd raspberry_pi_os
sudo ./apt_install_dependency
sudo ./cmake_configure

**Expected behavior**
so files created

**Screenshots**
![image](https://user-images.githubusercontent.com/7067386/141316990-d204dacc-5532-4cdd-bf4a-844045af2001.png)

**Additional context**
Log file
[CMakeOutput.log](https://github.com/emgucv/emgucv/files/7521161/CMakeOutput.log)

**Comment by emgucv** [comment]
The error says emgucv/opencv does not contains a CMakeLists.txt file.

Check after the "git submodule update --init --recursive" call and make sure the "emgucv/opencv" folder is not empty. If the source code are correctly checked out and submodules are initialized, there should be a "CMakeLists.txt" file under "emgucv/opencv" folder.

**Comment by emgucv** [comment]
Closing ticket now.
