### ISSUE TITLE
Question regarding push_back by vectorofpoint

### ISSUE THREAD

**Issue by ahyow** [emgucv/emgucv#652]
Hi, Sorry for asking again but need your help on this!

![image](https://user-images.githubusercontent.com/45448398/142134455-ed68c541-6c21-410f-abd0-70bef7da56d5.png)
From opencv_contrib/modules/structured_light/src/graycodepattern.cpp, the "camsPixels" which is type of VectorofVectorofPoint, it able to push_back after get the index  like below:
 **camsPixels[k][projPixel.x * params.height + projPixel.y].push_back( Point( i, j ) );** 
 
 However, i am unable to call the push function after initialize the index
 
![image](https://user-images.githubusercontent.com/45448398/142134612-f55245f5-5221-4174-b523-7726b1456f01.png)
 
 
 Can u suggest me how can i make it??
 
**My end goal is just want the camsPixels.

**Comment by emgucv** [comment]
You can construct "camPixels2" as a managed 2D array "Point[][]". 

The you can use the VectorOfVectorOfPoint constructor that accepts "Point[][]" to convert the 2d point array into native vector of vectors:
https://www.emgu.com/wiki/files/4.5.4/document/html/M_Emgu_CV_Util_VectorOfVectorOfPoint__ctor_2.htm

**Comment by emgucv** [comment]
Closing ticket now.
