### ISSUE TITLE
CameraCalibration namespace is missing ?

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [emgucv/emgucv#658]
**Describe the bug**
I was trying to implement CameraCalibration however the namespace is missing???

** OS / Platform **
Windows.

** .Net version **
.Net Core 5

**CPU Architecture**
x86_64

** Emgu CV package used**
Emgu.CV, Emgu.CV.Bitmap, Emgu.CV.runtime.windows (4.5.4.4788)

**To Reproduce**
namespace is not shown while using intellisense

**Expected behavior**
Namespace available for use

**Screenshots**

**Additional context**

**Comment by emgucv** [comment]
Camera calibration is handle by the CvInvoke.CalibrateCamera function in Emgu CV:
https://www.emgu.com/wiki/files/4.5.4/document/html/Overload_Emgu_CV_CvInvoke_CalibrateCamera.htm

The corresponding opencv function can be found here:
https://docs.opencv.org/4.5.4/d9/d0c/group__calib3d.html#ga3207604e4b1a1758aa66acb6ed5aa65d

There is no dedicated "CameraCalibration" namespace in Open CV or Emgu CV in the 4.5.4 release.

**Comment by martienpoels-bank2loyalty** [comment]
Thanks, that helps. Sorry for the misunderstanding. 

Cheers!
