### ISSUE TITLE
Linking EMGU.CV.UI.dll

### ISSUE THREAD

**Issue by wentata** [emgucv/emgucv#659]
Hi writer, may I know how to retrieve EMGU.CV.UI.dll from the release folder?
I have try several method but still not manage to get the file to involve in my C# project
![image](https://user-images.githubusercontent.com/30208646/143152701-44769ef1-321f-4c50-82ad-7b2b6b2a5a51.png)

**Comment by emgucv** [comment]
Thanks for pointing that out. The documentaion is out-dated. We have updated it now:
https://www.emgu.com/wiki/index.php/Download_And_Installation#GUI

If adding dlls from release package:
- For .Net Framework, add Emgu.CV.Platform.NetFramework.dll to References
- For .Net 3.1+, add Emgu.CV.Platform.NetCore.dll to References

**Comment by wentata** [comment]
thanks for the guide :)
