### ISSUE TITLE
using emgucv in a .NET 4.6.1 project

### ISSUE THREAD

**Issue by cguelcue** [emgucv/emgucv#66]
when building my code using targetframework 4.6.1 instead of for instance 3.5 calling CvInvoke.Canny results in a Crash of my application (no exception), any suggestions how to make it work? the solution's interfaces I have to reference to have target Framework 4.6.1

**Comment by marianvoicu2002** [comment]
Hello, Please check if you have VC++ redistributable package installed. For example Emgu 3.2 version use VC++ 2015 and 3.1 version need VC++ 2013. What OS did you use?

**Comment by cguelcue** [comment]
Hi,

Ok, will check that, we use windows 10 Pro

Best regards,

Von: marianvoicu2002 [mailto:notifications@github.com]
Gesendet: Montag, 16. Oktober 2017 20:18
An: emgucv/emgucv <emgucv@noreply.github.com>
Cc: Christiane Gülcü Senmicro <christiane.guelcue@senmicro.biz>; Author <author@noreply.github.com>
Betreff: Re: [emgucv/emgucv] using emgucv in a .NET 4.6.1 project (#66)


Hello, Please check if you have VC++ redistributable package installed. For example Emgu 3.2 version use VC++ 2015 and 3.1 version need VC++ 2013. What OS did you use?

**Comment by emgucv** [comment]
Closing ticket now.
