### ISSUE TITLE
how to use cv.dnn_superres in emgucv 

### ISSUE THREAD

**Issue by iwaitu** [emgucv/emgucv#667]
I can not found any infomatin about cv.dnn_superres , need some help plz.

**Comment by emgucv** [comment]
It is not exposed in 4.5.4 release. It was marked as internal but has since be made public in this commit:
38e01551e8bdf2de7a4df5ec3ee53d959fc2f16b

In the next release it will be public accessible.

**Comment by emgucv** [comment]
It is avilable in the 4.5.5 release
https://www.emgu.com/wiki/files/4.5.5/document/html/T_Emgu_CV_DnnSuperres_DnnSuperResImpl.htm

Closing ticket now.
