### ISSUE TITLE
[BUG] I cannot find the Traffic Sign Detection in CSharp example

### ISSUE THREAD

**Issue by jarnoburger** [emgucv/emgucv#668]
Where is it ?

**Comment by emgucv** [comment]
In the ".zip" release package, open the visual studio solution from the "Solution" folder, in the Xamarin Forms demo, you can test out traffic sign detection. The demo use Mask RCNN for more accurate detection and also compute the mask, but it is slower:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/XamarinForms/Core/App.cs#L328
If you need to use it for real time detection you should use Yolo or Mobilenet.

**Comment by emgucv** [comment]
Closing ticket now.
