### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pavithra777** [emgucv/emgucv#678]
We are capturing all frames in a video and use Mat to convert to image. After assigning to a Object, we dispose Mat immediately. but still we get **System.OutOfMemoryException**

Exception of type 'System.OutOfMemoryException' was thrown., exception trace    at Emgu.CV.Image`2.AllocateData(Int32 rows, Int32 cols, Int32 numberOfChannels)
   at Emgu.CV.Mat.ToImage[TColor,TDepth](Boolean tryShareData)

** OS / Platform **  Windows
**.Net version**   .Net Core 5
**CPU Architecture** x64
** Emgu CV package used** Emgu.CV 4.5.1.4349

**Code Snippet**
VideoCapture reader = new VideoCapture(file);

while (reader != null) 
{
	Mat mat = reader.QueryFrame();
	Object Frame = mat.ToImage<Bgr, Byte>();
	mat.Dispose();
}

**Comment by emgucv** [comment]
You need to disposed the Image<,> object created during the loop as well:

```
VideoCapture reader = new VideoCapture(file);

while (reader != null)
{
using(Mat mat = reader.QueryFrame())
using(var Frame = mat.ToImage<Bgr, Byte>())
{
}
}
```

**Comment by Pavithra777** [comment]
Sorry I forgot to mention I dispose Image<,>  after I use it.

**Comment by emgucv** [comment]
And "reader" will not become "null" so the while loop do not terminate.

Do you have some self contained workable code, preferablely less than 20 lines, for us to reproduce the issue?

**Comment by Pavithra777** [comment]
This error comes in Release- x64 platform. It works fine in Release- Any CPU platform.
