### ISSUE TITLE
DllNotFoundException on RPi4 with linux-arm-runtime NuGet Package

### ISSUE THREAD

**Issue by Sir-Photch** [emgucv/emgucv#685]
Hello, I get an exception trying to invoke emgu.cv-code on a Raspberry Pi 4 4GB, particularly when calling the `Mat`-ctor:

> DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory

The debug-output in visualstudio shows:

> Loading Open CV binary from default locations. Current directory: /root/debug
Trying to load libopencv_videoio_ffmpeg455_64.so using default path.
Failed to use dlopen to load libopencv_videoio_ffmpeg455_64.so (RTLD_NOW | RTL_GLOBAL)
Failed to load libopencv_videoio_ffmpeg455_64.so using default path
!!! Failed to load libopencv_videoio_ffmpeg455_64.so.
Found full path /root/debug/libcvextern.so for libcvextern.so. Trying to load it.
Failed to use dlopen to load /root/debug/libcvextern.so (RTLD_NOW | RTL_GLOBAL)
Failed to load libcvextern.so from /root/debug/libcvextern.so.
Trying to load libcvextern.so using default path.
Failed to use dlopen to load libcvextern.so (RTLD_NOW | RTL_GLOBAL)
Failed to load libcvextern.so using default path
!!! Failed to load libcvextern.so.

The OS running on the rpi is DietPi, a strapped down version of the usual Raspberry Pi OS, based on Debian.
`cat /etc/issue` shows:
> Raspbian GNU/Linux 10

I am using the most current linux-arm-runtime NuGet-Package. I have tried to execute the [steps](https://emgu.com/wiki/index.php/Download_And_Installation#Raspberry_Pi_OS) provided in the wiki but without success;
Running `ldd libcvextern.so` shows two mismatched dependencies:

> /lib/arm-linux-gnueabihf/libm.so.6: version 'GLIBC_2.29' not found (required by ./libcvextern.so)
/usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libcvextern.so)

as well as two missing ones:

> libgeotiff.so.5 => not found
libdc1394.so.25 => not found

I thought about compiling libc_2.29 from source, but have heard that this could cause my system to get unstable. The two missing dependencies are available though:
`apt list | grep 'geotiff\|dc1394'` shows:

> gem-plugin-dc1394/oldstable 1:0.94-1 armhf
geotiff-bin/oldstable 1.4.3-1 armhf
libdc1394-22-dbg/oldstable 2.2.5-1 armhf
libdc1394-22-dev/oldstable,now 2.2.5-1 armhf [installed]
libdc1394-22-doc/oldstable 2.2.5-1 all
libdc1394-22/oldstable,now 2.2.5-1 armhf [installed,automatic]
libdc1394-utils/oldstable 2.2.5-1 armhf
libgeotiff-dev/oldstable,now 1.4.3-1 armhf [installed]
libgeotiff-epsg/oldstable 1.4.3-1 all
libgeotiff2/oldstable,now 1.4.3-1 armhf [installed,automatic]

I also tried to compile emgu.cv-runtime from source, running `cmake_configure` in `emgucv/platforms/raspberry_pi_os`; multiple errors occur here:

<details><summary>long output</summary>
CMake Error: The source directory "/root/emgucv/eigen" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
Performing full build
CMake Error: The source directory "/root/emgucv/hdf5" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
CMake Error: The source directory "/root/emgucv/vtk" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
-- CSC_EXECUTABLE_120: CSC_EXECUTABLE_120-NOTFOUND
-- MSBUILD_EXECUTABLE_120 : MSBUILD_EXECUTABLE_120-NOTFOUND
-- CSC_EXECUTABLE_140: CSC_EXECUTABLE_140-NOTFOUND
-- MSBUILD_EXECUTABLE_140 : MSBUILD_EXECUTABLE_140-NOTFOUND
-- CSC_EXECUTABLE_150: CSC_EXECUTABLE_150-NOTFOUND
-- MSBUILD_EXECUTABLE_150 : MSBUILD_EXECUTABLE_150-NOTFOUND
-- CSC_EXECUTABLE_160: CSC_EXECUTABLE_160-NOTFOUND
-- MSBUILD_EXECUTABLE_160 : MSBUILD_EXECUTABLE_160-NOTFOUND
-- CSC_EXECUTABLE_170: CSC_EXECUTABLE_170-NOTFOUND
-- MSBUILD_EXECUTABLE_170 : MSBUILD_EXECUTABLE_170-NOTFOUND
-- NUGET_EXECUTABLE : NUGET_EXECUTABLE-NOTFOUND
-- SIGNTOOL_EXECUTABLE : SIGNTOOL_EXECUTABLE-NOTFOUND
-- Could not find csc
-- Could not find gacutil
-- Could not find al
-- Could not find resgen
-- Could not find msbuild
-- Could not find vstool
-- Found dotnet: /root/.dotnet/dotnet
CMake Error at cmake/modules/OpenCVVersion.cmake:2 (file):
  file STRINGS file
  "/root/emgucv/opencv/modules/core/include/opencv2/core/version.hpp" cannot
  be read.
Call Stack (most recent call first):
  CMakeLists.txt:228 (INCLUDE)

CMake Error: File /root/emgucv/opencv/modules/core/include/opencv2/core/version.hpp does not exist.
CMake Error at cmake/modules/OpenCVVersion.cmake:18 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:228 (INCLUDE)

-- Extracting Emgu CV git version, please wait...
-- Emgu CV GIT VERSION: 4848
-- CMAKE_SYSTEM_NAME: Linux
-- Building for arm
-- <<<< EMGUCV_ARCH: arm >>>>
-- <<<< CMAKE_SYSTEM_NAME: Linux >>>>
-- <<<< CMAKE_SYSTEM_VERSION: 5.10.63-v7l+ >>>>
-- <<<< CMAKE_GENERATOR: Unix Makefiles >>>>
-- <<<< CMAKE_HOST_SYSTEM_PROCESSOR: armv7l >>>>
-- <<<< CMAKE_SYSTEM_PROCESSOR: armv7l >>>>
-- Package name will be emgucv
CMake Error at CMakeLists.txt:897 (ADD_SUBDIRECTORY):
  The source directory

    /root/emgucv/opencv

  does not contain a CMakeLists.txt file.

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1107 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1135 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1161 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1186 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1208 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1255 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1278 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1299 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1323 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1350 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/CMakeLists.txt:1955 (CREATE_OCV_CLASS_PROPERTY):
  CREATE_OCV_CLASS_PROPERTY Macro invoked with incorrect arguments for macro
  named: CREATE_OCV_CLASS_PROPERTY

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:14 (file):
  file STRINGS file
  "/root/emgucv/Emgu.CV.Extern/tesseract/libtesseract/tesseract-ocr.git/VERSION"
  cannot be read.

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:15 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:16 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:17 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

-- LEPTON_DIR: /root/emgucv/Emgu.CV.Extern/tesseract/libtesseract/leptonica/leptonica.git
CMake Error at Emgu.CV.Extern/tesseract/libtesseract/leptonica/CMakeLists.txt:17 (include):
  include could not find load file:

    Configure

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/leptonica/CMakeLists.txt:21 (LIST):
  LIST sub-command REMOVE_ITEM requires two or more arguments.

-- leptonica HAVE_LIBJPEG: FALSE
-- leptonica HAVE_LIBPNG:
-- leptonica HAVE_LIBTIFF: FALSE
CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:68 (file):
  file STRINGS file
  "/root/emgucv/Emgu.CV.Extern/tesseract/libtesseract/tesseract-ocr.git/VERSION"
  cannot be read.

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:69 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:70 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:71 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error: File /root/emgucv/Emgu.CV.Extern/tesseract/libtesseract/tesseract-ocr.git/include/tesseract/version.h.in does not exist.
CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:80 (configure_file):
  configure_file Problem configuring file

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:129 (LIST):
  LIST sub-command REMOVE_ITEM requires two or more arguments.

-- CPU_BASELINE:
-- CPU_BASELINE_FINAL:
-- TESSERACT with AVX: OFF
-- TESSERACT with AVX2: OFF
-- TESSERACT with SSE4_1: OFF
-- TESSERACT with NEON: OFF
-- ------------------------------------ TESSERACT_SIMDDETECT_COMPILE_FLAGS:  -------------------------------------
CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:421 (file):
  file failed to open for reading (No such file or directory):

    /root/emgucv/Emgu.CV.Extern/tesseract/libtesseract/tesseract-ocr.git/VERSION

CMake Error at Emgu.CV.Extern/tesseract/libtesseract/CMakeLists.txt:426 (LIST):
  LIST sub-command REMOVE_ITEM requires two or more arguments.

-- CVEXTERN: ZLIB found.
-- CVEXTERN: GEOTIFF found. INCLUDE DIR: /usr/include/geotiff
-- date: 22/01/2022

-- LICENSE FILE: /root/emgucv/LICENSE
-- LICENSE_TYPE: Dual License
-- Checking for CPACK build type...
-- CPACK_GENERATOR:
-- Configuring incomplete, errors occurred!
See also "/root/emgucv/platforms/raspberry_pi_os/build/CMakeFiles/CMakeOutput.log".
See also "/root/emgucv/platforms/raspberry_pi_os/build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'package'.  Stop.
</details>

I have published my application with the following settings:

> Configuration: Debug | ARM32
framework: net6.0
publish-mode: Independent
target-runtime: linux-arm

raspberry-pi OS is still 32bit even though the raspberry pi 4 is a 64-bit arm-processor, thats why I am using ARM32. Using ARM64 does produce the same result, also with `ldd libcvextern.so`

What is the issue here? Is Raspbian Buster too old for the linux-runtime?

**Comment by Sir-Photch** [comment]
considering the build-problems with `cmake_configure`:
i forgot to run `git submodule update --init --recursive`.
after that, it build for some time, exiting with an error-message.
i tried reconfiguring, and now it is telling me that 

> _glob_locations
    ocv_glob_modules
    ocv_register_modules

are missing

**Comment by Sir-Photch** [comment]
well now I got the build to succeed, but loading `libcvextern.so` into my program gives me a segfault

**Comment by emgucv** [comment]
>There seems to be an issue with IplImage?

No, the size of 112 for 32-bit system is correct. The size 144 is for 64-bit system. Thanks for pointing that out, we have removed the "expected" value from the cvextern_test output in this commit:
7857aaefe24798a7544d4d7eeb4a4ccf5933e485

To gather more information, if you run our "BuildInfo" test program, does it also generate a SegFault?

To run the "BuildInfo" test program, after you have build the "libcvextern.so" file, go to the "Emgu.CV.Example/BuildInfo.NetCore.Console" folder, then type:
`dotnet run`
It works on our Raspberry Pi 4 using the 32-bit Raspberry Pi OS (Bullseye).

**Comment by Sir-Photch** [comment]
`dotnet run` outputs only compilation warnings, running the binary `BuildInfo.NetCore.Console` by itself also produces a segfault.
```
[1]    8531 segmentation fault  ./BuildInfo.NetCore.Console
```
