### ISSUE TITLE
Color conversion from Bgra to any Yuv fail in CvInvoke

### ISSUE THREAD

**Issue by AeroClassics** [emgucv/emgucv#7]
I have a  Mat that is from an Image<Bgra, byte>. If I try to do a CvInvoke.CvtColor(originalMat, convertedMat, ColorConversion.Bgra2YuvI420) the code fails in the CvInvoke call.

EmguCV version emgucv-windesktop_x64-cuda-tbb-ipp-icc 3.1.0.2504
Program compiled for x64

**Comment by liuxu0938** [comment]
//解码回调函数
        private void DecCallbackFUN(int nPort, IntPtr pBuf, int nSize, ref PlayCtrl.FRAME_INFO pFrameInfo, int nReserved1, int nReserved2)
        {
            // 将pBuf解码后视频输入写入文件中（解码后YUV数据量极大，尤其是高清码流，不建议在回调函数中处理）
            if (pFrameInfo.nType == 3) //#define T_YV12	3
            {

                Mat dst = new Mat(pFrameInfo.nHeight, pFrameInfo.nWidth, Emgu.CV.CvEnum.DepthType.Cv8U, 1);
                int step = nSize / (pFrameInfo.nHeight + pFrameInfo.nHeight / 2);
                Mat src = new Mat(pFrameInfo.nHeight + pFrameInfo.nHeight / 2, pFrameInfo.nWidth, Emgu.CV.CvEnum.DepthType.Cv8U, 3, pBuf, step);
                CvInvoke.CvtColor(src, dst, Emgu.CV.CvEnum.ColorConversion.Yuv2BgrYv12);

                tracker.OneFrameReceive(ref dst);
              }
        }

**Comment by emgucv** [comment]
Tested on the current release and works:

```
            Image<Bgra, Byte> bgraImg = new Image<Bgra, byte>(640, 480);
            bgraImg.SetRandNormal(new MCvScalar(100, 100, 100, 100), new MCvScalar(50, 50, 50, 50) );
            Mat yuv = new Mat();
            CvInvoke.CvtColor(bgraImg, yuv, ColorConversion.Bgra2YuvI420);
```

Closing ticket for now. If you still have issues, please provide the code that can reproduce the bug and re-open the ticket. Thanks.
