### ISSUE TITLE
Image Convolution Fails with Size & Channel Mismatch

### ISSUE THREAD

**Issue by aluitink** [emgucv/emgucv#70]
Hello trying Kernel Convolution on image, receiving the following:

`src->size() == dst->size() && src->channels() == dst->channels()`

Noticed the ForEachDuplicateChannel method creates two Mat objects one is filled from an extracted channel, the other should be populated by the Filter2D invocation, but fails because the second mat tmp2 is of a different size.

Attached is a workaround:

[EmguCVBug.txt](https://github.com/emgucv/emgucv/files/1424486/EmguCVBug.txt)

Found in Nuget Package version 3.2.0.2721, worked in 2.4

**Comment by emgucv** [comment]
Thanks for reporting. Issue has been fixed in Git repo.
