### ISSUE TITLE
Call the function of createDisparityWLSFilter() in ximgproc

### ISSUE THREAD

**Issue by wentata** [emgucv/emgucv#700]
![image](https://user-images.githubusercontent.com/30208646/153354455-76774e3e-da0b-4e35-b344-457f65d57dc9.png)

Hi, i am here to ask is it possible to call/invoke this function through emgucv?

**Comment by wentata** [comment]
![image](https://user-images.githubusercontent.com/30208646/153355087-c6b2bfe0-3a29-4501-9ef3-42f03b91a8a3.png)
i wish to translate the c++ above into c# using emgucv

**Comment by emgucv** [comment]
Closing ticket now.
