### ISSUE TITLE
How to multiply two Mat with different dimension?

### ISSUE THREAD

**Issue by michealChin** [emgucv/emgucv#701]
The following is Python code

 gradient_sigma=1
 sze= 7
  gauss = cv2.getGaussianKernel(np.int(sze),self.gradient_sigma) 
    # gauss is 7 X 1 Mat
    f = gauss * gauss.T 
    # output f is 7 X 7 Mat

Here is C# code

var gauss = Emgu.CV.CvInvoke.GetGaussianKernel((int)sze,gradient_sigma);
Mat f = new Mat(7,7, DepthType.Cv8U, -1);
CvInvoke.Multiply(gauss, gauss.T(), f,1, DepthType.Cv8U);

Here is the error message
: 'OpenCV: The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array''

I couldn't figure out how to get this to work, Please help! Thanks in advance.

**Comment by sn4k3** [comment]
You cant, Mat's must have same size.
You need to Roi the larger Mat to the size of the smaller and then you can do the operation

**Comment by michealChin** [comment]
Thanks

**Comment by emgucv** [comment]
Open CV use the '*' operator overload for convolution. You can use this function in Emgu CV to perform a matrix convolution:
https://www.emgu.com/wiki/files/4.5.5/document/html/M_Emgu_CV_CvInvoke_Filter2D.htm

**Comment by emgucv** [comment]
You should be able to use CvInvoke.Gemm for matrix multiplication:
https://www.emgu.com/wiki/files/4.5.5/document/html/M_Emgu_CV_CvInvoke_Gemm.htm
"src3" can be null in your case.

CvInvoke.Multiply is used for "element-wise" multiplication, not matrix multiplication, see its documentation here:
https://www.emgu.com/wiki/files/4.5.5/document/html/M_Emgu_CV_CvInvoke_Multiply.htm

**Comment by emgucv** [comment]
CvInvoke.MulTransposed can also be used in your special case:
https://www.emgu.com/wiki/files/4.5.5/document/html/M_Emgu_CV_CvInvoke_MulTransposed.htm
