### ISSUE TITLE
CudaInvoke.Gemm gives System.AccessViolationException

### ISSUE THREAD

**Issue by dennisai** [emgucv/emgucv#71]
Hi, I am trying to use the CudaInvoke.Gemm method, and the following codes throws a System.AccessViolationException.

    Mat a = new Mat(3, 3, DepthType.Cv32F, 1);
    Mat b = new Mat(3, 3, DepthType.Cv32F, 1);
    Mat c = new Mat(3, 3, DepthType.Cv32F, 1);
    Mat d = new Mat(3, 3, DepthType.Cv32F, 1);
    GpuMat ga = new GpuMat();
    GpuMat gb = new GpuMat();
    GpuMat gc = new GpuMat();
    GpuMat gd = new GpuMat();

    CvInvoke.Gemm(a, b, 1.0, c, 0.0, c);
    ga.Upload(a);
    gb.Upload(b);
    gc.Upload(c);
    gd.Upload(d);

    CudaInvoke.Gemm(ga, gb, 1.0, gd, 0.0, gc);

This is the stacktrace.

    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at Emgu.CV.Cuda.CudaInvoke.cudaGemm(IntPtr src1, IntPtr src2, Double alpha, IntPtr src3, Double beta, IntPtr dst, GemmType tABC, IntPtr stream)
       at Emgu.CV.Cuda.CudaInvoke.Gemm(IInputArray src1, IInputArray src2, Double alpha, IInputArray src3, Double beta, IOutputArray dst, GemmType tABC, Stream stream) in C:\Emgu\emgucv\Emgu.CV.Cuda\CudaInvoke.cs:line 1083

I am running Emgu 3.2, with Windows 10 x64.  Other CudaInvoke methods, like reduce and filtering, work fine.

**Comment by dennisai** [comment]
Sometimes when I run that code, it gives me the following exception coming from this line in arithm.cpp.

    CV_Assert( src1.type() == CV_32FC1 || src1.type() == CV_32FC2 || src1.type() == CV_64FC1 || src1.type() == CV_64FC2 );

I don't know why it would do that, since all my arrays are of CV32F and the number of channels is one.  I also tried downloading the latest Emgu 3.3, and installed CUDA 9, and am running into the same problem.

**Comment by emgucv** [comment]
Thanks for reporting.
It is fixed in the above commit.
