### ISSUE TITLE
Can I use this repo to get color quantization.

### ISSUE THREAD

**Issue by zydjohnHotmail** [emgucv/emgucv#711]
Hello:
I want to know if I can use this repo to get color quantization for an image.
There are a lot of such repo for Python, as indicated by this web page:
https://github.com/topics/color-quantization
But there no such repo in C#.
Please advise,
Thanks,

**Comment by emgucv** [comment]
Not a bug. Closing this ticket, please create a new topic in discussions:
https://github.com/emgucv/emgucv/discussions
