### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wentata** [emgucv/emgucv#712]
**Describe the bug**
File Storage write return error [Attempted to read or write protected memory. This is often an indication that other memory is corrupt.]

** OS / Platform **
Windows

** .Net version **
.NetFramework 4.8, 

**CPU Architecture**
x64

** Emgu CV package used**
e.g. 'libemgucv-windesktop-4.5.5.4823.zip',

**To Reproduce**
 string path = Application.ExecutablePath + "//data.xml";
 FileStorage fs = new FileStorage(path, FileStorage.Mode.Write);
 fs.Write(points);

points are the mat return from CvInvoke.ReprojectImageTo3D(show, points, _Q, false, DepthType.Cv32F);

![image](https://user-images.githubusercontent.com/30208646/157829324-248af99e-63c3-481f-820b-f6a4281638bc.png)

**Expected behavior**
I wish to export the mat into xml file using universal save. But it return memory error.

**Screenshots**
![image](https://user-images.githubusercontent.com/30208646/157829852-571d9e40-1037-4f28-8d17-95c4139051e2.png)

**Comment by emgucv** [comment]
Please also update the title to make it more clear.

**Comment by emgucv** [comment]
Closing ticket now.
