### ISSUE TITLE
Have to allocate memory for dst parameter before use?

### ISSUE THREAD

**Issue by xhuan8** [emgucv/emgucv#715]
I try to invoke cvtColor with emgucv, the code looks like:
`Mat imgGrayscale = new Mat(imgOriginal.Size, DepthType.Cv8U, 1);
    CvInvoke.CvtColor(imgOriginal, imgGrayscale, ColorConversion.Bgr2Gray);`
    

but for c++:

    `Mat gray_image;
    cvtColor( image, gray_image, CV_BGR2GRAY );`

python is much simpler:

    `image = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY )`

is it possible to make the memory allocation more automatically?

**Comment by emgucv** [comment]
Just 
`Mat imageGrayScale = new Mat();`
will do.
