### ISSUE TITLE
Please version all DLL's in release code

### ISSUE THREAD

**Issue by JohnTenney** [emgucv/emgucv#72]
Some installers (I use Wix, but I assume others are similar) will not by default upgrade DLL's when the version number is unchanged. I've had problems with Emgu in the past, since it seems there is no versioning of the DLL's. Simply right-click on the DLL and choose properties, and you'll see there is no version attached to the library. In the new 3.3, I'd expect a version of 3.3.0 on cvextern.dll, for example.

**Comment by emgucv** [comment]
Fixed in 220b0fe16e7222f473599018c1030d8922feb352
Thanks for pointing out.

**Comment by hulumiaomiao** [comment]
I did not find bin--X86 or X64 files and DLLS in more than 3.3 versions.But I didn't see any of these changes in the version update record.Why is that?

**Comment by emgucv** [comment]
Just checked again, files version are include in the cvextern.dll for the 4.5.1 release. 

Closing ticket now.
