### ISSUE TITLE
[BUG] Emgu.Cv.CvEnum.DepthEnum not existing yet defined

### ISSUE THREAD

**Issue by NTrouillet07** [emgucv/emgucv#725]
**Describe the bug**
I want to use the CvInvoke.WarpAffine method using a translation matrix. So I defined my matrix as follows : 
` Matrix<Emgu.CV.CvEnum.DepthType.Cv32F> array;`
` Size m_size = new Size(2, 3);   ` 
` array = new Emgu.CV.Matrix<Emgu.CV.CvEnum.DepthType.Cv32F>(m_size);`

I'm working on Visual Studio 19, so my IDE suggested me `Cv32F` when I typed `Emgu.CV.CvEnum.DepthType`
![image](https://user-images.githubusercontent.com/104618100/165901730-8bd1fe83-2d5e-4c8d-9cb9-18d891f3f23d.png)

But Visual Studio keeps tell me this error : 
![image](https://user-images.githubusercontent.com/104618100/165902454-e1fa3cc3-051f-40c0-9569-7485397d69cb.png)

When I go to the Definition of the Enum, there is all the type defined : 
![image](https://user-images.githubusercontent.com/104618100/165902556-5b7a56b9-c5e0-4492-952c-15e5d0f6aba3.png)

** OS / Platform **
Windows 10 Pro

** .Net version **
.NET Core 3.1

**CPU Architecture**
x86_64

** Emgu CV package used**
Emgu.CV.runtime.windows-4.5.5.4823 nuget package from nuget.org

**Comment by emgucv** [comment]
You should use `Matrix<float>` instead of `Matrix<Emgu.CV.CvEnum.DepthType.Cv32F>` to create a floating point matrix. This class is based on the old "CvMat" object. 

I would recommend using Mat (based on cv::Mat) instead.

**Comment by emgucv** [comment]
Closing ticket now
