### ISSUE TITLE
Load unmanaged libraries from external folder

### ISSUE THREAD

**Issue by nvgus** [emgucv/emgucv#729]
We are using EMGU Commercial 4.5.5.4823, but had same issue in 4.5.1.4349.

We are distributing the unmanaged x64 libraries by users downloading and installing a separate MSI from our main application. For example, might install here:

C:\Program Files\EMGU\x64\

In version 4.4.0.4099 we were able to set the external path with the following call:

Emgu.Util.Toolbox.SetDllDirectory(externalPath);

But this no longer works. We had to modify CInvoke.DefaultLoadUnmanagedModules to pass a static property set to the external folder before CInvoke is referenced by modifying this line from:

`libraryLoaded &= LoadUnmanagedModules(null, modules);`

To:

`libraryLoaded &= LoadUnmanagedModules(Toolbox.ExternalDllFolder, modules);`

Could the ability to set an external unmanaged library path be restored for the next released version?

**Comment by emgucv** [comment]
Fixed in this commit: 77e611665b1d9bf903a748894e61e439e01594e1

The fix will let you call
`Emgu.Util.Toolbox.SetDllDirectory(externalPath);`
before calling CvInvoke.Init() function to load native binary from the "externalPath".

It will be included in the next release.

**Comment by nvgus** [comment]
Thank you, that approach works well. What is the expected release date for the next version?

**Comment by emgucv** [comment]
We normally have new release ~1 month after a new official Open CV release.

**Comment by nvgus** [comment]
Sounds good, thanks!
