### ISSUE TITLE
Can't get it to work in Xamarin for android

### ISSUE THREAD

**Issue by bleh05** [emgucv/emgucv#732]
![image](https://user-images.githubusercontent.com/19368094/169095633-b487b302-0807-48f6-9ff1-4cd8033221a2.png)

Seems like the Image class can't be found by the compiler. However, I can see the dll packages in all the necessary directories. Are there additional steps that I need to take to make the program be able to run emgu?

**Comment by emgucv** [comment]
Are you using the Emgu.CV.runtime.android nuget package? Or are you using the .dll directly from the commercial release package? Which version of the package are you using?

FYI, More information for setting up an Emgu CV android project can be fond here:

https://www.emgu.com/wiki/index.php/Download_And_Installation#Android

**Comment by emgucv** [comment]
Closing ticket now.
