### ISSUE TITLE
Which a tool is it generated by?

### ISSUE THREAD

**Issue by Moon9R** [emgucv/emgucv#733]
recently,i tried to read the code of emgucv.I found some the code is automatically  generated .I want know it generated by? 

//----------------------------------------------------------------------------
//
//  Copyright (C) 2004-2018 by EMGU Corporation. All rights reserved.
//
//  Vector of Float
//
//  This file is automatically generated, do not modify.
//----------------------------------------------------------------------------

**Comment by emgucv** [comment]
It is generated by this CMake script during the build process:

https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Extern/CMakeLists.txt#L92

This issue tracker is used to track bugs. It will be better to move this ticket to discussion. Please close the ticket if you are satisfied with the answer. 

Thank you.

**Comment by Moon9R** [comment]
@emgucv Thank you.
