### ISSUE TITLE
About 4.6.0

### ISSUE THREAD

**Issue by luisrr1590** [emgucv/emgucv#745]
Hi guys....long time fan.

I just wanted to ask when 4.6.0 will be released. This version of OpenCV fixes a major issue with a memory leak while using FFMPEG and Hardware Acceleration.

I know I could built the Nuget myself but I always rather using your official releases.

Thanks for the hard work

**Comment by luisrr1590** [comment]
Thanks for the response

**Comment by emgucv** [comment]
Sorry for the delay. It taking much longer because we are trying to support MAUI in this release. The core technical part is completed but we are still working on the packaging side. It will be ready soon.

**Comment by luisrr1590** [comment]
Ohhh... That's actually great...thanks for the feedback!! I'm using 4.5.0 in a Blazor project its great to know I'll be able to migrate to MAUI now
