### ISSUE TITLE
MAUI and EmguCV.iOS

### ISSUE THREAD

**Issue by vmgolubev** [emgucv/emgucv#757]
I bought EmguCV for Droid and iOS, Droid NuGet packages work like a charm in MAUI app, but the iOS package does not, the errors when I try to install iOS package are:
Restoring packages ....App.csproj...
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0). Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0). Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / android-arm. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / android-arm64. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / android-x64. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / android-x86. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / ios-arm64. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0) / android-arm. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0) / android-arm64. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0) / android-x64. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0) / android-x86. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
NU1202: Package Emgu.CV.runtime.ios 4.5.5.4823 is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0) / ios-arm64. Package Emgu.CV.runtime.ios 4.5.5.4823 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)
Package restore failed. Rolling back package changes for 'App'.
Time Elapsed: 00:00:00.9677369
========== Finished ==========

This project has the Droid package and EmguCV package installed, but the installation of the EmguCV.iOS package is not possible. How can that be fixed?
Best,
V

**Comment by emgucv** [comment]
.net MAUI is actually a completely different platform compares with Xamarin. You will need a different nuget package to target .net MAUI.

We are preparing the new 4.6.0 release with .NET MAUI targeted nuget packages for iOS. If you want to get early access, please email [support@emgu.com](mailto:support@emgu.com) and we can reply with a development built.

**Comment by vmgolubev** [comment]
@emgucv when do you plan to release the 4.6.0 EmguCV.iOS package?

**Comment by emgucv** [comment]
We are trying to release 4.6.0 in a week or two.

**Comment by vmgolubev** [comment]
@emgucv any update on the 4.6.0 release?

**Comment by emgucv** [comment]
Pending on resolving an iOS MAUI device compilation issue.

**Comment by emgucv** [comment]
The 4.6.0 release has been out with support for MAUI for iOS. Closing ticket now.
