### ISSUE TITLE
CvInvoke.DrawContours run very slow

### ISSUE THREAD

**Issue by Erixz7777** [emgucv/emgucv#760]
I am using DrawContours method in emgucv package, but it's working very slow, it takes about "12" second
and I do the same thing in python, it only takes maybe "2" second to do this.

- The target is "Find out all external contour areas that is bigger than 800 pixels and Fill it up on a new canvas" 
than I will use this image as a mask
(The number of contours here is 74 )

Please tell me how can I improve the time consuming problem

Here's the C# code :

                VectorOfVectorOfPoint contours = new VectorOfVectorOfPoint();             
                CvInvoke.FindContours(img, contours, null, RetrType.External, ChainApproxMethod.ChainApproxSimple);
                UMat mask = new UMat(img.Size, DepthType.Cv8U, 1);

                int minArea = 800;
                for (int i = 0; i < contours.Size; i++)
                {
                    int area = CvInvoke.ContourArea(contours[i]);
                    if (area > minArea)
                    {
                        CvInvoke.DrawContours(mask, contours, i, new MCvScalar(255), -1);
                    }
                    else
                        continue;
                }

also show my python code :

    contours,_ = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

    C = len(contours)

    for i in range(0, C):
        if cv2.contourArea(contours[i]) > 800 :
            cv2.drawContours(mask, contours, i, (255,255,255), -1)
        else:
            continue

Thank you

**Comment by emgucv** [comment]
Which exact Emgu CV package do you use? What is the output for CvInvoke.BuildInformation?

Which open cv for python release do you use? What is the output for cv::getBuildInformation()?

What CPU did you use for testing and performance evaluation?

Comparing the two build information you can find out what is the different in build configuration and re-build Emgu CV / Open CV for your system to get the best performance.

**Comment by sn4k3** [comment]
Your python code does not show all, for example, are you using **UMat** with python?
`UMat` for fast and single operations is slower than `Mat`

Try to use `Mat` instead and report back

**Comment by Erixz7777** [comment]
> Your python code does not show all, for example, are you using `UMat` with python? `UMat` for fast and single operations is slower than `Mat`
> 
> Try to use `Mat` instead and report back

Dear sn4k3, 
In python I'm using `cv2.imread`. after searching, I think it is `Mat` format
I will try to use `Mat` to replace and test.

Thanks for your information.

**Comment by Erixz7777** [comment]
> Which exact Emgu CV package do you use? What is the output for CvInvoke.BuildInformation?
> 
> Which open cv for python release do you use? What is the output for cv::getBuildInformation()?
> 
> What CPU did you use for testing and performance evaluation?
> 
> Comparing the two build information you can find out what is the different in build configuration and re-build Emgu CV / Open CV for your system to get the best performance.

Dear emgucv, 
The version of emgucv package is 3.1.0
opencv is 4.6.0
The CPU performce is nearly same.
I will try to update the emgucv package

Thanks for your information.

**Comment by Erixz7777** [comment]
> Your python code does not show all, for example, are you using `UMat` with python? `UMat` for fast and single operations is slower than `Mat`
> 
> Try to use `Mat` instead and report back

It works!!!
now it run as fast as python.
Thank you, you save my project, I love you.
