### ISSUE TITLE
Am I properly disposing of my objects using EmguCv.Image<Bgr, byte[]> ?

### ISSUE THREAD

**Issue by eduardk1008** [emgucv/emgucv#761]
Good day,

We are using the EmguCv.Image object in a .NET Core 3.1 Worker service to perform facial matching against a pre-defined system. However, we do not have control of the image's rotation when we receive the messages (it could be rotated anything from 90 to 270 degrees, we receive the image from an external customer). 
To improve our chances of getting a match, we have implemented a loop to rotate the image 90 degrees right for a total of three times (so we get the full 360 degree view). 
We've had an incident recently where our server (8 vCPU's and 8GB RAM) eventually ran out of memory, and this 360 degree evaluation change was the only change implemented in a very long time, so I am just being cautious and pro-active to see if we did not perhaps implement this "loop rotation" fix incorrectly:

Below is a simple example of the code we are using to perform the extract.
Assume the "facialFeatureDetection" service returns an object containing amongst others, a value that indicates if facial extraction was successful ("FaceDetected" property):

```
public FacialExtractionResponse ExtractFace(Bitmap image)
{
	int rotationAttempts = 0;
	var inputImage = new Emgu.CV.Image<Bgr, byte>(image);
	FaceAttributes faceAttributes;

	do
	{
		faceAttributes = facialFeatureDetection.GetFacialFeatures(inputImage);

		if (!faceAttributes.FaceDetected)
		{
			// Could not detect face, so rotate 90 degrees right.
			inputImage = imageCropAndRotate.RotateImageNinetyDegreesRight(inputImage);
		}
	} while (!faceAttributes.FaceDetected && ++rotationAttempts < 3);



	if (!faceAttributes.FaceDetected)
	{
		// Just to ensure there are no memory leaks.                       
		inputImage?.Dispose();
		return new FacialExtractionResponse {  TransactionStatusId = 2 };
	}

	var rotatedImage = imageCropAndRotate.CropAndRotateImage(inputImage, faceAttributes);
	
	inputImage?.Dispose();

	return new FacialExtractionResponse { Image = $"data:image/jpeg;base64,{rotatedImage}" };
}
```

The service "imageCropAndRotate" has a method named "RotateImageNinetyDegreesRight" that looks like the following snippet:

```
public Image<Bgr, byte> RotateImageNinetyDegreesRight(Image<Bgr, byte> image)
        {            
            var rotated = image.Rotate(90, new Bgr());
            return rotated; // I cannot dispose here because it would cause a runtime error.
        }
```

When analyzing the above code, is there any possibility of a memory leak occurring during prolonged execution of this code?

Thanks in advance!

**Comment by leoshusar** [comment]
I'm not 100 % sure, but I would say this:
```cs
inputImage = imageCropAndRotate.RotateImageNinetyDegreesRight(inputImage);
```
could cause a memory leak.

The current image should be disposed before replacing it with another.
You can also try to run that loop maybe 100 or 1000 times and watch if your memory grows.

**Comment by eduardk1008** [comment]
Thank you @leoshusar 
I was thinking the same too. TBH I did have to make this change quickly and get it deployed we had a client complaining about issues with the system.

For now we can manage it, I have an idea on how to approach this in a better way to ensure there are no more leaks.
Always good to have an outsider's opinion on something like this.
