### ISSUE TITLE
Could not load type System.Windows.Freezable from assembly WindowsBase Version=4.0.0.0

### ISSUE THREAD

**Issue by GiganteX** [emgucv/emgucv#763]
I have a .NET Core 3.1 project and I'm using the latest version of Emgu.CV

Calling Image.GetSubRect(), works fine
then I'm trying to save it with subimage.Save(path)

and I get the exception
Could not load type System.Windows.Freezable from assembly WindowsBase Version=4.0.0.0

... which makes me confused. What's going on? If that one is required why isn't it included as a dependency?

**Comment by emgucv** [comment]
Not sure, it is not a dependency for Emgu CV. 

Can you reproduce the issue using a small project with a few lines of code and share it here?

**Comment by emgucv** [comment]
Closing ticket now.
