### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lucas-fsousa** [emgucv/emgucv#765]
**Describe the bug**
Hello. I'm using the lib to manipulate some images and change the colors to grayscale so I can work with image recognition and the like, but I ended up having a problem when opening an image. My code is pretty big, so I took the root of the problem for simplicity. Both in Ubuntu 20.04, 22.04 and Raspibian it is accusing the absence of the item "dl". I searched through several forums and found several solutions, but none worked. The problem is occurring in the Toolbox call to dlopen. I already checked here and it has the C dev package with the necessary items. Any suggestion? On windows it works fine without any problems.

**OS / Platform**
Ubuntu 20.04, Ubuntu 22.04, Raspberry Pi - Debian

**.Net version**
.NET6,

**CPU Architecture**
x86_64, ARM64, x86

**Emgu CV package used**
```xml
<PackageReference Include="Emgu.CV" Version="4.5.5.4823" />
<PackageReference Include="Emgu.CV.Bitmap" Version="4.5.5.4823" />
<PackageReference Include="Emgu.CV.runtime.linux-arm" Version="4.5.5.4823" />
<PackageReference Include="Emgu.CV.runtime.ubuntu.20.04-x64" Version="4.5.5.4823" />
<PackageReference Include="Emgu.CV.runtime.windows" Version="4.5.5.4823" />
```

**To Reproduce**
SOURCE-CODE:
```csharp
using Emgu.CV;
using Emgu.CV.Structure;
using PublicUtility.ScreenReader;
using Emgu.Util;

var path = $"/tmp/{DateTime.Now.Ticks:x2}.png";
ScreenManager.PrintScreen().SaveAsPng(path); // Save a screenshot in the current path
var img = new Image<Bgr, byte>(path); // exception here
```

STACK-TRACE:  
Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory
   at Emgu.Util.Toolbox.Dlopen(String dllname, Int32 mode)
   at Emgu.Util.Toolbox.LoadLibrary(String dllname)
   at Emgu.CV.CvInvoke.LoadUnmanagedModules(String loadDirectory, String[] unmanagedModules)
   at Emgu.CV.CvInvoke.DefaultLoadUnmanagedModules(String[] modules)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.Image`2..ctor(String fileName)
   at Program.<Main>$(String[] args) in /home/lks/Downloads/a/Program.cs:line 15

**Expected behavior**
The image should be processed and returned so that it could be manipulated

**Comment by emgucv** [comment]
It has been fixed in this commit:
https://github.com/emgucv/emgucv/commit/621121e13377cb77f0555328e80821102c1165c2

It will be included in the next release.

The reason is that: In recent Ubuntu releases, the file "libdl.so" has been renamed to "libdl.so.2". As a temperary work around you can add a symbolic link from "libdl.so.2" to "libdl.so". 

We are working on the v4.6.0 release and it should be out soon.

**Comment by lucas-fsousa** [comment]
Can you guide me how to do this correctly, because in other topics I had already done this procedure, but it didn't work.

**Comment by sn4k3** [comment]
> Can you guide me how to do this correctly, because in other topics I had already done this procedure, but it didn't work.

Run this command on a terminal: `wget -qO - https://raw.githubusercontent.com/sn4k3/UVtools/master/Scripts/libdl-solver.sh | sudo bash`

**Comment by lucas-fsousa** [comment]
this worked very well. Thank you very much!
