### ISSUE TITLE
Load() method missing in StatModelExtensions 

### ISSUE THREAD

**Issue by graspergazon** [emgucv/emgucv#78]
The StatModelExtensions provides a method to save StatModels like SVM or ANN_MLP, but there doesn't seem to be a way to load the saved models. How can I load my save SVM from file?

**Comment by emgucv** [comment]
You can use the "Write" and "Read" extension function from IAlgorithm with "FileStorage" to write and read the model. Code sample can be found in our unit-test:
https://github.com/emgucv/emgucv/blob/EMGUCV_3_3_0/Emgu.CV.Test/AutoTestML.cs#L105

I just added a few more method in the IAlgorithm interface in this commit:
945433a9b9264e27a5ab862336749e69e1bd90e4

In the next release you will be able to call the "Load" function directly.

**Comment by emgucv** [comment]
Closing ticket now.
