### ISSUE TITLE
Umat.ToBitmap() memory is not been freed

### ISSUE THREAD

**Issue by Skyhikeeper** [emgucv/emgucv#789]
I am using The ToBitmap Option on a UMat however the function is not releasing the memory after generating the bitmap.
I get a memory runaway on my application (looks like a saw tooth on the memory monitor)

                using (UMat mymatin = new UMat())
                {
                    _capture.Retrieve(mymatin, 0);
                    try
                    {
                        var test = mymatin.ToBitmap();
                   }
                    catch
                    {
                    }
                }

Does not work. memory goes up to 3GB used , Currently using 4.6.0.5131 on a  .net 4.6.2 application

Ternece

**Comment by emgucv** [comment]
For all Bitmap generated, if you don't manually free it, it will be up to the garbage collector to collect it. If you don't want to leave the task to garbage collector, you will need to manually free it.

Try:
 ```
           using (UMat mymatin = new UMat())
            {
                _capture.Retrieve(mymatin, 0);
                try
                {
                    using(var test = mymatin.ToBitmap())
                    {

                    } //bitmap object is released here.
               }
                catch
                {
                }
            }
```

This is how to use Bitmap object in C# in general.

**Comment by emgucv** [comment]
Closing ticket now
