### ISSUE TITLE
Emgu CV in .NET Core 2.0 MVC

### ISSUE THREAD

**Issue by mihaj** [emgucv/emgucv#79]
I tried the Emgu CV Nuget package in a .NET Core 2.0 MVC app but the ZedGraph needs the full framework. So I can not use it.

Then I tried to add Emgu.CV.World.dll in application and I get the error:
`Could not load file or assembly 'Emgu.CV.World, Version=3.3.0.2824, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

Which looks like a bug in .NET Core: [https://github.com/dotnet/corefx/issues/23678](https://github.com/dotnet/corefx/issues/23678)

Any ideas on how I can solve this?

**Comment by lokumcan** [comment]
EmguCv libs are not compatible with .Net Core. as far as I know. I have been looking for it for some time now but it is not ready yet.

**Comment by MaikuMori** [comment]
Somewhat related to #1.

**Comment by emgucv** [comment]
The current 4.5.1 release is compatible with .NetStandard 2.0 and can be used with .Net Core 2.0 and higher

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Closing ticket now.
