### ISSUE TITLE
[BUG] LineType.Filled of  CvInvoke.Rectangle() unable to use . report an error

### ISSUE THREAD

**Issue by southmilkyway** [emgucv/emgucv#798]
**Describe the bug**

** OS / Platform **
e.g. Windows C#

** .Net version **
e.g. .NetFramework 4.7,2 

**CPU Architecture**
e.g. x86_64, ARM64

** Emgu CV package used**
e.g. libemgucv-windesktop-4.5.5.4823

**To Reproduce**
            Mat srcMat = CvInvoke.Imread(@"D:\Image\Test\Src2.bmp", ImreadModes.Grayscale);
            CvInvoke.Imshow("src", srcMat);
            CvInvoke.Rectangle(srcMat, new Rectangle(1, 1, 50, 50), new MCvScalar(255,255,255), 1, LineType.Filled);
            CvInvoke.Imshow("srcMat", srcMat);

**Expected behavior**

**Screenshots**

Emgu.CV.Util.CvException:“OpenCV: connectivity == 8 || connectivity == 4”

**Additional context**

**Comment by emgucv** [comment]
The documentation for CvInvoke.Rectangle function can be found here:
https://www.emgu.com/wiki/files/4.6.0/document/html/M_Emgu_CV_CvInvoke_Rectangle.htm

You can use thickness of "-1" to draw a filled rectangle:

> thickness (Optional)
> Type: [System.Int32](https://docs.microsoft.com/dotnet/api/system.int32)
> Thickness of lines that make up the rectangle. Negative values make the function to draw a filled rectangle.

Line Type should be either "four connected" or "eight connected" (That is what the error message is saying).

**Comment by southmilkyway** [comment]
Thanks for you！



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 12, 2022 23:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [emgucv/emgucv] [BUG] LineType.Filled of  CvInvoke.Rectangle()unable to use . report an error (Issue #798)




 
The documentation for CvInvoke.Rectangle function can be found here:
 https://www.emgu.com/wiki/files/4.6.0/document/html/M_Emgu_CV_CvInvoke_Rectangle.htm
 
You can use thickness of "-1" to draw a filled rectangle:
  
thickness (Optional)
 Type: System.Int32
 Thickness of lines that make up the rectangle. Negative values make the function to draw a filled rectangle.
  
Line Type should be either "four connected" or "eight connected" (That is what the error message is saying).

**Comment by southmilkyway** [comment]
I gave it a try like you said , If LineType select Filled , It still doesn't work . can only choose  LineType.EightConnected.
Thank you so much for your assistance !

**Comment by emgucv** [comment]
Yep, LineType has to be either FourConnected or EightConnected, not Filled, according to Open CV specification. Use thickness of -1 to fill rectangle. Closing ticket now.
