### ISSUE TITLE
Will 3.1.0-r16.12 be released on NuGet?

### ISSUE THREAD

**Issue by dougthor42** [emgucv/emgucv#8]
The latest release on [NuGet is `3.1.0.1`](https://www.nuget.org/packages/EmguCV/). All of the documentation appears to be for `3.1.0-r16.12`.

Are there plans to release `3.1.0-r16.12` on NuGet? If so, when?

----

I'm not familiar with your versioning scheme yet, but it seems like `3.1.0-r16.12` is a pre-release. I'm primarily a Python developer so I'm used to pre-release versions being available on PyPI. I don't know if NuGet allows pre-release or not, so this request might be invalid.

**Comment by lgoudriaan** [comment]
NuGet allows pre-releases, you can click the "include prerelease" checkbox next to the search box. 3.1.0-r16.12 isn't available though.

**Comment by emgucv** [comment]
The Emgu CV NuGet package is not maintained by us and is not an official distribution. You may need to contact the package maintainer to check if they are going create a new package for the 3.1.0-r16.12 release.

**Comment by MicrocontrollersAndMore** [comment]
Can you add an officially supported Emgu CV NuGet package?  This is how most users include libraries now and is much neater and more convenient than manually importing DLLs.

**Comment by jeremejevs** [comment]
@gegenschall Could you, please, hand over the ownership of the EmguCV package to @emgucv?

Pretty disappointing that deployment via a package manager is still an afterthought, especially considering that NuGet is seven years old.

**Comment by emgucv** [comment]
FYI, the official Emgu CV nuget package is available here (just released):
https://www.nuget.org/packages/Emgu.CV/

Sorry for the late release of the nuget package, going forward we will have nuget packages for every future releases. 

Thanks @gegenschall for keeping an Emgu CV package on nuget when the offical release was not available. He did communicate with us to request an official nuget release but we haven't been able to make one on time.

**Comment by jeremejevs** [comment]
Thank you!
