### ISSUE TITLE
Need ReadNetFromTorch function

### ISSUE THREAD

**Issue by cyclonedll** [emgucv/emgucv#802]
Need DnnInvoke.ReadNetFromTorch function supports.

**Comment by emgucv** [comment]
Added in this commit: 4554eab3ba64fc109b0f53e0b95e57087ea996c8 

I am not sure if Open CV support Torch under windows (it is supported under linux) You may need to rebuild the windows binary with Torch enabled, which is not well documented by Open CV.

**Comment by cyclonedll** [comment]
It is supported by OpenCV official release under windows.
Another project **OpenCvSharp4** also supports it.

**Comment by emgucv** [comment]
If Torch model is supported in the current release, you can also use the "readNet" function from existing 4.6.0 release to import a torch model:
https://www.emgu.com/wiki/files/4.6.0/document/html/M_Emgu_CV_Dnn_DnnInvoke_ReadNet.htm
https://docs.opencv.org/4.6.0/d6/d0f/group__dnn.html#ga3b34fe7a29494a6a4295c169a7d32422

**Comment by cyclonedll** [comment]
It worked , thanks ! But it would be better if it could be directly supported.
