### ISSUE TITLE
Many build errors

### ISSUE THREAD

**Issue by marcelo-maciel** [emgucv/emgucv#81]
Hi guys!

I've cloned current version, installed CMAKE, ran Build_Binary_x86-64_doc.bat, then opened the EMGU.CV.sln and build, but have many erros.

![errors](https://user-images.githubusercontent.com/4993482/33802445-a5fbf750-dd5e-11e7-8011-b49a3eaf2d03.png)

**Comment by emgucv** [comment]
The "Build_Binary_x86-64_doc.bat" script should generate the files such as "VectorOfKeyLine", "VectorOfERStat" etc using CMake.

Is there any errors calling the build script?

**Comment by marcelo-maciel** [comment]
Hi @emgucv !

Based you sugestion i found the first error.
I use Sourcetree and the default clone not check "Recurse Submodules".
I cloned again, checking "Advanced >> Recurse Submodules", then I ran the bat again.
Resulted in many errors, highlighting above:

CMakeError.log:
../EmguCV\b\CMakeFiles\CMakeTmp\cmTC_75dd5.vcxproj --FAIL. Compilation Fail

..\EmguCV\b\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Não é possível abrir arquivo incluir: 'pthread.h': No such file or directory [C:\work\OneDrive\Crowd IT\Seguindo\EmguCV\b\CMakeFiles\CMakeTmp\cmTC_75dd5.vcxproj]

Cannot open file socket.lib

And many more.
Then, i rebuild solution and the errors decreased.
![errors](https://user-images.githubusercontent.com/4993482/33820220-7e3596cc-de35-11e7-81b4-866676523db6.png)

I will attach the prompt result, CMakeError.log and CMakeOutput.log.

[console.txt](https://github.com/emgucv/emgucv/files/1546885/console.txt)
[CMakeError.log](https://github.com/emgucv/emgucv/files/1546887/CMakeError.log)
[CMakeOutput.log](https://github.com/emgucv/emgucv/files/1546888/CMakeOutput.log)


,

**Comment by emgucv** [comment]
It also seems that you haven't checkout the "opencv_contrib" submodule. You have the following error when running the BuildScript:

> CMake Error at opencv/cmake/OpenCVModule.cmake:305 (message):
>   No extra modules found in folder: C:/work/OneDrive/Crowd
> 
>   Please provide path to 'opencv_contrib/modules' folder.
> Call Stack (most recent call first):
>   opencv/modules/CMakeLists.txt:7 (ocv_glob_modules)

Please following the instruction here to build from source:
http://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git
More specifically, the instructions to checkout from Git here for checking out all the submodules:
http://www.emgu.com/wiki/index.php/GIT

Once all the submodules has been checked out, please clean the repository before calling the build script. 

Hope that helps.

**Comment by marcelo-maciel** [comment]
Hi @emgucv !
I deleted all and tried again (opencv_contrib are not the problem, because there are files into the folder).
My first change was to change the folder path.
Older:
C:\work\OneDrive\Crowd IT\Seguindo\Emgucv
New:
C:\Emgucv

Cloned, ran bat, open solution and....it WORKS!

Really, I think that the problem is because the space "Crowd IT" in the older path.

BUT, compiling Emgu.CV.Example I have two errors because the type or namespace BackgroundSubtractor cannot be found in VideoSurveilance and Motion detection.

**Comment by marcelo-maciel** [comment]
?

**Comment by miftahrangga20** [comment]
I had the same issue for missing the BackgroundSubtractor namespace. Has anyone got the solution? This is so frustrating @emgucv

**Comment by emgucv** [comment]
Closing ticket now.
