### ISSUE TITLE
[BUG] CalcBlurriness method is inside internal class and unable to use it

### ISSUE THREAD

**Issue by sahin52** [emgucv/emgucv#811]
**Describe the bug**
I need to use CalcBlurriness method, in VideoStabInvoke.cs file. The method is public but the class is internal. I am unable to use the method, but I need it.
** OS / Platform **
Windows - VS
** .Net version **
.net standard 2.0
**CPU Architecture**
x64 intel core i7
** Emgu CV package used**
4.6 - latest
      

**Expected behavior**
I must be able to use it in my project

**Screenshots**
![image](https://user-images.githubusercontent.com/39086573/214557927-86862446-bd33-44c4-806f-8ec22b861b88.png)

**Additional context**

**Comment by emgucv** [comment]
Fixed in this commit: d32f323a9d00b2928235e457db764f37861ff600

**Comment by sahin52** [comment]
Thanks.
