### ISSUE TITLE
About Emgu.CV.runtime.windows.cuda

### ISSUE THREAD

**Issue by luisrr1590** [emgucv/emgucv#812]
Hi guys,

Is there any plans to update the Emgu.CV.runtime.windows.cuda nuget package?

I can see it is still in version 4.4 which is getting me mismatch warning with Emgu.CV 4.6.0.

I assume that version of the runtime does not support hardware decoding as that was introduced in 4.5.1

Looking forward to your comments.

Thanks

**Comment by emgucv** [comment]
See this for detail:
https://www.emgu.com/wiki/index.php/Download_And_Installation#CUDA_nuget_package_4.5.1.2B

The recent CUDA runtime contains large files (as large as 688MB for a single file) that can no longer fit into the nuget.org upload size limit (250MB). You will need to download the nuget files from the GitHub release page and host it locally yourself.

**Comment by luisrr1590** [comment]
Thanks for the feedback. Closing now.
