### ISSUE TITLE
How do two rtsp stream videos merge into one stream?

### ISSUE THREAD

**Issue by ice-ko** [emgucv/emgucv#813]
I have two cameras. How do I merge after getting the rtsp address? similar： https://www.youtube.com/watch?v=n3CsQEC4Z3U&t=10s&ab_channel=PyImageSearch

**Comment by emgucv** [comment]
The issues tracker are for reporting bugs, this should be moved to discussions.

If you have two RTSP stream, you can create two VideoCapture class, one for each stream. Stiching can be done with the stitching API:
https://www.emgu.com/wiki/files/4.6.0/document/html/T_Emgu_CV_Stitching_Stitcher.htm

Again, this should be a discussion...
