### ISSUE TITLE
SiftDescriptors AccessViolationException

### ISSUE THREAD

**Issue by LoriBru** [emgucv/emgucv#818]
**Describe the bug**
I get a AccessViolationException crash when computing the SiftDescriptors.

** OS / Platform **
Windows

** .Net version **
.NetFramework 4.8, .Net7

**CPU Architecture**
x64

** Emgu CV package used**
Emgu.CV 4.6.0.5131
Emgu.CV.runtime.windows 4.6.0.5131

**To Reproduce**
An example can be found in this repo https://github.com/LoriBru/SiftDescriptorsException.

**Expected behavior**
The crash happens after more or less 50 iterations. It happens only in release mode, in debug mode, everything runs fine.

**Comment by emgucv** [comment]
Try to replace this code 
```
var i = 0;
while (i < 1000)
{
    var image = new Image<Gray, byte>("CvFov.tiff");

    // Compute Sift descriptors
    (var kp, var des) = SiftComputer.ComputeSiftDescriptors(image);
    Console.WriteLine($"i: {i}, kp: {kp.Length}, des: {des.Total}");
    i++;
}
```
with this:
```
var i = 0;
while (i < 1000)
{
    using(var image = new Image<Gray, byte>("CvFov.tiff"))
    {
    // Compute Sift descriptors
    (var kp, var des) = SiftComputer.ComputeSiftDescriptors(image);
    Console.WriteLine($"i: {i}, kp: {kp.Length}, des: {des.Total}");
    i++;
    }
}
```
Puting the using statement around the image will make sure it is keep alive until the closing bracket. Sometimes when the Image<,> object is passed to the long running native function, the garbage collector may decided to kick in and dispose the managed object before the unmanaged function is finished. You will get an access violation.

Same to here:
```
 internal static (VectorOfKeyPoint kp, Mat des) ComputeSiftDescriptors(Image<Gray, byte> imageCV)
        {
            var featureDetector = new Emgu.CV.Features2D.SIFT();

            // Extract features from the reference image
            var kp = new VectorOfKeyPoint();
            var des = new Mat();
            featureDetector.DetectAndCompute(imageCV, null, kp, des, false);
            return (kp, des);
        }
```
replace it with:
```
 internal static (VectorOfKeyPoint kp, Mat des) ComputeSiftDescriptors(Image<Gray, byte> imageCV)
        {
            using(var featureDetector = new Emgu.CV.Features2D.SIFT())
            {
            // Extract features from the reference image
            var kp = new VectorOfKeyPoint();
            var des = new Mat();
            featureDetector.DetectAndCompute(imageCV, null, kp, des, false);
            return (kp, des);
            }
        }
```

**Comment by LoriBru** [comment]
Thanks a lot, that indeed did the trick.
I wonder if the same strategy should be applied potentially to many other parts of my project, to avoid similar issues.
Potentially that's quite tricky.
Any explanation why the GC would want to dispose an object that is clearly still in use?

**Comment by emgucv** [comment]
A good explaination to the issue can be found here:
https://stackoverflow.com/questions/56405624/when-gc-keepalivethis-is-needed-when-doing-p-invoke-on-unmanaged-resources
