### ISSUE TITLE
BackgroundSubtractor cannot be found

### ISSUE THREAD

**Issue by miftahrangga20** [emgucv/emgucv#83]
Hello @emgucv.

Currently I am installing emgucv on Raspberry Pi 3 with an OS Raspbian Stretch. According to steps in [here](http://www.emgu.com/wiki/index.php/Download_And_Installation#Raspbian_.28Raspberry_Pi_2.29_2), I am on the ./cmake_configure . It is now 99% built, BUT I got a problem at Building Example.MonoDetection.monoexe. It is error CS0246 and clearly stated that the BackgroundSubtractor could not be found. Hope anyone has solution for this

![error backgroundsubtractor](https://user-images.githubusercontent.com/34412345/34461086-63ec2298-ee54-11e7-99f6-379e5d0651a0.PNG)

**Comment by emgucv** [comment]
Current raspberry pi compilation (v4.5.1) do not have this issue. Closing ticket now.
