### ISSUE TITLE
[BUG] Library Missing from Mac OS/Xamarin Commercial Build

### ISSUE THREAD

**Issue by ambirdev** [emgucv/emgucv#831]
**Describe the bug**
Library missing from commercial package

** OS / Platform **
Mac OS

** .Net version **
Xamarin

**CPU Architecture**
ARM64

** Emgu CV package used**
Emgu.CV.runtime.xamarin.macos.4.6.0.5131.nupkg

**To Reproduce**
Set up a clean Mac Xamarin Project and integrate the emgu commercial package.   Run the app.  App crashes and throws error:
Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib

Note that no emgu APIs are called in the app.

**Expected behavior**
Obviously no crash and no error of failing to load the library.

**Screenshots**

**Additional context**
With the purchase of the commercial build, is it acceptable to distribute the non-commercial build if we have purchased the commercial license?  We would prefer to distribute the commercial build due to better performance, however, if it causes instability issues in our application, we would like the option to distribute the open source version.

**Comment by emgucv** [comment]
The 4.6.0 release is build with FREETYPE and depends on the homebrew freetype library. The dependency can be installed by calling

`brew install freetype`

on MacOS.

We have disbled freetype to elimiated the dependency on the upcoming 4.7.0 release: 9994475aa56bfd553f5950ecbb07cfb2ff6d18eb

**Comment by emgucv** [comment]
You can run the following command on the libfreetype.6.dylib file to check its dependencies:

`otool -L libfreetype.6.dylib`

If any of freetype library's dependencies is missing, it can't be loaded. 

I would recommend waiting for a few more days for the 4.7 release to come out, which should have this issue resolved (by eliminating freetype from the build).

**Comment by ambirdev** [comment]
What is the target release date of 4.7?  Is there a preview build available for the commercial release of 4.7?  We are close to releasing our software and need a target date for 4.7 as well as access to a pre-release version if it's available.

**Comment by emgucv** [comment]
We are running some more QA testing with the release packages now, should be ready soon if we didn't find any breaking issues.

**Comment by emgucv** [comment]
Mac OS Cataline 10.15.7 are no longer being maintained. We will not support that MacOS version.

Our release is build on MacOS 13 and we only have sufficient resource to support MacOS 13 release.

**Comment by emgucv** [comment]
> What is the target release date of 4.7? Is there a preview build available for the commercial release of 4.7? We are close to releasing our software and need a target date for 4.7 as well as access to a pre-release version if it's available.

4.7.0 release is out.

**Comment by emgucv** [comment]
Closing ticket now.
