### ISSUE TITLE
tesseract ocr support

### ISSUE THREAD

**Issue by mq00fc** [emgucv/emgucv#841]
Unhandled exception. Emgu.CV.Util.CvException: OpenCV: The library is compiled without tesseract ocr support
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
Aborted (core dumped)

I have installed the runtime of opencv, but this prompt confuses me, should I download the source code and recompile it?

**Comment by emgucv** [comment]
Which nuget package are you using? Is this with one of our "mini" runtime nuget packages? "mini" runtimes are not build with tesseract.

**Comment by mq00fc** [comment]
> Which nuget package are you using? Is this with one of our "mini" runtime nuget packages? "mini" runtimes are not build with tesseract.

![image](https://github.com/emgucv/emgucv/assets/50408721/3ef4a60d-1442-4185-8878-0f54960ed1f3)
When I quote like this, it will be abnormal in the linux system

**Comment by emgucv** [comment]
Which runtime nuget package do you use? 

Is it Emgu.CV.runtime.mini.ubuntu-x64? Or Emgu.CV.runtime.ubuntu-x64?

The "mini" runtime is not compiled with Tesseract. The none-"mini" version is compiled with Tesseract.

**Comment by mq00fc** [comment]
> Which runtime nuget package do you use?
> 
> Is it Emgu.CV.runtime.mini.ubuntu-x64? Or Emgu.CV.runtime.ubuntu-x64?
> 
> The "mini" runtime is not compiled with Tesseract. The none-"mini" version is compiled with Tesseract.

Thank you very much, it worked when I uninstalled the mini runtime! Thanks
