### ISSUE TITLE
Emgu CV does not detect CUDA

### ISSUE THREAD

**Issue by aleyzzz** [emgucv/emgucv#843]
I have GeForce GTX 1050 Ti with installed 531.79 NVidia driver and 12 CUDA driver. I'm using the latest version of Emgu CV 4.7, but it doesn't detect CUDA on the system, Emgu.CV.Cuda.CudaInvoke.HasCuda is always false. How do I enable CUDA for Emgu CV?

**Comment by emgucv** [comment]
Do you use the nuget package "Emgu.CV.runtime.windows.cuda" (built with CUDA)? 
Or, do you use "libemgucv-windesktop-4.7.0.5276.exe" (not build with CUDA)?

**Comment by aleyzzz** [comment]
I have added Emgu.CV.runtime.windows.cuda from Nuget as a reference and the existing project (Emgu.CV.Runtime.Windows.shproj) from libemgucv-windesktop-4.7.0.5276.exe as an existing project.

**Comment by emgucv** [comment]
Please only use the nuget pacakge (or only reference the Emgu.CV.Runtime.Windows.shproj). Do not use both at the same time , they will overwrite each other. 

If you need CUDA support, simply using the Emgu.CV.runtime.windows.cuda nuget pacakge is sufficient. 

The "libemgucv-windesktop-4.7.0.5276.exe" package is build without CUDA support. Referencing the Emgu.CV.Runtime.Windows.shproj from that package will have Emgu.CV.Cuda.CudaInvoke.HasCuda always return false.

**Comment by aleyzzz** [comment]
The Emgu.CV.Cuda.CudaInvoke.HasCuda() method returns true when the Emgu.CV.Runtime.Windows.shproj and the Nuget package Emgu.CV.runtime.windows are removed.

Thanks, it's working now

**Comment by aleyzzz** [comment]
The Emgu.CV.Cuda.CudaInvoke.HasCuda() method returns true when the Emgu.CV.Runtime.Windows.shproj and the Nuget package Emgu.CV.runtime.windows are removed.

Thanks, it's working now
