### ISSUE TITLE
[BUG] Commercial build nuget feed is down.

### ISSUE THREAD

**Issue by vissjb** [emgucv/emgucv#862]
**Describe the bug**
The repository at myget.org is down

** OS / Platform **
all

** .Net version **
.NET 6

**CPU Architecture**
x64

** Emgu CV package used**
commercial packages hosted on myget.org

**To Reproduce**
Try to restore using the myget.org feed

**Expected behavior**
I expected restore of the commercial (optimized) builds to work.

**Comment by emgucv** [comment]
We have migrated our commercial nuget repository from myget.org to a new self hosting nuget server. Please use the following instructions to get the url to the lastest nuget server:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Commercial_Release

You can also send you invoice number to support@emgu.com and we can reply with the direct link to the nuget commercial repo.

**Comment by emgucv** [comment]
I have removed the screen shot from the original posting because it contains link to the old myget.org commercial nuget repo.
