### ISSUE TITLE
Excess memory consumption when capturing with one camera

### ISSUE THREAD

**Issue by bernatDiaz** [emgucv/emgucv#877]
I have a excess RAM consumption when streaming with one camera. It only happens in some PC (all have Windows10 but only some have this issue). 
Code to grab the frame
```
private void ImageGrabbedCallback(object? sender, EventArgs eventArgs)
{
    Mat frame = new Mat();
    videoCapture.Retrieve(frame);
    FrameAvailable?.Invoke(frame);
}
```
Code to draw
```
FrameAvailable += (Mat frame) =>
{
        Application.Current.Dispatcher.BeginInvoke(() =>
        {
            CurrentFrameTop = FormatConversions.ToBitmapSource(frame);
            frame.Dispose();
        });
};
```
I added this code and it works on all PCs but only on Visual Studio, when I publish it freezes the application
```
gcTimer = new DispatcherTimer();
gcTimer.Tick += (sender, e) => 
{
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
}; 
gcTimer.Interval = TimeSpan.FromMilliseconds(500); 
gcTimer.Start();
```
without the GC -> excess memory consumption
with the GC -> OK on Visual studio, freezes on release
Windows 10
.Net6.0
emguCV 4.7.0.5276

**Comment by emgucv** [comment]
It depends on what you do with CurrentFrameTop. For every frame, a new BitmapSource is created, if you do not depose it, it will be left for the garbage collector.

**Comment by bernatDiaz** [comment]
Thank you. The solution was freezing the BitmapSource.

**Comment by emgucv** [comment]
Closing ticket now.
