### ISSUE TITLE
Question: Face Detection fail case

### ISSUE THREAD

**Issue by tonholis** [emgucv/emgucv#88]
Hello,

I purchased the pro license and I got started running the demos. 
I ran the FaceDetection demo using some random images available out there. I got 99% of accuracy in my samples but just one case failed. I am curious what was the problem with the image below. Too much noise in that image?

![girl-1163273_960_720-cropped-face](https://user-images.githubusercontent.com/5032355/34942949-d4d540f6-f9f9-11e7-8591-97b03fa0c01f.jpg)

**Comment by LingboTang** [comment]
I think so, I'm not using the pro version, and I'm getting more crappy faces like this.

**Comment by emgucv** [comment]
This issue has been discussed on the "Learning Open CV" book:
http://www.bogotobogo.com/cplusplus/files/OReilly%20Learning%20OpenCV.pdf
See page 514 of the book (page 530 of the pdf file).

The performance of the Cascade Classifier depends on the training data. A positive detection is an indication that the regions is similar to the positive samples in the training dataset. You can improve the performance of your detection by training your own cascade classifier. e.g. Including the false positive in the negative training sample will help eliminate the particular false positive. 

FYI, The Viola and Jones Cascade Classifier is based on an algorithm that is now 17 years old. (The original paper is written in 2001). A more modern implementation may be the SSD (Single Shot Multibox Detector) that may be able to provide better accuracy and faster detection speed. You can find a demo code here:
https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Test/AutoTestVarious.cs#L3368

**Comment by emgucv** [comment]
Closing ticket now.
