### ISSUE TITLE
[BUG]System.TypeInitializationException

### ISSUE THREAD

**Issue by Hardikzinzala** [emgucv/emgucv#893]
**Describe the bug**
When I Use Emgu.Cv 4.8.1.5350 that give this error 
  System.TypeInitializationException
  Message=The type initializer for 'Emgu.CV.CvInvoke' threw an exception.

** OS / Platform **
Android / IOS

** .Net version **
.Net Maui (Version 7)

** Emgu CV package used**
Emgu.CV Version :4.8.1.5350

**To Reproduce**
  var darknetConfigPath = Path.Combine("detection", "yolov3.cfg");
  var darknetWeightsPath = Path.Combine("detection", "yolov3.weights");
  var cocoNamesPath = Path.Combine("detection", "coco.names");   
  
  var net = DnnInvoke.ReadNetFromDarknet(darknetConfigPath, darknetWeightsPath);
  var classLabels = File.ReadAllLines(cocoNamesPath);

in this code line number 4 give the Error

**Comment by emgucv** [comment]
Have you installed Emgu.CV.runtime.maui 4.8.1.5350 nuget package from the commercial nuget repository?

**Comment by Hardikzinzala** [comment]
yes already install

**Comment by emgucv** [comment]
Looks like a duplicate of #894

If it is, please close this ticket.
