### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems

### ISSUE THREAD

**Issue by NkhilKajrekar** [emgucv/emgucv#896]
we are getting following error 
my-app
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
my-app
An unhandled exception has occurred while executing the request.
my-app
System.TypeInitializationException: The type initializer for 'Emgu.CV.MatInvoke' threw an exception.
my-app
---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
my-app
---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
my-app
/app/graphics-display/runtimes/linux-x64/native/cvextern.so: cannot open shared object file: No such file or directory
my-app
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/cvextern.so: cannot open shared object file: No such file or directory
my-app
/app/graphics-display/cvextern.so: cannot open shared object file: No such file or directory
my-app
/app/graphics-display/runtimes/linux-x64/native/libcvextern.so: cannot open shared object file: No such file or directory
my-app
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/libcvextern.so: cannot open shared object file: No such file or directory
my-app
/app/graphics-display/libcvextern.so: cannot open shared object file: No such file or directory
my-app
/app/graphics-display/runtimes/linux-x64/native/cvextern: cannot open shared object file: No such file or directory
my-app
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/cvextern: cannot open shared object file: No such file or directory
my-app
/app/graphics-display/cvextern: cannot open shared object file: No such file or directory
my-app
/app/graphics-display/runtimes/linux-x64/native/libcvextern: cannot open shared object file: No such file or directory
my-app
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/libcvextern: cannot open shared object file: No such file or directory
my-app
/app/graphics-display/libcvextern: cannot open shared object file: No such file or directory

i have attached docker that we are using in azure devops for deployment

[Dockerfile-my-app.txt](https://github.com/emgucv/emgucv/files/13411868/Dockerfile-my-app.txt)

in runtimes folder i can see ubuntu-x64 which is having libcvextern.so but its not present under linux-x64
please help me to resolve issue

**Comment by CODEWITHRIZA** [comment]
## Issue Analysis:

>@NkhilKajrekar, the error message indicates that Emgu.CV is encountering issues locating the shared library 'cvextern' and its dependencies, resulting in a System.DllNotFoundException.

### Resolution Steps:

#### 1. Library Location Check:
  - Confirm the presence and correct location of 'cvextern' shared library and its dependencies within the project structure, especially under the 'linux-x64' directory.

#### 2. Dockerfile Configuration:
  - Check your Dockerfile configuration to ensure that all necessary libraries and dependencies, including 'cvextern', are being properly included and mapped within the Docker container.

#### 3. Emgu.CV Configuration:
  - Verify the Emgu.CV setup within your project. Ensure the paths to the required libraries are correctly configured and accessible by the application.

#### 4. Azure DevOps Deployment:
  - If the issue persists during deployment in Azure DevOps, ensure that the Dockerfile configurations and the deployment pipeline are correctly set up to include the necessary 'cvextern' library.

### Suggested Actions:

- Check the Dockerfile and ensure that 'cvextern' and its dependencies are properly included and mapped within the container.
- Double-check the Emgu.CV setup and library paths within the project.
- Consider exploring the Azure DevOps deployment pipeline to verify if the necessary libraries are correctly deployed.

> Please provide more specific details or logs if available, especially related to the Dockerfile, Emgu.CV setup, or the deployment process in Azure DevOps. This information will help in offering more precise assistance.

#### Feel free to engage further for additional support or updates.

**Comment by NkhilKajrekar** [comment]
Can you help on this
As we are using .net core it should get installed from nuget correct ?

1. Library Location Check:

  *   Confirm the presence and correct location of 'cvextern' shared library and its dependencies within the project structure, especially under the 'linux-x64' directory.


From: Riza Mohamed ***@***.***>
Sent: Monday, November 20, 2023 3:50 PM
To: emgucv/emgucv ***@***.***>
Cc: Kajrekar, Nikhil [EMR/SYSS/PSS/PUNE] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [emgucv/emgucv] System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems (Issue #896)

Issue Analysis:

@NkhilKajrekar [github.com]<https://urldefense.com/v3/__https:/github.com/NkhilKajrekar__;!!OkyjEqkqqe9UhNQ!20YlaQ5RjvjfdhDcwIKCvHAkJZt7l97NUJlL3r2s_mAikXCCoEAlJ7_ITFgrJ2vSkfU2HDz6zO7K2kvbBLFxA8AsPDUKnQ$>, the error message indicates that Emgu.CV is encountering issues locating the shared library 'cvextern' and its dependencies, resulting in a System.DllNotFoundException.

Resolution Steps:
1. Library Location Check:

  *   Confirm the presence and correct location of 'cvextern' shared library and its dependencies within the project structure, especially under the 'linux-x64' directory.

2. Dockerfile Configuration:

  *   Check your Dockerfile configuration to ensure that all necessary libraries and dependencies, including 'cvextern', are being properly included and mapped within the Docker container.

3. Emgu.CV Configuration:

  *   Verify the Emgu.CV setup within your project. Ensure the paths to the required libraries are correctly configured and accessible by the application.

4. Azure DevOps Deployment:

  *   If the issue persists during deployment in Azure DevOps, ensure that the Dockerfile configurations and the deployment pipeline are correctly set up to include the necessary 'cvextern' library.

Suggested Actions:

  *   Check the Dockerfile and ensure that 'cvextern' and its dependencies are properly included and mapped within the container.
  *   Double-check the Emgu.CV setup and library paths within the project.
  *   Consider exploring the Azure DevOps deployment pipeline to verify if the necessary libraries are correctly deployed.

Please provide more specific details or logs if available, especially related to the Dockerfile, Emgu.CV setup, or the deployment process in Azure DevOps. This information will help in offering more precise assistance.

Feel free to engage further for additional support or updates.

**Comment by CODEWITHRIZA** [comment]
@NkhilKajrekar

### Regarding your query:

> As you rightly mentioned, when utilizing .NET Core, dependencies like 'cvextern' should typically be installed via NuGet packages.

#### 1. Library Location Check:
   - To resolve the issue, ensure to confirm the existence and accurate placement of the 'cvextern' shared library and its dependencies within the project structure, specifically under the 'linux-x64' directory.
   
>Feel free to check the NuGet package manager for the proper installation of 'cvextern' or any related dependencies. Double-checking the correct installation from NuGet might help in resolving the library loading issue.

>If you require further assistance or more detailed steps, please let me know.

**Comment by NkhilKajrekar** [comment]
![image](https://github.com/emgucv/emgucv/assets/102220474/1eaa42d7-246c-425e-a521-f2b5e7b5dc3a)
above files are present under linux-x64

**Comment by NkhilKajrekar** [comment]
any one has any solution

**Comment by blue00** [comment]
I have the same problem when using the nuget packages Emgu.CV and Emgu.CV.runtime.debian-arm64 on a raspberry pi 4 with Raspberry Pi OS (64-bit), but only when I use the version 4.7.0.5276 or higher.

The problem goes away when I downgrade both nuget packages to version 4.6.0.5131.

**Comment by NkhilKajrekar** [comment]
> I have the same problem when using the nuget packages Emgu.CV and Emgu.CV.runtime.debian-arm64 on a raspberry pi 4 with Raspberry Pi OS (64-bit), but only when I use the version 4.7.0.5276 or higher.
> 
> The problem goes away when I downgrade both nuget packages to version 4.6.0.5131.

are you using docker ?

**Comment by blue00** [comment]
No, I just copy the project onto the Pi and then start it with dotnet run.

**Comment by emgucv** [comment]
Do you put the "cvextern.so" into "/app/graphics-display/runtimes/linux-x64/native/cvextern.so"

> /app/graphics-display/runtimes/linux-x64/native/cvextern.so: cannot open shared object file: No such file or directory

If the file is not there, please copy the ".so" file to the specific folder.

If the file is already there and you still have the issue, please follow these steps to trouble-shot:
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

**Comment by NkhilKajrekar** [comment]
issue is resolved after updating docker  with below changes

# Build runtime image  
FROM mcr.microsoft.com/dotnet/aspnet:7.0-jammy-amd64 
WORKDIR /app/graphics-display 

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update && apt-get -y install  build-essential libgtk-3-dev libgstreamer1.0-dev libavcodec-dev libswscale-dev libavformat-dev libdc1394-dev libv4l-dev cmake-curses-gui ocl-icd-dev freeglut3-dev libgeotiff-dev libusb-1.0-0-dev libvtk9-dev libfreetype-dev libharfbuzz-dev qtbase5-dev libeigen3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgflags-dev libgoogle-glog-dev libatlas-base-dev liblapacke-dev libva-dev
