### ISSUE TITLE
TrackerKCF: Memory not released

### ISSUE THREAD

**Issue by machielvisser** [emgucv/emgucv#90]
Due to checking for a Zero pointer the memory is not released.

https://github.com/emgucv/emgucv/blob/a254bab32c2844105748e86a93859eb75d6071f5/Emgu.CV.Contrib/Tracking/Tracker.cs#L180

**Comment by machielvisser** [comment]
Changed equality not inequality should be enough. This bug exists multiple times in several classes in this source file.

**Comment by emgucv** [comment]
Closing ticket now.
