### ISSUE TITLE
[BUG] Wrong documentation of angle direction in RotatedRect

### ISSUE THREAD

**Issue by DiebBlue** [emgucv/emgucv#902]
**Describe the bug**

As like in the original OpenCV documentation described, the emgucv documentation of [RotatedRect.Angle](https://emgu.com/wiki/files/3.0.0/document/html/cb89c986-d976-b976-6ddf-8f50c0fb2e67.htm) should be corrected.
 The EmguCV documentation says "Possitive value means counter-clock wise rotation". But if you use CvInvoke.Ellipse than the ellipse is rotated in clock wise direction if the angle has a positive value.

** OS / Platform **
all

** .Net version **
all

**CPU Architecture**
all

** Emgu CV package used**
Emgu.CV.runtime.windows-4.8.1.5350 nuget package from nuget.org

**Expected behavior**
Documentation should describe as: "Positive value means clock wise rotation"

**Comment by emgucv** [comment]
Fixed in the above commit. Thanks for pointing that out.

**Comment by DiebBlue** [comment]
Thanks, but now it only says "rotation angle" without direction, which is no longer wrong, but it would certainly be helpful for the user to know the direction.

**Comment by emgucv** [comment]
We need to keep the document the same with Open CV to avoid any discrepancies. If Open CV updated their documentation to provide the rotation direction, we will do the same.

**Comment by emgucv** [comment]
Open CV documentation for the 4.8.0 release on RotatedRect can be found here: 
https://docs.opencv.org/4.8.0/db/dd6/classcv_1_1RotatedRect.html

**Comment by DiebBlue** [comment]
Ok, thanks for the feedback. That is understandable.
