### ISSUE TITLE
Wrongly converted parameter arguments for process method in AlignExposures class

### ISSUE THREAD

**Issue by ArdaFu** [emgucv/emgucv#905]
https://github.com/emgucv/emgucv/blob/abcfee3c2c14aef0e6453a5b99aa33afa33a88be/Emgu.CV/Photo/AlignExposures.cs#L36

origin:
using (InputArray iaResponse = times.GetInputArray())
should fix to:
using (InputArray iaResponse = response.GetInputArray())

**Comment by emgucv** [comment]
Fixed in the above commit. Thanks for pointing out.
