### ISSUE TITLE
Timeline of .Net 8.0 support

### ISSUE THREAD

**Issue by WilhelmJKilian** [emgucv/emgucv#914]
**Describe the bug**
When will .Net 8 be supported by Emgu.CV?

** OS / Platform **
Ubuntu 22.04

** .Net version **
.Net 8 (we are currently on .Net 6, but we need to upgrade to .Net 8)

**CPU Architecture**
x86

** Emgu CV package used**
Emgu.CV v4.6.0.5131
Emgu.CV.runtime.ubuntu-x64 v4.6.0.5131

**To Reproduce**
```
using Emgu.CV;

var image= new Mat();
```

**Expected behavior**
The `Mat` object must be initialised.

**Comment by emgucv** [comment]
What is the error message? 

The Emgu CV releases (e.g. 4.8.0 release) that was built after .Net 8.0 is tested to support .Net 8.0. You will need to install the dependency package on Ubuntu 22.04 first by using this script:
https://github.com/emgucv/emgucv/blob/dd63254a05763d34b4b674287ae679b9b1a40845/platforms/ubuntu/22.04/apt_install_dependency

Emgu CV 4.6.0 is built before .Net 8.0 was released, we have not tested the compatibility, but it should still works. You will need to install the native ubuntu package dependency using the "apt_install_dependency" from 4.6.0 release:
https://github.com/emgucv/emgucv/blob/34efc17e3844bab028f2b49e51cdf854b1f5833e/platforms/ubuntu/22.04/apt_install_dependency

**Comment by canmingh** [comment]
It looks like the build process is based on Debian bookworm, not based on Ubuntu.

>>> FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim AS build

It seems like as a result of that, the final binary does not look for the Ubuntu folder, it thought that the build is targeting Debian Bookworm instead of Ubuntu. 

The Emgu CV ubuntu runtime package place the binary under "/app/bin/Debug/net8.0/runtimes/ubuntu-x64/native/libcvextern.so". If you build the project under ubuntu image, it will check that folder. It looks like when you build the project under Debian Bookworm, the final binary will not check for the "/app/bin/Debug/net8.0/runtimes/ubuntu-x64/native/libcvextern.so" runtime folder.

Please build the dotnet project under Ubuntu image. I believe that should resolve the issue.

**Comment by WilhelmJKilian** [comment]
Thanks for finding that issue @canmingh, the Dockerfile was copied from one of our other repositories and that step was not updated.

After I corrected that problem, the error I mentioned did not go away. However, I checked the path you mentioned in the newly built container (`/app/bin/Debug/net8.0/runtimes/ubuntu-x64/native`) and the `libcvextern.so` does exist there:

![image](https://github.com/emgucv/emgucv/assets/59440824/f6b2c28a-db5e-4bd7-92be-e599458a1633)

I copied that `libcvextern.so` file to the Linux runtime folder (`/app/bin/Debug/net8.0/runtimes/linux/native`) and rebuilt the container. Now it suddenly works! Thanks for the help @canmingh and @emgucv 👍 

Do you have any suggestions for automating the copying of `libcvextern.so` in the Dockerfile, or even better, a suggestion to avoid copying the file altogether?

**Comment by emgucv** [comment]
You mention that you have added Emgu.CV.runtime.ubuntu-x64 v4.6.0.5131 in your ticket. That nuget pacakage should automatically deploy the libcvextern.so file into "net8.0/runtimes/ubuntu-x64/native" and it should be found by the application running on Ubuntu. Can you double check? If the nuget package does not deploy the .so file to the folder of the executable, can you make a small project to reproduce the issue and send it to us for further investigation?

Thanks.

**Comment by emgucv** [comment]
Found another issue. If you are using .Net 8.0 (and future releases), you will need to add this property in your project:

`<PropertyGroup><UseRidGraph>true</UseRidGraph></PropertyGroup>`

This will use the RID Graph to load the native binary, to keep the same native runtime loading behavior as in .Net 7.0 and older releases. Without that .Net 8.0 will not look for platform specific native runtime folders.

We have updated our help page with this information:
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

**Comment by WilhelmJKilian** [comment]
Thank you! Adding that property to my project removed the requirement to copy the file between the runtime folders. Thank you for updating the documentation as well.

**Comment by kimrhh** [comment]
@emgucv  will you consider changing your runtime package to deliver the native libraries as "linux-x64" instead? the suggested fix here is not going to work past .net8 as they want to remove the distro specific runtime identifiers completely.
