### ISSUE TITLE
CvInvoke.CalibrateCamera has problem

### ISSUE THREAD

**Issue by zhonglanrong** [emgucv/emgucv#92]
reprojectionError = CvInvoke.CalibrateCamera(
                       vvObjPts,
                       vvImgPts,
                       imageSize,
                       cameraMatrix,
                       distortionCoeffs,
                       rVecs,
                       tVecs,
                       calibrationType,
                       termCriteria);

                    rotationVectors = new Mat[imageCount];
                    translationVectors = new Mat[imageCount];
                    for (int i = 0; i < imageCount; i++)
                    {
                        rotationVectors[i] = new Mat();
                        using (Mat matR = rotationVectors[i])  **// Here  should be  using (Mat matR = rVecs[i])** 
                            matR.CopyTo(rotationVectors[i]);
                        translationVectors[i] = new Mat();
                     using (Mat matT = translationVectors[i])   **// Here  should be  using (Mat matT = tVecs[i])** 
                            matT.CopyTo(translationVectors[i]);
                    }

**Comment by emgucv** [comment]
Thanks for reporting. 

The bug has been fixed in this commit back in Nov 2017:
47de69ed5638a36cb192d62e14bfe4c7dd97beed
It will be included in the next release.

**Comment by emgucv** [comment]
Closing ticket now.
