### ISSUE TITLE
Expose new cv::rotate command

### ISSUE THREAD

**Issue by JohnTenney** [emgucv/emgucv#93]
We could possibly improve performance of rotating 90 or 270 degrees using the cv::rotate command rather
than transpose followed by flip. Can you port this API over?
As of OpenCV3.2, you can now rotate an image in a single line of code:
cv::rotate(image, image, ROTATE_90_CLOCKWISE);
For the direction you can choose any of the following:
ROTATE_90_CLOCKWISE
ROTATE_180
ROTATE_90_COUNTERCLOCKWISE

**Comment by emgucv** [comment]
Added in this commit: 
e6eda6f05e431ff73da410cf4b3453cb33b887a7

Will be included in the next release.

**Comment by gabrielrobert** [comment]
@emgucv Do you know when the next version will be released (paid license)? Thank you!

**Comment by emgucv** [comment]
The 3.4.1 version was released on Apr 14. Thanks.

**Comment by emgucv** [comment]
Closing ticket now.
