### ISSUE TITLE
[BUG/QUESTION] DllNotFoundException cvextern on Ubuntu raspberry pi arm64 - What am I missing?

### ISSUE THREAD

**Issue by JPasterkampRotec** [emgucv/emgucv#933]
**Describe the bug**
A DllNotFoundException occurs when calling any Emgu.CV code in my .Net 8 console application running on Ubuntu 24.04 on a raspberry pi 5.

**OS / Platform** 
Building/Publishing on Windows 11 with Visual Studio 2022
Running on Ubuntu 24.04 (Raspberry Pi 5)
_For extra clarity: I'm coding on Windows, but the application has to run on the Ubuntu raspberry pi._

**.Net version**
.Net 8

**CPU Architecture**
ARM64

**Emgu CV package used**
Installed multiple runtimes just to be sure:
```
<PackageReference Include="Emgu.CV" Version="4.9.0.5494" />
<PackageReference Include="Emgu.CV.runtime.debian-arm64" Version="4.9.0.5494" />
<PackageReference Include="Emgu.CV.runtime.ubuntu-x64" Version="4.9.0.5494" />
<PackageReference Include="Emgu.CV.runtime.windows" Version="4.9.0.5494" />
```

**To Reproduce**
- Create a .Net 8 console app (with a single emgu call, like CVInvoke.Something())
- Publish it as: FolderProfile, Debug, net8.0, Self-contained and linux-arm64
- Copy the published files to the Ubuntu 24.04 raspberry pi
- Make the runnable file executable with 'chmod +x ./RunnableFileName'
- Run the executable with './RunnableFileName'

**Expected behavior**
I expected all library files (.so/.dll/etc) to be installed by having the runtime nuget packages installed.

**Screenshots**
The exception:
![image](https://github.com/emgucv/emgucv/assets/55790148/afa1588b-b00c-4b36-a57b-1b4707047da9)

All files in the folder on Ubuntu:
![image](https://github.com/emgucv/emgucv/assets/55790148/00ca7e28-5af6-427f-bd47-ce81dea39a90)

**Additional context**
None

**What I've tried already**
- I added `<UseRidGraph>true</UseRidGraph>` to my csproj file.
- I tried this script: https://github.com/emgucv/emgucv/blob/4.7.0/platforms/debian/bullseye/apt_install_dependency (without libdc1394-22-dev).
-  I tried this script too: https://github.com/emgucv/emgucv/blob/4.7.0/platforms/ubuntu/22.04/apt_install_dependency (without libatlas-base-dev).
- I read https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException, but don't understand much of the instructions.
- Command `ldd libcvextern.so` resulted in some missing things:
![image](https://github.com/emgucv/emgucv/assets/55790148/fe0ed011-3786-4293-8b0b-9449916dfec0)
- Tried to install libavcodec, but got an error:
![image](https://github.com/emgucv/emgucv/assets/55790148/0bc62bbc-6bca-476b-a784-b2f8e6a6b6a6)

**Comment by emgucv** [comment]
We do not have an official release that target Ubuntu 24.04 for Arm64 architecture. 

For raspberry pi, we only provided the build for Raspbian arm64 & arm architecture 
https://www.nuget.org/packages?q=emgu.cv.runtime.debian

If you need to use Ubuntu 24.04 with raspberry pi, you will need to compile the nuget package from source code:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Ubuntu_24.04

**Comment by JPasterkampRotec** [comment]
Thanks for the response.
I specifically chose Ubuntu over Raspbian because I hoped it would be supported better by third-party software.
This is not the first instance where arm64+Ubuntu is not supported, but arm64+Raspbian is, so I'll probably install Raspbian now haha.
