### ISSUE TITLE
Does it support Image URL comparison

### ISSUE THREAD

**Issue by SaiGaneshKrishnan** [emgucv/emgucv#943]
**Describe the bug**

** OS / Platform **
e.g. Windows, Mac OS, Android, iOS, Ubuntu 20.04, Raspberry Pi, or all platforms.

** .Net version **
e.g. .NetFramework 4.8, .Net Core 5, .Net 6, Xamarin Android, Xamarin iOS

**CPU Architecture**
e.g. x86_64, ARM64, x86

** Emgu CV package used**
e.g. 'libemgucv-windesktop-4.5.2.4673.zip', Emgu.CV.runtime.windows-4.5.2.4673 nuget package from nuget.org, Git commit bf999b39fcd0a0bb6a78c35772cc1493ef3c011a

**To Reproduce**
Source code to reproduce the issue. Please keep source code as small as possible, it is prefferred to contains less than 20 lines of code and we will be able to run it with installing other external libraries. If the bugs only occurs for cetrain image, please attach the image as well.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by emgucv** [comment]
For direct image file comparison, you can download the two image url to bytes / local file and compare the bytes. No image processing is required.

This doesn't seems to be a bug though. If you want to ask a question or discuss ideas, please use "Discussion". The "Issues" tracker are for tracking bugs.
