### ISSUE TITLE
Installation Documentation outdated

### ISSUE THREAD

**Issue by TonyCongqianWang** [emgucv/emgucv#948]
[The Download and Installation page](https://www.emgu.com/wiki/index.php/Download_And_Installation) on your documentation is outdated for linux and raspberry pi in particular. It mentiones the runtime nugets for windows, but not for linux, giving the impression that you still have to build everything yourself. Since 4.6.0 it is possible to just use the runtime nugets for debian-arm64 for raspberry pi. For ubuntu it depends on the version.

It would be great if you can adjust the documentation page to reflect this change and also add information to the nuget packages about which os version are supported.

**Comment by emgucv** [comment]
Thanks for pointing out. The documentation for using nuget pacakge on Linux has been updated:

https://www.emgu.com/wiki/index.php/Download_And_Installation#Nuget_2

**Comment by TonyCongqianWang** [comment]
Nice! Thank you for the quick fix. I will close the issue
