### ISSUE TITLE
No Filled enum in LineTypes

### ISSUE THREAD

**Issue by Callum-Shipton** [emgucv/emgucv#95]
Is there a reason that CvEnum.LineType does not contain the Filled enum like it does in OpenCV?

[OpenCV 3.3.0 Docs - LineTypes enum](https://docs.opencv.org/3.3.0/d0/de1/group__core.html#gaf076ef45de481ac96e0ab3dc2c29a777)

**Comment by emgucv** [comment]
Fixed in 8948a5ffc96158b87c3d28d1cdf7e47956f6af64
Thanks for pointing out.
