### ISSUE TITLE
ConnectedComponentTypes enum typo

### ISSUE THREAD

**Issue by Callum-Shipton** [emgucv/emgucv#96]
The ConnectedComponentsTypes in CvEnum.cs has a typo, it says Connecte**c**ComponentsTypes.

Also, the documentation for accessing it is incorrect as it is a copy of the OpenCV docs.
Since there is no `stats.at<int>(componentIndex, ConnectecComponentsTypes.Area)`.

I am currently accessing it like this:
`int area = BitConverter.ToInt32(stats.GetData(i, (int)ConnectecComponentsTypes.Area),0);`

Is this approach the current recommended way of accessing the statistics?
It feels wrong converting it to an Image<Gray, int> (even with the sharing data) to access statistics.

**Comment by emgucv** [comment]
Fixed the typo in 8948a5ffc96158b87c3d28d1cdf7e47956f6af64 

Thanks for pointing out. 

I will need to take a look into the statistic access at a later time.
