### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by dataangel** [emgucv/emgucv#98]
CMake Deprecation Warning at vtk/ThirdParty/libproj4/vtklibproj4/cmake/policies.cmake:2 (cmake_policy):
  The OLD behavior for policy CMP0022 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  vtk/ThirdParty/libproj4/vtklibproj4/CMakeLists.txt:43 (include)

**Comment by emgucv** [comment]
Hi, 

This is a depreciation warning from the CMake script in VTK. It would be a VTK issue rather than an Emgu CV issue. 

It won't prevent cmake from generating the project file.

Can we close this ticket?

**Comment by emgucv** [comment]
Closing ticket now.
