### ISSUE TITLE
Hadoop Installation

### ISSUE THREAD

**Issue by bhrigwish** [emgucv/emgucv#99]
I installed Hadoop but something went wrong. I have checked all the files but all seems to be working. Can someone help
![hadoop](https://user-images.githubusercontent.com/31668594/36463553-b86026d4-16f0-11e8-8f24-8bb964dc7c45.png)

**Comment by emgucv** [comment]
This is not related to Emgu CV, right?

**Comment by bhrigwish** [comment]
Yes, sorry about that but I was terribly stuck at this so I thought if someone knew here on GitHub to help me on Hadoop

**Comment by emgucv** [comment]
This issue board is for Emgu CV related ticket. I am closing the issue now.
